- docs/tutorial/1-serialization.md
There is more documentation about widget style in https://github.com/tomchristie/django-rest-framework/blob/master/docs/api-guide/fields.md#style - however, I'm not clear about what the API is going to be for this parameter.
> fix the serializer widget style formatting documentation

- setup.py
I just found that sometime Django REST Framework HTML renderer may not work depending on how you install it. In my case, this was listed within a `setup.py`'s `install_require` which lead Django REST Framework to be installed as an egg.
Django doesn't load templates from eggs by default and has no way to gather the static files from an egg at all.
jezdez & dstuff confirm the way to fix that is to mark the packages as `zip_safe = False`.
> Mark Django REST Framework as incompatible with eggs

- docs/tutorial/1-serialization.md
- docs/tutorial/3-class-based-views.md
- docs/tutorial/4-authentication-and-permissions.md
- docs/tutorial/5-relationships-and-hyperlinked-apis.md
1. Adjusted the verbiage in part 1, to replace the class with the code snippet. 
2. Removed an unused import in code sample of urls.py in part 3.
3. Clarified SnippetDetail view class in part 4.
4. Added a missing import in part 5.
> Tweaked a few issues in the tutorial documentation.

- rest_framework/throttling.py
If `NUM_PROXIES` setting is set to None, `HTTP_X_FORWARDED_FOR` might be used as is, which
might contain spaces and cause errors on cache backends like memcached. Ref #2400
> Fix ident format when using HTTP_X_FORWARDED_FOR

- rest_framework/parsers.py
Output from parsers ends up in a Django MergeDict and they exists elements to be dicts - not None
Right now if FileUploadParser is used then trying to access request.data['file'] will give ** TypeError: 'NoneType' object has no attribute '__getitem__'
Making  sure that the data part is an empty dict fixes this
> Make FileUploadParser work with standard django API

- .travis.yml
- requirements.txt
- tests/test_multitable_inheritance.py
- tox.ini
This PR adds Django 1.8 alpha to the test matrix.
It also *begins* to address failing Django 1.8 Alpha tests:
-  Bumps `pytest` and `pytest-django` to their latest versions in both `requirements.txt` and the Tox builds to resolve `Failed: Database access not allowed, use the "django_db" mark to enable` failures which were [related to the older version of pytest-django](https://github.com/pytest-dev/pytest-django/issues/189)
- Save objects before assigning them in `InheritedModelSerializationTests.test_onetoone_primary_key_model_fields_as_expected()` to [resolve a new error raised in Django 1.8](https://docs.djangoproject.com/en/dev/releases/1.8/#assigning-unsaved-objects-to-relations-raises-an-error)
Related issue: https://github.com/tomchristie/django-rest-framework/issues/2425
> Preliminary Support For Django 1.8 Alpha

- rest_framework/compat.py
- rest_framework/utils/encoders.py
Timedelta serialisation does not work on Python 2.6.
`timedelta.total_seconds()` is only supported since Python 2.7 (https://docs.python.org/2.7/library/datetime.html#datetime.timedelta.total_seconds), so we need a fallback for python 2.6.
> Fix timedelta JSON serialization on Python 2.6.

- rest_framework/renderers.py
`NotImplemented` is a singleton object, not an exception. You should be raising `NotImplementedError` here instead.
> NotImplemented is not an exception

- docs/index.md
- requirements.txt
- tox.ini
[Django-Filter 0.9.2](https://pypi.python.org/pypi/django-filter/0.9.2) adds compatibility with Django v1.8a1. 
This PR: 
* Restores Django-Filter to the `tox` run for v1.8
* Updates various references to Django-Filter to latest version.
> Update Django-Filter references

- docs/api-guide/fields.md
- rest_framework/fields.py
- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- tests/test_fields.py
> Added UUIDField.

- docs/api-guide/fields.md
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_fields.py
> Added DictField and support for HStoreField.

- rest_framework/parsers.py
> Pass {} as data to DataAndFiles, as it ends up in a MergeDict

- rest_framework/settings.py
- tests/test_filters.py
- tests/utils.py
Closes #2466, however not yet entirely happy with this.
Note that various REST framework views set class attributes such as...
renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES
Effect of this is that if `rest_framework.views` has been imported then changing `api_settings` isn't enough, as `APIView.renderer_classes` (and others) have already been set.
The two tests using `override_settings` in this pull request use `reload_module` to ensure that the required REST framework modules are reloaded to get the new settings.
Possible approaches to solve:
* `api_settings.something` returns a lazy object. (Or wrap the class declarations)
* Only access `api_settings` inside running code, not inside class declarations.
* Document the constraint, possibly adding a helper function for reloading …
> Reload api_settings when using Django's 'override_settings'

- rest_framework/authtoken/south_migrations/0001_initial.py
This pull request handles the somewhat special case of using a custom user model with a custom `db_table` attribute. When migrating a pre-existing database that was using the `auth.User` model, [one guide for doing so recommends](http://django-authtools.readthedocs.org/en/latest/how-to/migrate-to-a-custom-user-model.html) creating a custom user table where `db_table = 'auth_user'` so that few database migrations are required. 
This pull request updates the `Meta` parameters passed for the custom user model to include the `db_table` from the real `settings.AUTH_USER_MODEL` model. 
Without this change, using a custom `db_table` attribute leads to errors like the following:
> FATAL ERROR - The following SQL query failed: ALTER TABLE "authtoken_token" ADD CONSTRAINT "user_id_refs_id_79b40daa" …
> Use the proper db_table argument when constructing meta

- rest_framework/relations.py
- tests/test_relations.py
A PATCH to a serializer's non-related CharField was clearing an ancillary StringRelatedField(many=True) field.
The issue appears to be in the ManyRelatedField's get_value method, which was returning a [] instead of empty
when the request dictionary was a MultiDict.
This fix mirrors code in fields.py, class Field, get_value, Ln. 272, which explicitly returns empty on a partial update.
Tests added to demonstrate the issue.
>  ManyRelatedField.get_value clearing field on partial update

- docs/api-guide/generic-views.md
- docs/api-guide/routers.md
- docs/topics/3.0-announcement.md
- rest_framework/routers.py
- tests/test_routers.py
As far as I understand, if it was removed, then mentioning it in the docs will just confuse people.
> Cleanup '.model' shortcut from code and docs

- docs/topics/third-party-resources.md
The original adapter was deprecated, and is soon to be fully replaced by the new ember-cli addon.
> Update link for ember-django-adapter

- rest_framework/authentication.py
- tests/test_authentication.py
...
Since the user object is fetched 4 lines after getting Token from the database, this removes a DB query for each token-authenticated request.
> Prefetching the user object when getting the token in TokenAuthentication

- rest_framework/decorators.py
Fixes `@list_route` and `@detail_route` so that they don't initialize their `methods` parameter as a list. In some cases the list gets cleared, and the result is that default parameter is now empty, and may get reused unexpectedly.
> FIX: Don't default to list in method args

- rest_framework/throttling.py
Use pk pseudo attribute for identifying the user (in case the user model is not the default and has a different column name for the unique id)
> Allow non-standard User models with Throttling

- requirements.txt
- setup.py
As explained on the twine page (https://pypi.python.org/pypi/twine):
The biggest reason to use twine is that python setup.py upload authenticates you to PyPI over http. This means anytime you use it you expose your username and password to being sniffed. Twine uses only verified TLS to upload to PyPI protecting your credentials from theft.
By using twine, we'll make the upload process more secure.
> Use twine to upload to pypi.

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
If set to `True` then leading and trailing whitespace is trimmed. Defaults to `True`.
> Add trim_whitespace to CharField

- docs/tutorial/1-serialization.md
- docs/tutorial/2-requests-and-responses.md
- docs/tutorial/5-relationships-and-hyperlinked-apis.md
Fixed a couple of small errata I noticed when going through the tutorial.
> Small fixes to the tutorial

- rest_framework/settings.py
Clears up the warning: 
>      rest_framework/settings.py:23: RemovedInDjango19Warning: 
>          django.utils.importlib will be removed in Django 1.9.
>      from django.utils import importlib, six
> Adjust importlib import

- docs/topics/project-management.md
- requirements.txt
- requirements/requirements-codestyle.txt
- requirements/requirements-documentation.txt
- requirements/requirements-optionals.txt
- requirements/requirements-packaging.txt
- requirements/requirements-testing.txt
- tox.ini
Layout requirements in a way that ensures we have a single source of truth on the set of packages used when running our tests.
This does away with the current split between `tox.ini` and `requirements.txt` that we have.
Closes #2563.
> Requirements refactor.

- docs/api-guide/testing.md
Doing a bit of testing with authentication and I noticed there was no mention of where to import the `force_authenticate` method anywhere, so I've added it to the first example where `force_authenticate` is introduced.
Fixes PEP8 W503 errors
> Add import example for force_authenticate in testing

- rest_framework/test.py
Used the same logic that <a href="https://github.com/django/django/blob/0ed7d155635da9f79d4dd67e4889087d3673c6da/django/test/client.py#L415">Django uses for checking</a> if sessions app is installed.
> Check if sessions are enabled before calling logout.

- docs/api-guide/testing.md
The link to Django's standard class, `Client` was outdated. Its been fixed.
> updated outdated link at testing.md#APIClient

- rest_framework/fields.py
- rest_framework/metadata.py
- tests/test_metadata.py
The SimpleMetadata class in metadata.py tries to getattr() attributes
on a field. For this to work, (CharField) max_length and min_length have to be
actually set as an attribute.
Did the same for (IntegerField) min_value and max_value and added those two to
SimpleMetadata.get_field_info
> Set field max_length/max_value as actual attribute.

- rest_framework/routers.py
- tests/test_routers.py
As reported in #2583, `SimpleRouter.get_routes` was popping out the `url_path` kwarg for dynamic routes, which was causing troubles in some situations.
This PR fixes this issue, removes duplicated code, and adds a test.
> Fix url_path on dynamic routes for inherited viewsets. Fix #2583

- rest_framework/routers.py
As a follow-up to #2595, this PR removes duplicated code in `SimpleRouter.get_url`.
The duplication could have been removed in several way, so I choose what seemed to be the more elegant one, not polluting `SimpleRouter`'s API.
> Remove duplicated code in routers.SimpleRouter

- rest_framework/serializers.py
This is the test I used:
```python
import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient
from reports import models
@pytest.mark.django_db
def test_get_200():
user = get_user_model().objects.create(is_superuser=True, is_staff=True, is_active=True)
client = APIClient()
client.force_authenticate(user)
models.Report.objects.create()
response = client.get('/api/v1/reports')
print(response.content)
print('*' * 20)
for _ in range(3):
models.Report.objects.create()
client2 = APIClient()
client2.force_authenticate(user)
response = client2.get('/api/v1/reports')
print(response.content)
assert 0
```
So two independent APIClients are created. They both request `/reports`. In between the two requests, more Report instances are created. But they don't …
> List resource not updated between requests

- docs/api-guide/testing.md
Found a little typo in the documentation on the testing page.
First PR :)
> Documentation test fix double word

- rest_framework/fields.py
- tests/test_fields.py
`CreateOnlyDefault` should call `set_context()` on it's default if it's callable. This allows you to combine `CreateOnlyDefault` with other callables that rely on `set_context()`, e.g.:
```python
created_by = UserSerializer(read_only=True, 
default=CreateOnlyDefault(CurrentUserDefault()))
```
I would have expected this to be the case already, so I didn't think any documentation change was necessary.
> Updated CreateOnlyDefault to call set_context on its default

- rest_framework/request.py
[The class MergeDict is deprecated and will be removed in Django 1.9](https://docs.djangoproject.com/en/dev/releases/1.7/#django-utils-datastructures-mergedict-class)
> Remove `MergeDict`

- rest_framework/relations.py
- tests/test_relations_pk.py
- In both RelatedField and ManyRelatedField, provide an empty return
when trying to access a relation field if the instance in question has
no PK (so likely hasn't been inserted yet)
- Add relevant tests
- Without these changes, exceptions would be raised when trying to
serialize the uncreated models as it is impossible to query 
relations without a PK
> Support serializing unsaved models with related fields.

- docs/api-guide/pagination.md
Came across a minor typo on the CursorPagination documentation.
> Fixed missing word in CursorPagination docs

- docs/api-guide/pagination.md
This replaces all locations of the old setting `DEFAULT_PAGE_SIZE` for the current setting `PAGE_SIZE`
`PageNumberPagination`:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L214
`LimitOffsetPagination`:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L383
`CursorPagination`:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L488
> Update documentation over PAGE_SIZE

- tutorial/2-requests-and-responses/index.html
The link is displayed in the tutorial as "http://example.com/api/items/4.json" but the hyperlink itself and what the example code actually works with are (in my opinion, less pretty) URLs like "http://example.com/api/items/4/.json".
> Fix example of explicit format URL.

- docs/tutorial/2-requests-and-responses.md
Do what I meant to do in #2670:
The link is displayed in the tutorial as "http://example.com/api/items/4.json" but the hyperlink itself and what the example code actually works with are (in my opinion, less pretty) URLs like "http://example.com/api/items/4/.json".
> Fix example of explicit format URL (for real).

- rest_framework/pagination.py
I've experienced a problem while imporing rest_framework.views in apps.py, where I would get the notorious 'django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time' error. I've traced it back to DRF's pagination.py, where I noticed you are making use of 'ugettext' instead of 'ugettext_lazy'. Replacing this, seems to have fixed my issue.
> Fixed problem with imporing rest_framework.views in apps.py

- rest_framework/routers.py
- tests/test_routers.py
The ``lookup_url_kwarg`` is intended to set the name of a field in the
URL regexps when using custom ``lookup_field``, but the routers ignore
it altogether.
When a ViewSet is defined with:
```python
class ProfileViewSet(ViewSet):
lookup_field = 'user__username'
lookup_url_kwarg = 'username'
```
Then we should get an URL along the lines of ``/profiles/(?P<username>[^./]+)/``.
However, we get ``/profiles/(?P<user__username>[^./]+)/``...
This PR fixes the bug (reported as #2591), along with an inelegant test.
> Fix lookup_url_kwarg handling in viewsets (Fixes #2591).

- rest_framework/templates/rest_framework/pagination/previous_and_next.html
when next_url is none, big part of page html will be rendered under the <a href='#'> as it does not have a closing tag.
> fixed missing anchor closing tag

- rest_framework/templates/rest_framework/horizontal/radio.html
- rest_framework/templates/rest_framework/inline/radio.html
- rest_framework/templates/rest_framework/vertical/radio.html
For this https://github.com/tomchristie/django-rest-framework/issues/2559
> Allow blank/null on radio.html choices

- rest_framework/pagination.py
> Do not paginate if PAGE_SIZE=None

- docs/api-guide/pagination.md
There was a bit of documentation that wasn't updated in #2655. This simply fixes that.
> Updates ducumentation DEFAULT_PAGE_SIZE left over after #2655

- docs/tutorial/5-relationships-and-hyperlinked-apis.md
Clarifies `urls.py` example in tutorial. This pull request is a follow up from an earlier one, #2696.
> Add necessary imports to final urls.py example

- rest_framework/permissions.py
SAFE_METHODS should be a tuple so that it can't be accidentally changed
one place should be using it, but wasn't
> use SAFE_METHODS and make tuple

- rest_framework/authtoken/serializers.py
Tests are passing locally, but I cannot manually verify the correct behaviour in the browsable api because of https://github.com/tomchristie/django-rest-framework/pull/2424
> AuthTokenSerializer - properly render password field

- rest_framework/authtoken/views.py
- rest_framework/renderers.py
This complicates a little bit the logic in BrowsableAPIRenderer.get_rendered_html_form, but it allows to use view.serializer_class when get_serializer is not there.
I tested it locally and it seems to be working.
> Use `serializer_class` for browsable API display, even on plain APIView.

- rest_framework/reverse.py
- rest_framework/versioning.py
- tests/test_reverse.py
- tests/test_versioning.py
> Handle reversal of non-API view_name in HyperLinkedRelatedField

- rest_framework/response.py
Ticket: https://code.djangoproject.com/ticket/24137
Pull Request: https://github.com/django/django/pull/3902
`django.core.handlers.wsgi.STATUS_CODE_TEXT` has been removed in favor of using Python's stdlib instead, `http.client.responses` for Python 3 and `httplib.responses` for Python 2.
> Use default reason phrases from HTTP standard.

- docs/api-guide/fields.md
Code fails if copied directly with this typo
> Reference typos in fields.md

- docs/api-guide/relations.md
This is just a really minor documentation fix - in the example models for Serializer Relations, the Tracks model should be using `ordering`.   `order_by` is an invalid Meta attribute and will result in the following
`TypeError: 'class Meta' got invalid attribute(s): order_by`
This felt a bit silly to PR, but I did actually get briefly tripped up by it in an end of day moment... so yea ;)
> Should use "ordering" in model Meta, not order_by in Serializer Relations example [documentation]

- docs/api-guide/filtering.md
- docs/api-guide/generic-views.md
The usage of `request.QUERY_PARAMS` is now pending deprecation in favor of the lowercased `request.query_params`.
> `query_params` in favor of `QUERY_PARAMS`

- rest_framework/relations.py
I implemented the enhancement with the `id_field` to provide users using non-django ORM backends the ability to still utilize the check originally provided by `if obj.pk is None`, prior to providing a related reference. I believe this gives more flexibility but also potentially provides unnecessary functionality as alternative backends may not generate an identification value solely upon storage and could potentially have their identifier provided prior to save. If the backend does that this check would only serve to verify that the user properly assigned an identifier but would not provide the intended affect of verifying the object has been created. That being said, there is the potential for this to also be done with the django ORM as the following example illustrates:
```
from …
```
> Enhancement dont require pk strictly related #2745

- docs/api-guide/serializers.md
It seems that allow_add_remove was removed from 3.x, yet the docs still mention it. I propose the update to avoid confusion.
> Update serializers documentation (removed feature)

- docs/topics/release-notes.md
- requirements-test.txt
- rest_framework/__init__.py
- rest_framework/static/rest_framework/js/default.js
- tox.ini
Per @tomchristie's [comment](https://github.com/tomchristie/django-rest-framework/commit/7872d0acbffeea5f4420aae5627f8767c6418ba3#commitcomment-10348009) on 7872d0acbffeea5f4420aae5627f8767c6418ba3, I backported the 3.1.1 security fix to the 2.4 series and bumped the version.
I wasn't sure what to do about release notes. Should I add it to this branch? Or should that go in master so it's also on the main site?
> Backport 7872d0acbffeea5f4420aae5627f8767c6418ba3 to 2.4.x

- README.md
Point to version 2 docs instead of the latest and greatest docs.
> Update 2.4 docs url

- docs/api-guide/renderers.md
The `StaticHTMLRenderer` section refers to `TemplateHTMLRenderer`
instead of `StaticHTMLRenderer`, which appears to be incorrect.
> docs/renderers: `StaticHTMLRenderer` instead of `TemplateHTMLRenderer`

- rest_framework/renderers.py
Since pagination is now included in every generic viewset, we should have ability to disable it and we have it: paginator=None or pagination_class=None. But this piece of code relies on existence of property instead of its value.
> Now it is possible to display viewset w/o paginator

- rest_framework/views.py
The `exception_handler` does not actually handle django.core.exceptions.ValidationError, so remove any mention of it.
This closes #2872
> Remove mention of Django's built-in ValidationError in docstring

- rest_framework/negotiation.py
- tests/test_versioning.py
When request contains `Accept` header with value `*/*; version=1` then the `request.accepted_media_type` attribute looses additional parameters send to `Accept` header.
Thus defeating versioning support.
> Check AcceptHeaderVersioning with content negotiation in place

- rest_framework/static/rest_framework/css/bootstrap-tweaks.css
- rest_framework/static/rest_framework/css/default.css
When importing other bootstrap themes from sites like bootswatch, the
margin in default.css persists and adds a 70px margin below the header.
This change will remove that margin when users choose to use a different
bootstrap theme.
> Move ul.breadcrumb margin to bootstrap-tweaks.css

- rest_framework/serializers.py
- rest_framework/utils/model_meta.py
- tests/test_model_serializer.py
Closes https://github.com/tomchristie/django-rest-framework/issues/2630
Raising an exception (ValueError) if an abstract model is used with a ModelSerializer. The check is happening in get_fields method of the ModelSerializer immediately after some other similar checks.
Do you think is better to make the checks earlier? Maybe in the constructor?
> Raise error when ModelSerializer used with abstract model

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/routers.py
- rest_framework/serializers.py
- rest_framework/settings.py
- rest_framework/utils/encoders.py
- rest_framework/views.py
- tests/test_fields.py
- tests/test_serializer.py
I need to support django-rest-framework on django 1.8 a little bit more, but there are some errors and irritating warnings. This PR fixes error and changes deprecated SortedDict to OrderedDict (as I seen you are not using something special from SortedDict which not compatible with OrderedDict)
> change SortedDict to OrderedDict + fix list and tuple concatination

- rest_framework/serializers.py
> Depth should reduce

- rest_framework/fields.py
- tests/test_fields.py
Let me know if these tests and fixes aren't appropriate.
> DateField to_representation can handle str and empty values. Fixes #2656, #2687.

- docs/api-guide/generic-views.md
I'm guessing switching it out for something that's not deprecated is good enough?
> Fix Invalid keyword model with generic views

- rest_framework/serializers.py
i ran into this issue when using v2.4 with django v1.8. (i didn't previously read it isn't supported)
It's not in the release notes but django.db.model.Options many_to_many() now returns an ImmutableList which is really just a tuple with a bunch of warnings and hooks on it.
if we don't make this typecast change we get the following error
TypeError: can only concatenate tuple (not "list") to tuple
I'm not sure if this change is appropriate and not sure what, if any, additional tests to include with this .
I attempted to test this but must be doing something wrong.
Every test fails when trying to use cursor. most of the errors I get are
Failed: Database access not allowed, use the "django_db" mark to enable
i followed the instructions here. …
> increase serializer compatibility to django 1.8

- docs/api-guide/authentication.md
In 'Generating Tokens' section, the example code imported get_user_model but not used.
> Delete imported but not used method

- docs/api-guide/generic-views.md
- docs/api-guide/viewsets.md
This fixes the reference to get_paginated_response for 3.x docs
From issue #2797
> Document correct method usage for get_paginated_response

- LICENSE.md
- MANIFEST.in
- README.md
As discussed in https://github.com/tomchristie/django-rest-framework/issues/2906
I separated the license in a second file.
> Separate LICENSE and README to two files.

- docs/topics/third-party-resources.md
Closes WGBH/django-versatileimagefield#12
> Adding django-versatileimagefield to DRF 3rd party docs

- docs/api-guide/permissions.md
- rest_framework/permissions.py
- tests/test_permissions.py
I'm sorry for the noise. I hope this time it is the right one.
It is a refactoring of #2904, I added explicit support for `APIRoot` with a test.
> Allow DjangoObjectPermissions to use views that define get_queryset

- rest_framework/fields.py
- tests/test_fields.py
> Allow unexpected values for ChoiceField/MultipleChoiceField representations

- rest_framework/authentication.py
- rest_framework/compat.py
Support basic authentication with custom user models with a username field that is not named 'username'.
> Support basic authentication with custom user models that change username field

- requirements/requirements-documentation.txt
The old version of mkdocs required 'Markdown>=2.3.1,<2.5' and
requirements-optionals.txt lists markdown==2.5.2 causing mkdocs
to fail.
> Update mkdocs version to 0.12.2

- docs/topics/third-party-resources.md
As discussed in issue #2968, add [drf-tracking](https://github.com/aschn/drf-tracking) to the third-party resources list.
> Add drf-tracking to third-party-resources.md

- rest_framework/fields.py
- tests/test_fields.py
Fixes #2947 
No idea why Travis failed, but I run all tests and all passed.
> Added test ensuring DecimalField accepts `2E+2` as 200 and validates decimal place correctly.

- rest_framework/serializers.py
- tests/test_model_serializer.py
I came across an unexpected issue when trying to create a read-only nested serializer for a related field that's part of a `unique_together` constraint (in [vera](https://github.com/wq/vera)).  An `extra_kwargs` entry of `required=True` is set for the constraint, but that conflicts with `read_only=True` set as the nested field's `kwargs`.
> can't create nested serializers for unique_together relations

- tests/test_fields.py
I noticed we had an extra MockHTMLDict definition that could be avoided.
> Remove an extra MockHTMLDict definition.

- docs/api-guide/fields.md
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_fields.py
- tests/test_model_serializer.py
Field that map to `django.db.models.fields.DurationField` for Django>=1.8 otherwise
with `django.db.models.fields.BigIntegerField`
> Add DurationField

- rest_framework/fields.py
- tests/test_fields.py
This is the first part to get #2894 fixed.
> MultipleChoiceField empties incorrectly on a partial update using multipart/form-data (#2894)

- rest_framework/compat.py
- rest_framework/views.py
- tests/test_atomic_requests.py
- tox.ini
based on #1787 
fixes #2034
I open the pull request for discussion.
> Rollback the transaction on error if ATOMIC_REQUESTS is set.

- rest_framework/metadata.py
- tests/test_metadata.py
This fixes #2811 
**Problem**
The issue was discovered when an `OPTIONS` request to an endpoint blew up with the following error:
```
...
rest_framework/views.py:451: in dispatch
response = self.handle_exception(exc)
rest_framework/views.py:448: in dispatch
response = handler(request, *args, **kwargs)
rest_framework/views.py:462: in options
data = self.metadata_class().determine_metadata(request, self)
rest_framework/metadata.py:64: in determine_metadata
actions = self.determine_actions(request, view)
rest_framework/metadata.py:90: in determine_actions
actions[method] = self.get_serializer_info(serializer)
rest_framework/metadata.py:107: in get_serializer_info
for field_name, field in serializer.fields.items()
rest_framework/metadata.py:107: in <listcomp>
for field_name, field in …
```
> Read-Only RelatedField Metadata Failure Test and Fix

- tox.ini
Once discussed never done.
This will allow short traceback format to help with readability.
See https://pytest.org/latest/usage.html#modifying-python-traceback-printing for documentation.
Basically it's a one line per level stack display.
> Let py.test use the short traceback format.

- docs/topics/project-management.md
> Include translations in release process

- rest_framework/fields.py
Hello,
I did some cleanup in the DecimalField class to make the methods shorter and more focused on their responsibility, but the main goal is to allow developer do to something like this:
```python
class PermissiveDecimalField(serializers.DecimalField):
"""
Consider the configured `max_digits` and `decimal_places` for both
serialization and deserialization, but do not reject input values with 
bigger precisions.
"""
def validate_precision(self, value):
return self.quantize(value)
```
Without this refactor, covering such a use-case is quite ugly. You have to copy paste the `to_internal_value` to benefit for the sanity checks and then override the precision validation part:
```python
class PermissiveDecimalField(serializers.DecimalField):
"""
Consider the configured `max_digits` and …
```
> [enhancement] Refactored DecimalField to allow easier subclassing

- docs/topics/browsable-api.md
The Bootstrap Customizer has been discontinued and is no longer available (http://getbootstrap.com/2.3.2/customize.html), so I removed the reference to it in the page.
Fixes issue #3009.
> Remove reference to Bootstrap Customizer in browsable-api.md

- rest_framework/pagination.py
- tests/test_pagination.py
For `LimitOffsetPagination`, if the limit from the query param is invalid or greater than the `max_limit`, then the previous and next links should contain the actual limit being used instead of the originally requested limit. 
Examples:
- with a `default_limit` set, a request to `http://testserver/?limit=hello`
```python
url = 'http://testserver/?limit=hello&offset{0}'.format(default_limit)
url = 'http://testserver/?limit={0}&offset={1}'.format(default_limit, default_limit)
```
- similarly, with a `max_limit` set to 10, a request to `http://testserver/?limit=100` should provide a next link with url `http://testserver/?limit=10&offset=10` instead of `http://testserver/?limit=100&offset=10`
> Include correct limits in LimitOffsetPagination link urls

- rest_framework/compat.py
- tests/test_atomic_requests.py
```python
set_rollback()
``` 
checks only `ATOMIC_REQUEST` value, but it can be turned off per view by 
```python 
@transaction.non_atomic_requests
```
Attempt to rollback without atomic block raises
```python
raise TransactionManagementError("The rollback flag doesn't work outside of an 'atomic' block.")
```
https://github.com/django/django/blob/06dc6759d85c6c24b599de07cea47387d3dc2cf9/django/db/backends/base/base.py#L361
Really critical, due `http404` for every `@transaction.non_atomic_requests`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/tomchristie/django-rest-framework/3016)
> Fix set_rollback on @transaction.non_atomic_requests.

- docs/api-guide/filtering.md
The examples in the DjangoFilterBackend documentation omit the setting of the filter_backends class variable. The examples seem to assume that the configuration setting DEFAULT_FILTER_BACKENDS is set to default to DjangoFilterBackend.
This is not immediately clear to new users and may lead to confusion. This pull request simply adds the filter_backends setting to the examples to make these more easy to reproduce.
> Set the filter_backends class variable in the DjangoFilterBackend docs

- rest_framework/routers.py
- rest_framework/urls.py
- tests/browsable_api/auth_urls.py
- tests/browsable_api/no_auth_urls.py
- tests/test_authentication.py
- tests/test_filters.py
- tests/test_htmlrenderer.py
- tests/test_middleware.py
- tests/test_renderers.py
- tests/test_request.py
- tests/test_response.py
- tests/test_reverse.py
- tests/test_testing.py
- tests/test_urlpatterns.py
- tests/test_utils.py
- tests/urls.py
Since they already have been removed from the doc and will be removed in Django 2.0
> Remove `django.conf.urls.pattern`

- docs/api-guide/relations.md
- rest_framework/relations.py
- tests/test_relations.py
Support custom serialization options for `PrimaryKeyRelatedField`s.
> Primary key serialization

- rest_framework/urlpatterns.py
- tests/test_urlpatterns.py
> `format_suffix_patterns` is applied before the trailing slash.

- rest_framework/authentication.py
- tests/test_authentication.py
Resolve #2928.
Request headers are passed as `bytes()` on Py3 (or `str()` on Py2), so, we try to decode it before calling `self.authenticate_credentials()`.
If we got an error decoding token we raise an AuthenticationFailed() exception.
> Handle invalid characters in "Authorization: token ..." headers

- docs/api-guide/versioning.md
Document the `default_version`, `allowed_version` and `version_param` class variables. This tripped me up in #2731, thank you @tomchristie! By the way, @tomchristie warned me about an issue with reverse. It works fine here, so I'm not sure what to say about this in the docs.
Anything I can improve to make my commit clearer?
> Document per-view versioning settings

- docs/api-guide/settings.md
- rest_framework/templates/rest_framework/base.html
This also hides the format dropdown from the Browsable API if `URL_FORMAT_OVERRIDE` is disabled.
> Document setting URL_FORMAT_OVERRIDE to None

- rest_framework/utils/field_mapping.py
When I actually looked at fixing it for myself, it seemed like a pretty quick fix so I just went ahead and made a PR.  The issue is described in #3011
> only include 'allow_blank' on supported fields

- rest_framework/fields.py
If a file object is unsaved it may not have an associated URL.
If we're using `FileField(use_url=True)` in that case then return `None` for the field representation.
Superseeds #2759.
> Unsaved file objects may not have an associated URL.

- rest_framework/serializers.py
- tests/test_model_serializer.py
> Progressing #2704

- rest_framework/relations.py
When overriding the get_queryset() method the property that outputs the choices sometimes uses a different queryset due to hardcoded .all()
> Use get_queryset() for RelatedField choices property

- runtests.py
Follow up to #3048
```
$ ./runtests.py --lintonly
Running flake8 code linting
flake8 passed
Running isort code checking
ERROR: /Users/jpadilla/Projects/django-rest-framework/setup.py Imports are incorrectly sorted.
isort failed: Fix by running `isort --recursive .`
```
> Print helpful command if isort fails

- rest_framework/relations.py
Child relation is already responsible for generating choices for that kind of field. When we can select more than one element this does not change possible choices.
We can just simply use what `self.child_relation.choices` will generate.
> Fix ManyRelatedField.choices

- docs/api-guide/generic-views.md
- remove the `files` and `allow_add_remove` arguments that were part of the 2.x API.
> Update `get_serializer` signature (fix #2893)

- rest_framework/serializers.py
- tests/test_model_serializer.py
Ensures that `read_only` is pulled from `extra_kwargs` and `required` is set appropriately.
Closes #3091.
> Update extra_kwargs on model serializer for required and read_only

- docs/tutorial/2-requests-and-responses.md
Was confused by patterns which seems to be deprecated in [django 1.8](https://docs.djangoproject.com/en/1.8/ref/urls/#django.conf.urls.patterns).
> Remove unused import from docs example

- rest_framework/settings.py
This is a minor fix to show the meaningful ImportError (referencing the setting name and the value) when the specified module does exist but the function or class does not. (Which raises an AttributeError instead of an ImportError, and which the original code allowed to propagate.)
> Handle AttributeError as well (when the imported module exists but the specified function/class does not).

- rest_framework/fields.py
This exception helps you to upgrade from 2 -> 3 and since a lot of fields may be in 2 using serializers.Field as parent class, this message should contain at least name of upgraded field to help user to grep and fix the codebase faster.
> Made exception message more verbose

- rest_framework/fields.py
This could be applied to DateField and TimeField, but I thought I'd propose the general idea with this.
DateTimeField is very nicely put together, but datetime.datetime.strptime is extraordinarily limited and in several ways doesn't even work as documented.  This change would allow the user to substitute a different datetime parser in so long as it took the same value, format pair as an argument. While it might require a small wrapper function to handle exceptions, the Arrow module's parser should work as a drop-in replacement (albeit with a different format syntax).
This could be problematic with regards to the to_representation implementation, as there should probably also be a way to customize output formatting.
I can flesh this out a bit more if it seems like something worth pursuing.
> Ability to customize DateTimeField with a custom datetime_parser

- rest_framework/metadata.py
- tests/test_metadata.py
This pull request add recursively the metadata of the child in a list field.
For a serializer like this : 
```python
class PowerSerializer(serializers.Serializer):
groups = serializers.ListField(child=serializers.IntegerField(), default=[], required=False)
```
You will have this metadata:
```json
"actions": {
"POST": {
"groups": {
"type": "list",
"required": false,
"read_only": false,
"label": "Groups",
"child": {
"type": "integer",
"required": true,
"read_only": false
}
}
}
}
```
I included the test directly in a existing test. Don't know if it was necessary to create a new one.
In the test provided, I use the recursion to be sure it works correctly.
> Adding recursion on child of List Field

- docs/api-guide/generic-views.md
- docs/topics/third-party-resources.md
Just updated the docs to provide a link to a third-party generic view package.
> added link to Django Rest Multiple Models to Third Party Packages on Generic Views API docs

- docs/topics/third-party-resources.md
This PR adds a link to [`django-rest-framework-braces`](https://github.com/dealertrack/django-rest-framework-braces) in the `Mist` 3rd party tools list
> Added django-rest-framework-braces in Misc list of 3rd party tools

- rest_framework/serializers.py
- tests/test_serializer_nested.py
After reviewing  https://github.com/tomchristie/django-rest-framework/pull/2796, https://github.com/tomchristie/django-rest-framework/issues/2719, and https://github.com/tomchristie/django-rest-framework/pull/2919, I thought it might not hurt to propose a fix for the simpler use case where mulitpart data for nested serializers with required=False fails validation when the field is not present.
I agree that great care is needed regarding the design decisions still needed on how the data in a serializer's "validated_data" property should be constructed (and that it should be consistent and predictable), but the fact still remains that currently, you cannot use a View with a serializer that defines a nested serializer with required=False.
I'm hoping this fix can make it into the core, so the …
> Fix nested serializer required=False multipart data validation bug

- docs/api-guide/renderers.md
The BrowsableAPIRenderer was misspelled with an extra 'e' letter
> Changed typo in Renderer docs of BrowsableAPIRenderer

- rest_framework/pagination.py
- tests/test_pagination.py
Allows developers to easily customize support for `page_size` parameters or any other page size behaviors.
The default behavior is left intentionally simple, on the basis that cursor paginations should *tend* to present their query parameters as opaque cursors, and should *tend* to have page sizes determined server side, rather than client side.
> Add `get_page_size` hook to `CursorPagination`

- docs/tutorial/1-serialization.md
That import is not used. Widgets are just used in the description text but not in the code.
> Removed import of unused django.forms.widgets

- rest_framework/serializers.py
Provide user with more information when incorrect argument `serializer.save(commit=False)` is used.
Refs #3166.
> Helpful error on erronous 'serializer.save(commit=False)'

- rest_framework/exceptions.py
- rest_framework/serializers.py
- rest_framework/utils/serializer_helpers.py
- tests/test_generics.py
Closes #3024.
Refs #2926.
Example:
> Errors in browsable API on error.

- rest_framework/views.py
- tests/test_generics.py
For further consideration...
Evaluating the results for `.queryset` on a CBV is an error as it'll be cached and returned between requests. We could explicitly guard against this.
> Guard against erroneous direct .queryset evaluation in CBVs.

- docs_theme/base.html
- docs_theme/js/theme.js
Steps:
1. Click on search button at the top
2. Type search term
3. Hit return. "Searching..." text shows. No results show.
4. Hit return again. Results show up.
Problem seemed to be with how we were deferring requiring mkdocs search index after hitting return. I changed it to initialize after the modal's shown event has triggered.
> Fix weird search behavior

- rest_framework/routers.py
Hi all,
This small modification is needed to be able to completely build parametered urls in the API Root.
> Correct API ROOT to enable parametered urls

- docs/api-guide/permissions.md
- docs/topics/third-party-resources.md
This pull request is to add our new package, DRY Rest Permissions, to the drf documentation.
https://github.com/Helioscene/dry-rest-permissions
This is a package that allows developers to define permissions for individual api actions and also return permission check results to a client app through a serializer.
> Add package reference to docs: DRY Rest Permissions

- rest_framework/pagination.py
- rest_framework/request.py
- rest_framework/serializers.py
- rest_framework/views.py
- tests/test_renderers.py
- tests/test_request.py
- tests/test_views.py
**Removed**:
* request.DATA -> request.data
* request.FILES -> request.files
* request.QUERY_PARAMS -> request.query_params
* `write_only_fields`, `view_name`, `lookup_field` removed from `ModelSerializer.Meta`, use `extra_kwargs` instead.
**Pending -> Deprecated**
* view.paginate_by -> paginator.page_size
* view.page_query_param -> paginator.page_query_param
* view.paginate_by_param -> paginator.page_size_query_param
* view.max_paginate_by -> paginator.max_page_size
* settings.PAGINATE_BY ->  paginator.page_size
* settings.PAGINATE_BY_PARAM -> paginator.page_size_query_param
* settings.MAX_PAGINATE_BY -> max_page_size
> Version 3.2 deprecations.

- rest_framework/serializers.py
- tests/test_serializer_nested.py
**EDIT from @tomchristie**
Summary of this:
children = ChildSerializer(many=True, allow_null=True)
Will allow `null` instead of a list, but not `null` items *in* the list.
If you want to treat null items in the list as valid, you'll need to instead do this:
children = ListSerializer(child=ChildSerializer(allow_null=True))
---
This fixes #2673 
I tried to keep the test case minimal, but at the same to show a relevant use case. I agree that it might be done differently (suing a different API design), but that will work only for new projects. For existing projects that need to be migrated to DRF >= 3, it's a pain not to be able to just pass `allow_null=True` as it was done in DRF 2.x. The good part about this is that the fix is a single line of code changed.
> Modify subtle ChildSerializer(many=True, allow_null=True) behavior.

- docs/api-guide/relations.md
Fix `get_object` method signature to match [`HyperlinkedRelatedField.get_object`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L227-L236).
> Fix custom HyperlinkedRelatedField example

- .coveragerc
- .travis.yml
- README.md
- tox.ini
**Full disclosure**: I work for Codecov
Changes:
- Measure code coverage in tox
- Report code coverage to [Codecov][]
- When using coverage.py, always measure branch coverage
Coveralls support was discussed in #3107 (which was closed until #2936 was resolved).
Here are a few reasons you might prefer Codecov over Coveralls:
- The reports are easier to navigate (Codecov uses a tree view by default, like GitHub)
- Codecov has a browser plugin for viewing coverage overlaid on GitHub
- Codecov supports branch coverage (this is the sole reason I switched my projects to Codecov initially)
[Here's an example Codecov report for django-rest-framework][example]
If enabling coverage in all tox environments is undesirable, we could probably enable it conditionally based on an environment variable or …
> Report test coverage via Codecov

- rest_framework/fields.py
- rest_framework/templates/rest_framework/horizontal/select.html
- rest_framework/templates/rest_framework/horizontal/select_multiple.html
- rest_framework/templates/rest_framework/inline/select.html
- rest_framework/templates/rest_framework/inline/select_multiple.html
- rest_framework/templates/rest_framework/vertical/select.html
- rest_framework/templates/rest_framework/vertical/select_multiple.html
- rest_framework/utils/field_mapping.py
- tests/test_fields.py
- tests/test_model_serializer.py
- tests/test_validation.py
Based on the work in #3108 from @maxpeterson - Thank you!
Closes #1533.
Renders as:
> Support grouped choices.

- README.md
- docs/index.md
Before, the "release notes" link was pointing to the announcement. I think it's actually useful to have both.
> Update README with 3.2 release

- rest_framework/fields.py
- tests/test_fields.py
Closes: #3235
- 08d60f5 provides the failing test.
- 0078f66 implements the fix which lets the tests pass.
Tested against CPython 2.7 via `./runtests.py`
> Fixed #3235 - ListField now returns the QueryDict value even if it's a list of only one item.

- docs/api-guide/relations.md
- rest_framework/relations.py
- tests/test_model_serializer.py
> Add a method to return the string value used in `choices` of a `RelatedField`

- rest_framework/fields.py
There's no need to recalculate them every time they are accessed.
> Cached the field's root and context property

- docs/api-guide/filtering.md
`from rest_framework import filters` was missing from one of the examples
> Add import to example for filtering

- rest_framework/fields.py
- tests/test_fields.py
> Raise error when `source=` use on a child.

- tests/test_model_serializer.py
Using the ModelSerializer with a model containing a GenericIPAddressField
produces duplicated validation error messages.
> Duplicated IPAddressField validation errors

- docs/api-guide/fields.md
- docs/api-guide/relations.md
- rest_framework/fields.py
- rest_framework/relations.py
- rest_framework/templates/rest_framework/horizontal/select.html
- rest_framework/templates/rest_framework/horizontal/select_multiple.html
- rest_framework/templates/rest_framework/inline/select.html
- rest_framework/templates/rest_framework/inline/select_multiple.html
- rest_framework/templates/rest_framework/vertical/select.html
- rest_framework/templates/rest_framework/vertical/select_multiple.html
> Limit selects

- docs/api-guide/filtering.md
- rest_framework/filters.py
- tests/test_filters.py
Using https://docs.djangoproject.com/en/1.8/ref/models/querysets/#iregex for search filter by starting field with '$'.
> Regex search

- rest_framework/fields.py
- tests/test_fields.py
> Resolve empty HTML charfield behavior.

- docs/api-guide/serializers.md
- rest_framework/serializers.py
- tests/test_model_serializer.py
Ref #3335
`ModelSerializer`s without explicit `fields` or `exclude` will raise an exception in the future similar to what Django `ModelForm`s do.
According to https://github.com/tomchristie/django-rest-framework/issues/3335#issuecomment-135460961 the deprecation path might be as follows:
> - 3.3 is compatible with 3.2 and add a `PendingDeprecationWarning`
- 3.4 would escalate these warnings to DeprecationWarning, which is loud by default.
- 3.5 would remove the deprecated bits of API entirely.
> Update ModelSerializer fields behavior

- docs/api-guide/filtering.md
- docs/topics/third-party-resources.md
This PR adds https://github.com/miki725/django-url-filter as a 3rd party resource.
> Added django-url-filter to 3rd party libraries

- docs/api-guide/relations.md
> Replacing self.tag with self.tag_name in Generic Relationships documentation.

- rest_framework/fields.py
- tests/test_fields.py
When sending an integer value for a duration field, I get a 500 because `parse_duration` blows up.
This PR makes `DurationField` accept integer values instead. I'm open to restricting `DurationField` to string values, but then we should return a 400 with an error message.
```bash
./runtests.py TestDurationField
```
> DurationField accepts integers

- rest_framework/serializers.py
- tests/test_serializer_nested.py
This should fix #3361.
Root cause is `allow_empty` applies to the `ListSerializer` but not for its children.
> Don't pass `allow_empty` to `ListSerializer`'s children.

- docs/api-guide/fields.md
The documentation now not only mentions that callables are acceptable
arguments, it also tells the reader what the callable should look like.
> Improve documentation of default argument for fields

- docs/api-guide/serializers.md
The documentation added warns the user that field level validation will
be skipped if the field is declared on the model with the parameter
`required=False`.
> Add note about field level validation, fixes #3306

- rest_framework/fields.py
- tests/test_fields.py
An uncaught `TypeError` occurs when an unhashable value is provided as input to a `BooleanField`.
```python
from django.conf import settings
settings.configure(INSTALLED_APPS=['rest_framework'])
import django
django.setup()
from rest_framework import serializers
bfield = serializers.BooleanField()
print(bfield.to_internal_value([]))
```
A `ValidationError` with the message '"[]" is not a valid boolean."
An uncaught `TypeError` occurs.
> Correctly handle [] and {} as invalid inputs to BooleanField

- docs/api-guide/serializers.md
This is in refs to #3391. Adding `serpy` serialization note to the serializer docs.
> Add link to serpy serialization

- requirements/requirements-packaging.txt
This pins the `transifex-client` to `0.11b3`. This allows the install of the `requirements/requirements-packaging.txt` on python 3.4.
Without this change the install of the devel requirements fail:
```shell
Collecting transifex-client==0.10 (from -r requirements/requirements-packaging.txt (line 8))
Downloading transifex-client-0.10.tar.gz (68kB)
100% |████████████████████████████████| 69kB 26.6MB/s
Complete output from command python setup.py egg_info:
File "<string>", line 20, in <module>
File "/private/var/folders/zz/zyxvpxvq6csfxvn_n32txkg4rpqcls/T/pip-build-vs8d_8zq/transifex-client/setup.py", line 14, in <module>
if long_description.startswith(BOM):
TypeError: startswith first arg must be str or a tuple of str, not bytes …
```
> Update transifex-client requirement to latest release version 0.11b3

- rest_framework/fields.py
- tests/test_serializer_lists.py
- Previously, partial serialization during an update request, such as in the case of HTTP PATCH, would have truncated any old values in ListField data. This is because it had relied on the default value of an empty list. But an empty list has different functionality than the sentinel value of ``empty``. Namely, the semantic meaning of an empty list on an update is to remove all the values. Instead, this PR changes validation internals to use the sentinel value of ``empty`` instead of an empty list.
- Included minor refactor of both `ListField` and `MultipleChoiceField`, for the sake of consistent code.
- Included proof of bug in a unit test at cb42b99.
- Should resolve Issue #2761.
> Fixed #2761 - ListField truncation on HTTP PATCH

- tox.ini
Fixes #3406
Excluding Django Guardian clears up the test run against Django `master`
> 3 failed, 287 passed, 2 warnings, **456 error in 220.90 seconds**
vs
> 1 failed, 735 passed, 10 skipped, 2 warnings in 7.39 seconds
* Made against v3.3 branch. 
* Easy enough to re-add when Guardian fixes this. 
* There's probably some neater way of specifying the exclude in tox config — but I couldn't think of it offhand.
> Exclude Guardian testing against Django master

- rest_framework/serializers.py
- tests/test_serializer.py
- Added test_data_access_before_save_raises_error test
> Guard against calling `serializer.data` before `serializer.save()`

- rest_framework/utils/field_mapping.py
- tests/test_validators.py
In the automatically applied UniqueValidator, use the error message from
error_messages defined in the model instead of the generic default
UniqueValidator message.
This fixes #2878.
> Use model error_messages when available

- docs/api-guide/fields.md
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_fields.py
> Added JSONField.

- docs/api-guide/throttling.md
Super small, just reading through and noticed it.
Thanks for keeping the api-guide so up to date!
> Small doc typo `throttles` --> `throttling`

- rest_framework/authtoken/serializers.py
Per django rest framework docs, and to prevent confusion with Django's ValidationError, `serializers.ValidationError` is preferred to `exceptions.ValidationError`.
> Use serializers.ValidationError in AuthTokenSerializer

- docs/api-guide/authentication.md
As @tomchristie starred the project, I figured out I could permit myself to include it in somewhere in the documentation.
I was waiting for some kind of approval before doing this :)
If this is not suitable for the documentation as more and more third packages are added or not adding any value to the project, don't mind closing this, I wouldn't want contributing in the wrong way.
> Added django-rest-framework-social-oauth2 to list of third party packages

- .travis.yml
- runtests.py
Codecov is not actually working correctly on Travis CI if you look at the output of the `codecov` command on one of the builds: https://travis-ci.org/tomchristie/django-rest-framework/jobs/84089157
You can see why this is here: https://github.com/rackerlabs/mimic/pull/427#issuecomment-142523645
This PR adds the arguments necessary to `pytest-cov` to generate the `coverage` xml report within the `tox` execution context. Then when `codecov` is run outside of the `tox` context it finds the xml coverage report.
> Fix codecov on Travis CI

- rest_framework/exceptions.py
- rest_framework/fields.py
- rest_framework/metadata.py
- rest_framework/pagination.py
- rest_framework/routers.py
- rest_framework/serializers.py
- rest_framework/validators.py
Since we dropped Django 1.6 and below we don't support Python 2.6 any more.
That means we can replace all list conversions to dict and set with dict and set literals which is more idiomatic and wee bit faster.
> Replaced all dict and set conversions from lists to dict and set literals

- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- rest_framework/utils/model_meta.py
Closes #2426.
Rebased copy of PR #2435 which is abandoned by the author
> Added support for the to_field on ForeignKey fields

- rest_framework/templatetags/rest_framework.py
Resolves #3545
Follows rules in Django 1.9 [simple_tag](https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape) release notes.
> Use format_html in tags that generate HTML

- rest_framework/utils/serializer_helpers.py
- tests/test_bound_fields.py
`False` was getting sent to `force_text`, which converts it into the string `'False'`. When rendering as HTML, this was causing checkboxes to be checked by default when they shouldn't be.
`BoundField.as_form_field()` correctly handles `False` so I did the same thing here.
Fixes https://github.com/tomchristie/django-rest-framework/issues/3523
> Correctly handle False in NestedBoundField.as_form_field()

- rest_framework/templates/rest_framework/admin.html
Trans template tag requires `{% load i18n %}` at top of template.
> Fix trans template tag error on admin

- rest_framework/compat.py
- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
DecimalValidator was introduced in Django 1.9.
Resolves #3562
> Add compat util for DecimalValidator

- docs_theme/css/default.css
- mkdocs.yml
This patch tells `mkdocs` to add permalinks to section headers in the docs.
The link styles only show on hover:
Thanks for DRF!
> Add section permalinks to docs

- docs/api-guide/relations.md
Since we aren't passing in any args, we must specify kwargs as a keyword argument.
> docs - reverse needs kwargs keyword

- docs/index.md
- docs/topics/3.3-announcement.md
- docs/topics/release-notes.md
- mkdocs.yml
- rest_framework/__init__.py
- rest_framework/authentication.py
- rest_framework/request.py
> Request parsing when .POST accessed

- rest_framework/filters.py
Previously it required a filter_class,
or else it would error when calling `cls()`.
This now sets the `filter` context to `None`
if one does not exist.
This fixes #3559
> Allow HTML to render when no filter_class is defined.

- rest_framework/serializers.py
> Proper 'is primary key' checking.

- tox.ini
Bugfix release 1.8.6 was just [released](https://docs.djangoproject.com/en/1.8/releases/1.8.6/).
> Test against Django 1.8.6

- tox.ini
tox automatically includes basepython definitions for all the common python versions, and will recognize it in factors of envs in the envlist.
> Don't specify basepython

- tests/test_request.py
This should fix our test suite under Python 3.5.
Fix #3534
> Fix module name with Python 3.5 (#3534)

- rest_framework/templates/rest_framework/base.html
34eb18b498e20ab1f869365cca6880186d64e966 introduced  #3578 that causes raw data form to not display when there is no html form tab.
This change reverts a specific change in the referred to commit that changed the logic of when to show the HTML and|or Raw Data POST forms as tabs in the API browser.
The correct logic is to show the Raw Data form as a tab if there is also an HTML form to render (i.e. there's two tabs in total). Otherwise display the Raw Data form as an unstyled div.
The faulty logic attempted to show the the Raw Data form as a tab whether or not there was a second tab containing the HTML form. As a result of Bootstrap's default styling on tab-pane (display: none), the raw data form would not be displayed.
See #3578 for screenshots.
> Fix regression causing raw data form to not display

- rest_framework/utils/model_meta.py
Fixes [issue 3634](https://github.com/tomchristie/django-rest-framework/issues/3634)
> Relation fields no to_fields attribute attribute break serializer

- docs/api-guide/generic-views.md
> Removing references to get_paginate_by() as it no longer exists.

- rest_framework/fields.py
- tests/test_fields.py
A dictionary is allowed as input in a ListField.  If a dictionary is received as input, the keys of the object are retained, and the values are ignored.  I assume the ListField should enforce that the input is an array, especially because the error message in `to_internal_value` includes "not a list" if something is wrong with the data.
Enforces that data cannot be a collections.Mapping.
> ListField does not enforce that input is a list

- rest_framework/compat.py
- rest_framework/filters.py
- rest_framework/pagination.py
- rest_framework/renderers.py
- rest_framework/templatetags/rest_framework.py
Passing `RequestContext` to `Template.render` is deprecated, see https://github.com/django/django/pull/3883
https://github.com/django/django/blob/1.9rc1/django/template/backends/django.py#L82-L84
> Fix template.render deprecation warnings for Django 1.9

- rest_framework/renderers.py
...to keep the same order instead of some random order. 
Every app reload they jump around which may be distracting.
> Sort response headers in api renderer 

- rest_framework/compat.py
- rest_framework/utils/model_meta.py
> Fix #3252 -- Use related_objects api for Django 1.9+

- .isort.cfg
- requirements/requirements-codestyle.txt
- requirements/requirements-packaging.txt
- rest_framework/utils/representation.py
These are refined versions of the commits that previously lived in #3668.
Version 0.11b3's setup.py had an undeclared dependency on `py2exe` when running on Windows (see https://github.com/transifex/transifex-client/blob/0.11b3/setup.py#L23), which made it impossible to install without having a working `py2exe` to begin with.
This has been fixed in 0.11 proper.
This gets rid of a file encoding bug that occurs on Windows boxes where the default implied encoding is cp1252, but the files themselves aren't. The actual patch that seems to fix this is
https://github.com/timothycrosley/isort/commit/1057d5e12edbb3030045b7a7a8c82f0848635fef
but it seems like a good idea to upgrade to the latest and greatest.
This re-stabilizes sorting after upgrading to 4.2.2.
Windows Pythons seem to like printing …
> Make tests pass on Windows too

- rest_framework/permissions.py
This ensures AttributeErrors and TypeErrors do not get hidden when DRF is just looking for a `get_queryset()`.
> Reveal previously hidden AttributeErrors and TypeErrors

- rest_framework/utils/serializer_helpers.py
- tests/test_bound_fields.py
If a NestedBoundField field has a value of `None` and is inside another NestedBoundField field, it will have its value converted to an empty string while the form of its enclosing field is being rendered. So, NestedBoundField fields with an empty string value must be handled the same way as NestedBoundField fields with a `None` value.
> Updated NestedBoundField to also handle empty string when rendering its form

- rest_framework/static/rest_framework/css/bootstrap-tweaks.css
- rest_framework/templates/rest_framework/base.html
Added a modal to confirm deletion of data
> #3228 - add confirm modal for delete

- rest_framework/fields.py
- tests/test_fields.py
Fixed #3679 
Added validation to UUIDField to properly catch invalid input types (lists, tuples, etc).
Also added a new invalid input to UUIDField test.  Not sure I'm entirely happy with
the patch as it currently is, since it seems to have some unnecessary redundancy
but I figured I go ahead and push it up now since it does work.  Comments and
suggestions are appreciated.
> Fixed #3679 -- UUID Validation

- docs/api-guide/versioning.md
booking list regexp was fixed in https://github.com/tomchristie/django-rest-framework/commit/8b97bb8f68970881190a3b62cf53495cc0e20786 but single booking wasn't for some reason, and `v1v2/bookings/123/` shouldn't be allowed here
> Fixed versioning regexp

- rest_framework/filters.py
Closes #3597 (supersedes it but without using `Context`)
Closes #3596.
> Admin and API browser fails for views without a filter_class

- docs/index.md
- docs/tutorial/4-authentication-and-permissions.md
- rest_framework/urls.py
This allows users in Django 1.9+ to include the authentication urls
without specifying the namespace, as in:
```python
urlpatterns = [
...
url(r'^auth/', include('rest_framework.urls'))
]
```
The urls will still be namespaced, but will use the namespace set by the `app_name`.
> Add app_name to rest_framework.urls.

- rest_framework/renderers.py
Rendered would suggest using `format='JSON'` when the right argument is `format='json'`.
> Fixed suggestion for format in test renderer

- docs/api-guide/parsers.md
Added missing import statements in code snippet of API guide.
Closes-Issue: #3727
> Import parser added to docs in API guide

- requirements/requirements-testing.txt
With the current versions for pytest I get errors while collecting some files against python3.5:
.tox/py35-django19/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:682: in visit_Name
locs = ast.Call(self.builtin("locals"), [], [], None, None)
E   TypeError: Call constructor takes either 0 or 3 positional arguments
> Fix tox build against python 3.5 by upgrading pytest.

- docs/tutorial/1-serialization.md
If you follow the current tutorial precisely the user will end up with an error when they try to run the first migration. In order to work as written, the part where tutorial/urls.py is edited needs to be moved after the new snippets/urls.py file is created. This has no effect on the first part of the tutorial as the urls.py file is not needed until the web interface is created in the second half.
Additionally, it is helpful to note that 'include' needs to be added to the pre-existing imports as it is not part of the generated file from Django.
> Move urls.py changes down and add necessary import

- rest_framework/filters.py
A regression was introduced here: https://github.com/tomchristie/django-rest-framework/commit/aeb57913c9f2a7ad1ffc1db825c3e6f44b4818ee
The super class of `AutoFilterSet` was change to just `FilterSet`, which causes custom default filter sets to be ignored. This PR fixes the regression.
> Subclass AutoFilterSet from self.default_filter_set

- rest_framework/locale/en_US/LC_MESSAGES/django.po
- rest_framework/settings.py
- tests/test_settings.py
I'm not sure if the error message is detailed enough. Does anyone have a better solution?
> Raise error when setting a removed rest_framework setting for #3644

- docs/topics/browsable-api.md
I was quite confused for a while because I was using Bootstrap v2.1.1 themes, which I assumed would work with the v2.1.1 that the [Customizing](http://www.django-rest-framework.org/topics/browsable-api/#customizing) section of the documentation claims django-rest-framework uses. However, this resulted in very odd visuals.
It wasn't until I searched github and found that the framework has apparently abandoned v2.1.1 for quite some time, and is apparently on v3.3.5 as of https://github.com/tomchristie/django-rest-framework/pull/3547, that I realized what was wrong.
So, this simple fix updates the version of Bootstrap mentioned in the docs.
Another alternative to this fix may be to simply mention that REST framework uses "bootstrap 3", in which case the docs are less likely to become …
> Update bootstrap version in browsable-api.md

- rest_framework/templates/rest_framework/base.html
Turned out to be pretty easy. I tested this locally and it's a major usability win.
> Fixes #3756, adding the name to the HTML title, if it exists.

- docs/api-guide/filtering.md
I just updated the documentation as was suggested because [rest_framework.filters.Filterset](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L22) already checks for dependencies and builds the appropriate FilterSet class.
> Initial fixes #3636 and fixes #3637

- docs/tutorial/1-serialization.md
All the other code blocks in the Serialization tutorial can be copied and pasted, but there is one that includes the >>> shell prompt characters. This commit removes those characters, and also makes the output consistent with other code blocks by making it a comment.
> Make code block consistent in serialization tutorial

- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
After upgrading from DRF 3.2.5 to 3.3.2, a bunch of our tests started failing because the `min_value` and `max_value` are no longer being transferred over to the automatically generated fields. This is a regression that does not appear to be documented anywhere, and there is still code that is supposed to be setting these arguments.
> Min/MaxValueValidator is no longer transferred from a model's DecimalField

- rest_framework/authentication.py
- rest_framework/authtoken/models.py
- tests/test_authentication.py
This PR updates the usage of the authtoken model for better compatibility with Django 1.9, specifically to make it possible to define module-level app APIs that rely on `rest_framework` with the default authentication settings (which import `rest_framework.authentication`).
Some background: it is forbidden in Django 1.9 to import models before the app infrastructure has finished loading.  This makes it a bit tricky when implementing module-level shortcut APIs like Django's `admin.site`, wq.db's [`rest.router`](https://wq.io/docs/router) interface, and the [`rest_pandas`](https://github.com/wq/django-rest-pandas/blob/master/rest_pandas/__init__.py) module (though the latter isn't strictly a Django "app").  Any code imported in the `__init__.py` for those modules needs to defer importing …
> don't import authtoken model until needed

- docs/api-guide/relations.md
`slug field` in code snippet was replaced to `slug_field`
> Typo fix in docs/api-guide/relations.md

- rest_framework/serializers.py
- tests/test_validation.py
Previously an extra list wrapped nested validation errors raised from serializer's `validate()` methods.
That was inconsistent with the format of validation errors raised by `validate_<fieldname>` methods.
i.e. these two resulted in *different* behaviour:
def validate_foo(self):
raise ValidationError(['bar'])
...
def validate(self):
raise ValidationError({'foo': ['bar']})
> Fix nested validation error being rendered incorrectly.

- rest_framework/fields.py
- tests/test_fields.py
Hello!
Seems like `DateField.to_representation` doesn't work with `unicode` values on Python 2.*, but it can accept `str` values. I think it should work with `unicode` too.
Here is example:
```
from rest_framework import serializers.
class Example(object):
def __init__(self, created):
self.created = created
class ExampleSerializer(serializers.Serializer):
created = serializers.DateTimeField()
example = Example(created=u'2016-01-10')
es = ExampleSerializer(example)
print(es.data)
```
Traceback:
```
File "<console>", line 1, in <module>
File "/Users/m1kola/.virtualenvs/drf_dev/lib/python2.7/site-packages/rest_framework/serializers.py", line 503, in data
ret = super(Serializer, self).data
File "/Users/m1kola/.virtualenvs/drf_dev/lib/python2.7/site-packages/r …
```
> PY2: DateField.to_representation can't work with unicode value

- rest_framework/fields.py
- tests/test_fields.py
Similar to https://github.com/tomchristie/django-rest-framework/pull/3731 but for TimeField
> Fixed TimeField not handling empty values

- rest_framework/__init__.py
In the history, somebody update the copyright in the documentation, but left this out, be this the intention or not, I updated also this. Probably the __version__ variable will be updated for future releases.
> 2015 update in __init__.py file

- docs/api-guide/authentication.md
With focus on large user base, but can be extended.
per comment in #3830
> Document how to tweak authtoken.admin.TokenAdmin

- runtests.py
- tox.ini
This is pretty much the first step to ensure we don't skip some tests.
At the moment, it's not possible to mark them as errors (https://github.com/pytest-dev/pytest/issues/1173) however, it's better to show them rather than leave them hidden.
In particular since we already have two of them which may break some tests:
WC1 [...]/django-rest-framework/tests/test_model_serializer.py cannot collect test class 'TestMetaClassModel' because it has a __init__ constructor
WC1 [...]/django-rest-framework/tests/browsable_api/test_browsable_nested_api.py cannot collect test class 'TestNestedSerializerSerializer' because it has a __init__ constructor
> Display py.test internal warnings

- rest_framework/versioning.py
QueryParameterVersioning does not fall back to the value used in the `DEFAULT_VERSION` setting, while other versioning schemes do. This looks like a minor change, and incorporates the `self.default_version` set in the superclass.
I'll sheepishly admit that I edited this inline without running any tests or anything, so please let me know if this needs more work.
> QueryParameterVersioning does not use default version

- docs/api-guide/serializers.md
If the id field is implicitly created, it is created as `read_only=True`. This causes the data validation step to remove the id values in the validated data.
> Added explicit id field in multi update example

- rest_framework/templates/rest_framework/admin.html
CSRF token was missing during object creation through Create form in AdminRenderer. An analogous csrf_token tag in the base browsable API form was introduced in 41182c6f.
> Add missing csrf_token in AdminRenderer post form.

- .travis.yml
This is to avoid pip8 installation.
> Maintain py32 test builds

- docs/api-guide/relations.md
- rest_framework/relations.py
- rest_framework/utils/overridden.py
- tests/test_relations.py
Currently `get_queryset` is not a part of the documented API of `RelatedField`. This pull request makes it a documented part of the API, and adds a test using that feature with a subclass of `SlugRelatedField`.
> RelatedField get_queryset and context

- rest_framework/templates/rest_framework/login_base.html
I would be handy if the login input of the login form was auto-selected when landing on the page. 
This is easily done by adding the HTML5 tag `autofocus`.
> Login form autofocus

- rest_framework/authtoken/models.py
Fixes #3858.
The fact that we don't import Token from authentication doesn't invalidate the need for the model to be abstract whenever the authtoken isn't listed in the INSTALLED_APPS.
> Restore the abstract on Token model when the app isn't declared

- docs/api-guide/fields.md
- Add missing comma in kwargs
- Remove spaces around keyword / parameter equals
- Replace incorrect curly brace with parenthesis
> Fix syntax errors in docs example

- rest_framework/authtoken/__init__.py
- rest_framework/authtoken/apps.py
- rest_framework/authtoken/models.py
- rest_framework/authtoken/serializers.py
+ verbose_name in models.Token fields
+ Meta-options verbose_name & verbose_name_plural
+ Labels in AuthTokenSerializer fields in case of usages in Brousable API
+ provide AppConfig class as described in django documentation with verbose_name came through ugettext_lazy
> enhancement #3886 Internationalization in admin interface for authtoken

- rest_framework/renderers.py
- tests/test_renderers.py
If `HTMLFormRenderer.render` will be called with default arguments, `AttributeError: 'NoneType' object has no attribute 'get'` will be raised.
> Fixes AttributeError in HTMLFormRenderer.render

- rest_framework/fields.py
Fixes docstrings for `to_choices_dict` and `flatten_choices_dict` functions in fields.py.
Mistakes were introduced in 4d69286
> Fixes docstrings in fields.py

- docs/tutorial/4-authentication-and-permissions.md
- docs/tutorial/quickstart.md
Trying to create a new user on Django 1.9.x with the password 'password'
will fail with the error message 'This password is too common.'. Because
of that it is necessary to change the used password from 'password' to
'password123'.
> Use 'password123' as password for new users in the tutorial

- rest_framework/compat.py
This API is deprecated since Django 1.8, see #3656.
> Silenced deprecation warnings on Django 1.8.

- rest_framework/templates/rest_framework/vertical/checkbox.html
`HTMLFormRenderer` renders `BooleanField` field as not checked if vertical layout are used.
> Fixes vertical html layout for BooleanField

- rest_framework/templates/rest_framework/base.html
Closes #3878.
I just removed it from the template. I left the version string in the context so if people want to include it they can.
> Remove version string from base template

- rest_framework/templates/rest_framework/admin.html
Should be the last instance of publicly accessible version strings - takes care of #3878.
> Remove version string from admin template

- rest_framework/exceptions.py
- tests/test_exceptions.py
Looks like a typo. 
Steps to reproduce:
>>> from django.utils.translation import ugettext_lazy as _
>>> from rest_framework.exceptions import _force_text_recursive
>>> _force_text_recursive(_("fdsf"))
'fdsf'
>>> _force_text_recursive({'a': _("fdsf")})
{'a': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x10ba73e80>}
> Fixed _force_text_recursive typo

- requirements/requirements-packaging.txt
- setup.py
Use Pandoc to set the setup.py's `long_desc`.
Fixes #3817 and #3911.
> Use pandoc to generate a nice PyPI information page.

- .travis.yml
- docs/topics/release-notes.md
- tox.ini
As per discussion on #3915: drops Django 1.7 in a separate pull request.
> Drop EOL Django 1.7

- rest_framework/pagination.py
- tests/test_pagination.py
We remove a couple of informations to lower the exposition of our internals.
This is somewhat related to security. We remove those informations to lower the leak of informations.
> Remove page information in pagination error messages

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
Please, refer to the #3937 for more information.
> Closes #3937. Support callable as the value of `initial` for any `serializer.Field`

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/renderers.py
- rest_framework/serializers.py
- rest_framework/test.py
- rest_framework/utils/model_meta.py
- tests/test_fields.py
- tests/test_generics.py
- tests/test_model_serializer.py
- tests/test_request.py
Check #3952 for more information.
Remove skipping of tests for Django<1.8.
Remove several functions from compat.py not needed for Django>=1.8
> Closes #3952: Remove old django checks from tests and compat

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
Work in progress pull request to discuss further. GitHub added [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates). I think having an issue template might help with managing issues and triage, helping to reduce noise, and help to point people in a direction where they will get the most traction.
I'm still working on the pull request template, but I think there's something regarding #3916.
> Create issue and pull request templates

- docs/tutorial/1-serialization.md
In the Tutorial part 1, Serialization, word using was repeating. This PR fixes the error.
> Docs: Fix repetitive word in the tutorial

- docs/api-guide/versioning.md
Minor fix to versioning.md -- URLPathVersioning was being referred to as URLParameterVersioning in subsequent sections.
> Fixes incorrect references to URLPathVersioning

- docs/tutorial/5-relationships-and-hyperlinked-apis.md
to fix "@api_view" usage error in "docs/tutorial/5-relationships-and-hyperlinked-apis.md"
> [change] using safer calling way of  "@api_view" in docs/tutorial/5-relationships-and-hyperlinked-apis.md

- docs/api-guide/versioning.md
Their guidelines added localization to the repo structure.
> Add `/en` to Heroku guidelines link

- docs/api-guide/relations.md
Based on the work of [#755](https://github.com/tomchristie/django-rest-framework/pull/755), this library is solving a really typical use case for generic foreign keys. I think it should be more visible.
> add rest-framework-generic-relations link to docs

- rest_framework/relations.py
- tests/test_relations.py
This implementation allows detection of empty values that are non-nullable, allowing the field to return `None` values for such cases. Fixes https://github.com/tomchristie/django-rest-framework/issues/3959
> Fix empty pk detection in HyperlinkRelatedField.get_url

- README.md
Remove django1.7 since #296c56764574b178be2d0ac96b38d7879e0b3947 took django1.7 off the build.
> Remove django1.7 from README.md

- docs/api-guide/serializers.md
Adds a documentation reference to the dynamic-rest addon.
For some context, we have been enjoying Django REST Framework for quite some time and ended up adding our own functionality in the form of an addon package. We have open-sourced this addon and hope that it will prove useful to other teams and developers.
> Add a reference to the dynamic-rest addon

- rest_framework/static/rest_framework/js/default.js
In custom themes one might want to move all JavaScript to the `<head>`. But currently JavaScript provided by DRF is not written in this way. This pull requests wraps it simply into a `$(document).ready` to assure that.
Diff is ugly because indentation changed.
> Run JavaScript only when DOM is ready

- rest_framework/decorators.py
- rest_framework/generics.py
- rest_framework/parsers.py
- rest_framework/permissions.py
- rest_framework/relations.py
- rest_framework/renderers.py
- rest_framework/request.py
- rest_framework/routers.py
- rest_framework/throttling.py
- rest_framework/utils/breadcrumbs.py
Add / remove some blank lines around docstrings to make the autistic(ish) devs like me happy :cake: :smile:
> Fix blank lines around docstrings

- rest_framework/filters.py
In Django 1.8 [`Query.aggregates` is replaced by `annotations`](https://docs.djangoproject.com/es/1.9/releases/1.8/#aggregate-methods-and-modules).
Using aggregates currently raises a `RemovedInDjango110Warning`. See [Django's source](https://github.com/django/django/blob/1.8.11/django/db/models/sql/query.py#L194). This PR fixes it.
> Fixed use of deprecated Query.aggregates

- .travis.yml
- rest_framework/__init__.py
- rest_framework/compat.py
- rest_framework/response.py
- rest_framework/serializers.py
Hey guys,
we are bumping our app to newest Django and I started working a little bit on some changes that are already not supported in Django 1.9.4
However, exception I catch... I am not sure if this is proper way.
Due to change of `m2m.add()` now Django by default picks `bulk=True`, which is something we don't want here.
For now, workaround is to catch exception and try to do `.add(bulk=False)` but it is not perfect solution.
Could you point me in a way how to check if this is M2M or One2One relation? Or foreign key?
> [2.4] Fixes for Django 1.9

- docs/topics/release-notes.md
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/models.py
- tests/test_relations_pk.py
Replaces #3915
> A nullable foreign key with a UUID primary key on the other end would result in incorrect serialisation as (the string) 'None'.
> 
> This PR adds a minimal test case and fix.
> Fix None UUID ForeignKey serialization

- docs/api-guide/serializers.md
- docs/topics/third-party-resources.md
Follow up to #2148 and #2682.  Per the discussion, HTML JSON Forms support will remain a third party package for now.
> links to html-json-forms package

- docs/topics/3.1-announcement.md
- rest_framework/pagination.py
http://cramer.io/2011/03/08/building-cursors-for-the-disqus-api/ 404s but 
http://cramer.io/2011/03/08/building-cursors-for-the-disqus-api works.
> remove trailing slash from cramer cursor link

- docs/api-guide/viewsets.md
The `ModelViewSet` inherits from the `UpdateModelMixin`, which provides the `.partial_update` method. This should be reflected in the documentation.  It should be noted that this is already documented in the `ModelViewSet` docstring:
```python
class ModelViewSet(mixins.CreateModelMixin,
mixins.RetrieveModelMixin,
mixins.UpdateModelMixin,
mixins.DestroyModelMixin,
mixins.ListModelMixin,
GenericViewSet):
"""
A viewset that provides default `create()`, `retrieve()`, `update()`,
`partial_update()`, `destroy()` and `list()` actions.
"""
pass
```
> Add .partial_update to ModelViewSet documentation

- rest_framework/views.py
Determining the version and performing content negotiation should be done before ensuring the permission of the request. The reason is that these information can be used in handling the exceptions. For example different versions may return different error scheme. Also, the rendering class can be used to determine how to exception handler response should be rendered.
> Reorder initializing the view

- rest_framework/authentication.py
> type('') to str

- rest_framework/views.py
- tests/test_authentication.py
A view with no `authentication_classes` set and that fails a
permission check should raise a 403 with the message from the
failing permission.
Fixes #4039
> No auth view failing permission should raise 403

- rest_framework/authentication.py
#4025 introduced a `string_types` comparison before encoding headers data. However, `string_types` are both binary and unicode in Python 2 and we don't want to encode binary data.
This change fixes that error by using `text_types` instead.
> Fix the string_types / text_types confusion introduced in #4025

- rest_framework/filters.py
- tests/test_filters.py
Two small changes to the `OrderingFilter`'s browsable API display.
1. Always use `Field.verbose_name` when `__all__` is specified as `Field.label` doesn't exist;
2. Marked the ordering labels (`'ascending'`, `'descending'`) for translation.
> OrderingFilter adjustements

- .gitignore
- tests/browsable_api/test_browsable_nested_api.py
- tests/test_model_serializer.py
Classes whose name begins with `Test` but are not test classes were collected by py.test, and giving the following errors at the end of the test run:
```
WC1 test_model_serializer.py cannot collect test class 'TestMetaClassModel' because it has a __init__ constructor
WC1 browsable_api/test_browsable_nested_api.py cannot collect test class 'TestNestedSerializerSerializer' because it has a __init__ constructor
779 passed, **2 pytest-warnings** in 3.57 seconds
```
I changed the name so that the meaning is the same but they are not picked up as tests.
Also running the tests produced a coverage.xml file which was not in .gitignore and I added as `coverage.*` since py.test also supports other report formats like *.html etc.
> Fix warnings when running tests

- rest_framework/renderers.py
- rest_framework/static/rest_framework/js/csrf.js
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
Instead of hardcoding the CSRF cookie name, the value is passed to the template as a context variable, rendered as a JavaScript variable, and read by csrf.js.
refs #4048
> Added support for custom CSRF cookie names

- rest_framework/fields.py
- tests/test_fields.py
`DecimalField` has some support for non strict number of decimal places (checking here and there that `decimal_places` is not None but it fails in `quantize()` with "unsupported operand type(s) for ** or pow(): 'Decimal' and 'NoneType'".
This changeset fixes the problem and allows `DecimalField` to handle `decimal_places=None`. Tests added too.
> Fixed DecimalField arbitrary precision support

- docs/api-guide/authentication.md
This fixes #4081.
Simply removes references to migrations as they are expected to be part of 3rd parties and there's nothing to take care about:
- order is already contained in the migration file
- superuser can't be created before migrations (removed the warning about that special use case with South).
> Remove references to South as we don't need it any longer.

- rest_framework/authentication.py
- tests/test_authentication.py
Fixes #4089
Includes regression test.
> Handle incorrectly padded HTTP basic auth header

- .travis.yml
- tox.ini
should the python 3.2 checks dropped?
> added python 3.5 checks for django 1.8

- docs/api-guide/permissions.md
I believe this is a simple spelling typo in the docs.
> Fix typo in permissions docs

- docs/api-guide/authentication.md
- rest_framework/authentication.py
- tests/test_authentication.py
This allows subclassing TokenAuthentication and setting custom keyword,
thus allowing the Authorization header to be for example:
Bearer 956e252a-513c-48c5-92dd-bfddc364e812
It doesn't change the behavior of TokenAuthentication itself,
it simply allows to reuse the logic of TokenAuthentication without
the need of copy pasting the class and changing one hardcoded string.
Related: #4080
> TokenAuthentication: Allow custom keyword in the header

- rest_framework/pagination.py
- tests/test_pagination.py
This fixes #4079 which raised exception in the Browsable API when using `LimitOffsetPagination` and `limit` is set to 0.
Thanks to @awbacker for raising the issue.
> Prevent raising exception when limit is 0

- docs/api-guide/serializers.md
Document allow_empty arguments for ListSerializer fields or serializers with `many=True`
> Document allow_empty argument

- rest_framework/renderers.py
> Set proper status code in AdminRenderer for the redirection after POST/DELETE requests.

- rest_framework/fields.py
None values in childs of DictField, ListField not check in representation.
> Fields. Fix None values representation in childs of ListField, DictField.

- rest_framework/utils/serializer_helpers.py
Fixes typos in the <code>ReturnDict</code> and <code>ReturnList</code> docstrings.
> Fix typos in ReturnDict and ReturnList docstrings

- rest_framework/validators.py
- tests/test_validators.py
This PR fix a bug in `UniqueValidator` when applied to related model fields. As discussed in #3844 , I first made a proposal, with a demo code and no test, and it got rejected. Two days ago, somebody reported the same error as I met, so I think I should spent a little more time on this and add a regression testcase for this bug fix.
When serializers has fields with something like `source=user.email`, the
uniqueness validator should check `email` field instead of `user`, cause
`user` is a model object.
> Fix #3844, refine validator for fields with <source=> kwargs

- rest_framework/filters.py
- tests/test_filters.py
`OrderingFilter` backend checks whether a view specifies an
`ordering_fields` or `serializer_class` attribute. Views can however
override `get_serializer_class` to determine the serializer class
but the `OrderingFilter` doesn't catch this. This patch fixes that.
Here's an example of a view that would benefit from this patch:
```py
class MyView(generics.ListAPIView):
queryset = MyModel.objects.all()
filter_backends = (filters.OrderingFilter, )
def get_serializer_class(self):
return MySerializer
```
This would formerly raise an `ImproperlyConfigured` error.
> Use get_serializer_class in ordering filter

- rest_framework/filters.py
In django-guardian 1.4.2 version has list type and [1,4,2] >= (1,3) return False
Type should not depend on a third party library.
> Wrap guardian.VERSION in tuple

- CONTRIBUTING.md
- docs/api-guide/authentication.md
- docs/api-guide/fields.md
- docs/api-guide/filtering.md
- docs/api-guide/serializers.md
- docs/topics/2.4-announcement.md
- docs/topics/browsable-api.md
- docs/topics/contributing.md
- docs/topics/third-party-resources.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified. I also fixed some which weren't quite pointing at the wrong thing.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- rest_framework/metadata.py
- tests/test_metadata.py
Listing related fields can leak sensitive data and result in poor performance
when dealing with large result sets.
Large result sets should be exposed by a dedicated endpoint instead.
> Fixed #3751 -- Stopped listing related field choices through metadata.

- .travis.yml
- requirements/requirements-optionals.txt
Replaces #4028. Just pulls in @avuipy's work from there. 
Django Filter is already 1.10 compatible. It just needed updating. 
Opening PR to see what Travis says.... — And it's good. 
Removing Django 1.10 from allowed_failures. 
@tomchristie fixed the underling issue (identified in #4028) in 994e1ba927cb93b674330c885375b0409ea725cf. 
He removed the `abstract = True` from `BaseFilterableItem` in the the test suite. 
This was introduced in 4d45865b. The test there was to check that subclasses of the FilterSet's model class are correctly allowed by `get_filter_class`. There's nothing about this that requires allowing abstract superclasses. 
**If** this is needed, **if** it's an issue, it's an issue with Django-Filter. I'm happy to look at issues there, but it's out of scope for DRF.
> Updated Guardians and Filter Versions

- rest_framework/authtoken/migrations/0001_initial.py
- rest_framework/authtoken/migrations/0002_auto_20160226_1747.py
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/serializers.py
- rest_framework/utils/model_meta.py
- tests/test_authentication.py
- tests/test_filters.py
- tests/test_generics.py
- tests/test_metadata.py
- tests/test_model_serializer.py
- tests/test_multitable_inheritance.py
- tests/test_permissions.py
- tests/test_relations_generic.py
- tests/test_relations_slug.py
- tests/test_response.py
- tests/test_utils.py
- tests/test_validation.py
- tests/test_validators.py
Cleaning up areas of the codebase that currently raise deprecation warnings.
Running tests with `PYTHONWARNINGS=once py.test tests -s` in order to highlight these.
Closes #3906
Closes #4062
> Clean up existing deprecation warnings.

- rest_framework/templates/rest_framework/horizontal/checkbox.html
- rest_framework/templates/rest_framework/horizontal/checkbox_multiple.html
- rest_framework/templates/rest_framework/horizontal/input.html
- rest_framework/templates/rest_framework/horizontal/radio.html
- rest_framework/templates/rest_framework/horizontal/select.html
- rest_framework/templates/rest_framework/horizontal/select_multiple.html
- rest_framework/templates/rest_framework/horizontal/textarea.html
- rest_framework/templates/rest_framework/raw_data_form.html
- rest_framework/templates/rest_framework/vertical/checkbox.html
- rest_framework/templates/rest_framework/vertical/checkbox_multiple.html
- rest_framework/templates/rest_framework/vertical/input.html
- rest_framework/templates/rest_framework/vertical/radio.html
- rest_framework/templates/rest_framework/vertical/select.html
- rest_framework/templates/rest_framework/vertical/select_multiple.html
- rest_framework/templates/rest_framework/vertical/textarea.html
Some fields in django forms (SetPasswordForm for example, new_password1 field) have html help_text. I think in browsable api help_text must be rendered as is.
> Do not escape html help_text in browsable api

- docs/api-guide/parsers.md
Better documentation on using a filename URL keyword argument.
Closes #4167.
[ci skip]
> Update FileUploadParser docs.

- rest_framework/authtoken/models.py
guess proposed change make sense as of dj 1.8+
> removed AUTH_USER_MODEL compat property

- rest_framework/serializers.py
- tests/test_serializer_bulk_update.py
When `.is_valid` fails for a ListSerializer, the `.validated_data` attribute should be `[]`, not `{}`.
When `is_valid` passes for a ListSerializer, the `.errors` attribute should be `[]`, not `{}`.
Note that users don't typically hit this, as they've already checked `is_valid`, so the empty case doesn't get typically get inspected.
Closes #3437.
Closes #3434.
Closes #3476.
Thanks to @nip3o, @jpadilla and @xordoquy.
> Empty cases of .validated_data and .errors as lists not dicts for ListSerializer

- rest_framework/renderers.py
- tests/browsable_api/test_form_rendering.py
For custom view where a POST request returns a list of objects,
the browsable API can fail with a `TypeError` when attempting to render the form.
Broadly, this is because it is attempting to render a single-item serializer, with a list of data.
This pull request implements a more robust fallback when the initial form rendering fails.
Closes #3164.
> More robust form rendering in the browsable API

- docs/api-guide/validators.md
- rest_framework/serializers.py
- tests/test_model_serializer.py
- tests/test_validators.py
Closes #2848
Docs update closes #2996
Docs update closes #3970
> Exclude read_only=True fields from unique_together validation & add docs.

- rest_framework/pagination.py
- tests/test_pagination.py
Treat `limit=0 in the same way as an other invalid amount in the `limit` parameter.
> In LimitOffsetPagination `limit=0` should revert to default limit.

- tests/test_relations_pk.py
> Add test confirming that required=False is valid on a relational field.

- rest_framework/fields.py
- tests/test_fields.py
Closes #4013.
Closes #4019.
Ignore strings and pass through as-is from date/time fields.
Note that the existing implementation in TimeField/DateField was unnecessarily convoluted.
We can't know that the strings are necessarily in the correct format, but since they're already a valid type we'll just pass them through as-is.
> Pass through strings as-in with date/time fields.

- rest_framework/filters.py
- tests/test_filters.py
Calling distinct can have disastrous performance impact. This patch makes sure we only call it if required.
> Prevented unnecessary distinct() call in SearchFilter.

- rest_framework/filters.py
> Minor refactoring of `must_call_distinct`

- .travis.yml
- rest_framework/validators.py
- tests/test_validators.py
Uniqueness checks for an invalid value should quietly pass, as the value does not exist.
This allows other validators to correctly catch the invalid input and return an appropriate error message, rather than resulting in a hard 500 failure.
Closes #3381
Closes #3493
> Robust uniqueness checks.

- tests/test_versioning.py
Set `ALLOWED_HOSTS = ['*']` during hostname versioning tests.
> Resolve tests against Django master

- rest_framework/utils/html.py
- tests/test_serializer_nested.py
Parsing multipart data using a nested serializer with a list can result in incorrect behavior. If the list contains more than one item, only the last item will be saved.
Here is an example:
```python
class NestedSerializer(serializers.Serializer):
example = serializers.MultipleChoiceField(choices=[1, 2, 3])
class TestSerializer(serializers.Serializer):
nested = NestedSerializer()
```
When you send the following data formatted as JSON everything will be fine:
```python
{
'nested': {
'example': [1, 2],
}
}
{
'nested': {
'example': [1, 2],
}
}
```
However, when you send the same data formatted as multipart data the serialized object will only take the last element of the list:
```python
{
'nested.example': [1, 2]
}
{
'nested' {
'example': 2,
}
}
```
The bug is situated in …
> Fix parsing multipart data using a nested serializer with list

- docs/api-guide/validators.md
This fixes a bug in the documentation of the "optional fields" extra_kwargs.
> Added missing colon in extra_kwargs documentation

- rest_framework/routers.py
I have a serializer:
```python
class TestViewSet(viewsets.ViewSet):
@list_route(['PUT'])
def update(self, *args, **kwargs):
return Response({})
@list_route(['PUT'])
def hello_rest(self, *args, **kwargs):
return Response({})
```
and a router config
```python
router = routers.DefaultRouter(trailing_slash=False)
router.register('test', TestViewSet, base_name='test')
```
Ideally the above configuration should fail as per https://github.com/tomchristie/django-rest-framework/blob/d41ddc9e5f3346892e46659245522d4be8abdc1a/rest_framework/routers.py#L157.  But this passess.
And when I remove the the method hello_rest it fails as expected.
> Fix issues with routers for custom list-route and detail-routes

- setup.py
When compile djang REST framework with pypandoc using OpenWRT toolchain,
it raises the error:
```
warning: pypandoc module not found, could not convert Markdown to RST
File "./setup.py", line 86, in <module>
long_description=read_md('README.md'),
File "./setup.py", line 19, in read_md
return open(f, 'r').read()
File "/GIT_POOL/OpenWRT/OpenWrt-SDK-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, …
```
> Fix the error without specified encoding when compiling

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
Added support for localized decimal and float fields.
Addresses #2897
> Add localize keyword argument to `DecimalField`

- docs/api-guide/authentication.md
- docs/api-guide/content-negotiation.md
- docs/api-guide/filtering.md
- docs/api-guide/format-suffixes.md
- docs/api-guide/generic-views.md
- docs/api-guide/parsers.md
- docs/api-guide/permissions.md
- docs/api-guide/renderers.md
- docs/api-guide/serializers.md
- docs/api-guide/settings.md
- docs/api-guide/throttling.md
- docs/api-guide/validators.md
- docs/api-guide/views.md
- docs/index.md
- docs/topics/2.3-announcement.md
- docs/topics/3.0-announcement.md
- docs/tutorial/2-requests-and-responses.md
- docs/tutorial/3-class-based-views.md
- docs/tutorial/4-authentication-and-permissions.md
- docs/tutorial/quickstart.md
Added a dash between "class based" in the phrase "using the GenericAPIView class based views". After a quick Google search I found that the official Django docs refer to class-based views with a dash.
Thank you for considering this small pull request!
> Replace "class based views" occurrences with "class-based views"

- rest_framework/response.py
> Resolve incorrect inclusion of media type parameters

- rest_framework/utils/encoders.py
> Don't strip microseconds in JSON output.

- docs/api-guide/filtering.md
- tests/test_filters.py
- tests/test_model_serializer.py
- tests/test_renderers.py
- tests/test_versioning.py
- tests/test_write_only_fields.py
assertEquals is deprecated in favor of assertEqual
app_name is a required keyword as of Django 1.10
> lookup_type is deprecated in favor of lookup_expr

- docs/tutorial/2-requests-and-responses.md
Changed http://example.com/api/items/4/.json to http://example.com/api/items/4.json
> Change incorrect example URL in Tutorial

- docs/index.md
Currently generating invalid URL at index page.
http://www.django-rest-framework.org/'api-guide/schemas.md'
Though it is correct in navigation.
> Fix Typo in index.md

- docs/tutorial/7-schemas-and-client-libraries.md
The coreapi command line arguments are missing an equal sign between the argument and the value.
> Fix coreapi param arguments.

- docs/api-guide/schemas.md
Couple of updates on the schema view examples in the documentation:
1. The returns from the views needs to be an HTTP Response
2. I found that instantiating the generator at the module level caused an import error when starting Django, likely because it is executing before all the app load magic happened. Moving it inside the view method solves this.
> Schema documentation update

- setup.cfg
The wheel released on Pypi does not include the license file . The way to do this is by updating the setup.cfg accordingly. This fix will ensure that the LICENSE.md file is available in the `dist-info` dir of the built wheels as `LICENSE.txt`.
This way folks redistribution an official DRF wheel are complying with the BSD license... otherwise they would not by virtue of not including the license text!
> Add LICENSE.md to the built wheel

- docs/api-guide/schemas.md
A small fix in implementation of SwaggerRenderer. The `.dump()` method must be called as an instance method.
> Fix SwaggerRenderer implementation example

- rest_framework/filters.py
- tests/test_filters.py
The meta information stored in opts needs to be restored for
each search field. Otherwise it references the wrong model
when an attribute of a related model comes before an attribute
of the original model in search fields. This doesn't apply to
m2m relations since must_call_distinct returns True in that
case.
> Restore meta information for each search field.

- rest_framework/utils/field_mapping.py
- tests/test_validators.py
It should use `verbose_name`, not `object_name`, took me 2 hours to find out why parts of error were not translated as I didn't expect it to happen in drf.
> use verbose_name instead of object_name in field_mapping

- docs/api-guide/schemas.md
- rest_framework/compat.py
- rest_framework/routers.py
- rest_framework/schemas.py
> Added `url` and `schema_url` arguments.

- rest_framework/schemas.py
simplify_regex return an url with a leading slash which is interpreted as a root path by urlparse;
```
>>> urlparse.urljoin("http://localhost:8000/api/", "/foo/")
'http://localhost:8000/foo/'
```
leads to SchemaGenerator returning a wrong link.
> urljoin with leading slash remove part of path

- rest_framework/fields.py
- tests/test_fields.py
> Handle non-string input for IP fields

- rest_framework/fields.py
- tests/test_fields.py
`DecimalField` now quantizes incoming values, ensuring that the resulting value includes the correct representation.
Previous the value would be correct, but would not be associated with the precision used by the field, so eg...
>>> class ExampleSerializer(serializers.Serializer):
>>>     total_price = serializers.DecimalField(max_digits=5, decimal_places=2)
>>> serializer = ExampleSerializer(data={'total_price': '12'})
>>> assert serializers.is_valid()
>>> print serializer.validated_data['total_price']
12.00  # Now correctly represented. Previously would print 12.
Closes #4318.
> Quantize incoming digitals

- rest_framework/parsers.py
- tests/test_parsers.py
If a Content-Disposition including a `filename=` parameter is not included, then always raise a consistent and informative error. Previous behavior would be:
* Small files raised an unhelpful and non-descriptive `ParseError`.
* Large files succeeded with a randomly generated system filename.
Closes #3610.
Closes #4296.
> Descriptive error from FileUploadParser when filename not included.

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_serializer.py
When a partial update is applied, defaults should never be populated.
The only fields which get values should be those that are explicitly included.
Closes #3565.
> Serializer defaults should not be included in partial updates.

- rest_framework/renderers.py
Make ``TemplateHTMLRenderer`` more subclass-friendly. Refs #4230.
- Change the name of ``resolve_context()`` to ``get_template_context()``.
- Pass the renderer context to this method, to give subclasses more flexibility
when overriding.
This allows users to write code like this:
```
class ViewInContextHTMLRenderer(TemplateHTMLRenderer):
def get_template_context(self, data, renderer_context):
context = super().get_template_context(data, renderer_context)
context['view'] = renderer_context['view']
return context
```
Or maybe even:
```
class ExtraContextHTMLRenderer(TemplateHTMLRenderer):
def get_template_context(self, data, renderer_context):
context = super().get_template_context(data, renderer_context)
context.update(renderer_context['extra_template_context'])
return context
``` …
> Change template context generation in TemplateHTMLRenderer

- rest_framework/serializers.py
- tests/test_model_serializer.py
When an option is specified in extra_kwargs it should always override any implict extra_kwargs that are generated by uniqueness constraints.
Closes #4199.
Closes #4198.
> extra_kwargs takes precedence over uniqueness kwargs

- docs/api-guide/validators.md
Not having imports in the docs is always confusing... I added them to the validators section here.
See http://stackoverflow.com/questions/28848221/validation-in-django-rest-framework for another person who was confused by this.
> Add imports in validators docs

- rest_framework/schemas.py
Refs #4356
`HEAD` shouldn't be included in `allowed_methods`, as it's not required, but let's not error if it is.
> Filter HEAD out from schemas

- rest_framework/compat.py
- rest_framework/permissions.py
- rest_framework/schemas.py
- rest_framework/throttling.py
> Access `request.user.is_authenticated` as property not method, under Django 1.10+

- rest_framework/schemas.py
- rest_framework/viewsets.py
- tests/test_schemas.py
When a view is instantiated using `as_view()` any additional keyword arguments that have been passing in `as_view()` should also be respected when performing schema generation.
Closes #4331.
Closes #4330.
> Include kwargs passed to 'as_view' when generating schemas.

- rest_framework/renderers.py
Remove erronous `self` argument.
>  Fix call to TemplateHTMLRenderer.resolve_context() fallback method.

- rest_framework/relations.py
Closes #3329.
Closes #3330.
Closes #3877.
Thanks to @rubendura and @blag for the work on this.
> Limit queryset when rendering relational choices.

- docs/api-guide/versioning.md
- rest_framework/versioning.py
- tests/test_versioning.py
When only `ALLOWED_VERSIONS` but no `DEFAULT_VERSION` is specified, a
version should be enforced.  When changing this, no existing tests were
failing.  This adds tests for the fixed behavior.
The old behavior can be restored by adding `None` explicitly to
`ALLOWED_VERSIONS`.
> Fix handling of ALLOWED_VERSIONS and no DEFAULT_VERSION

- rest_framework/views.py
Closes https://github.com/tomchristie/django-rest-framework/issues/4042
> Show Traceback HTML in browsable API

- rest_framework/relations.py
- tests/test_model_serializer.py
> .choices property of RelatedField should preserve non-string values.

- rest_framework/fields.py
- rest_framework/relations.py
- tests/test_fields.py
- tests/test_model_serializer.py
CharField now only accepts string and numeric types, and will raise a validation error on other inputs.
Closes #3394.
> Stricter type validation for CharField.

- rest_framework/schemas.py
- tests/test_schemas.py
Closes #4278.
Closes #4279.
Closes #4373.
Closes #4382.
> Pass request to schema generation

- rest_framework/schemas.py
- tests/test_schemas.py
> Fix schema categories for custom list actions

- rest_framework/fields.py
It seems that the example was copy&pasted and not updated properly.
> Fix comment for SerializerMethodField.bind method

- rest_framework/utils/urls.py
- tests/test_pagination.py
Fixes issue with pagination when the url contains empty query params. The previous implementation would strip out any empty query params from the `next` and `previous` urls. This PR fixes the query parsing and ensures that empty query params are preserved.
This possibly fixes #3328.
> Don't strip empty query params when paginating

- rest_framework/schemas.py
> Fix issue with generating categories for schema endpoints

- docs/api-guide/permissions.md
I think the [permissions section of the docs](http://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy) has an error in the code example concerning using the `@api_view` decorator with function based views.
> fix a b0rked code example in the permissions section of api guide

- rest_framework/templates/rest_framework/vertical/checkbox_multiple.html
Fixes template syntax error for `as_list_of_strings` introduced in v3.4.4 from PR https://github.com/tomchristie/django-rest-framework/pull/4374
> Fix template syntax error for `as_list_of_strings`

- rest_framework/request.py
- tests/test_request.py
Multipart uploads are included in the `.request.POST` attribute, when they should *only* appear in `request.FILES`.
Typically this won't be noticed as users of REST framework will be typically working with the unified `request.data` instead, but it is nonetheless a bug.
> Do not include request.FILES items in request.POST

- rest_framework/schemas.py
- tests/test_schemas.py
> Include .action attribute on viewsets when generating schemas

- README.md
Before this:
```
$ python setup.py bdist_rpm --spec-only
warning: pypandoc module not found, could not convert Markdown to RST
running bdist_rpm
running egg_info
creating djangorestframework.egg-info
writing djangorestframework.egg-info/PKG-INFO
writing top-level names to djangorestframework.egg-info/top_level.txt
writing dependency_links to djangorestframework.egg-info/dependency_links.txt
writing manifest file 'djangorestframework.egg-info/SOURCES.txt'
reading manifest file 'djangorestframework.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'djangorestframework.egg-info/SOURCES.txt' …
```
> Replace utf8 character ' with its ascii counterpart, makes bdist_rpm happy on CentOS 7

- rest_framework/request.py
- rest_framework/views.py
Closes #4409 
Ensures that Django's standard exception handling still runs in all uncaught cases, but forces the debug.technical_500_response to render in either plaintext or html, depending on the content negotiation that's taken place.
We have to implement a hack to achieving this, overriding the underlying `HTTPRequest.is_ajax()` method, however this is probably better than the alternative of reimplementing and keeping up to date with Django's exception handling inside REST framework.
> Improve debug error handling

- docs/api-guide/permissions.md
Adds a section linking to [django-rest-framework-roles](https://github.com/computer-lab/django-rest-framework-roles) in the _permissions_ docs.
* Verified that `mkdocs build` runs.
* Verified that the rendered markdown looks pleasing with `mkdocs serve`
> Add django-rest-framework-roles to third party packages in permissions docs

- rest_framework/relations.py
> Add `__str__` method to `PKOnlyObject`

- rest_framework/serializers.py
This small pull request includes the original exception traceback in the re-raised TypeError, re: #3503. If there is an error somewhere during the create operation the error message turns from:
```
...
File "/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 863, in create
raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Document.objects.create()`. This may be because you have a writable...
Original exception text was: 'NoneType' is not iterable.
```
To the much more helpful:
```
File "/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 863, in create
raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Document.objects.create()`.  This may be because you have a writable field on... …
```
> Improve Create to show the original exception traceback

- rest_framework/schemas.py
- tests/test_schemas.py
Fixes #4425 by skipping HiddenField in SchemaGenerator.get_serializer_fields. Tests for HiddenField as well as serializer fields with `read_only=True`.
> Skip HiddenField from Schema fields

- docs/api-guide/throttling.md
There was a mistake in this code example in article about throttling:
```python
import random
class RandomRateThrottle(throttling.BaseThrottle):
def allow_request(self, request, view):
return random.randint(1, 10) == 1
```
The description says it throttles one random request in each 10, while in reality it throttles 9 out of 10. Fixed this.
> Throttling random request code example fix

- rest_framework/test.py
- tests/test_testing.py
If the URL contains unicode arguments, `APIClient` and `APIRequestFactory` `.get()` cause an exception to be raised when the request query dict is accessed, because we end up with an unicode `QUERY_STRING` and that's not what django expects. 
Without this patch (which is [adapted from django](https://github.com/django/django/blob/5bd967e1c52bfe811daffaccd3ef8964f8a3cb35/django/test/client.py#L402-L408)), the test I've added fails with:
```
tests/test_testing.py:252: in test_request_factory_url_arguments_with_unicode
self.assertEqual(dict(request.GET), {'demo': [u'testé']})
../../.virtualenvs/drf-testing/local/lib/python2.7/site-packages/django/utils/functional.py:35: in __get__
res = instance.__dict__[self.name] = self.func(instance) …
```
> Fix APIClient.get() when path contains unicode arguments

- rest_framework/decorators.py
When run the `django.core.urlresolvers.resolve ( '/')` to the @api_view decorated function, ResolverMatch.func_name has been set a invalid dotted name
https://github.com/tomchristie/django-rest-framework/issues/4462
> Fixed an issue where the incorrect value is set to ResolverMatch.func_name of api_view decorated view  #4462

- docs/api-guide/serializers.md
There was a part in the docs that said reverse relations were explained "below" but they were actually referenced in the serializer relations file. Fixed to include the link to the proper file
> Update to correct location of reverse relation doc

- rest_framework/templates/rest_framework/base.html
In commit 5392be4ddba37da3e50c3feabc8b3b1c944481a8, there was a [change made](https://github.com/tomchristie/django-rest-framework/commit/5392be4ddba37da3e50c3feabc8b3b1c944481a8#diff-261afecdd8ae47666b7560a36e554180R153) when cleaning up the template for the API listing that caused 2 spaces to appear before every header item (except the first) and before the first line of the body of the response. This meant that the API listing often looked like:
```
HTTP 200 OK
Allow: GET, OPTIONS
Content-Type: application/json
Vary: Accept
{
"key": "value",
"key2": "value2"
}
```
This change removes those leading spaces, so that it will now look like:
```
HTTP 200 OK
Allow: GET, OPTIONS
Content-Type: application/json
Vary: Accept
{
"key": "value",
"key2": "value2"
}
```
> Fix indentation regression in API listing

- rest_framework/response.py
This PR allows `response.render` to be called when `response.rendered_context == {}`.
I believe this should be allowed, since if [the JSONRenderer, for example](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/renderers.py#L85-L92) receives a `None` context, it sets it to an empty dictionary itself.
> Fix response rendering with empty context

- docs/api-guide/authentication.md
Minor **documentation fix** only.
Seems `BasicToken` was renamed to `Token` in commit 003a65f but the docs were not updated accordingly.
> Rename an invalid reference to BasicToken in the docs

- rest_framework/request.py
- tests/test_parsers.py
> Fallback behavior for request parsing when request.POST already accessed

- README.md
- docs/api-guide/permissions.md
- docs/topics/release-notes.md
- requirements/requirements-optionals.txt
- rest_framework/__init__.py
- rest_framework/fields.py
- rest_framework/relations.py
- rest_framework/renderers.py
- rest_framework/request.py
- rest_framework/schemas.py
- rest_framework/serializers.py
- rest_framework/static/rest_framework/js/csrf.js
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- rest_framework/templates/rest_framework/vertical/checkbox_multiple.html
- rest_framework/test.py
- rest_framework/views.py
- tests/test_api_client.py
- tests/test_request.py
- tests/test_schemas.py
> API client

- docs/api-guide/filtering.md
- enabling validations on incoming query params with the ease of adding new filters as easy as adding a new key in a dict.
> add drf-url-filters app to django-rest-framework in filtering docs

- docs/api-guide/validators.md
- rest_framework/validators.py
- tests/test_validators.py
Sometimes fields need to be validated as unique in a case insensitive manner, e.g. a usernames. This PR adds a `ignore_case` argument to `UniqueValidator` which causes the queryset lookup to use `iexact`.
Haven't added any tests yet - wanted to first see if you think this is useful and the right approach.
> Case insensitive uniqueness validation

- docs/api-guide/filtering.md
- docs/topics/third-party-resources.md
This pull request fixes a typo in name of a python package `voluptuous` in filtering docs and adds `drf-url-filters` in topics/third-party-resources under filtering topic.
> add drf-url-filters in third party filtering resources and fixed typo

- docs/api-guide/relations.md
`The Roots` are the band: https://en.wikipedia.org/wiki/The_Roots
`Undun` is their album: https://en.wikipedia.org/wiki/Undun
This was reversed in the docs, so I switched them around.
> Corrected `artist` and `album_name` typo in docs

- rest_framework/mixins.py
- tests/test_prefetch_related.py
> Fix prefetch_related updates.

- rest_framework/schemas.py
When generating docs I noticed that the fields listed were the source fields instead of the field name defined. 
So i.e. if you had something like `new_name = serializers.IntegerField(source='db_name')` the generated docs would list db_name instead of new_name.
In my eyes the correct behaviour should be to use the defined name but I am willing to concede if there is a reason for using source.
> Use field name instead of source when generating docs

- rest_framework/fields.py
- tests/test_fields.py
When HTML form input is used, JSONField should treat the input as a JSON encoded string, rather than a JSON primitive.
Closes #4135
> Allow JSONField to handle HTML form input.

- rest_framework/request.py
- tests/test_testing.py
HTML form input has slightly differing behavior than non-form input. In particular any empty BooleanField is treated as `False` by default, because empty checkboxes do not send any value through.
For the case where no data is included in the request body we shouldn't treat this as an HTML input, unless a form content type has been explicitly included. (nb. have confirmed that at least chrome still includes the form content type with 0 length body in the case of submitting a form with a single empty checkbox.)
Refs. #3649
Closes #3891 - thanks for your work @callorico! 😄 
Closes #3892
Closes #3647
This change isn't perfect, but it is the most minimal change that we can make in order to fix the main issue. (BooleanField treated as True for empty input)
Other options would have been:
* Use …
> Do not treat empty non-form input as HTML.

- rest_framework/pagination.py
- tests/test_schemas.py
When Pagination class has custom `page_size_query_param` name, schema generation will throw exception:
```
rest_framework/schemas.py:361: in get_link
if fields and any([field.location in ('form', 'body') for field in fields]):
E   AttributeError: 'list' object has no attribute 'location'
```
> Fix schema generation with custom page_size pagination param

- rest_framework/serializers.py
Doesn't have an associated test case, but this should resolve the issue.
Closes #4312.
> Use field.source to perform check for writable nested field, not key.

- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- rest_framework/utils/model_meta.py
- tests/test_model_serializer.py
Closes #3674
Closes #3852
This fix specifically only addresses the issue described by the test cases.
It is possible that there is a related issue for the 'reverse' relationship case that we *also* need to deal with, but we can't do that unless/until we have a reproducible test case for it.
> Handle ModelSerializer case for relationships to models with custom pk.

- topics/third-party-resources/index.html
As proposed by Xavier (https://twitter.com/linovia_net/status/788341380284284928), this adds 9 links to our quite of articles in the form of tutorials (added `[Français]` before each to warn viewers]
> Add french tutorial links in thrid-party resources

- docs/api-guide/filtering.md
- requirements/requirements-optionals.txt
- rest_framework/filters.py
- tests/test_filters.py
Deprecate the built-in `rest_framework.filters.DjangoFilterBackend` in favour of the third-party `django_filters.rest_framework.DjangoFilterBackend`
Closes #4507 
Closes #3371
> Deprecate DjangoFilter backend

- docs/topics/3.5-announcement.md
... in section ModelSerializer 'fields' and 'exclude'
Fairly obvious, don't need to add more :)
> Fix code formatting missing in 3.5 announcement

- rest_framework/compat.py
when using with django-filter and rest_framework_swagger need to import coreapi before django-filter as django filter tries to load rest_framework.coreapi which is undefined at this point
> changing order of django-filter and core api imports in compat

- rest_framework/serializers.py
- tests/test_serializer.py
More robust check in serializer error handling.
Closes #4606.
> Fix for case of ListSerializer with single item

- rest_framework/schemas.py
- tests/test_schemas.py
> Fix schema base paths

- rest_framework/compat.py
- rest_framework/filters.py
- rest_framework/schemas.py
- tests/test_schemas.py
> Fix guardian import

- docs/api-guide/relations.md
- docs/tutorial/4-authentication-and-permissions.md
Django 2 demands this key, although ``on_delete=models.CASCADE`` is already default.
I specifically did not touch the documentation for the release notes for v. 3. I can update the PR if requested.
> added on_delete=models.CASCADE to models.ForeignKey in the documentation

- rest_framework/fields.py
- tests/test_fields.py
Fix #4602
py3k `is_simple_callable` was not accounting for variable args and kwargs
> Fix is_simple_callable with variable args, kwargs

- docs/api-guide/exceptions.md
APIException has a get_full_details() method but the documentation refers to full_details().
> Fix APIException full_details() typo in documentation

- rest_framework/views.py
Closes #4631. If anyone wants to progress this forward for Python 3.5+ we'll need test cases demonstrating the correct behavior in both cases.
> Don't lose exception info

- rest_framework/test.py
This class isn't actually used, got included during the work on the requests test client, but can actually be removed.
> Drop redundant requests adapter

- rest_framework/serializers.py
- tests/test_serializer.py
This is a better approach to fixing the `from fields import *` in `serializers` (see #4626/#4613).
- Field class imports are separated from utility imports (`SkipField`, `empty`, etc...)
- The test ensures all fields & related fields are imported into the serializers module. New field classes won't accidentally be skipped.
> Make serializer fields import explicit

- rest_framework/filters.py
- tests/test_filters.py
Fix FilterSet proxying to be aware of parent metaclasses.
Closes #4619.
> Fix FilterSet proxy

- rest_framework/exceptions.py
- tests/test_exceptions.py
Since `str` objects are immutable, appending to existing `str` creates
in fact a new `str` instance.
Thus `ErrorDetail.detail.code` attribute is lost after `str` concatenation operation.
> Fix support of get_full_details() for Throttled exceptions

- rest_framework/pagination.py
- tests/test_pagination.py
To do `GROUP_BY` queries in django requires one to use `.values()`
eg this groups posts by user getting a count of posts per user.
```
Posts.objects.order_by('user').values('user').annotate(post_count=Count('post'))
```
This would produce a value queryset which serializes its result
objects as dictionaries while `CursorPagination` requires a queryset
with result objects that are model instances.
This commit enables cursor pagination for value querysets.
- had to mangle the tests a bit to test it out. They might need
some refactoring.
- tried the same for `.values_list()` but it turned out to be
trickier than I expected since you have to use tuple indexes.
> Enable cursor pagination of value querysets.

- docs/topics/html-and-forms.md
- rest_framework/templates/rest_framework/horizontal/input.html
- rest_framework/templates/rest_framework/inline/input.html
- rest_framework/templates/rest_framework/vertical/input.html
This change adds support to use `'autofocus': True` in the style options and have the `autofocus` attribute included on the input field when rendered.
> Add autofocus support for input.html templates

- tox.ini
Bump release versions to 1.10.3, 1.9.11 and 1.8.16
More info on:
https://www.djangoproject.com/weblog/2016/nov/01/security-releases/
> Update versions of Django on tox.ini

- rest_framework/schemas.py
This is to address https://github.com/tomchristie/django-rest-raml/issues/5
The problem is that if you try to generate RAML docs when you haven't set up any views, you get the above error (min called on an empty list).  
unfortunately, this PR is not very helpful since it doesn't actually surface a readable error to the user.  
Next steps:
- this PR should be updated to surface a readable error to the User in the browser.  Open to thoughts on best way to address...
> handle error when no links are found

- docs/api-guide/testing.md
- rest_framework/mixins.py
- tests/test_prefetch_related.py
Invalidate the prefetch cache instead of reloading the object from the database when a prefetch_related queryset is used with a PUT request.
Would be nice to also have a test case demonstrating why this approach has a different behavioral effect.
Closes #4661.
Refs #4553.
> Invalidate any existing prefetch cache on PUT requests.

- tests/test_relations_pk.py
not sure about how assertNumqueries should be converted
not sure about self.assertNotIn('target', serializer.validated_data)
and self.assertTrue(serializer.is_valid(), serializer.errors) ?
@xordoquy can you suggest?
> converted primary key relations test asserts to pytest

- docs/api-guide/fields.md
- docs/api-guide/settings.md
- Use https to access Python doc
- Point to Python 3 documentation instead of the legacy Python 2.
> Update the Python doc links to use https and point to Python 3

- docs/api-guide/fields.md
As of PR #4377, `max_digits=None` is allowed for `DecimalField`.
refs #4377 #4372
> docs: Fix description of `DecimalField`'s `max_digits`

- docs/tutorial/quickstart.md
Hi! 👋 
As discussed on #4731, it is somewhat easy make a mistake when following the quickstart tutorial. This change should help newcomers understand that ``DEFAULT_PERMISSION_CLASSES`` needs to be an iterable.
> Change DEFAULT_PERMISSION_CLASSES to a list in quickstart.md

- docs/api-guide/throttling.md
The Url to the settings/#caches Link changed in Django documentation, only one line changed.
> Updated Link ti Django Docs

- docs/api-guide/views.md
- rest_framework/views.py
It is possible to set custom exception handler using the `EXCEPTION_HANDLER` setting key.
But it's hard to override exception handler on per-view basis.
To do this it's necessary to override `rest_framework.view.APIView.handle_exception` method.
What is unreasonably complex.
This PR adds ability to easily override custom exception handler on view using `rest_framework.view.APIView.get_exception_handler` method.
> Add per-view custom exception handler support

- rest_framework/schemas.py
The order of the line break was wrong
When docstrings were like: 
```
retrieve: fetches some data.
Also the data will be formatted.
create: creates more data.
Take care of format
```
The generated string was:
```
retrieve: fetches some data.Also the data will be formatted.
```
Instead of 
```
retrieve: fetches some data.
Also the data will be formatted.
```
> Add new line correctly in docstring sections

- rest_framework/utils/breadcrumbs.py
- tests/test_utils.py
> Breadcrumb view name suffix fix

- docs/api-guide/metadata.md
Adds the thirs-party section to the metadata documentation as well as a link to and a short description of drf-schema-adapter
> Add drf-schema-adapter to 3rd party metadata mods

- docs/api-guide/serializers.md
Add DRF-Base64, which provides serializers to handle base64-encoded files, to third-party serializers packages
> Add DRF-Base64 to third-party serializers

- docs/api-guide/serializers.md
- rest_framework/serializers.py
- tests/test_serializer.py
This corresponds to a similar [PR](https://github.com/carltongibson/django-filter/pull/591) for django-filter. In short, the django form API supports a syntax for disabling fields on child forms ([django ticket](https://code.djangoproject.com/ticket/8620)), but this does not work on serializers.
Example:
```py
class Parent(forms.Form):
field = forms.CharField()
class Child(Parent)
field = None
```
> Add disabling of declared fields on serializer subclasses

- tests/test_urlpatterns.py
- tests/test_utils.py
> convert some more test asserts to pytest

- docs/tutorial/1-serialization.md
Django==1.8.17 chokes on this unless it’s just `snippets`.
I'm relatively new to Django and DRF but it appears as the documentation is wrong.
> Fixes documentation.

- rest_framework/utils/encoders.py
- tests/test_encoders.py
`JSONEncoder.default` didn't raise `RuntimeError` as intended because there is another "if" above which returns earlier.
Maybe it is better to put check for `coreapi` objects on top of `default` method?
> Raise `RuntimeError` when trying to encode coreapi objects

- docs/api-guide/schemas.md
- rest_framework/schemas.py
I have django virtual hosts, after last changes I've lost ability to generate swagger info for any domains but default one, this patch fixes it
> get view for django 'virtual hosts'

- docs/api-guide/serializers.md
Just noticed I misspelled paramaters -> parameters.  Sorry about that.
> fix a spelling error in api-guide

- docs/tutorial/3-class-based-views.md
Minor grammar fix.  The "that" seems to be necessary (citation needed).
> docs: tutorial: Minor grammar "fix"

- docs/api-guide/routers.md
- rest_framework/routers.py
Enabling custom reverse names on Viewsets detail_route and list_route using url_name parameter in decorator definition.
Example usage
```python
@detail_route(methods=['post'], url_path='experimental/save-feedback', url_name='save-feedback')
def save_feedback(self, request, pk=None):
pass
```
This allows us to retrieve our custom view using reverse utility by simply doing
```python
reverse('<viewset-base-name>-save-feedback')
```
instead than 
```python
reverse('<viewset-base-name>-experimental/save-feedback')
```
and in general reverse name can be customized as desired.
> Parametrizable viewset custom views reverse name

- rest_framework/compat.py
- rest_framework/fields.py
- tests/test_fields.py
Cleanup. `utc` backward compatibility wrapper is unnecessary. `utc` is available since Django 1.4 (see [b2f81ff0](https://github.com/django/django/commit/9b1cb755a28f020e27d4268c214b25315d4de42e#diff-b2f81ff06ef4aa2a1e7dbfbc620f73d6R87)).
> Removed unnecessary utc wrapper.

- rest_framework/templates/rest_framework/login_base.html
> Use correct label for username field in login template

- tests/test_one_to_one_with_inheritance.py
Added missing `on_delete` attribute to `OneToOneField`. `on_delete` is required since Django 2.0.
```
==================================== ERRORS ====================================
__________ ERROR collecting tests/test_one_to_one_with_inheritance.py __________
tests/test_one_to_one_with_inheritance.py:16: in <module>
class ChildAssociatedModel(RESTFrameworkModel):
tests/test_one_to_one_with_inheritance.py:17: in ChildAssociatedModel
child_model = models.OneToOneField(ChildModel)
E   TypeError: __init__() missing 1 required positional argument: 'on_delete'
```
> Added required on_delete attribute to OneToOneField field.

- docs/topics/documenting-your-api.md
I believe the original statement was wrong.  You can, in fact, document the various API endpoints of a ViewSet.
> Direct readers to info on how to add viewset docs

- rest_framework/utils/model_meta.py
Fixed #4574 and https://github.com/carltongibson/django-filter/issues/607. 
Bisected to https://github.com/django/django/commit/74a575eb7296fb04e1fc2bd4e3f68dee3c66ee0a (see [[1]](https://github.com/django/django/commit/74a575eb7296fb04e1fc2bd4e3f68dee3c66ee0a#diff-98e98c694c90e830f918eb5279134ab9R300)).
> Removed multi-table inheritance auto created PK from serialize.

- rest_framework/compat.py
- rest_framework/settings.py
Cleanup. `importlib` backward compatibility wrapper is unnecessary.  `importlib` is available in python>=2.7 (see [doc](https://docs.python.org/2/library/importlib.html)) and in python>=3.1 (see [doc](https://docs.python.org/3/library/importlib.html)), moreover in [rest_framework/schemas.py](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/schemas.py#L3) we already use `importlib` from stdlib.
> Removed unnecessary importlib wrapper.

- rest_framework/compat.py
- rest_framework/urlpatterns.py
- tests/test_routers.py
- tests/test_versioning.py
Fixed Django 2.0 compatibility due to `django.conf.urls.include` parameters change (see Django documentation [1.8](https://docs.djangoproject.com/en/1.8/ref/urls/#include), [2.0](https://docs.djangoproject.com/en/dev/ref/urls/#include)).
```
==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_routers.py ____________________
tests/test_routers.py:84: in <module>
url(r'^namespaced/', include(namespaced_router.urls, namespace='example')),
/django/conf/urls/__init__.py:44: in include
'Specifying a namespace in django.conf.urls.include() without '
E   django.core.exceptions.ImproperlyConfigured: Specifying a namespace in
django.conf.urls.include() without providing an app_name is not supported.
Set the app_name …
```
> Fixed Django 2.0 compatibility due to `django.conf.urls.include` parameters change.

- rest_framework/test.py
[RequestClient](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/test.py#L117) In this line it's checking with ':'. But think when url="example.com:2121" then this this check can't be OK. So if it checks only for `http` or `https` then we can use `http` for checking. :) That's all. :+1:
> fixed url checker ':' to 'http'

- rest_framework/utils/formatting.py
- tests/test_description.py
> Fixed `dedent` for tab indent.

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
You can use these two arguments to limit `ListField` member length
> Add max_length and min_length arguments for ListField

- rest_framework/static/rest_framework/docs/css/base.css
- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/index.html
- rest_framework/templates/rest_framework/docs/link.html
- rest_framework/templates/rest_framework/docs/sidebar.html
> Docs - Improve UI

- rest_framework/utils/model_meta.py
https://github.com/django/django/commit/0595bca221825c0c6bd572a32f3bf9eff7069328 reverted https://github.com/django/django/commit/74a575eb7296fb04e1fc2bd4e3f68dee3c66ee0a, hence we can revert 1ecbeebbe5e1f4ac5f7f8112d80f3ea13972cc0f that fixed bugs caused by https://github.com/django/django/commit/74a575eb7296fb04e1fc2bd4e3f68dee3c66ee0a (see also #4852, #4574).
> Reverted "Removed multi-table inheritance auto created PK from serialize".

- docs/api-guide/fields.md
Delete not relevant documentation paragraph.
Paragraph says about microseconds behavior which was changed in  https://github.com/tomchristie/django-rest-framework/pull/4256
> Refs: #4256 delete not relevant documentation

- docs/api-guide/serializers.md
Corrected documentation https://github.com/tomchristie/django-rest-framework/issues/4706
> [ISSUE-4706] API guide for serializers is outdated 

- docs/api-guide/serializers.md
I've added [drf-writable-nested](https://github.com/Brogency/drf-writable-nested) package to third-party serializer docs.
This package provides `WritableNestedModelSerializer` (based on `ModelSerializer`) and allows to create/update models with nested related fields.
> Add drf-writable-nested package to third-party serializers

- rest_framework/serializers.py
- tests/test_model_serializer.py
> Guard against the possible misspelling `readonly_fields` in model serializers

- docs/topics/jobs.md
This fixes the broken mailto link in http://www.django-rest-framework.org/topics/jobs/
> Fix mailto link

- docs/topics/documenting-your-api.md
Schemas as documentation: Examples link in topics/documenting-your-api/ points to a non existent api-guide page under topics. Added a parent directory short string at the beginning of the URL.
> Fix Schemas Example URL

- docs/index.md
The requirements on this page are outdated.  It lists Django Filter 0.9.2+ as an optional requirement, but filters.py includes code that will break if django_filters isn't at 1.0.1
django-rest-framework/filters.py 
from django_filters.rest_framework.filterset import FilterSet as DFFilterSet
django_filters only added the .rest_framework module in version 1.0.1.
(https://github.com/carltongibson/django-filter/releases/tag/1.0.1)
> Update django-filter requirement

- rest_framework/templates/rest_framework/admin/detail.html
- rest_framework/templates/rest_framework/admin/dict_value.html
- rest_framework/templates/rest_framework/admin/list.html
- rest_framework/templatetags/rest_framework.py
- tests/test_renderers.py
#4931 This shows that if the there is a dict with a key `items` or `iteritems`, less likely but it proves the point, the main content is not rendered.
> Add failing tests and fix for dict that have a key `items` #4931

- docs/tutorial/1-serialization.md
Use Django's built-in JsonResponse in the tutorial, rather than defining a custom `JSONResponse` class.
> Directly using Django's JSONResponse in the Tutorial

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_serializer.py
Fix for the issue described in #2785. 
When serializing an dict or object, now the default value is used if the key or attribute is missing from the dict or object. Previously a KeyError or AttributeError was raised.
Two tests failed after implementing the change, which was to be expected as they specifically targeted the behaviour of key or attribute being required even if default is set for the field (serializers.py, TestNotRequiredOutput). 
They have been replaced by tests targeting the use of defaults when key or attribute is not present in the instance. 
Deserialization seems unaffected.
What isn't clear to me is what the rationale was of explicitly requiring the instance key/attribute to be present, even if a default is provided, so I'm wondering if there's a scenario I'm …
> Allow required false and default

- rest_framework/__init__.py
- rest_framework/compat.py
Refs #4941. - See https://github.com/tomchristie/django-rest-framework/issues/4941#issuecomment-285393678.
> Ensure 'markdown' dependancy is optional.

- rest_framework/schemas.py
First time pull request.
I was getting the following error when trying out the new api documentation support feature.
```
UnboundLocalError: local variable 'model_field' referenced before assignment
```
I found that if the try/except on `model_field = model._meta.get_field(variable)` failed it would simply pass and not set the `model_field` to `None` which would then cause an error at line 536
```python
if model_field is not None and model_field.verbose_name:
```
Fixed this by telling the except to set `model_field` to `None`. Passed all the tests as per the guidelines.
> UnboundLocalError: local variable 'model_field' on schemas.py

- rest_framework/serializers.py
This commit fixes the issue when you set the keyword argument `source`
and your have not set the serializer fields explicitly. Then the
construction of field failed because there is not actually any model
field with that name.
However, you are still able to imply the name of model field by
taking advantage of the `source` keyword argument.
> Do not ignore source when building fields dynamically

- rest_framework/templates/rest_framework/base.html
- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/sidebar.html
- rest_framework/templates/rest_framework/horizontal/checkbox_multiple.html
- rest_framework/templates/rest_framework/horizontal/radio.html
- rest_framework/templates/rest_framework/inline/checkbox_multiple.html
- rest_framework/templates/rest_framework/inline/radio.html
- rest_framework/templates/rest_framework/vertical/checkbox_multiple.html
- rest_framework/templates/rest_framework/vertical/radio.html
Templates that use `obj.dict.items` should use the `obj.dict|items` template filter instead, so as not to break when a dictionary contains an key named `"items"` (Which takes precedence over the attribute)
Closes #4964.
> Use 'items' templatetag throughout.

- rest_framework/viewsets.py
- tests/test_generics.py
- tests/test_viewsets.py
> Support HEAD in viewsets

- docs/tutorial/7-schemas-and-client-libraries.md
There was a missing "r" before regular expression pattern.
> Fix Django url syntax.

- rest_framework/templates/rest_framework/base.html
This change allows using the rest_framework/base.html as-is for all pages on a website and should have no impact on existing code.
I typically start new projects with [cookiecutter-django](https://github.com/pydanny/cookiecutter-django).
It includes many pages for registration, login, change password, etc.  All of their templates use a "content" block.  In order to make all of those pages immediately compatible with DRF and styled the same, simply add these two files to a new project:
```django
{% extends "rest_framework/api.html" %}
{% block content %}{% endblock %}
```
```django
{% extends "rest_framework/base.html" %}
{% load staticfiles i18n %}
{% block title %}{% if name %}{{ name }} – {% endif %}My Project{% endblock %}
{% block branding %}
<a class="navbar-brand" rel="nofollow" …
```
> add content block and breadcrumbs_empty block to base.html for reuse

- docs/api-guide/viewsets.md
Ctrl-F on the ViewSets page doesn't show where the `mixins.SomeMixin...` classes come from.
> Mention where the mixins live

- rest_framework/static/rest_framework/docs/js/api.js
This fixes #4994 where the authentication scheme was always being set to the default `Bearer`.
> Correctly set scheme in coreapi TokenAuthentication

- rest_framework/schemas.py
- rest_framework/settings.py
Because there is a default value for pagination_class,
Also check page_size to see if the user is using it.
Closes #4996 
Closes #4997
> Ensure that pagination is not included in API schema when `page_size=None`. 

- rest_framework/schemas.py
This is follow-up #5011 and #5006. 
Path param based on AutoField is converted into Integer unless view has `lookup_value_regex` attribute.
Path constraints should be based on view configuration and not on underlying model, but I'm aware that this solution is not optimal.
> Include URL path regexs in API schemas where valid.

- docs/api-guide/filtering.md
I was caught out whilst following the filtering documentation. After installing django-filters there's no mention of adding it to `INSTALLED_APPS`.
So I was getting the following traceback when visiting viewsets with filtering enabled in the browsable API.
```
File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
42.             response = get_response(request)
File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
217.                 response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
215.                 response = response.render()
File "/usr/local/lib/python3.5/dist-packages/django/template/response.py" in render …
```
> Document adding django_filters to INSTALLED_APPS

- docs/api-guide/authentication.md
- docs/topics/third-party-packages.md
Adds [drfpasswordless](https://github.com/aaronn/django-rest-framework-passwordless) to the Authentication page in Api Guides and Third Party Packages topic page.
> Add drfpasswordless to Third Party Packages and Authentication pages

- rest_framework/fields.py
**Python Reference:**
[distutils.util.strtobool(val)](https://docs.python.org/2/distutils/apiref.html?highlight=distutils.util#distutils.util.strtobool)
Convert a string representation of truth to true (1) or false (0).
True values are y, yes, t, true, on and 1; false values are n, no, f, false, off and 0. Raises ValueError if val is anything else.
> Update Boolean field to support 'yes' and 'no' values

- docs/tutorial/7-schemas-and-client-libraries.md
there are non-space whitespace characters on line `44` of `7-schemas-and-client-libraries.md` that break up the code example in the generated `html`.  here's the diff using `od -a` to visualize the problem:
before:
```
0000000   sp   Â      sp   Â      sp   Â      sp   Â       u   r   l   (
0000020    r   '   ^   s   c   h   e   m   a   /   $   '   ,  sp   s   c
0000040    h   e   m   a   _   v   i   e   w   )   ,  nl                
```
after:
```
0000000   sp  sp  sp  sp  sp  sp  sp  sp   u   r   l   (   r   '   ^   s
0000020    c   h   e   m   a   /   $   '   ,  sp   s   c   h   e   m   a
0000040    _   v   i   e   w   )   ,  nl                                
```
> fix whitespace in code example

- rest_framework/views.py
- tests/test_views.py
Instead of using the api_settings exception handler, we use the
overridden settings attribute to find the correct handler.
Closes #5054
> Use overridden settings exception handler

- rest_framework/utils/breadcrumbs.py
Change intended to fix issue with APIViews with overridden __init__, which expect kwargs from as_view call in urls.py
> Pass initkwargs stored on view to instance

- rest_framework/views.py
I've changed the behaviour of finalize_response to update vary headers in the response - previously, any existing vary headers would be wiped out going through DRF. Using patch_vary_headers assures that existing headers remain.
I ran the tests but am getting a bunch of (hopefully unrelated?) problems, so I'm passing the problem on to travis.
I'll happily add a test for this as well, some guidance on where it might best go would be good though :)
> Update existing vary headers in response instead of overwriting them.

- docs/api-guide/filtering.md
- docs/api-guide/pagination.md
I had to look for the signature of `get_schema_fields()`in source code for my custom filter.
> Clarify get_schema_fields signature

- README.md
- docs/index.md
- setup.py
DRF was tested on Django 1.11 and has green builds on Travis, but README file and `setup.py` doesn't have this information. 
This pull request adds 1.11 to the list of supported Django versions.
> Add Django 1.11 into *.md and setup.py

- rest_framework/documentation.py
- rest_framework/routers.py
- rest_framework/schemas.py
This PR makes it possible to override which `SchemaGenerator` class is used, both in Routers and the browseable documentation.
I have a slightly extended/improved SchemaGenerator in my project, but actually using it means having to copy-paste code since the class is not currently injectable.
> Customizable schema generator classes

- docs/topics/tutorials-and-resources.md
I submitted a previous pull request that added Two Scoops of Django to the book section of the docs. Alas, my brain was its normal sort of stupid and I put it above @limedaring's book, "Hello Web App: Intermediate Concepts". This was thoughtless of me and I apologize. This pull request fixes that mistake.
> Corrected order of books. Apologies to @limedaring

- rest_framework/relations.py
- tests/test_relations.py
- tests/test_routers.py
Fix for #4748 
I added couple tests, but in fact only one of them would fail without change introduced by this PR
`TestHyperlinkedRelatedField.test_hyperlinked_related_lookup_url_encoded_exists`
> add URL path unquote to HyperlinkedRelatedField.to_internal_value

- rest_framework/schemas.py
When using master (bd768d62) with `LimitOffsetPagination`, `SchemaGenerator` crashes:
```
File "rest_framework/schemas.py", line 607, in get_pagination_fields
if not pagination or not pagination.page_size:
AttributeError: type object 'LimitOffsetPagination' has no attribute 'page_size'
```
This is related to #4998.
> SchemaGenerator: Avoid crashing with pagesizeless paginators

- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- rest_framework/utils/serializer_helpers.py
Per issue #4999, JSONFields are not rendered properly in the DRF
browsable API HTML forms.  This patch attempts to fix that behavior by
introducing a JSONBoundField helper similar to the NestedBoundField
helper.
I experienced #4999 today and put together this patch as an attempt to fix it.  I'd appreciate any feedback as to whether this approach makes sense as this is my first dive into the DRF code.  I could particularly use some guidance on what tests, documentation, etc. I should add.
./runtests.py reports all tests pass.  tox reports failures in py35-djangomaster and py36-djangomaster, but those are present in my environment without this patch also.  All other tox tests pass.
> PoC Add JSONBoundField to serializers (Fixes #4999)

- docs/api-guide/testing.md
* Remove unnecessary comma
* Remove the "and simple" copied from the line above.
* Add "entirely" to emphasize that this function bypasses the authentication step.
> Improve grammar in .force_authenticate() docs

- rest_framework/utils/serializer_helpers.py
Fixes an error that occurs on rendering response with error that says that required nested serializer field must be specified in data.
When viewset receives a data without field that specified in used serializer as nested serializer with **required**=**True**, response fails to render correctly because of occured AttributeError in **NestedBoundField** class, `__getitem__` method (_/rest_framework/utils/serializer_helpers.py_).
That happens because 'required' error was saved in parent serializer and passed as list but used as dict in NestedBoundField that expects errors from fields of nested serializer, not from serializer itself. 
1. Create simple model structures.
```python
from django.db import models
class Data(models.Model):
name = models.CharField(max_length=50)
class …
```
> Fixed render error of required nested serializer.

- rest_framework/serializers.py
- tests/test_serializer_lists.py
I have two serializers:
``` python
class ItemSerializer(serializers.ModelSerializer):
class Meta:
model = Item
class ObjectSerializer(serializers.ModelSerializer):
class Meta:
model = Object
fields = ['id', 'title', 'items']
items = ChatMemberSerializer(many=True, allow_empty=False)
```
When I make partial update for ObjectSerializer without items, I get the error:
``` python
{'items': {'non_field_errors': ['This list may not be empty.']}}
```
> Fix partial update for the ListSerializer.

- rest_framework/pagination.py
Just a minor change.
By setting **self.count** before **self.limit** in the **LimitOffsetPagination** it is possible, if one wants, to override **get_limit** in order to return all records if the request has a predefined param.
For example, if one wants that all records are retrieved if url has &limit=-1, in this case, **get_limit** could return **self.count**.
Otherwise, if **self.count** is set after **self.limit** then, to achieve the same result, one has to override **get_limit** and **paginate_queryset**, or run **get_limit** twice.
> Set self.count before self.limit in LimitOffsetPagination

- rest_framework/schemas.py
- tests/test_schemas.py
This limits the schema generation by `http_method_names` attribute (Django CBV). I just updated `get_allowed_method` to have a set intersection check.
Closes #4691.
> Generate schema with respect to http_method_names provided by CBV

- rest_framework/utils/field_mapping.py
Spotted a typo in field_mapping.py, which apparently is a result of copy and paste. @tomchristie
> Fix a typo in a comment

- requirements/requirements-optionals.txt
- rest_framework/filters.py
- tests/test_filters.py
> Fix DjangoFilterBackend mro

- rest_framework/generics.py
- tests/test_generics.py
Add `ValidationError` to `except` in `rest_framework.generics.get_object_or_404` to handle change in Django 1.11 where `get_object_or_404` returns a `ValidationError` (as opposed to earlier versions that returned a `ValueError`) when passing an invalid value for the `uuid`.
Refs #3377  (I'd be happy to open up a separate issue for this as well, but wasn't sure if I should)
> Add ValidationError to except in get_object_or_404 for django 1.11

- rest_framework/filters.py
- tests/test_filters.py
Closes #4989. 
For using ordering filters, parameters are added to the URL in the following manner and the output is the listed in the increasing order of the passed parameter. 
`http://example.com/api/users?ordering=username`
For decreasing order, the following URL is used: 
`http://example.com/api/users?ordering=-username`
If multiple hyphens are added, it should be treated as an invalid ordering parameter and should be discarded. The failing testcase's error traceback is as follows: 
```
tests/test_filters.py:778: in test_incorrecturl_ordering
response = view(request)
../venv-test/lib/python2.7/site-packages/django/views/decorators/csrf.py:58: in wrapped_view
return view_func(*args, **kwargs)
../venv-test/lib/python2.7/site-packages/django/views/generic/base.py:68: in view
return …
```
> Ignore any invalidly formed query parameters for OrderingFilter.

- requirements/requirements-optionals.txt
Latest is [v1.0.3](https://github.com/carltongibson/django-filter/releases/tag/1.0.3) — improving support for schema generation
> Update Django Filter requirement

- rest_framework/schemas.py
Refs https://github.com/encode/django-rest-framework/issues/5144
This fixes a bug that was introduced in commit:  https://github.com/encode/django-rest-framework/commit/6ad0be44d3275b10ad69ae60167db144b620e7ca#diff-eae91da078f88bdb425b240be0ee5487
Then was mutated by this followup commit:  https://github.com/encode/django-rest-framework/commit/72da73310d6da11e4beeba815498fa4aecc6635a
I change the logic back to not consider the page_size attribute at all as it is irrelevant for generating the schema -- should have nothing to do with the actual page size.
> If pagination class, include the schema generation

- tests/test_relations.py
I fixed `TestHyperlinkedRelatedField.test_hyperlinked_related_lookup_url_encoded_exists` on Django master:
```python
TestHyperlinkedRelatedField.test_hyperlinked_related_lookup_url_encoded_exists 
rest_framework/relations.py:347: in to_internal_value
return self.get_object(match.view_name, match.args, match.kwargs)
rest_framework/relations.py:298: in get_object
return self.get_queryset().get(**lookup_kwargs)
tests/utils.py:30: in get
raise ObjectDoesNotExist()
E   django.core.exceptions.ObjectDoesNotExist
During handling of the above exception, another exception occurred:
tests/test_relations.py:119: in test_hyperlinked_related_lookup_url_encoded_exists
instance = self.field.to_internal_value('http://example.org/example/baz%20qux/')
rest_framework/relations.py:349: in to_internal_value …
```
> Fixed test_hyperlinked_related_lookup_url_encoded_exists.

- rest_framework/relations.py
- tests/test_relations.py
- tests/utils.py
Add tests for HTML_CUTOFF setting and fix issue where setting it to None would raise an exception.
Fixes https://github.com/encode/django-rest-framework/issues/5140
> Fix exception when HTML_CUTOFF is set to None

- docs/api-guide/schemas.md
In actual [documentation for schemas](http://www.django-rest-framework.org/api-guide/schemas/) i did't found from where i should import the `get_schema_view` shortcut. So i found it in [DRF 3.5 Announcement Page](http://www.django-rest-framework.org/topics/3.5-announcement/).
In this pull request i putted two imports to documentation to clarify from where to import the `get_schema_view` shortcut.
```
from rest_framework.schemas import get_schema_view
```
> Added documentation from where to import get_schema_view

- rest_framework/parsers.py
Large encoded string take a very long time to to release from memory, but if we just pass the stream directly into json.load we get much better memory performance. refs #5146
> Improve memory footprint when reading large JSON requests.

- docs/api-guide/schemas.md
[`get_schema_view` accepts `generator_class` parameter](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas.py#L701)
Was added in 51a6c076e27931c89a37d76301975e7e548e3324 (tagged in [3.6.3](https://github.com/encode/django-rest-framework/tree/3.6.3))
> Add `generator_class` parameter to `get_schema_view` docs.

- rest_framework/routers.py
- tests/test_routers.py
refs : [#5172](https://github.com/encode/django-rest-framework/issues/5172)
before: [#5177](https://github.com/encode/django-rest-framework/pull/5177)
when list_route and detail_route's url_path contains curly brackets, it raise IndexError
as we can see at [#5172](https://github.com/encode/django-rest-framework/issues/5172).
added test code ensure that when I escape curly bracket it works fine.
I think list_route and detail_route need url_path with regex lookup for making restful url
unless we can use nested route on list_route and detail_route.
> Fix list_route, detail_route with kwargs contains curly bracket in url_path

- rest_framework/templates/rest_framework/base.html
Navigating the page with a reader is easier if there is aria-label and region defined, especially if the page is filled with a big json.
I don't think there was an issue open for this, but its a really fast feature to do and really helpful for my users.
> Added aria-label and a new region for accessibility purposes in base.html

- rest_framework/filters.py
- rest_framework/routers.py
This makes the warnings refer to the code where it is used, which makes
it easier to find and fix.
> Use stacklevel=2 with DeprecationWarnings

- rest_framework/static/rest_framework/docs/js/api.js
I sometimes have parameter names with a period (.) in them, to represent nested objects, e.g. containerobj.inner_param. The Javascript was throwing an error in the browsable API when interacting with those parameters.
> Quote nested API parameters in api.js

- rest_framework/serializers.py
- tests/models.py
- tests/test_relations_pk.py
Closes:  https://github.com/encode/django-rest-framework/issues/5135
I've been working this issue occasionally since the last day of the PyCon sprints.  I setup a test case to reproduce the problem from the issue and then iterated in a debugger to determine where I thought the best spot to make a code change was.  I determined that `build_standard_field` feels like the right place for a couple reasons.  One was that I first tried to do the change in `get_field_names` except that expects all the results to be retuned Django fields and I am trying to override it to be the right serializer field.    I followed the code further down and determined that it was falling back to the generic `models.Field: ModelField` in `serializer_field_mapping`.
I found two convenient attributes on the field …
> Special case for when OneToOneField is also primary key.

- rest_framework/static/rest_framework/js/ajax-form.js
- Autodetect missing boundary parameter for Content-Type header
- textarea value normalises EOL chars to \n when multipart/form-data requires \r\n
Fixes #1579
> Fix browsable API not supporting multipart/form-data correctly

- docs/api-guide/authentication.md
DOT renamed `ext` to `contrib` on their new release `1.0.0`
https://github.com/evonove/django-oauth-toolkit/commit/cdc00603e738fdf78a217754196113cadc000f4f
> Update API guide section referring to DOT

- docs/api-guide/exceptions.md
The link to the _Python Exception Handling Techniques_ article written by _Doug Hellmann_ is broken.
I could find the article in the URL I proposed in this PR.
> Link in the home page is broken

- rest_framework/viewsets.py
- tests/test_viewsets.py
This fixes issue #5228
Actually I didn't find when `args`, `kwargs` and `request` are set in the dispatch and just set them before that as Django does.
P.S.
I found where "the magic happens". If we want restframework's request to be available as early as possible (before `dispatch` as is with Django's request object), even on normal API views then setting of djangorestframework's request can be done in `as_view` method (but should be done twice - once for `APIView` and once for `ViewSet`).
Even If we decided that it's not a problem django's request object to be available before `dispatch` (as is right now for APIView) because RestFramework supports Django 1.8+ we can remove  setting of `args` and `kwargs` in dispatch, because they are already set by `as_view` decorator.
I can update the …
> Fixed #5228 Set ViewSet args/kwargs/request before dispatch

- rest_framework/fields.py
- tests/test_api_client.py
- tests/test_fields.py
This implements the `allow_unicode` argument for `SlugField` per #5223, to align with the behavior of the Django `SlugField` (https://docs.djangoproject.com/en/1.11/ref/models/fields/#slugfield).
Also fixing a couple tests that don't pass on Windows because `tempfile.NamedTemporaryFile` cannot be opened more than once simultaneously. If this change isn't appropriate for this pull request, let me know and I'll pull it.
Closes #5223
> Fixed tests on Windows. Added unicode support to SlugField

- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/sidebar.html
- tests/test_atomic_requests.py
- tests/test_fields.py
- tests/test_permissions.py
- tests/test_renderers.py
- tests/test_request.py
- tests/test_response.py
- tests/test_reverse.py
- tests/test_schemas.py
- tests/test_validation.py
Closes #5162.
Add case for check user auth
Lint fix
> Fix API documentation templates do not check for user authentication #5162

- rest_framework/authtoken/management/commands/drf_create_token.py
- tests/test_authtoken.py
This pull request add the Django manage command called **drf_create_token** as documented in the issue #5173
> Add Django manage command to create a DRF user Token

- rest_framework/renderers.py
Sanitize `serializer.data` to remove hidden fields before rendering template
JSON instance to raw data form.
refs #5258 
closes #5258
> Fix issue #5258

- rest_framework/filters.py
- tests/test_filters.py
Fixes #4655. Thanks @cdosborn for the patch!
> Fix SearchFilter to-many behavior/performance

- docs/api-guide/pagination.md
A third-party package has been created for Link header pagination as requested in https://github.com/encode/django-rest-framework/pull/5268.
> Add link to third-party package for LinkHeaderPagination.

- rest_framework/fields.py
- tests/test_fields.py
- tests/test_serializer.py
Reverting #3288 solves issues demonstrated in #5087 and #2555. Accessing a field/serializer `root` *before* the parent is bound resulted in the incorrect object being cached. My thoughts on this are that the caching benefits have nominal performance improvements and isn't really worth the incorrect behavior.
> Revert 3288

- docs/api-guide/fields.md
> keeps **you** error messages
to
> keeps **your** error messages
and 
> **more cleanly separated** from your code
to 
> **cleaner and more separated** from your code
> Fix typo on `fields.md`

- docs/api-guide/authentication.md
- rest_framework/authentication.py
- tests/test_authentication.py
Support for delegating authentication to a web server.
This is a little thing, but I thought it would be worth providing an obvious way to do it. The alternative is to use `RemoteUserBackend`, `RemoteUserMiddleware` and `SessionBasedAuthentication`, but then one has to mess with working out how/whether to disable CSRF protection.
> RemoteUserAuthentication, docs, and tests

- docs/api-guide/authentication.md
This PR adds documentation for `drf_create_token` command that has been introduced in Django Rest Framework. Fixes #5327
> Add documentation to create user token with the new command

- docs/api-guide/testing.md
Minor fix in the Testing API Guide.
> Fix token param in force_authenticate example

- docs/topics/api-clients.md
Fixes #5247
Adds missing `new` to the instantiation examples for the JS client.
> Update JS constructor syntax

- docs/api-guide/fields.md
Fixes #5301 
Closes #5303
Emphasises that `child` is in fact a `kwarg` (closing the issue) but without suggesting `None` or altering the behaviour. 
The dummy value `<A_FIELD_INSTANCE>` is clearly not valid Python. (It is clearly not the actual signature.) It is explained perfectly in the docs that follow.
> Adjust ListField & DictField signature docs

- rest_framework/static/rest_framework/docs/js/api.js
- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/interact.html
- rest_framework/templates/rest_framework/docs/link.html
- rest_framework/templates/rest_framework/docs/sidebar.html
- rest_framework/templatetags/rest_framework.py
- tests/test_templatetags.py
Multiple nested resources with multiple methods were not displayed. Also
`detail_routes` and `list_routes` with multiple methods. This PR attempts to fix it. 
I created a template tag, that **recursively** finds the links inside a given section. What do you guys think?
I am not sure if the format I've given to the generated links it's okay, but it's a start.
Issues related:
#5324 
[#4391](https://github.com/encode/django-rest-framework/issues/4391)
#4965 
Default actions
```
users: {
list()
create()
read(id)
update(id)
}
```    
--------------------------------
Single action
```
users: {
list([page])
}
```
--------------------------------
Single detail_route url
```
users: {
list()
create()
read(id)
update(id)
farmers(id) <--
}
```
--------------------------------
More than one …
> Fix docs multiple nested and multiple methods

- rest_framework/schemas.py
- tests/test_schemas.py
I hope the commit is self-explanatory. Please let me know if you need more information.
> Fix introspection of list field in schema

- rest_framework/permissions.py
Hello! I have been using DRF for a while and was looking at some issues to start contributing.
I found issue  #4585 and tried to solve the confusing error message when a `.get_queryset()` method exists but does not return anything.
----
Closes #4585
> Adding a more explicit error message when a view does have a get_queryset method but it returned nothing

- docs/api-guide/responses.md
Response data attribute was confusingly referencing the Request object. I added what I think is a better description from looking at the code.
refs #5360
> Fix doc Response data attribute description

- docs/topics/api-clients.md
The documentation suggests creating `new` classes for various authentication methods but does not specify `new` operator explicitly, which results in the `_classCallCheck` throwing an error.
> ~api-clients documentation: installation code fix

- docs/api-guide/serializers.md
I've changed a link to the repository for drf-writable-nested package.
> Update link to drf-writable-nested repository in third-party serializers

- MANIFEST.in
I definitely see files from `__pycache__` as well as `.pyc` files in the 3.6.4 package. Fixed according to [reddit](https://www.reddit.com/r/Python/comments/40s8qw/simplify_your_manifestin_commands) and https://github.com/django/django/pull/5817.
> Fix excludes

- rest_framework/fields.py
- tests/test_serializer.py
This fixes #5371. In short, default handling works as expected when traversed attributes return an `object`/`dict`, but not when one part of the traversal returns `None`.
```python
class Serializer(serializers.Serializer):
bar = serializers.CharField(default='x', source='foo.bar')
>>> Serializer({}).data
ReturnDict([('bar', 'x')])
>>> Serializer({'foo': {}}).data
ReturnDict([('bar', 'x')])
>>> Serializer({'foo': None}).data
ReturnDict([('bar', None)])
```
> Fix default value handling for dotted sources

- rest_framework/request.py
- rest_framework/test.py
- tests/test_testing.py
This resulted from and fixes #5349. In short, because of how DRF overrides `RequestFactory`, passing `data=None` to the request methods will result in the request object *not* having it's `CONTENT_TYPE` set. 
The solution is to just simply set the header if present.
----
In more detail:
- Django's `RequestFactory` methods will generally [override](https://github.com/django/django/blob/1.11/django/test/client.py#L346) `data=None` to an empty dict.
- DRF's `RequestFactory` overrides this behavior, and does *not* set `data` to an empty dict. 
- Django's `RequestFactory` has special handling when [encoding](https://github.com/django/django/blob/1.11/django/test/client.py#L309-L311) `data` for *multipart/form-data* requests, otherwise it simply …
> Unexpected result when passing empty body to RequestFactory

- docs/topics/release-notes.md
- rest_framework/permissions.py
- tests/test_permissions.py
The below will replicate the old behavior where `MethodNotAllowed` preceded the authentication check:
```python
class DjangoModelPermissions(permissions.DjangoModelPermissions):
def has_permission(self, request, view):
if request.method not in self.perms_map:
raise exceptions.MethodNotAllowed(request.method)
return super().has_permission(request, view)
````
----
This is an updated version of #5367 that includes a regression test. 
Note:
This does *slightly* change the behavior for when the request has no authentication. Previously, if a user made an unauthenticated request, they would receive a 405. With the PR, users would receive the 401 first, then 405 once authenticated. 
I'd argue that the change is more correct, given the general ordering of [authentication, …
> DjangoModelPermissions should perform auth check before accessing the view's queryset

- rest_framework/renderers.py
Sometimes, probably in the upgrade from Django 1.9 to 1.10, a post with
empty content is forbidden by javascript, with the message "Please fill
in this field". Filling the form with '{}' allows an application/json
request to be submitted.
The API call itself works perfectly well with a post with empty content:
the interface shouldn't make assumptions about it.
> Don't make the content mandatory in the generic content form

- rest_framework/serializers.py
- tests/test_model_serializer.py
Fixes #5389 
Includes a test that fails on master, passes before #5138, and now passes with included fix.
> Fix ModelSerializer custom named fields with source on model

- docs/api-guide/generic-views.md
The MultipleFieldLookupMixin example on the documentation does not check for object level permission. Thus, when it is used in conjunction with a custom permission (e.g., the IsOwner permission), it behaves unexpectedly.
> Fixed the MultipleFieldLookupMixin example to properly check for object level permission

- docs/api-guide/permissions.md
I'm a bit confused about the example that's provided in the 'Object level permissions' section.  Other examples (e.g. Tutorial 3 - Class Based Views) provided a pk to get_object().  It doesn't seem like this example has any way of identifying a specific object.  
Just in case I'm correct, I've prepared this pull request. But if I'm wrong, would it be possible for you to explain the example I modified?  
Many Thanks...
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the pull …
> Update get_object() example in permissions.md

- tests/test_fields.py
For the `FieldValues` tests, multiple input/output values can result in the same validated/rendered value. Since the assertion is testing the validated/rendered value, it's not possible to discern which raw input is actually causing the test to fail. Fixed by adding the raw value representation to the assertion message.
> Add value repr to the assertion output in FieldValues tests

- docs/api-guide/throttling.md
There's no such HTTP header called Remote-Addr and the throttling code is indeed not using any HTTP variable to get this.
Instead it is using the WSGI environment variable REMOTE_ADDR, which may be set by the webserver according to configuration. For example, in nginx it is possible to use the nginx_http_realip_module and set it based on any HTTP header, if it comes from a trusted reverse proxy server.
On the other hand, X-Forwarded-For is a valid HTTP header and that's why it is also prefixed with HTTP_ in the request.META object.
Please describe your pull request. If it fixes a bug or resolves a feature …
> Fix throttling documentation about Remote-Addr

- rest_framework/authtoken/management/commands/drf_create_token.py
- tests/test_authtoken.py
Command raised an error when creating token because username param is a list.
Two options
- Make username param single argument
- Iterate trough username params
I choose to go with second.
> Fix authtoken managment command

- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
Removes incorrect `strip` call from `AutoSchema.get_descrition()` that was breaking markdown formatting. 
Update of #5378, following #5354. Closes #5240.
> 5378 fix schema generation markdown

- docs/api-guide/schemas.md
- docs/api-guide/views.md
- docs/topics/release-notes.md
- rest_framework/decorators.py
- rest_framework/routers.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/views.py
- rest_framework/views.py
- tests/test_schemas.py
The PR allows setting `schema = None` to exclude APIView subclasses from schema generation. 
For function based views use `@schema(None)`. 
It deprecates `exclude_from_schema` on APIView and the `exclude_from_schema` argument to `api_view`.
> Allow `schema = None`. Deprecate `exclude_from_schema`

- rest_framework/fields.py
- tests/test_fields.py
The `choices` field for the `ChoiceField` class should be able to be edited after `__init__` is called.
```
field = ChoiceField(choices=[1,2])
field.choices = [1]  # Should no longer allow `2` as a choice
```
Currently, you must update `choices`, `grouped_choices`, and `choice_strings_to_values` to achieve this. This P/R keeps `grouped_choices` and `choice_strings_to_values` in sync whenever the `choices` are edited.
> Allow `ChoiceField.choices` to be set dynamically

- docs/tutorial/quickstart.md
The quickstart layout is pretty uncommon and gives a regular feed of failures and questions despite the comment added.
Let's add a project layout and a brief note about it to let user auto correct themselves.
> Add the project layout to the quickstart

- docs/topics/release-notes.md
- requirements/requirements-optionals.txt
- rest_framework/fields.py
- tests/test_fields.py
Adds Release note, rebases and closes #5408. Closes #3732
> Fix DateTimeField TZ handling

- docs/api-guide/settings.md
- requirements/requirements-codestyle.txt
- rest_framework/fields.py
- rest_framework/parsers.py
- rest_framework/renderers.py
- rest_framework/settings.py
- rest_framework/utils/encoders.py
- rest_framework/utils/json.py
- rest_framework/utils/serializer_helpers.py
- setup.cfg
- tests/test_fields.py
- tests/test_parsers.py
- tests/test_renderers.py
- tests/test_routers.py
- tests/test_utils.py
Resolve #4918, fix #5235. The important bits that I gathered from the discussion were:
- DRF should internally encode/decode only strict JSON, since other modules (eg, postgres's `JSONField`) may not be compatible with the extended float values (`Infinity`, `NaN`). Incompatible values should raise an exception.
- Users may still want to render/parse extended JSON. 
This PR does the following:
- Adds an internal `rest_framework.utils.json` module that defaults to strict JSON encoding/decoding. 
- All imports have been changed to `rest_framework.utils.json`, so they obey the stricter behavior. 
- Adds flake8-tidy-imports, which allows us direct users to import the json wrapper module. 
- Adds `settings.STRICT_JSON`, which controls the strictness of `JSONParser` & `JSONRenderer`. This …
> Use strict float handling in JSON functions

- rest_framework/utils/encoders.py
- tests/test_encoders.py
Closes #4749.
This is the matching commit to the fix for `datetime` in #4256
> JSONEncoder: Don’t strip microseconds from `time`

- docs/api-guide/testing.md
…in case you’re reusing the same in-memory user whilst updating it in the DB.
Closes #5016, closes #5066, closes #4102
> Add note on force_authenticate + refresh_from_db

- rest_framework/pagination.py
- tests/test_pagination.py
`CursorPaginator` receives identical support for page size query parameter as `PageNumberPagination`.
Solving https://github.com/encode/django-rest-framework/issues/5249
> Add support for page_size parameter in CursorPaginator class

- docs/api-guide/schemas.md
- rest_framework/documentation.py
- rest_framework/schemas/__init__.py
Incorporates and closes #5309. Fixes #5399 
* Adapts work by @Omnipotence456 after #5354. 
* Adds note to `get_schema_view` docs. 
**Aside**: I note, in passing, that `include_docs_urls` and the helper functions from `documentation.py` are essentially undocumented. I'll add an issue for that but want to address it separately.
> Allow setting custom authentication and permissions on docs view. 

- rest_framework/schemas/inspectors.py
The documentation generator calls view.get_serializer() in order to
inspect it for documentation generation. However, if get_serializer()
throws an APIException (e.g. PermissionDenied), it doesn't get caught at
the call site, but instead propagates up and aborts the entire view.
With the try/except in this commit, the documentation generator instead
gratiously ignores that particular view and moves on to the next one
instead. Practical concequences of this commit is that the docs no
longer break if any view's get_serializer(..) throws an APIException.
> Catch APIException in doc generation

- rest_framework/schemas/inspectors.py
This now prints `Foo.get_serializer()` instead of `<class 'Foo'>.get_serializer()`
> Fix warning in AutoSchema.get_serializer_fields()

- rest_framework/compat.py
- rest_framework/fields.py
This PR originated with the changes in this PR: https://github.com/encode/django-rest-framework/pull/3438 . However, that PR stalled and was closed. This PR proposes the same change again - defer the error message string evaluation until the messages are actually used.
As stated in the original PR, our project uses a forked version of DRF only because of the issue described in https://github.com/encode/django-rest-framework/issues/3354 . Our fork contains only one custom change - the one in this commit: https://github.com/edx/django-rest-framework/commit/3c72cb5ee5baebc4328947371195eae2077197b0  Our project (Open edX) performs a non-standard startup which causes DRF to be imported before the Django translation infrastructure is initialized.
An initial attempt to fix this issue was made in …
> Defer translated string evaluation on validators. 

- rest_framework/exceptions.py
In the current implementation, _detail_ is a positional argument. But the code in line [127](https://github.com/encode/django-rest-framework/pull/5342/files#diff-7215000329f5ee2146a1d6bdcdf270b3L127) expects an keyword. If I do not pass the argument _detail_ when creating an instance of _ValidationError_, then we get: 
TypeError: __init__() missing 1 required positional argument: 'detail'
but not __('Invalid input.')_
> Added default value for 'detail' param into 'ValidationError' exception

- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
Closes #5237
Generics/ModelViewset performs filtering on: list, retrieve, put, patch and destroy (plus method equivalents).
i.e. on list plus anything that calls `get_object`.
This PR makes schema generation follow that.
It adds `AutoSchema._allows_filters()` which can be overridden in subclasses.
I’ve made this initially “private” so we can make quick changes if needs be in a 3.7.1 etc.
> Adjust schema get_filter_fields rules to match framework

- .travis.yml
- requirements/requirements-codestyle.txt
- requirements/requirements-documentation.txt
- requirements/requirements-optionals.txt
- requirements/requirements-packaging.txt
- requirements/requirements-testing.txt
- tox.ini
Replaces #5442, focusing just on the text matrix. 
* Update test requirements. 
* Add Django 2.0
* Drop Django 1.8 in preparation for #5058 
* Drop 1.9: EOL.
> Update test matrix: Add Django 2.0, drop 1.8

- rest_framework/fields.py
Simple fix that's using deprecated django api.
was getting "/usr/local/filewave/python/lib/python3.6/site-packages/djangorestframework-3.6.1-py3.6.egg/rest_framework/fields.py:1774: RemovedInDjango20Warning: Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead."
> Fixed a deprecation warning

- docs/api-guide/pagination.md
Closes #5160, closes #5164.
As per https://github.com/encode/django-rest-framework/issues/5160#issuecomment-332469893, adds a note to `CursorPagination` caveats saying don't use floats. 
Links to gist for `CursorPagination` subclass as a possible workaround.
> Add note on not using floats with CursorPagination

- rest_framework/templates/rest_framework/filters/django_filter.html
- rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html
Removes the old django-filter templates. This was a forgotten part of ~~#5273~~ #4507.
> Remove old django-filter templates

- rest_framework/templatetags/rest_framework.py
refactoring to avoid code duplication and scope isolation
> Reuse 'apply_markdown' function in 'render_markdown' templatetag func

- docs/tutorial/6-viewsets-and-routers.md
Added `from rest_framework.response import Response` in the viewset code snippet example
> Added Response import in Code Snippet

- rest_framework/compat.py
- rest_framework/templatetags/rest_framework.py
- tests/test_description.py
Currently: 
- tests are missing
> Docstrings highlighting with pygments

- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/sidebar.html
- rest_framework/templatetags/rest_framework.py
- tests/conftest.py
- tests/test_renderers.py
- tests/urls.py
Closes #5395. 
If your `coreapi.Document` contains a `Link` called `data` then calls to `document.data` in the templates would fail. 
This PR adds a test case for that and a template tag to resolve the issue. (Note, it's the same fix as #4972)
> Fix documentation `data` rendering

- docs/api-guide/serializers.md
This should resolve #3864 and #5438.
> Clarify 'to_internal_value()' validation behavior

- rest_framework/exceptions.py
The call was added in 426547c61c725ca7dc47671c084d1a2805c92305
to allow for dict-style arguments to ValidationError but does not
apply to other APIException descendants.
It is possible to hit edge cases when printing an APIException in a
custom exception handler, that was passed a non-string as its first
argument (eg. AuthenticationError({"code": "foo", "detail": "bar"}))
> Fix missing six.text_type() call on APIException.__str__

- docs/topics/documenting-your-api.md
Closes #5198. Closes #5142. Closes #4980
This PR add docs for the three functions in `documentation.py`. 
It adds a Note explaining the `public` parameter to `include_docs_urls` (and others) which controls whether a `request` instance is passed to views during schema generation.
> Document documentation.py

- rest_framework/schemas/generators.py
- tests/test_schemas.py
Closes #4704
**WIP DO NOT MERGE**
If urls include elements in `['retrieve', 'list', 'create', 'update', 'partial_update', 'destroy'] — I **think** just those — schema generation can fail is a **nested** item clashes with a previously defined `Link`. 
(We want a dictionary to insert a `Link` to, but a `Link` is already there.) 
Thus far, just added a couple of failing test case for the reported cases.
> Fix naming collisions in Schema Generation 

- rest_framework/authentication.py
- rest_framework/authtoken/serializers.py
- rest_framework/authtoken/views.py
- rest_framework/compat.py
As of Django 1.11 the `authenticate` function accepts a request as an
additional argument. This commit fixes compatibility between newer Django
versions and custom authentication backends which already depend on the request
object.
See also:
[Django 1.11 release](https://docs.djangoproject.com/en/1.11/releases/1.11/)
```
authenticate() now passes a request argument to the authenticate() method of
authentication backends. Support for methods that don’t accept request as the
first positional argument will be removed in Django 2.1.
```
> Call Django's authenticate function with the request object

- rest_framework/schemas/utils.py
- tests/test_schemas.py
Fixes #5165
Adds `isinstance` check for `RetrieveModelMixin`. Useful when you've routed a view to a URL without a lookup parameter. e.g. `/accounts/profile/` which pulls its object (the current user) from the `request`.
> Have `is_list_view` recognise RetrieveModel… views

- rest_framework/authtoken/management/commands/drf_create_token.py
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/filters.py
- rest_framework/pagination.py
- rest_framework/permissions.py
- rest_framework/renderers.py
- rest_framework/serializers.py
- rest_framework/settings.py
- rest_framework/templatetags/rest_framework.py
- rest_framework/throttling.py
- rest_framework/urlpatterns.py
- rest_framework/utils/field_mapping.py
- rest_framework/utils/model_meta.py
- rest_framework/utils/representation.py
- tests/test_authentication.py
- tests/test_compat.py
- tests/test_htmlrenderer.py
- tests/test_model_serializer.py
- tests/test_one_to_one_with_inheritance.py
- tests/test_permissions.py
- tests/test_prefetch_related.py
- tests/test_relations_pk.py
- tests/test_request.py
- tests/test_requests_client.py
- tests/test_routers.py
- tests/test_versioning.py
- tests/urls.py
- tests/utils.py
> Remove Django 1.8 & 1.9 compatibility code

- rest_framework/routers.py
To be removed in accordance with deprecation policy.
> Remove deprecated schema code from DefaultRouter

- rest_framework/static/rest_framework/docs/js/api.js
Closes #5477.
The value was being correctly determined, but was never assigned as the parameter value for the request.
> Interactive documentation always uses false for boolean fields in requests

- docs/topics/release-notes.md
Adds an entry to the 3.7 announcement stating the refactoring of schema generation in #5354 and suggests a fix for the refactoring of `get_serializer_fields`.
Refs/Fixes #5493
> Version 3.7 announcement fix

- rest_framework/compat.py
- rest_framework/schemas/generators.py
- rest_framework/urlpatterns.py
- tests/test_urlpatterns.py
Fixes #5456
My attempt to make sense of the new [URL routing API](https://github.com/django/django/commit/df41b5a05d4e00e80e73afe629072e37873e767a#diff-b2f90a810a553411112f412de2a26617) from Django 2.0:
* `RegexURLPattern` and `RegexURLResolver` are renamed to `URLPattern` and `URLResolver` respectively.
* Their regexes are now encapsulated inside `RegexPattern`/`RoutePattern` instances and are located at `self.pattern.regex` (was `self.regex`).
* Both `url()` and the new `path()` return `URLPattern`. So, no changes needed to support the new routing syntax.
> Support URLPattern and URLResolver from Django 2.0

- rest_framework/renderers.py
This potentially fixes #5498 and related comments in #5929. Ideally, this would be tested, but I'm not familiar with the rendering/parsing tests.
> Fix HiddenField stripping in BrowsableAPIRenderer

- rest_framework/documentation.py
- rest_framework/fields.py
- tests/test_routers.py
- tests/test_schemas.py
- tests/test_versioning.py
**WIP Don't merge yet** (Opening now for Travis to play.) 
Following from #5500, fixing failures against Django 2.0a1
> Django 2.0a1 compat

- rest_framework/schemas/generators.py
- tests/test_schemas.py
If urls include elements in `['retrieve', 'list', 'create', 'update', 'partial_update', 'destroy']` schema generation can fail (if a **nested** item clashes with a previously definedLink) or replace other link.
PR fixes https://github.com/encode/django-rest-framework/issues/5484 and https://github.com/encode/django-rest-framework/issues/4704.
Also took unit tests from another PR targeting this issue: https://github.com/encode/django-rest-framework/pull/5464
> Fixed issues with schema name collisions

- docs/api-guide/fields.md
- tests/test_serializer.py
**WIP** changes to docs, and additional tests for behavior of `source` w/ dotted notation.
Closes #5488.
Waiting for a nested `ModelSerializer` example from @xordoquy.
Also, is the current exception sufficient, or do we need to mention the necessity of a `default` value? 
eg, this serializer:
```python
class ColleagueUserSerializer(BaseModelSerializer):
city = serializers.IntegerField(source='profile.contact.address.city')
```
generates this exception:
```
AttributeError: Got AttributeError when attempting to get a value for field `city` on serializer `ColleagueUserSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'NoneType' object has no attribute 'address'.
```
> Docs about default value for dotted source, additional tests

- docs/topics/release-notes.md
- rest_framework/__init__.py
> Version 3.7.1 Release

- rest_framework/compat.py
- rest_framework/urls.py
Fixed Django 2.1 compatibility due to removal of `django.contrib.auth.login()/logout()` views (see Django documentation [1.11](https://docs.djangoproject.com/en/1.11/releases/1.11/#django-contrib-auth), [2.1](https://docs.djangoproject.com/en/dev/releases/2.1/#features-removed-in-2-1)).
```
________________ ERROR collecting tests/test_authentication.py _________________
tests/test_authentication.py:85: in <module>
url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
.tox/py35-djangomaster/lib/python3.5/site-packages/django/urls/conf.py:34: in include
urlconf_module = import_module(urlconf_module)
.tox/py35-djangomaster/lib/python3.5/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
rest_framework/urls.py:24: in …
```
> Fixed Django 2.1 compatibility due to removal of django.contrib.auth.login()/logout() views.

- rest_framework/compat.py
If pygments did not recognize the language name it was being passed,
this would raise a `NameError` because `TextLexer` import was missing.
> Add import for TextLexer.

- docs/api-guide/caching.md
The default caching system of Django works very well with DRF. However, the usage is not very easy to understand for class based views as the documentation is spread across pages. This pull-request provides example code on how to use caching with `apiviews` and `viewsets`.
(Edit: @carltongibson: Closes #370)
> Adding examples and documentation for caching

- .travis.yml
A simple syntax change to the Travis CI configuration file's include/exclude lists, which may seem awkward at first sight, but enhances readability:
1. Python versions are aligned vertically, line by line
1. Django versions are aligned vertically, line by line
1. `TOXENV`, which luckily has the same width as `DJANGO`, is aligned with environment values above
This allows for faster vertical scanning of the related configuration, and makes it easier to understand the reasoning behind those configurations.
**Credits:** Seen at the [django-analytical](https://github.com/jcassee/django-analytical) project.
> Make Travis CI include/exclude faster to read

- rest_framework/static/rest_framework/docs/css/base.css
Closes https://github.com/encode/django-rest-framework/issues/5370
Current solution is to make .menu-list-bottom: {position: fixed; width: inherit;}, and .menu-list: {width: inherit;}
This appears to have the desired effect of keeping the Auth/Code buttons always at the bottom of the sidebar, and always above the rest of the menu items.
Simply changing the CSS position of menu-list-bottom to 'sticky' instead of 'absolute' causes the Authentication/Source Code buttons to operate as expected.
**NOTE:** The 'position: sticky' is a more recent CSS feature, and so browser support is not universal. See here for a list of supported browsers: [http://caniuse.com/#feat=css-sticky](http://caniuse.com/#feat=css-sticky). Notably, it appears that this change would not work in any version of IE.
The …
> Interactive docs - make bottom sidebar items fixed to bottom (refs #5370)

- rest_framework/utils/serializer_helpers.py
- tests/test_bound_fields.py
> Stop JSONBoundField mangling invalid JSON (#5526)

- rest_framework/schemas/generators.py
- tests/test_schemas.py
Closes #5528.
Viewset custom actions (@detail_route etc) OPTIONS (and HEAD) methods were not being excluded from Schema Generations.
This PR adds a test reproducing the reported error and adjusts `EndpointEnumerator.get_allowed_methods()` to filter ViewSet actions in the same way as other `APIView`s
> Schema: Exclude OPTIONS/HEAD for ViewSet actions

- rest_framework/filters.py
- tests/test_filters.py
Replaces #5525.
Comment from original PR:
> I ran into an issue the other day where a serializer referring to a field in a related object didn't provide the correct field name for the ordering filter backend.
>
> Updating the get_default_valid_fields method so that for dotted sources the . for __ fixes my use case. 
>
I just added a test to check the non-dotted source didn't raise an `AttributeError` calling `replace` on `None`. (It doesn't: `Serializer.fields` provides a sensible `source` even when `None` on the field.)
> Fix dotted source ordering

- rest_framework/fields.py
- tests/test_serializer.py
The following currently fails as it's missing a `default` value for serialization. 
```python
class Serializer(serializers.Serializer):
bar = serializers.CharField(source='foo.bar', allow_null=True)
```
The question is whether or not `allow_null=True` should imply `default=None`. 
Thanks to @eschercode for pointing this out [here](https://github.com/encode/django-rest-framework/commit/07258ca032e062334310c112469d6432f6eeb818#commitcomment-25097134).
cc @xordoquy
> Fields with 'allow_null=True' should imply a default serialization value

- rest_framework/mixins.py
> Ensure Location header is strictly a 'str', not subclass.

- rest_framework/fields.py
- tests/test_fields.py
Closes: #5545
I would expect that this invalid value would raise a ValidationError but instead it raises an OverflowError.
> Catch OverflowError for "out of range" datetimes

- docs/topics/third-party-packages.md
Add https://github.com/allisson/django-rest-framework-rapidjson to third party packages.
> Add djangorestframework-rapidjson to third party packages

- tests/test_authtoken.py
Before jumping into bigger things  I've decided that it would be nice to check the test coverage and see if I can learn more from there. This pr brings test coverage for `drf_create_token` command to 100%.
> increase test coverage for drf_create_token command

- setup.py
Helps users know, at a glance, if the library is compatible with a project.
> Add trove classifier for Python 3.6 support.

- .travis.yml
For documentation on the feature, see:
https://docs.travis-ci.com/user/caching/#pip-cache
With packages cached, builds will be slightly faster and help reduce load on PyPI.
> Add pip cache support to the Travis CI configuration

- tests/test_schemas.py
When running tests with warnings enabled, appear as:
```
DeprecationWarning: invalid escape sequence \d
```
Starting with Python 3.6, invalid escape sequences are deprecated. In a future Python versions they will be a syntax error. For more details, see:
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior
> A backslash-character pair that is not a valid escape sequence now generates a DeprecationWarning. Although this will eventually become a SyntaxError, that will not be for several Python releases.
> Fix invalid escape sequence deprecation warnings

- rest_framework/renderers.py
- rest_framework/templates/rest_framework/docs/error.html
Closes #5496 
Adds a **plain** error template for `DocumentationRenderer`. 
Previously we've not had to switch template for the error case, since both cases are presented the same. With the interactive docs we need to switch to a different template. (We do this by checking whether we have a `coreapi.Document`, as expected, or not.) 
I've not added any styling here. For the 90% case seeing this template is a configuration error, so I've added DEBUG-only notes for explaining that. 
Those that need a better template can easily override in their own projects. 
We can **happily** take PRs improving this template, but I'd rather leave that for community input at this point.
> Add interactive docs error template

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
Closes #5535. Closes #5531
Updates #5535
> Add rounding parameter to DecimalField

- rest_framework/renderers.py
- rest_framework/utils/mediatypes.py
- tests/test_negotiation.py
- tests/test_renderers.py
Running the tests with bytes warning enabled shows some bytes/str mixups. Fix them all.
Some examples of mixing usage:
`str(b'foo')` -- calling str() on bytes
`b'foo' == 'foo'` -- compare str with bytes
`'foo' + b'bar`' -- concatenating str and bytes
> Fix all BytesWarning caught during tests

- rest_framework/decorators.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/inspectors.py
- rest_framework/serializers.py
- tests/test_fields.py
- tests/test_multitable_inheritance.py
- tests/test_one_to_one_with_inheritance.py
- tests/test_renderers.py
- tests/test_serializer_nested.py
Set literals are available on all supported Python versions. They are idiomatic and always faster:
```
$ python3 -m timeit '{}'
10000000 loops, best of 3: 0.0357 usec per loop
$ python3 -m timeit 'dict()'
10000000 loops, best of 3: 0.104 usec per loop
```
```
$ python3 -m timeit '{1, 2, 3}'
10000000 loops, best of 3: 0.0754 usec per loop
$ python3 -m timeit 'set([1, 2, 3])'
1000000 loops, best of 3: 0.228 usec per loop
```
> Use dict and set literals instead of calls to dict() and set()

- rest_framework/fields.py
- tests/test_fields.py
Related to #5534 
Well it is fixes the issue. But I don't know how to test this.
Probably there is a different way to resolve this problem.
> Change ImageField validation pattern

- rest_framework/utils/urls.py
- tests/test_utils.py
Existing code fails under Python 2.7 if it got incorrect unicode from query string (see new tests).
I propose fix that allow correctly work under Python 2 & 3.
> fix processing unicode symbols in query_string by Python 2

- rest_framework/compat.py
- rest_framework/urls.py
- tests/conftest.py
- tests/importable/__init__.py
- tests/importable/test_installed.py
> Add rest_framework.compat import test

- rest_framework/compat.py
- rest_framework/schemas/inspectors.py
The `urlparse` shim in `compat.py` duplicates Django's bundled six. Can rely on upstream instead of duplicating their works. Unifies shim with other files already using six.
> Remove ulrparse compatability shim; use six instead

- rest_framework/compat.py
- rest_framework/utils/encoders.py
- tests/test_compat.py
`TimeDelta.total_seconds()` was introduced in Python 2.7 and 3.2. It is available on all supported Python versions.
https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds
https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds
> Drop compat wrapper for TimeDelta.total_seconds()

- rest_framework/compat.py
- rest_framework/relations.py
- rest_framework/reverse.py
- rest_framework/routers.py
- rest_framework/schemas/generators.py
- rest_framework/templatetags/rest_framework.py
- rest_framework/urlpatterns.py
- rest_framework/utils/breadcrumbs.py
- tests/test_permissions.py
- tests/test_reverse.py
- tests/test_urlpatterns.py
- tests/utils.py
- flake8 was globally disabled on the `compat` module, which is why whitespace issues went undetected by the linter. Removed the global noqa and re-added where necessary to individual lines.
- simplified and removed unnecessary imports (eg, unnecessary urls imports, old templates imports).
- `RegexURLPattern` => `URLPattern`
- `RegexURLResolver` => `URLResolver`
> Compat cleanup

- rest_framework/renderers.py
PRs #5462 and #5513 added a pygments plugin to the markdown converter for API docs.  The same conversion is applied by DocumentationRenderer and BrowsableAPIRenderer, but the latter was missing the style block with the pygments CSS declarations.
This PR adds it.
> Add pygments CSS block in browsable API views

- rest_framework/request.py
- tests/test_middleware.py
Supersedes/closes #5583 and fixes #5582.
> Fix request body/POST access

- tests/test_serializer.py
Test incorrectly references #2505, should be #2555.
> Rename test to reference correct issue

- docs/api-guide/serializers.md
- model serializers must provide either "fields" or "exclude" as attribute (since version 3.3.0). In case of doubts, please check the django-rest-framework/rest_framework/serializers.py file, around line 1065.
> Fix in documentation

- docs/api-guide/fields.md
- docs/index.md
- docs/tutorial/1-serialization.md
- docs/tutorial/4-authentication-and-permissions.md
- rest_framework/authtoken/serializers.py
- rest_framework/renderers.py
- rest_framework/urls.py
- rest_framework/utils/model_meta.py
- tests/test_atomic_requests.py
- tests/test_fields.py
- tests/test_filters.py
Per the trove classifiers, DRF only supports Django versions 1.10+. Can drop documentation, code comments, and workarounds for older Django versions.
> Remove references to unsupported Django versions in docs and code

- rest_framework/serializers.py
- tests/test_model_serializer.py
- First commit adds a test for the existing behavior. 
- Second commit would fix #5596.
I'm not particularly inclined towards the change in behavior, but it was fairly trivial to implement. 
Thoughts @xordoquy, @carltongibson?
> Test Serializer exclude for declared fields

- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
This contains a test for #5594 as well as a fix for that issue.
Fixes: #5594
> Fixed schema generation for filter backends

- rest_framework/request.py
- tests/test_request.py
Supersedes #5576. Many thanks to @yotamofek for the original PR.
> Reimplement request attribute access w/ __getattr__

- rest_framework/renderers.py
- tests/test_renderers.py
Under Py3 the base64.b64encode() method returns a binary object, which gets rendered as `b'...'` in schema.js. This results in the output becoming:
var coreJSON = window.atob('b'eyJf...'');
which is invalid Javascript. Because base64 only uses ASCII characters it is safe to decode('ascii') it. Under Py2 this will result in a unicode object, which is fine. Under Py3 it results in a string, which is also fine. This solves the problem and results in a working schema.js output.
refs #5608
> SchemaJSRenderer renders invalid Javascript

- rest_framework/request.py
- tests/test_metadata.py
- tests/test_request.py
Fixes #2771 by implementing a simple check on the `request` argument's type.
> Perform type check on passed request argument

- docs/api-guide/authentication.md
- docs/api-guide/requests.md
- rest_framework/request.py
- tests/test_request.py
Fixes #4033. There is an existing test for the issue, however there are a couple of issues:
- No authentication middleware is used, so the `request.user` is never set. Because of this, `__getattribute__` will re-raise the `AttributeError`. However, typical use does include an authentication middleware and will yield a `user` on the underlying request, as demonstrated by #4033.  
- The `SessionMiddleware` is applied to the DRF request object instead of the underlying Django request, which doesn't mirror how middleware is actually applied.
> Fix AttributeError hiding on request authenticators

- .isort.cfg
- requirements/requirements-codestyle.txt
- requirements/requirements-optionals.txt
- requirements/requirements-testing.txt
- rest_framework/schemas/inspectors.py
- rest_framework/templatetags/rest_framework.py
- rest_framework/utils/encoders.py
- rest_framework/validators.py
- tests/importable/test_installed.py
- tests/test_description.py
- tests/test_one_to_one_with_inheritance.py
Pulled this out of #5624. Updates the test requirements and fixes the newly raised issues:
- bare except statements
- whitespace around imports
> Update test requirements

- MANIFEST.in
- setup.py
I've punted on moving the package under a `src` directory, and just made the minimum necessary changes. Also, fixes #5615.
----
I don't know if we want to accept this as is, given that I moved the package contents into a `src` directory. If we're willing to accept that change, the move is for a good reason. `tox` *does* create and install the package distribution into the test environment, however this conflicts with the `rest_framework` package that's located on the current path. Because the distribution and local files conflict, you cannot effectively test the distribution's packaged files. eg, the distribution may not be correctly configured (missing templates/static files), but the files on the local path *do* have them, so the tests pass erroneously.
The solution is to move the …
> Fix packaging?

- .travis.yml
- README.md
- requirements/requirements-packaging.txt
- setup.py
- tox.ini
Adds a CI build for checking README markdown => restructuredtext conversion.
Fixes #3817.
Requires a few changes:
- The HTML that centers the sponsor images needs to be removed.
- The italics around funding links needs to be removed
- Add hr between image and subsequent section
> Fix readme, add to CI

- rest_framework/fields.py
- tests/test_serializer.py
Prior to the #5518, all fields with `required=False` and without a explicit default value were not included in the output.
After the patch, even non-required fields now had a default value, which is counter-intuitive if you look at the [`required`](http://www.django-rest-framework.org/api-guide/fields/#required) documentation, which says _Set to false if this field is not required to be present during deserialization_.
This PR restore the original `required=False` behaviour. Now, any `required=False` without a explicit default value should not be returned in the output.
However, it keeps the implicit `default=None` for required fields introduced in #5518.
Question I: Did I wrote the test in the correct class (`TestNotRequiredOutput`) or should it be in the `TestDefaultOutput` class? …
> Non-required fields with 'allow_null=True' should not imply a default value

- docs/api-guide/fields.md
From #5639, although I'm indifferent to its inclusion.
> Add allow_null serialization output note

- tox.ini
Was previously using a release candidate as the minimum version.
> Update to use the Django 2.0 release in tox.ini

- rest_framework/serializers.py
- tests/browsable_api/test_form_rendering.py
- tests/test_serializer.py
> Fix Serializer.data when provided invalid 'data'

- docs/api-guide/schemas.md
- docs/topics/release-notes.md
- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
Allows reuse of logic to replace Field instances in a field list by `Field.name`.
Adds a utility function for the logic plus a wrapper method on `AutoSchema`.
Closes #5632
TODO:
> Extract method for `manual_fields` processing

- docs/api-guide/schemas.md
AutoSchema uses GenericAPIView hooks to introspect. If these are not present it’s results will be limited. Note this.
Closes #5121
> Note AutoSchema limitations on bare APIView

- docs/api-guide/viewsets.md
- rest_framework/routers.py
- rest_framework/viewsets.py
- tests/test_routers.py
- tests/test_viewsets.py
Just breaking out a portion of #5605. 
`ViewSet`s cannot effectively reverse their action URLs, as they aren't aware of the `basename` they were registered to the router with. This value can be hardcoded in the view class, however this is problematic when the `ViewSet` is registered with a different `basename`. 
- Routers now provide the `basename` with the viewset's `initkwargs`.
- Added `.reverse_action()` convenience method to viewsets.
> Add '.basename' and '.reverse_action()' to ViewSet

- docs/api-guide/serializers.md
Fixes #5651.
Change `update()` to `.update()` in serializers documentation to get a
consistency with `.create()`.
> Typos in serializers documentation

- rest_framework/settings.py
- tests/test_settings.py
Closes #2466 Ref #5658
As per #2466, the `override_settings` integration was updating the APISettings object correctly but was not functioning as expected since the documented usage `from rest_framework.settings import api_settings` is bound at import time.
This PR adds a (failing) test checking compat and adjusts the code to refresh APISettings in place, rather than replace the instance. `override_settings` then works as expected. 
Fix was suggested by @daggaz — thanks for that! (PRs always welcome! 🙂)
> Fix `override_settings` compat

- docs/api-guide/fields.md
- docs/api-guide/serializers.md
Closes #5664
1. Explains/explicitly states that BooleanField is generated with `required=False`, because `models.BooleanField` is always `blank=True`. This has come up a few times so should (help to) clear up confusions.
2. Additionally adds link to [a worked example configuring serialiser generation to use a BooleanField subclass with `required=True`](http://notes.noumenal.es/2017/12/13/required-by-default.html). This should be helpful, as it's not hard but it's not trivial either.
3. Finally adds same link to `.serializer_field_mapping` docs, since an example (especially needing to use `deepcopy`) may be handy there too.
> Add docs note re generated BooleanField being `required=False` 

- .travis.yml
- runtests.py
- tox.ini
This is a continuation of #5624, proposing that the package be moved under a `src` dir. To recap: 
> `tox` *does* create and install the package distribution into the test environment, however this conflicts with the `rest_framework` package that's located on the current path. Because the distribution and local files conflict, you cannot effectively test the distribution's packaged files. eg, the distribution may not be correctly configured (missing templates/static files), but the files on the local path do have them, so the tests pass erroneously.
>
> The solution is to move the package off of the path (usually into a `src` directory), so that the local files are not importable.
This iteration fixes issues with coverage data. Most of the builds do use the local files via an editable …
> Add 'dist' build

- rest_framework/throttling.py
Title says it all. I was reading the implementation of `SimpleRateThrottle` in order to set custom rate limit for specific API and I found the typo.
> Fix typo in docstring

- docs/api-guide/settings.md
When removing authentication entirely you cannot import `django.contrib.auth.models.AnonymousUser`
Closes #3494
Adds a note to the `UNAUTHENTICATED_USER` setting docs saying to set to `None`. 
* #3494 has been sat there forever. It's never going to be addressed directly, so beyond this I don't see what we can do. 
* I think removing `django.contrib.auth` is sufficiently beyond the core case that we can expect users to have discovered this (or do so with a quick search).
> Add UNAUTHENTICATED_USER = None note

- docs/topics/documenting-your-api.md
Closes #3489
* Updates example to post-3.0 API, using metadata class
* Adds link to metadata docs.
> Update OPTIONS example from “Documenting Your API”

- docs/api-guide/views.md
Closes #5636 as per https://github.com/encode/django-rest-framework/issues/5636#issuecomment-348143281
Adds Note linking to Classy DRF near beginning of `Views` docs. This should be prominent enough.
> Add link to Classy DRF in docs

- docs/api-guide/viewsets.md
Closes #2941
Provides example of adjusting permission by action.
> Document ViewSet.action

- rest_framework/compat.py
- rest_framework/schemas/generators.py
- tests/test_renderers.py
- tests/test_schemas.py
- Call `str(pattern)` to get non-escaped route.
- Strip converters from route to comply with uritemplate format.  Background: https://github.com/encode/django-rest-framework/issues/5675#issuecomment-352829363
Closes #5675
> Fix URL pattern parsing in schema generation

- docs/api-guide/fields.md
Closes #2032 closes #3066
Adds an example using `source='*'` to create a nested representation from a flat object. 
> Need to explain how this interacts with non-read_only fields, and describe why a dictionary is expected from to_internal_value in that case. — https://github.com/encode/django-rest-framework/issues/3066#issue-90381563
Does that.
> Add example using `source=‘*’` to custom field docs.

- rest_framework/compat.py
- rest_framework/schemas/generators.py
- rest_framework/urlpatterns.py
- tests/test_urlpatterns.py
Broken urls are generated by `format_suffix_patterns` when using `urlpatterns` specified with the new `path()` routes added in Django 2.
Closes #5672
> Fix format_suffix_patterns behavior with Django 2 path() routes

- MANIFEST.in
Resolves #5695
(Tiny typo in https://github.com/encode/django-rest-framework/pull/5696)
> Fix typo to bring back locale files to installed files

- docs/topics/release-notes.md
I Was looking through the release notes before upgrading and I noticed that [3.7.4](http://www.django-rest-framework.org/topics/release-notes/#374) wasn't reading nicely. It's because it's missing an empty line after the note:
> Fix formatting of the 3.7.4 release note

- docs/api-guide/serializers.md
A simple update to the status of writable nested serializers.
> Update writable nested serializers status

- docs/tutorial/4-authentication-and-permissions.md
Fixing code "typo" in example.
In the original file, line 145 reads:
url(r'^api-auth/', include('rest_framework.urls'),
It's missing the closing parenthesis.
> Fixed "typo" in example.

- rest_framework/fields.py
- tests/test_fields.py
Fixes #3274
This is an extension of the discussion in #5644. Errors raised on composite fields (`DictField` & `ListField`) are confusing, since child validation errors don't contain any indication of what index/key failed.
As stated by the [django docs](https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#hstorefield), the hstore field accepts nulls as values.
```python
class Product(models.Model):
attributes = HStoreField()
class ProductSerializer(serializers.ModelSerializer):
class Meta:
model = Product
fields = ['attributes']
```
With the below input data, we currently exhibit the following error:
```python
>>> q = ProductSerializer(data={"attributes": {"first": "value", "second": None}})
>>> q.is_valid()
>>> q.errors
{'attributes': ['This field may not be null.']}
``` …
> Improve composite field child errors

- rest_framework/renderers.py
- rest_framework/templates/rest_framework/horizontal/dict_field.html
- rest_framework/templates/rest_framework/horizontal/list_field.html
- rest_framework/templates/rest_framework/inline/dict_field.html
- rest_framework/templates/rest_framework/inline/list_field.html
- rest_framework/templates/rest_framework/vertical/dict_field.html
- rest_framework/templates/rest_framework/vertical/list_field.html
`ListField` & `DictField` do not seem to have proper HTML form support. Until they do, it would make sense to render a disabled form input, similar to how nested list serializers are currently handled.
Is there any reason not to disable these inputs?
Additionally, I would add tests for this, but I don't see any relevant tests for serializer form rendering.
> Disable HTML inputs for dict/list fields

- docs/api-guide/versioning.md
Reformulated a nonsensical sentence in HostNameVersioning documentation.
> Fix typo in HostNameVersioning doc

- rest_framework/settings.py
While checking the code to steal the import parts to a project of my own I came across this two lines that could be rewritten, nothing fancy but hey, one line less
> using rsplit to get module and classname for imports

- docs/api-guide/testing.md
- rest_framework/test.py
- tests/test_routers.py
- tests/test_testing.py
- tests/test_versioning.py
In working on #5609, I found myself reusing the `URLPatternsTestCase` from the API versioning tests. This PR formalizes it with tests and docs, as well as refactoring the router tests (per #5609). If we don't want to formalize this, an alternative would be to just move this under the `tests.utils` module, and use it internally.
> Formalize URLPatternsTestCase

- tests/test_exceptions.py
Test for #5696. 
This PR is based off of the commit that adds the `dist` build, which doesn't include the fix from #5696. Running the tests locally, this fails. However, Travis creates a merge commit from the current master, so this passes in CI.
> Add basic translation tests

- runtests.py
- tests/conftest.py
- tox.ini
Test for #5692. This is committed in the same vein as #5700, which is based off of d12005cf902e3969b5002593eab83bb63feda840 (added the dist build). Tests will fail locally (as expected), but the merge commit in CI causes this to pass (as expected, since master contains the fixed MANIFEST.in).
By default `ManifestStaticFilesStorage` is strict in that missing static files will raise exceptions during the `collectstatic` call. The missing .woff2 and .ico files would have been caught by this.
> Test staticfiles

- docs/api-guide/serializers.md
- rest_framework/fields.py
- rest_framework/filters.py
- rest_framework/relations.py
- rest_framework/renderers.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/inspectors.py
- rest_framework/serializers.py
- rest_framework/test.py
- rest_framework/utils/html.py
- rest_framework/utils/mediatypes.py
- tests/test_bound_fields.py
- tests/test_fields.py
- tests/test_metadata.py
- tests/test_multitable_inheritance.py
- tests/test_one_to_one_with_inheritance.py
- tests/test_permissions.py
- tests/test_request.py
- tests/test_serializer_lists.py
Calling `dict.keys()` is unnecessary. The two are functionally equivalent on modern Pythons.
Inspired by Lennart Regebro's talk "Prehistoric Patterns in Python" from PyCon 2017.
https://www.youtube.com/watch?v=V5-JH23Vk0I
> Perfer iter(dict) over iter(dict.keys())

- docs/topics/project-management.md
- setup.py
Helps pip decide what version of the library to install.
https://packaging.python.org/tutorials/distributing-packages/#python-requires
> If your project only runs on certain Python versions, setting the
> python_requires argument to the appropriate PEP 440 version specifier
> string will prevent pip from installing the project on other Python
> versions.
https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords
> python_requires
>
> A string corresponding to a version specifier (as defined in PEP 440)
> for the Python version, used to specify the Requires-Python defined in
> PEP 345.
> Pass python_requires argument to setuptools

- docs/api-guide/authentication.md
- docs/api-guide/caching.md
- docs/api-guide/fields.md
- docs/api-guide/filtering.md
- docs/api-guide/pagination.md
- docs/api-guide/permissions.md
- docs/api-guide/relations.md
- docs/index.md
- docs/topics/2.2-announcement.md
- docs/topics/browsable-api.md
- docs/topics/internationalization.md
- docs/topics/release-notes.md
- docs/topics/rest-framework-2-announcement.md
- docs/topics/rest-hypermedia-hateoas.md
- docs/tutorial/quickstart.md
Each removed link has no inline use.
> Remove unused links from docs

- docs/api-guide/fields.md
- requirements/requirements-optionals.txt
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_fields.py
- tests/test_model_serializer.py
Fixes #5644
- Add postgres to optional reqs
- Add postgres fields mapping tests
- Add importable `HStoreField`
- Ensure `HStoreField` accepts `null` values by default
> Add HStoreField, postgres fields tests

- docs/api-guide/serializers.md
As specified in the [exceptions documentation](http://www.django-rest-framework.org/api-guide/exceptions/):
>By convention you should import the serializers module and use a fully qualified `ValidationError`
Most examples in the [serializers documentation](http://www.django-rest-framework.org/api-guide/serializers/) followed this convention, but there were several cases (including three confusing lines of code) that didn't.
> Always fully qualify ValidationError in docs

- rest_framework/schemas/inspectors.py
ManualSchema.get_link had two return statements. Prune the second
(unreachable) return.
> Remove unreachable code from ManualSchema

- docs/topics/documenting-your-api.md
- rest_framework/documentation.py
- rest_framework/renderers.py
- rest_framework/templates/rest_framework/docs/document.html
- rest_framework/templates/rest_framework/docs/index.html
- rest_framework/templates/rest_framework/docs/langs/shell-intro.html
- rest_framework/templates/rest_framework/docs/langs/shell.html
- rest_framework/templates/rest_framework/docs/link.html
- rest_framework/templates/rest_framework/docs/sidebar.html
Includes #5257, rebases, and adds documentation.
By subclassing `DocumentationRenderer` and providing appropriate templates, users can customise the languages/libraries for the code samples available in the interactive API docs.
> Allowed customising API documentation code samples

- docs/api-guide/metadata.md
- docs/api-guide/routers.md
- docs/api-guide/viewsets.md
- docs/topics/release-notes.md
- docs/tutorial/6-viewsets-and-routers.md
- rest_framework/decorators.py
- rest_framework/routers.py
- rest_framework/viewsets.py
- tests/test_decorators.py
- tests/test_routers.py
- tests/test_schemas.py
- tests/test_viewsets.py
Pulling a slightly more manageable chunk out of #5605 for review. The goal is to remove logic from the router in order to make the viewsets and list/detail actions more introspectable.
**Changes:**
- Deprecated `list_route` & `detail_route` in favor of `action` decorator w/ `detail` boolean.
- Deprecated dynamic list/detail route variants in favor of `DynamicRoute` w/ `detail` boolean.
- Added `detail` boolean argument to regular `Route`
- A route's `detail` is now provided as an `initkwarg` to the ViewSet, similar to `suffix`.
- Added `ViewSet.get_extra_actions()` to formalize extra action access.
- Added `url_path` and `url_name` to `action` signature. These values are no longer set/altered by the router, and can be more reliably inspected by the parent viewset.
- Refactored dynamic …
> Rework dynamic list/detail actions

- docs/topics/api-clients.md
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- rest_framework/templates/rest_framework/docs/error.html
- rest_framework/templates/rest_framework/docs/index.html
- rest_framework/templates/rest_framework/docs/langs/javascript-intro.html
- rest_framework/templates/rest_framework/login_base.html
Starting with Django 1.10, it is preferable to load the `static` template tag library instead of `staticfiles`. If `django.contrib.staticfiles` is in `INSTALLED_APPS`, the `static` template tag library will use the `staticfiles` app to determine static paths. For additional details, see:
https://docs.djangoproject.com/en/dev/releases/1.10/#django-contrib-staticfiles
> The static template tag now uses `django.contrib.staticfiles` if it’s in `INSTALLED_APPS`. This is especially useful for third-party apps which can now always use `{% load static %}` (instead of `{% load staticfiles %}` or `{% load static from staticfiles %}`) and not worry about whether or not the `staticfiles` app is installed.
The `staticfiles` template tag library will be deprecated and removed in a future Django …
> Use {% load static %} instead of {% load staticfiles %} in templates

- docs/api-guide/versioning.md
There was a typo in the documentation when referring to the class name `NamespaceVersioning` that tripped me up. This should fix that.
> Refer to "NamespaceVersioning" instead of "NamespacedVersioning" in the documentation

- rest_framework/exceptions.py
- tests/test_exceptions.py
This mainly adds `__eq__` to handle `code` in comparisons.
When comparing an ErrorDetail to a string (missing `code` there) the
ErrorDetail's `code` is ignored, but otherwise it is taken into account.
> ErrorDetail: add __eq__/__ne__ and __repr__

- rest_framework/views.py
Map Django's 404 & 403 to DRF's exceptions, making responses consistent (otherwise `default_code` / `code` is not honored).
> Make 404 & 403 responses consistent with `exceptions.APIException` output

- docs/api-guide/schemas.md
In the API-documentation: Adding missing parameters to get_manual_fields()
Closes #5794
> small fix to API documentation: schemas

- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
By default all subclasses of RelatedField are output as string fields in
the schema, which works well for StringRelatedField, SlugRelatedField or
HyperlinkedRelatedField.
Handle the common case of a PrimaryKeyRelatedField pointing to an
AutoField.
> Fix schema generation for PrimaryKeyRelatedField

- rest_framework/request.py
- tests/test_request.py
Pulling this out of #5771. This fixes a bug from #5590, where the request POST/FILES were *also* set for requests that did not have a form media type.
> Fix request formdata handling

- rest_framework/authtoken/views.py
Some of the imports seem to be incorrectly sorted, which has been causing problems with new PRs.
> Fix authtoken views imports

- docs/api-guide/permissions.md
Add https://github.com/allisson/django-rest-framework-role-filters to third party packages in permissions doc.
> Add Django Rest Framework Role Filters to Third party packages

- docs/tutorial/4-authentication-and-permissions.md
- rest_framework/routers.py
Updates the tutorial and the codebase to be be PEP308-compliant with regards to conditional ternary operations `this if condition else that`.
I came across this from following the tutorial and found that the example was using `condition and this or that`-style conditional which seemed not very Pythonic. The codebase only uses this style once and this pull request also changes that instance.
> Changes ternary conditionals to be PEP308 compliant

- .isort.cfg
- requirements/requirements-codestyle.txt
- rest_framework/fields.py
- rest_framework/pagination.py
- rest_framework/parsers.py
- rest_framework/reverse.py
- rest_framework/serializers.py
- rest_framework/test.py
- runtests.py
- setup.cfg
- setup.py
- tests/test_description.py
TODO:
~~- [ ] rebase after #5819 is merged~~
> Upgrade isort

- rest_framework/fields.py
- tests/test_fields.py
Updates and closes #5821. 
* Adds (previously failing) test for non-ISO8601 formatted datetimes, when overriding active timezone. (Thanks @hakib.)
* Applies `enforce_timezone` in all cases, not just ISO 8601 datetimes.
> Fixed active timezone handling for non ISO8601 datetimes. 

- rest_framework/templates/rest_framework/horizontal/input.html
- rest_framework/templates/rest_framework/inline/input.html
- rest_framework/templates/rest_framework/vertical/input.html
- tests/test_bound_fields.py
Fixes #5767. Updates & Closes #5768.
* Adjusts templates to allow integer field 0 values. Thanks @nikhil96sher
* Adjusts test case.
> Made TemplateHTMLRenderer render IntegerField inputs when value is `0`. 

- docs/tutorial/7-schemas-and-client-libraries.md
Closes #5810
Issue report was correct: corejson is not available on the [root endpoint](https://restframework.herokuapp.com/), but on the [/schema/ endpoint](https://restframework.herokuapp.com/schema/).
> Corrected endpoint in tutorial instructions

- rest_framework/serializers.py
This fixes a small but somewhat confusing typo in a comment.
> Fix comment typo in ModelSerializer

- tests/conftest.py
The tests look for the "admin" app in the list of apps. If not present, running `runtests.py` gives the following error:
```
LookupError: No installed app with label 'admin'.
```
Adding admin to `INSTALLED_APPS` fixes it.
OS : Windows 10
Python version: 3.6.4
Django version: 2.1
> Add admin to installed apps to avoid test failures

- rest_framework/metadata.py
- tests/test_metadata.py
> Fixed schema for UUIDField in SimpleMetadata.

- docs/api-guide/routers.md
For Django 2.0 you MUST provide `app_name` when using `namespace`.
Closes #5659
> Corrected docs on router include with namespaces.

- tests/models.py
- tests/test_serializer.py
Test using model objects for dotted source default when path components may be null.
Ref #5375, #5727
There are two branches in `rest_framework.fields.get_attribute`: 
https://github.com/encode/django-rest-framework/blob/0da461710ad552c401a47b29b93e829ce879a696/rest_framework/fields.py#L97-L100
Previous tests were only exercising the `if` branch. This PR adds similar tests covering the `else`.
> Test using model objects for dotted source default

- docs/api-guide/validators.md
- rest_framework/serializers.py
- tests/test_fields.py
- tests/test_serializer.py
Since ≈forever `read_only` fields with a `default` have set that default in `validated_data` on create and update operations. 
This has led to issues as we have tried to _Fix default value handling for dotted sources_ #5375: uses such as `source=a.b.c, default='x'` where e.g. `b` may be null were returning `None`, rather than the default `x`. 
#5375 resolved the _serialisation_ issues with dotted `source` — `default` will be used if any step in the chain is `None` —  but revealed a latent issue for _deserialisation_ when using `read_only` plus a `default`. This comes up in a couple of ways: 
* The check for nested writes errors on a read_only field with dotted source and default. #4666. (Exact reproduce pending on this one.)
* Skipping that, `validated_data` ends up including a nested …
> Alter read_only+default behaviour

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_serializer.py
This PR reverts #5639. There `required=False` would override the implicit default coming from `allow_null`, omitting the field from inclusion. This was incorrect, as reported in #5708. 
* Adds a test for #5708. (Thanks @ticosax for the original report and test) 
* Reverts #5639 
* Adjusts Field docs slightly. 
Closes #5708. 
There's a slight BC issue here — although we're restoring an older behaviour. Overriding `data` to remove the offending field if `None` would serve as a fallback. 
TODO:
> Correct allow_null behaviour when required=False
