docs/api-guide/authentication.md
+ It is consistent with docs about DEFAULT_PERMISSION_CLASSES
=> fixed doc : DEFAULT_AUTHENTICATION_CLASSES -> DEFAULT_AUTHENTICATION

docs/api-guide/routers.md
correcting unclosed quote in routers.md
=> correcting unclosed quote in docs routers.md 

rest_framework/request.py, tests/test_metadata.py
Should be self-explanatory after #2456 :)
=> Clone the versioning_scheme when necessary. Fixes #2477

rest_framework/response.py
=> _closable_objects as an empty list, not deleted

docs/topics/3.0-announcement.md, docs/tutorial/1-serialization.md
Fixes #2493 and updates example in 3.0 announcement.
=> Fix base_template examples 

docs/api-guide/routers.md, docs/api-guide/viewsets.md
* Remove "you you" from viewsets API-guide
* Fix link from routers API-guide to viewsets API-guide
=> Small documentation fixes

docs/topics/3.1-announcement.md
=> Fix typo in 3.1 announcement

rest_framework/filters.py, tests/test_filters.py
=> Address Search Filter duplicates

rest_framework/compat.py, rest_framework/settings.py
=> Move `importlib` fallback into compat.

docs/api-guide/requests.md
I just bumped across this one when reading the docs :) .
=> Fix typo in requests.md

rest_framework/renderers.py, tests/test_renderers.py
Proves that #2410 didn't work and that #2552 fixes the problem.
=> Fixes HiddenField being rendered in HTMLFormRenderer

rest_framework/templates/rest_framework/horizontal/select_multiple.html, rest_framework/templates/rest_framework/inline/select_multiple.html, rest_framework/templates/rest_framework/vertical/select_multiple.html
=> Disable select field if no choices available

rest_framework/validators.py, tests/test_validators.py
According this https://github.com/tomchristie/django-rest-framework/issues/2452
=> Fix UniqueTogetherValidator for NULL values

rest_framework/fields.py, tests/test_fields.py
Hey Tom,
Here's a possible fix for the original part of #2598. I'm no python expert, so if this is a bad idea please tell me why I'm wrong. Thanks for your time!
Evan
=> Dont swallow errors in callable sources

rest_framework/validators.py
=> Ensure validators are new-style classes on python2

rest_framework/fields.py
as requested, small fix for #2611, partially fixes issues described in #2485
=> fix DictKey initial value

tests/conftest.py
Remove unused middleware and password hashers.
=> Simplify test settings

docs/api-guide/versioning.md
Nothing fancy, hope that helps.
=> Put the needed import in one example

docs/api-guide/validators.md
Prevents having to lookup the import
=> Specifying module for CurrentUserDefault()

README.md
=> Update 2.4 docs url for real

docs/api-guide/routers.md
=> update info about wq.db.rest router

docs/api-guide/filtering.md
In section "Third party packages" added link to my package.
=> Added link to djangorestframework-word-filter package

docs/api-guide/relations.md
Love the framework, here's a little grammar fix for the documentation.
=> minor grammar fix

README.md
pypip.in has been having some issues for a while now, any objections on changing to shields.io?
=> Use shields.io instead of pypip.in

docs/api-guide/authentication.md
=> Add a warning about totally custom login views.

docs/api-guide/fields.md, rest_framework/fields.py, tests/test_fields.py
This is  #2788 with format examples.
=> Add 'format' argument to UUIDField (overides #2788)

docs/api-guide/generic-views.md
=> Replace the former `get_filter_backends` by `filter_queryset`.

docs/api-guide/versioning.md, rest_framework/versioning.py, tests/test_versioning.py
The example versioning regex never did match.
=> Fix versioning urls

docs/api-guide/viewsets.md
I'm not sure what the contribution policy for the docs is, but I thought it'd be faster to issue a pull request than reaching out to you guys/creating an issue for something so simple. Hope it's not a problem :)
=> Fixed minor typo on viewsets.md

docs_theme/base.html, docs_theme/css/default.css
=> Set dynamic maximum height for dropdown widgets

rest_framework/compat.py, tests/test_request.py
fixes https://github.com/tomchristie/django-rest-framework/issues/3053
=> Compat requestfactory secure

rest_framework/relations.py, tests/test_relations.py
Added failing test for ticket https://github.com/tomchristie/django-rest-framework/issues/3042 
Another patch that fixes the issue will be coming shortly
=> Fixed many=False issue on related fields

rest_framework/serializers.py
Is there any reason why this is a bad idea?
=> Cache fields list for to_internal_value and to_representation

docs/index.md, docs_theme/css/default.css
=> Remove Twitter button for mobile rendering

docs/api-guide/pagination.md
Based on #2614. (Thanks @stevelacey!)
=> Fix link headers in examples, as per RFC5988.

rest_framework/fields.py, tests/test_fields.py
Closes #2710.
Thanks to @johtso for the original work in #2712.
=> Support allow_blank=False with trim_whitespace=True.

docs/api-guide/validators.md
Updated example in docs as suggested by @jpadilla and seconded by @tomchristie.
=> Fixed #2900 -- Made example validator class in docs inherit from object

rest_framework/filters.py
=> Ensure no duplication of results with SearchFilter with Oracle databases.

docs/topics/3.0-announcement.md
Fixed typo in Miscellaneous notes of 3.0 release announcement docs
=> Fixed typo in docs

rest_framework/fields.py, rest_framework/relations.py, rest_framework/serializers.py, tests/test_fields.py
Available for:
* ListField
* ListSerializer
* ManyRelation
* MultipleChoiceField.
Closes #2250.
=> Added allow_empty flag

requirements/requirements-optionals.txt, rest_framework/filters.py
=> Upgrade guardian support to 1.3.

rest_framework/filters.py
Upgrade guardian support to 1.3. #3165 
Is it possible to port this fix in time for 2.4.7?  Apologies if this is not the correct procedure, or if this is already in hand. 
Thanks for all the hard work!
=> Cherry picks

docs/api-guide/fields.md, rest_framework/compat.py, rest_framework/fields.py, rest_framework/filters.py, rest_framework/renderers.py, rest_framework/serializers.py, tests/test_fields.py
Mostly just the work in #2626, with some minor tweaks/tidy up.
Thanks to @Ins1ne!
Closes #1854.
=> Add `FilePathField`

docs/api-guide/permissions.md
many people don't know how to import permission_classes
=> import permission_classes

rest_framework/response.py
=> Raise error if passed a serializer instance

rest_framework/utils/serializer_helpers.py
=> Resolved issue with rendering of nested serializers form when value is None

rest_framework/filters.py
=> Don't error on missing `search_fields` attribute.

docs/tutorial/1-serialization.md
hi,
I’ve fixed the issue #3395  in the branch named “ 3395” in my fork. 
**ISSUE** :The output text at line 184 in docs/tutorial/1-serialization.md is not correct. #3395
=> fix issue #3395

docs/api-guide/authentication.md
As suggested, pr with django-rest-knox reference
=> added knox package reference to 3rd party auth apps

rest_framework/fields.py, rest_framework/serializers.py, rest_framework/settings.py
Refs #2466. See also #3430.
Still needs eg settings on views to be updated.
=> Access settings lazily, not at module import.

.travis.yml, README.md, docs/index.md, rest_framework/utils/field_mapping.py, tox.ini
=> Django 1.9 support

rest_framework/utils/field_mapping.py, tests/test_model_serializer.py
=> Map TextField max_length to CharField

docs/api-guide/fields.md
=> Missing the `source=` keyword for the URLField parameter

docs/topics/3.3-announcement.md
Really small one, the link wasn't working.
=> Fix announcement link typo

docs/api-guide/renderers.md, rest_framework/templates/rest_framework/admin.html, rest_framework/templates/rest_framework/admin/list.html
For https://github.com/tomchristie/django-rest-framework/issues/3338
=> update docs about detail page link for AdminRenderer

docs/api-guide/serializers.md
See https://groups.google.com/forum/?fromgroups=#!topic/django-rest-framework/01ra1-h_J3w
=> Documentation fix for list serializers.

tox.ini
Security release issued https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/
=> Update Django versions

rest_framework/compat.py
Linked to #3654 (https://github.com/tomchristie/django-rest-framework/pull/3654#issuecomment-159417427)
=> Make DRF compatible with multi template engine in Django 1.8

docs/api-guide/pagination.md
=> Document how to turn pagination off

docs/api-guide/versioning.md
PR for the same. Please review and accept.
=> Fix for Incorrect regex in URLPathVersioning documentation #3638

tox.ini
:fireworks:  Django 1.9 stable was [just released](https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/)!
=> Use latest release of Django 1.9

rest_framework/authtoken/views.py
This fixes #3718 and possibly other incompatibilities.
=> Add extra args/kwargs to authtoken's views (#3718)

docs/api-guide/pagination.md
Reading the pagination page, I came across a couple of typos and grammar changes.
* Changed "loosing" to "losing"
* Changed "usecases" to "use cases"
=> Some minor typos and grammar changes.

rest_framework/serializers.py, tests/test_model_serializer.py
=> Fixes #3804, avoiding update of Meta.extra_kwargs

rest_framework/settings.py
Minor fix for dictionary key lookup in settings file
=> Fixes #3786

rest_framework/authtoken/models.py, tests/models.py
python -Werror generates warnings informing that on_delete is a required keyword in Django 2.0
=> Regarding #3729

docs/topics/html-and-forms.md
=> Fix update model example in html-and-forms.md

docs/api-guide/versioning.md
They seem to have changed the structure of the document.
=> Update link to Heroku guidelines

docs/api-guide/serializers.md
=> Fix broken link format

tests/test_relations.py
=> Refactor the `get_queryset` overriding test

tox.ini
This should make #3729 easier.
=> Displayed warnings during test suite.

docs/api-guide/relations.md
=> Fix typo in relations docs

docs/tutorial/1-serialization.md
Since django >= 1.9 adopted a new style for including apps, drf tutorial should be updated
=> updated tutorial for django 1.9

rest_framework/authtoken/migrations/0002_auto_20160226_1747.py
Fixes [missing migration](https://github.com/tomchristie/django-rest-framework/pull/3887#issuecomment-189297296).
Thanks to @itbabu for noticing.
=> Add missing migration file for #3887

tox.ini
[Django security releases issued: 1.9.3 and 1.8.10](https://www.djangoproject.com/weblog/2016/mar/01/security-releases/)
=> Update Django security releases 1.9.3 and 1.8.10

tox.ini
[Django bugfix releases issued: 1.9.4 and 1.8.11](https://www.djangoproject.com/weblog/2016/mar/05/bugfix-releases/)
=> Update Django versions after bugfix release

tox.ini
=> updated minor django versions on tox

docs/topics/third-party-resources.md
Added the 3 Django Rest Messaging packages to the doc.
=> Add Django Rest Messaging to Third Party Packages

docs/topics/third-party-resources.md
Include a link to the Medium "Django REST framework" collection.
=> Add the medium collection related to Django REST framework.

tox.ini
=> upgraded minor django version on tox

docs/api-guide/routers.md
Fixes a minor indentation typo that caught my eye.
=> minor docs indentation fix

rest_framework/fields.py, tests/test_fields.py
=> Resolve TimeField representation for midnight value.

rest_framework/templates/rest_framework/admin.html, rest_framework/templates/rest_framework/admin/detail.html, rest_framework/templates/rest_framework/admin/list.html, rest_framework/templates/rest_framework/admin/list_value.html, rest_framework/templates/rest_framework/base.html
Meant to have done this a while back. Mostly trying to have consistent code styling throughout all templates.
=> Spring cleaning template styles

rest_framework/static/rest_framework/js/ajax-form.js, rest_framework/static/rest_framework/js/csrf.js, rest_framework/static/rest_framework/js/default.js
Trying to have consistent code styling, and also removed extra `getCookie` function. There's a better one in `csrf.js`.
=> Clean up js style and remove extra getCookie function

docs/api-guide/renderers.md
Adds a section about the Latex renderer we open sourced at Pebble
=> Add LaTeX renderer to documentation

docs/api-guide/serializers.md
`print` is available as a function on every supported version of Python (2.7+)
=> Remove Py2/Py3 difference from Example

.travis.yml, tox.ini
=> django 1.10 support initials

tests/browsable_api/test_browsable_api.py, tests/models.py, tests/test_authentication.py
If this kind of changes are accepted then I will push more.
=> Style fix of tests 

rest_framework/filters.py
=> More robust default behavior on OrderingFilter.

.travis.yml
* Reformat travis.yml to consistent spacing throughout. (4 spaces) 
* Turn off email notifications.
=> Reformat travis.yml and turn off email notifications.

rest_framework/metadata.py
=> Don't list many-to-many choices in OPTIONS requests.

tox.ini
=> upgraded django to 1.9.7 release

docs/api-guide/authentication.md
=> Note on obtain_auth_token and throttles/permissions.

docs/tutorial/quickstart.md
=> Minor docs tweaks. 

rest_framework/utils/encoders.py
=> Handle bytestrings in JSON.

rest_framework/fields.py, tests/test_fields.py
=> Simplfy TimeField passing through strings

docs/topics/third-party-resources.md
I recently released a 3-hour video tutorial on Treehouse and you requested a link for it in the docs :)
=> Add Treehouse tutorial

rest_framework/pagination.py
Makes `offset_cutoff` a class attribute in `CursorPagination` so that it can be easily overridden in subclasses. Addresses https://github.com/tomchristie/django-rest-framework/issues/4053
=> Overridable offset cutoff in CursorPagination

.travis.yml, tox.ini
[Django 1.10 beta 1 released](https://www.djangoproject.com/weblog/2016/jun/21/django-110-beta-1-released/)
=> Test against Django 1.10b1

rest_framework/versioning.py, tests/test_versioning.py
Closes #3816.
Closes #4009.
Closes #4010.
=> Namespace versioning with nested namespaces

docs/api-guide/settings.md
=> docs.settings: fix name of `VERSION_PARAM`

rest_framework/compat.py
=> Add missing return statement.

docs/topics/third-party-resources.md
Removed links to Youtube videos that are no longer available and updated a link to a tutorial that has moved.
=> Remove outdated resources

tests/test_model_serializer.py
Test case corresponding to #4272 and #4288
=> Test case for #4272

docs/api-guide/schemas.md, rest_framework/response.py, rest_framework/routers.py, tests/test_negotiation.py
=> Fix json indent parameter.

rest_framework/schemas.py
=> Schema support should function when 'pagination_class = None'

rest_framework/schemas.py
=> Set view.format_kwarg in schema generator

rest_framework/serializers.py
=> Unique together checks should apply to read-only fields which have a default.

docs/api-guide/fields.md
=> Improve datetime format docs

docs/api-guide/schemas.md, rest_framework/routers.py
=> Added root_renderers argument

docs/api-guide/filtering.md
It seems unlikely that anyone still cares about Django 1.3
=> Remove note about Django 1.3

rest_framework/utils/formatting.py, tests/test_description.py
=> Dedent tabs in docstrings.

tests/test_fields.py
=> Test cases for DictField with allow_null options

docs/topics/release-notes.md, rest_framework/__init__.py
=> Version 3.4.2

docs/topics/release-notes.md, rest_framework/__init__.py, rest_framework/renderers.py
Include fallback for users of older TemplateHTMLRenderer internal API.
=> Version 3.4.3

docs/api-guide/fields.md
=> Fix minor typo

rest_framework/compat.py, rest_framework/fields.py, rest_framework/negotiation.py, rest_framework/pagination.py, rest_framework/serializers.py, rest_framework/templatetags/rest_framework.py, rest_framework/utils/field_mapping.py, rest_framework/utils/html.py, rest_framework/versioning.py, rest_framework/viewsets.py, tests/test_authentication.py, tests/test_fields.py, tests/test_filters.py, tests/test_model_serializer.py, tests/test_pagination.py, tests/test_templatetags.py, tests/test_testing.py
=> Fixed various typos

rest_framework/fields.py, tests/test_fields.py
=> Allow `max_digits=None` on DecimalField.

rest_framework/relations.py
Closes #3872
Closes #3868
Thanks to @jamesbeith for having raised this a while back. Has been resolved in the meantime.
=> Test case for rendering checkboxes in vertical form style.

rest_framework/schemas.py, tests/test_schemas.py
=> Add form field descriptions to schemas

rest_framework/pagination.py
=> Do not re-run query for empty results with LimitOffsetPagination

docs/topics/release-notes.md, rest_framework/__init__.py
=> Version 3.4.4

rest_framework/renderers.py, rest_framework/static/rest_framework/js/csrf.js, rest_framework/templates/rest_framework/admin.html, rest_framework/templates/rest_framework/base.html
=> Allow custom CSRF_HEADER_NAME setting.

docs/topics/release-notes.md, rest_framework/__init__.py
* Improve debug error handling. (#4416, #4409)
* Allow custom CSRF_HEADER_NAME setting. (#4415, #4410)
* Include .action attribute on viewsets when generating schemas. (#4408, #4398)
* Do not include request.FILES items in request.POST. (#4407)
* Fix rendering of checkbox multiple. (#4403)
* Fix docstring of Field.get_default. (#4404)
* Replace utf8 character with its ascii counterpart in README. (#4412)
=> Version 3.4.5

rest_framework/templates/rest_framework/admin.html
=> Add missing comma

rest_framework/fields.py, tests/test_fields.py, tests/test_serializer.py
=> Fix regression of `RegexField`.

tox.ini
[Django security releases issued: 1.9.10 and 1.8.15](https://www.djangoproject.com/weblog/2016/sep/26/security-releases/)
=> Update Django security releases 1.9.10 and 1.8.15

docs/api-guide/serializers.md
As discussed in IRC.
See project README for more information about the mixin.
=> Add drf-dynamic-fields to third party packages

tox.ini
Update Django version to 1.10.2 on tox.ini
=> Update Django security release 1.10.2

tests/test_templatetags.py
Adds tests for [rest_framework.py](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templatetags/rest_framework.py)
=> Adding tests for rest_framework.py

tests/test_encoders.py
=> Adding tests to encoder.py

rest_framework/static/rest_framework/css/bootstrap-tweaks.css
refs : [https://github.com/tomchristie/django-rest-framework/issues/4512]
=> Browsable API navbar gets overlapped by highlighted pagination item fix;

rest_framework/relations.py, rest_framework/templatetags/rest_framework.py, tests/test_lazy_hyperlinks.py
=> Lazy hyperlink names

rest_framework/serializers.py, tests/test_serializer.py, tests/test_serializer_nested.py
Closes #4561
Closes #4562
Thanks to @johnraz
=> Handle errors when empty data passed to serializer

tests/test_one_to_one_with_inheritance.py
Pulled in test case from #4290.
Issue appears to be resolved (possibly via #4571?)
Closes #4290.
=> Test one to one with inheritance

docs/api-guide/generic-views.md
=> Removed incorrect line from generic-views.md

docs/tutorial/6-viewsets-and-routers.md
Small change to documentation for clarity.
=> Mentioning that '@detail_route' responds to GET only by default

rest_framework/filters.py
Fixed the sentence from "We try to avoid this _is_ possible" to use if instead of is
Now "We try to avoid this if possible , for performance reasons."
=> Fixed minor sentence in Filter.py filter_queryset() Comment

docs/tutorial/1-serialization.md, docs/tutorial/2-requests-and-responses.md, docs/tutorial/3-class-based-views.md, docs/tutorial/4-authentication-and-permissions.md, docs/tutorial/5-relationships-and-hyperlinked-apis.md, docs/tutorial/6-viewsets-and-routers.md
=> Use pk for URL conf and views.

docs/api-guide/pagination.md
=> Add `drf-proxy-pagination` reference to Pagination docs

rest_framework/templates/rest_framework/admin/dict_value.html, tests/test_templatetags.py
_Note_: Before submitting this pull request, please review our [contributing guidelines](https://github.com/tomchristie/django-rest-framework/blob/master/CONTRIBUTING.md#pull-requests).
refs #4532
Fixes displaying of dicts in the admin console.
=> Fixes #4532

rest_framework/fields.py
=> Support 'on'/'off' literals with BooleanField.

rest_framework/schemas.py, tests/test_schemas.py
This PR fixes issue #4645. Test illustrating the problem was also provided.
=> Fix unhandled Http404, PermissionDenied in schema generation (#4645)

docs/api-guide/fields.md
=> Fix documentation error: removed unused variable

rest_framework/filters.py
=> Fix FilterSet warnings.

rest_framework/serializers.py
=> Only apply the nested writes test to writable fields.

docs/api-guide/exceptions.md
Correct a small typo in the documentation about exceptions.
=> Correct a small typo in exceptions documentation

docs/api-guide/filtering.md
`django_filters` doesn't export `rest_framework` by default so it's required to import it.
=> Edit to the import in Setting filter backends

requirements/requirements-optionals.txt
=> update django-filter to version 1.0.0

tests/test_views.py, tests/test_viewsets.py
was going through the tests and thought these should be converted. If these changes are welcome then I am OK to convert more.
=> convert tests asserts to pytest style

docs/api-guide/validators.md
=> docs: grammar fix

docs/api-guide/validators.md
=> docs: grammar fix - it's -> its

docs/api-guide/validators.md
=> docs typo fix

tests/test_relations_generic.py
=> converted generic relations assert to pytest style

tests/test_filters.py
=> converted filters tests asserts to pytest style

tests/test_generics.py
@xordoquy I am not sure if my assertion is done in wrong way or whats the reason of test fails?
suggestion?
=> converted test asserts of generics-test to pytest

tests/test_validation.py, tests/test_validation_error.py
@xordoquy here goes another two test module for your review :D
=> more pytest style assert

tests/test_atomic_requests.py, tests/test_decorators.py
=> converted asserts of atomic requests and decorators tests to pytest

tests/test_description.py, tests/test_encoders.py
=> converted descriptions and ecoders test asserts to pytest

tests/test_exceptions.py
=> converted asserts of exceptions test to pytest

tests/test_fields.py
converted this remaining while investigating.
=> converted remaining unittes asserts of fields test to pytest

docs/api-guide/authentication.md, docs/api-guide/fields.md, docs/api-guide/filtering.md, docs/api-guide/generic-views.md, docs/api-guide/pagination.md, docs/api-guide/parsers.md, docs/api-guide/permissions.md, docs/api-guide/relations.md, docs/api-guide/renderers.md, docs/api-guide/responses.md, docs/api-guide/reverse.md, docs/api-guide/schemas.md, docs/api-guide/serializers.md, docs/api-guide/settings.md, docs/api-guide/testing.md, docs/api-guide/throttling.md, docs/api-guide/validators.md, docs/topics/2.2-announcement.md, docs/topics/2.4-announcement.md, docs/topics/3.0-announcement.md, docs/topics/ajax-csrf-cors.md, docs/topics/release-notes.md
Update links to the latest current Django documentation page instead of dev ones.
=> Documentation update

docs/api-guide/renderers.md
Just makes the topic page easier to find.
Closes #1673
=> Add additional link to HTML & Forms topic page

tests/test_authentication.py
=> converted authentication test asserts to pytest

docs/topics/third-party-resources.md
Hey there, please add this module to the docs, thanks.
=> Add drf-oidc-auth to docs

docs/api-guide/schemas.md
Fix a docstrings of sample code in api guide documentation.
=> Fix a docstrings of sample code in api guide documentation.

rest_framework/fields.py
=> docs: typo fix: it's -> its

docs/api-guide/serializers.md
I added a short description and link to the DRF - FlexFields addon to the docs page for serializers.
=> added drf-flexfields addon info

docs/topics/documenting-your-api.md
Adds one more package for automated api documentation into documenting-your-api topic.
=> modify documenting-your-api docs topic with additional package

docs/api-guide/serializers.md, docs/topics/third-party-resources.md
See https://groups.google.com/forum/?fromgroups#!topic/django-rest-framework/uSQUuOOre_c
=> Add Serializer Extensions documentation

tests/test_negotiation.py
=> converted negotiation tests asserts to pytest

tests/test_throttling.py
=> converted throttling tests asserts to pytest

docs/api-guide/serializers.md, docs/topics/third-party-resources.md
=> add links to djangorestframework-queryfields to docs

requirements/requirements-testing.txt
in test requirements text. lets see what fails
=> updated version of test dependencies

docs/api-guide/metadata.md, docs/api-guide/permissions.md, docs/api-guide/settings.md, docs/topics/3.1-announcement.md, docs/topics/3.4-announcement.md, docs/topics/api-clients.md, docs/topics/kickstarter-announcement.md, docs/topics/release-notes.md, rest_framework/fields.py, rest_framework/serializers.py
Fix several spelling errors in docs and Python files
=> Fix several spelling errors

tox.ini
upcoming 1.11 and master will support 3.6
=> added python3.6 on tox

rest_framework/fields.py, rest_framework/pagination.py, rest_framework/relations.py, rest_framework/renderers.py, rest_framework/request.py, rest_framework/versioning.py
Removed extra parentheses from several "if" statements.
=> Remove redundant parentheses from "if" statements

tests/test_encoders.py
Convert existing asserts to `pytest` style
=> Convert encoders tests to pytest style

rest_framework/renderers.py, tests/test_renderers.py
Add unit tests for BaseRenderer and StaticHTMLRenderer
=> Renderer tests

tests/test_throttling.py
Renamed tested class, coverage of `throttling.py` is 100%
=> Throttle tests fix

rest_framework/utils/mediatypes.py, tests/test_negotiation.py
=> Add mediatype tests

tests/test_validators.py
=> Add tests for qs_exists

docs/api-guide/permissions.md
=> Include a link to the django-rest-framework-api-key package

tests/test_templatetags.py
=> Add tests for some template tags

tests/test_relations_slug.py
=> converted test asserts of relations slug to pytest

tests/test_authentication.py
=> Add tests for BasicAuthentication and TokenAuthentication

tests/test_compat.py
Add `setUp` and `tearDown` methods to properly restore things in case of failed tests, 
thanks @kevin-brown
=> Refactor according to comments in PR

README.md, docs/index.md
Hey Tom!
Just updated the /docs/index.md and /README.md files to include the new Machinalis link.
=> Updated Machinalis links

docs/index.md, docs/topics/funding.md
I updated the Support section as discussed during our call yesterday. Please let me know if this works.
I also replaced your personal email with the funding email in case people have questions, as discussed in a previous call.
Thank you!
=> Updated Support section and added funding email

tests/test_pagination.py
=> Add test for pagination when limit not set

docs/api-guide/serializers.md
=> Missing comma

tests/test_encoders.py
This PR increased `utils/encoders.py` test coverage to 100%.
=> Increased utils/encoders.py test coverage.

rest_framework/static/rest_framework/docs/css/base.css, rest_framework/templates/rest_framework/docs/index.html, rest_framework/templates/rest_framework/docs/interact.html, rest_framework/templates/rest_framework/docs/link.html
=> Interact Modal

rest_framework/static/rest_framework/docs/css/base.css, rest_framework/templates/rest_framework/docs/index.html, rest_framework/templates/rest_framework/docs/interact.html, rest_framework/templates/rest_framework/docs/sidebar.html
=> Docs Interact

rest_framework/serializers.py, tests/test_serializer.py
Refs #4901
Use the `Mapping` abc in `isinstance` checks in the serializer; instead of `dict`
=> Check for collection.Mapping instead of dict

rest_framework/request.py
Fix outdated docstring in `_not_authenticated`.
=> Update _not_authenticated's docstring

rest_framework/fields.py
=> Rearrange code

rest_framework/permissions.py, tests/test_permissions.py
Expose the issue described in #4927
=> Added a failing test for #4927

docs/topics/tutorials-and-resources.md
=> Fixed broken mail link in tutorials and resources

docs/api-guide/generic-views.md
It should be documented how to remove pagination from generic view.
=> Added doc for removing pagination in generic-view.

rest_framework/static/rest_framework/docs/js/api.js, rest_framework/templates/rest_framework/schema.js
=> Fallback to more widely supported JS feature sets.

rest_framework/templates/rest_framework/docs/langs/javascript-intro.html
Update coreapi.js version in JavaScript API docs to `coreapi-0.1.0.js`
=> Update coreapi.js version in JavaScript API docs.

docs/tutorial/4-authentication-and-permissions.md
At the beginning of tutorial4, The database had been removed
=> ID must start from 1 again

docs/topics/funding.md
I changed the name from "agconti" to "Andrew Conti". Thought that would look nicer.
=> Updated testimonial name on funding site

docs_theme/404.html, docs_theme/main.html, docs_theme/nav.html, requirements/requirements-documentation.txt
Mkdocs has fixed this issue in https://github.com/mkdocs/mkdocs/pull/1039
I have upgraded the mkdocs in this PR
Closes https://github.com/tomchristie/django-rest-framework/issues/4758
=> [ISSUE-4758] Website 404 page is broken for everything in a nested directory

rest_framework/utils/field_mapping.py, tests/test_model_serializer.py, tests/test_serializer.py
Fix missing unique validators in ChoiceFields for issue #5004
=> fix unique=True validation for ChoiceField

rest_framework/settings.py
There was a typo at doc string. Now it is fixed.
=> Fix typo at doc string

docs/topics/funding.md
=> Updated monthly report link on funding page

docs/index.md, requirements/requirements-optionals.txt
I bumped `django-guardian` version to fix Django 2.0 compatibility (see [comment](https://github.com/encode/django-rest-framework/pull/4866#issuecomment-276104912)).
=> Bumped django-guardian version.

docs/api-guide/schemas.md
Per: http://www.django-rest-framework.org/topics/3.5-announcement/#corejson-media-type
(I was *wondering* why this didn't seem to work!)
=> Updates the core json media type in the docs

docs/topics/tutorials-and-resources.md
This PR adds Two Scoops of Django 1.11 as a resource to Django REST Framework. We now have a dedicated chapter and numerous sections, subsections, and tips that focus on what DRF brings to development of projects.
=> add Two Scoops of Django 1.11 to tutorials and resources

rest_framework/serializers.py, tests/test_model_serializer.py
For https://github.com/encode/django-rest-framework/issues/5137.
Closes #5137
=> Fix source="*" with HyperlinkedModelSerializer

runtests.py, setup.cfg
This allows for flake8 to pick it up when running it by itself.
=> Move flake8 config to setup.cfg

rest_framework/authtoken/serializers.py, tests/test_authtoken.py
=> Don't trim whitespace from authtoken passwords

requirements/requirements-optionals.txt
A quick fix to Django Filter. Latest is 1.0.4
=> Update Django-Filter requirement

docs/topics/funding.md
Hey Tom!
I thought this would be useful to put up on the homepage since I get asked these questions a lot in emails.
=> Added FAQ section for funding site

rest_framework/request.py
=> doc: fix documentation for Request._authenticate

docs/api-guide/authentication.md, docs/topics/third-party-packages.md
Add information about new JWT authentication package.
=> Add information in docs about djangorestframework-simplejwt package

rest_framework/fields.py, tests/test_fields.py
=> Raise validation error on invalid timezone parsing.

rest_framework/request.py, tests/test_fields.py, tests/test_request.py
=> Ensure closables in request.FILES get closed.

rest_framework/pagination.py, rest_framework/status.py, rest_framework/utils/formatting.py
+ Simplified chained comparisons (mostly in `status.py`), taking advantage of interval comparisons in Python.
+ Fixed a typo in code
=> Simplified chained comparisons and minor code fixes

rest_framework/exceptions.py
=> typo: may -> many

docs/api-guide/views.md
So it is possible to copy paste the example and it will work out of the box.
=> Added the django user model

rest_framework/pagination.py
The blog post referenced in the documentation has been since moved to a new location.
=> Docs: update link in pagination.py

docs/tutorial/2-requests-and-responses.md
Made it consistent with Part I. Caught it when commiting the code into my local tutorial repo.
=> Update 2-requests-and-responses.md: consistency

tests/test_serializer.py
=> Fix test name

rest_framework/fields.py, tests/test_fields.py
Updated supported values for the NullBooleanField.
Added check for unhashable types in NullBooleanField.
=> Updated supported values for the NullBooleanField

docs/api-guide/status-codes.md
=> Make status_code documentation more readable.

tox.ini
=> update tox to django 2.0 beta1

rest_framework/checks.py
* Add `id` to allow silencing.
* Expand `hint` to clarify.
Ref #5170 Closes #5523
=> Clarify pagination system check

rest_framework/renderers.py
=> JSONField renders as textarea (#5529)

docs/api-guide/parsers.md
Add import to improve example in api-guide/parsers
=> Add import to improve example (api-guide/parsers)

docs/api-guide/filtering.md
Previous link led to a maze. :/
=> Update link to documentation

docs/topics/release-notes.md, rest_framework/__init__.py
=> Version 3.7.3 Release 

rest_framework/templates/rest_framework/base.html
I missed the edits to this file in #5584
=> Fix pull request #5584

.travis.yml, README.md, tox.ini
- Updates Django 2.0 to rc1
- Removes Django 2.0 from allowable failures in CI
=> Update Django 2.0 support

rest_framework/serializers.py
instance without affecting every other serializer instance.
=> Serializer._declared_fields enable modifying fields on a serializer

docs/api-guide/permissions.md
Closes #3269
As per https://github.com/encode/django-rest-framework/issues/3269#issuecomment-200074712
=> Add note on object permissions for FBVs

docs/api-guide/serializers.md
Closes #5425 as per https://github.com/encode/django-rest-framework/issues/5425#issuecomment-341063819
=> Add example to to_representation docs

MANIFEST.in
Resolves https://github.com/encode/django-rest-framework/issues/5695
=> Add locale files back to installed files

docs/topics/release-notes.md, rest_framework/__init__.py
Release manager is @***.
Pull request is #***.
Checklist:
To modify this process for future releases make a pull request to the [project management](http://www.django-rest-framework.org/topics/project-management/) documentation.
=> 3.7.7 Release

docs/tutorial/4-authentication-and-permissions.md
I've added a missing parenthesis in one of the code snippets here: http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api .
=> Adding missing parenthesis

rest_framework/compat.py, tests/test_utils.py
Last use removed in c674687782ef96a3bb8466b412e99debd3d04f00.
=> Remove unused compat._resolve_model()

docs/api-guide/fields.md
=> Fixed a typo in third party package name

docs_theme/css/default.css
=> Replace `background-attachment: fixed` in docs

docs/topics/contributing.md
* Create a fork, then clone it.
* Link to GitHub’s How-To.
Closes #5791.
=> Updated step 1 of contributing guide

docs/topics/tutorials-and-resources.md
A Todo List API with React and Blog API tutorial
=> Two new tutorials

docs/api-guide/throttling.md
The current link was broken, fixed it. A good article on rate limiting indeed.
=> Updated Link to Rate Limiting Article

docs/topics/release-notes.md, rest_framework/__init__.py
Checklist:
To modify this process for future releases make a pull request to the [project management](http://www.django-rest-framework.org/topics/project-management/) documentation.
=> Version 3.8.1

docs/api-guide/settings.md
=> [DOCS] python print syntax docs/api-guide/settings.md

docs/topics/3.8-announcement.md
=> Fix a typo in the 3.8 announcement

rest_framework/schemas/inspectors.py, tests/test_schemas.py
=> docs: Correct schema parsing for JSONField

setup.cfg, tox.ini
Also adds `testspath` to improve test collection performance.
=> Move pytest config to setup.cfg

docs/tutorial/quickstart.md
Added description how to add pagination support to the quickstart tutorial.
refs #5983
=> Added pagination section to the quickstart page (issue #5983)

.travis.yml, tox.ini
=> updated tox and travis for django 2.1 alpha1

docs/api-guide/exceptions.md
=> Fix exceptions.md

.travis.yml, tests/test_encoders.py, tests/test_filters.py, tests/test_renderers.py, tests/test_schemas.py, tests/urls.py, tox.ini
Supersedes #6041 - thanks @blueyed!
=> Add "optionals not required" build

codecov.yml
From #6050 - testing a minimal comment layout. Not sure if codecov will pick up on the change and add its comment.
=> Add minimal codecov comment

docs/api-guide/schemas.md
=> fix typo error, Link to Field

codecov.yml
Ref: https://github.com/encode/django-rest-framework/pull/6077#issuecomment-403838095
This is https://github.com/encode/django-rest-framework/pull/6050
without the project status, and fixes/improves the comment added in
https://github.com/encode/django-rest-framework/pull/6077.
=> codecov: enable status for patch/changes, comment: diff

docs/tutorial/quickstart.md
Just felt the sentence could use some improving hence tweaked it a bit. I feel like it reads better now.
=> Small grammar correction in quickstart.

rest_framework/models.py
Since Django 1.7, an empty models.py file is not required.
See https://docs.djangoproject.com/en/dev/releases/1.7/#app-loading-refactor
> It is possible to omit models.py entirely if an application doesn’t have any models.
=> Remove unnecessary models.py file

docs/api-guide/serializers.md
Fixes a minor issue in a documentation example.
=> Fix validate_my_field signature

docs/api-guide/requests.md
=> Fix spelling error

docs/api-guide/testing.md
Fixes a typo in the documentation.
=> Fix typo in testing.md

docs/tutorial/5-relationships-and-hyperlinked-apis.md
Simple documentation change.
refs #6266
=> Fixes an import statement in chapter 5 of the tutorial.

docs/community/3.9-announcement.md
Fix small typos in the release announcement for 3.9
=> Typo fix in the release announcement

README.md, docs/index.md
=> Add 'Lights On Software'

docs/api-guide/serializers.md
Simple code-example consistency update in serializers.md
=> update docs/api-guide/serializers.md: consistency

.travis.yml
=> Travis has released Xenial support

docs/api-guide/permissions.md
=> docs: typo in permissions (double space)

docs/tutorial/quickstart.md
Fixed a few small typos. This helps improve peoples' first impression of DRF.
=> Fix quickstart.md typos

README.md, docs/index.md
=> Note that only latest patches of Python & Django are supported.

docs/api-guide/relations.md
=> Update quote in relations.md

docs/api-guide/permissions.md
Fix missing import of SAFE_METHODS in permissions example code.
=> Fix missing import in example code

docs/api-guide/filtering.md
=> Updated filtering docs to use `filterset_fields`.

docs/api-guide/permissions.md
https://github.com/florimondmanca/djangorestframework-api-key is maintained version of 
https://github.com/manosim/django-rest-framework-api-key project
=> replace unmaintained django-rest-framework-api-key

requirements/requirements-optionals.txt, rest_framework/compat.py
Required for compatibility with Django 2.2
=> Update Django Guardian dependency.

docs/api-guide/requests.md
=> Fix typo: 'what' to 'that'

docs/api-guide/permissions.md
=> fix for a couple of missing words

docs/api-guide/caching.md
=> Fix typo in caching docs

requirements/requirements-testing.txt, tests/test_generateschema.py
Hello, I've added tests for generateschema command. Take a look please ;)
=> Tests for generateschema management command

setup.py
This PR adds Python 3.7 trove classifier in setup.py
=> Add Python 3.7 to classifiers

docs/api-guide/permissions.md
…when using provided permission classes.
Closes #6402.
=> Doc’d requirement to implement has_object_permission()

docs/api-guide/pagination.md
=> Fixed a typo

rest_framework/fields.py
https://docs.python.org/3/library/functions.html#isinstance
> If classinfo is a tuple of type objects (or recursively, other such
> tuples), return true if object is an instance of any of the types.
=> Merge multiple isinstance() calls to one

docs/community/release-notes.md, rest_framework/__init__.py
=> Version 3.9.2 release

docs/tutorial/1-serialization.md
=> Fixed a document mistake

rest_framework/views.py
ref #6404
My greatest contribution yet 😄 
Although, knowing my luck, this _will_ break something.
=> Explicitly raise exc in 'raise_uncaught_exception'

docs/community/release-notes.md
Fixed documentation typo: /Janurary/January/
=> Fixed typo: /Janurary/January/

docs/api-guide/permissions.md
=> Fixed typo

docs/api-guide/schemas.md, docs/tutorial/1-serialization.md
Minor documentation fixes.
1. Correction of typo in `schemas.md`
2. Corrected link in `1-serialization.md`
3. Removed redundant import (and tested) from `1-serialization.md` (fixes [this reported issue](https://github.com/encode/rest-framework-tutorial/issues/52))
=> Minor documentation fixes

tox.ini
=> Update tox to use Django 2.2 final.

docs/community/third-party-packages.md
Update of documentation - just adds link to new third-party package
=> Add new link to third party package

rest_framework/compat.py
=> Adjust guardian check

tests/test_fields.py
https://docs.python.org/3/library/typing.html
=> Correct misspelled module 'typing'

docs/api-guide/validators.md
This is similar to #6627 (I had missed this the last time :disappointed:)
=> Correct misspelled class name

docs/community/third-party-packages.md
Adds [django-rest-witchcraft](https://github.com/shosca/django-rest-witchcraft) to third party package list.
=> Add django-rest-witchcraft to third party packages

docs/api-guide/status-codes.md
=> Update status code docs

rest_framework/schemas/openapi.py, tests/schemas/test_openapi.py, tests/schemas/views.py
Adds field properties based on Field attributes and/or Field validators.
@carltongibson ^
=> generate openapi schema field validators

docs/api-guide/caching.md, docs/api-guide/fields.md, docs/api-guide/settings.md, docs/api-guide/throttling.md, docs/community/3.6-announcement.md, docs/community/release-notes.md, docs/community/third-party-packages.md
=> Fix typo in docs

docs/api-guide/filtering.md, docs/community/third-party-packages.md, rest_framework/decorators.py
Forgot to update these in #6687.
=> Remove old documentation

rest_framework/fields.py, tests/test_fields.py
=> Fix ModelField max_length argument

rest_framework/exceptions.py
=> Translate Throttled exception messages

README.md, docs/index.md
Update the Rollbar URL on the README and docs homepage.
=> Update rollbar sponsor URL

docs/api-guide/settings.md, rest_framework/settings.py
This builds off of #6797 and updates the default settings to uses lists instead of tuples. 
cc @tomchristie, @spookylukey
=> Update default settings to use lists instead of tuples

docs_theme/main.html, docs_theme/nav.html
=> Use 'url' template filter in docs

docs_theme/js/theme.js, docs_theme/main.html
Fixes #6807. Plugin scripts are defer loaded in the base template instead of from the theme script.
=> Update docs search plugin

docs/api-guide/serializers.md
=> fix indent

rest_framework/schemas/openapi.py, tests/schemas/test_openapi.py
Attempt to fix #6831, plus test
=> fix #6831 (force_text on OpenAPI response field descriptions)

rest_framework/exceptions.py, rest_framework/filters.py, rest_framework/metadata.py, rest_framework/pagination.py, rest_framework/parsers.py, rest_framework/schemas/coreapi.py, rest_framework/schemas/openapi.py, rest_framework/templatetags/rest_framework.py, rest_framework/utils/encoders.py, rest_framework/utils/formatting.py, rest_framework/utils/representation.py, rest_framework/utils/serializer_helpers.py
Refs #6838
This seemed like low hanging fruit and since I'm extremely new to contributing here and the issue wasn't assigned to anyone, I thought I would try this out.
=> Replace force_text with force_str

docs/community/tutorials-and-resources.md
=> Update tutorial links

docs/api-guide/validators.md
=> changed outdated "data" keyword to "attrs"

rest_framework/serializers.py, tests/test_serializer_nested.py
Continuing work started in #6741 . This MR fixes dotted write and adds the related tests.
=> Fix nested write of non-relational fields

docs/community/project-management.md
per the ticket anyway https://github.com/encode/django-rest-framework/issues/2162
=> proper Github repo issue already resolved

.travis.yml, requirements/requirements-codestyle.txt, setup.py, tox.ini
Python 3.8 is available, add tests in tox and travis
=> Bump CI to Python 3.8

docs/api-guide/caching.md
- modify the correct attr from viewsets
- add import from django
=> Update docs to use correct import and param

rest_framework/relations.py
- add space and rm redundant parentheses
- replace str class with super
- replace cls with self in class method (but I see someone fixed it)
=> Fix override func style and regular usage

docs/api-guide/relations.md
While refreshing my memory on serializers, I thought it made sense to distinguish explicitly between serializations with nested and referenced objects with an additional sentence.
=> Documentation: Elaborated on nested relationships

.travis.yml, requirements/requirements-optionals.txt, tests/conftest.py, tests/test_relations.py, tox.ini
* Install latest Django Guardian.
* Drop Django Guardian from 1.11 tests.
* Tweak a URLCONF override.
=> Django 3 compat

rest_framework/fields.py
Outdated since 91ea13840699abca0e14e20732fd445d65c91914.
=> Remove outdated comment in SerializerMethodField

docs/tutorial/2-requests-and-responses.md
any is used with uncountable nouns and plurals
https://english.stackexchange.com/questions/112996/any-followed-by-singular-or-plural-countable-nouns
=> Grammar fix

rest_framework/fields.py, rest_framework/validators.py, tests/test_fields.py
=> Make CharField prohibit surrogate characters (#7026)

rest_framework/settings.py
Resolves #7120. Also happy to close as a wontfix, given that `APISettings` is undocumented.
=> Add note that APISettings is an internal class

rest_framework/schemas/openapi.py
=> Fix _get_serializer argument order

docs/api-guide/schemas.md
=> Update docs for OpenAPI (#6814)

docs/community/release-notes.md
=> Release notes for 3.11.0

tests/test_viewsets.py
*Note*: Before submitting this pull request, please review our [contributing guidelines]
Description
-----
I think there is a typo in test_viewset.py
def testhead_request_against_viewset(self): →　def test_head_request_against_viewset(self):
=> Fix - test method typo

docs_theme/main.html
ancient IE6-8 support can be dropped
=> Remove unavailable script

docs/community/release-notes.md
the truncation changes the meaning somewhat..
=> update release note to include full message

docs/index.md
=> Add hint: coreapi is abandoned #7242

rest_framework/schemas/openapi.py, tests/schemas/test_openapi.py
#7254 fixes #7253 for DecimalField.
This fixes #7253 for EnumField.
=> Add handling for COERCE_DECIMAL_TO_STRING & Decimal for ChoiceField

docs/api-guide/viewsets.md
The cited sentences are from actually the action controller docs from ruby on rails not from routing.
=> Docs: Updates Ruby on Rails reference link

rest_framework/pagination.py, tests/test_pagination.py
=> improve schema for pagination

rest_framework/authtoken/admin.py
I don't know for sure if that is useful or not, but I'm using it in my Django projects. For me, is looks concise and more readable. Feel free to reject pull request if it is not recommended practice to use this decorator.
=> use @admin decorator in admin.py

docs/api-guide/authentication.md
=> (Docs) Nginx basic auth tutorial moved

rest_framework/__init__.py
Added accidently in e888fc11c76d1a671f6f7d3c080915ffe722f3f6
Thanks @jairhenrique for the catch and fix.
=> Removed duplicated class RemovedInDRF314Warning.

docs/api-guide/serializers.md
the drf-encrypt-content package added into third party list in the documentation on the serializer page.
=> drf-encrypt-content added into third party list in the documentation

tests/test_serializer_nested.py
=> Fix tests crash on SQLite without JSON1 extension.

docs/tutorial/quickstart.md
=> Just smalling cleaning up, causing confusion

docs/api-guide/serializers.md
I've reworded the docs to remove the inaccuracy
=> Fix some documentation errors. (Fix #7412)

docs/api-guide/views.md
=> Correct indentation

docs/tutorial/6-viewsets-and-routers.md
Small doc change to add missing import statement for viewsets
=> docs(tutorial): add missing permission import in viewsets

docs/api-guide/viewsets.md
=> Documentation: improve the action decorator documentation (#7316)

docs/api-guide/exceptions.md
I was reading through the docs and noticed the typo. Figured this is an easy fix.
=> nit: Typo fix

docs/api-guide/relations.md, docs/topics/internationalization.md
Fixed url to django docs in several places, fixes refs #7627
=> Changed url to django docs so it points to the stable version

docs/api-guide/authentication.md
Update `unicode` python 2 to `str` python 3.
=> changed unicode to str

docs/api-guide/serializers.md
Just a fix for a small typo in the documentation.
=> Small documentation fix

requirements/requirements-testing.txt
Fix failing test
@tomchristie @seppeljordan
=> Fixed test

rest_framework/fields.py
That change add support for "Yes" and "No" literals and evaluate them to Boolean value.
=> add support for Yes/No literals with BooleanField

.travis.yml, tox.ini
django/django renamed development branch to `main`.
=> Updated tox/travis to point to Django `main` branch.

rest_framework/test.py
Closes https://github.com/encode/django-rest-framework/issues/7132
=> Fix WSGI signature for DjangoTestAdapter

rest_framework/throttling.py
Reverts encode/django-rest-framework#7849
See https://github.com/encode/django-rest-framework/discussions/7870
=> Revert "pick deque instead of list"

docs/community/tutorials-and-resources.md
fixes broken link for article number 2 given at https://www.django-rest-framework.org/community/tutorials-and-resources/#articles
=> fix broken article link

.github/workflows/main.yml
This is a [tox plugin I just made](https://pypi.org/project/tox-py/) to replace this shell-fu.
=> Use tox-py in CI

docs/api-guide/schemas.md
Just fixed [a broken cite in the docs](https://www.django-rest-framework.org/api-guide/schemas/).
=> FIX: Broken cite.

docs/api-guide/renderers.md
=> fix: broken cite

setup.py
=> add changelog project_url

docs/tutorial/5-relationships-and-hyperlinked-apis.md
unnecessary import, because it is already added in the previous section
=> Update Tutorial - Relationships & Hyperlinked APIs

docs/api-guide/validators.md
=> Fix typo in api-guide docs

docs/api-guide/filtering.md
=> Fix subtitle of schemas for filtering

docs/community/tutorials-and-resources.md
=> Added an article - implementing rest apis with embedded privacy from doordash engineering blog

docs/tutorial/quickstart.md
Reverts encode/django-rest-framework#7995
=> Revert "Fix arguments of `path()`"

README.md, docs/index.md
=> Update stream.io link

docs/api-guide/filtering.md, docs/api-guide/serializers.md, docs/tutorial/4-authentication-and-permissions.md, rest_framework/fields.py, rest_framework/schemas/coreapi.py
A small tweak for the serializer docs
=> Docs: remove old-style `super` call

tests/test_description.py
Prompted by #8160
Neaten up one bit of markdown-in-docstring that *might* be resulting in flaky test runs on some systems.
=> Tweak test_description

docs/api-guide/pagination.md
Nothing serious here, just a minor fix in the docs that caught my eye.
BTW, thanks for this awesome library!
=> Add missing commas in pagination response samples

docs/tutorial/1-serialization.md
minor update on serialization tutorial ( django version, installed app name, miagrate)
=> minor update on tutorial serialization

README.md, docs/index.md
Update URL for stream sponsorship
=> Update sponsor URL

docs/api-guide/throttling.md
Clearer messaging around throttling, with regards to potential for denial of service and brute forcing attacks.
=> Throttling disclaimer

docs/index.md
Following on from discussion with the Django team. I believe our shared outlook is that security issues are better handled by the Django security team, than via the existing route. This change will ensure more comprehensive oversight and transparency around resolving security issues.
=> Update security email.

docs/api-guide/throttling.md
Closes https://github.com/encode/django-rest-framework/issues/8127
=> Update throttling docs

CONTRIBUTING.md, docs/community/contributing.md
Clarify guidelines around new issues and pull requests to the project.
=> Update contribution guidelines

docs/api-guide/routers.md
Updated the links to the 4.0 version.
=> Update include and namespace URLs

docs/tutorial/2-requests-and-responses.md
A small tweak for the [2-requests-and-responses.md](https://github.com/encode/django-rest-framework/blob/master/docs/tutorial/2-requests-and-responses.md) docs
=> Add trailing slash

docs/api-guide/authentication.md
=> Docs: edit headings in Authentication

rest_framework/request.py, tests/test_request.py
=> Fix infinite recursion with deepcopy on Request

docs/api-guide/fields.md, docs/api-guide/relations.md
refs https://github.com/encode/django-rest-framework/discussions/8690#discussioncomment-3859111
=> Docs: use `asterisk` for unordered list

requirements/requirements-testing.txt
trying to update the testing tools
=> pytest versions update

requirements/requirements-optionals.txt
=> update minimum version to psycopg2-binary>=2.9.5

rest_framework/metadata.py
=> [FIX] add missing DurationField to SimpleMetada label_lookup

docs/api-guide/validators.md
Reverts encode/django-rest-framework#8779
=> Revert "Fix bug in validators documentation"

docs/api-guide/serializers.md
=> docs: fix code example

rest_framework/authtoken/admin.py
**Original discussion:** #8927 
Add `user__username` search field to `TokenAdmin` for search created tokens by usernames.
=> Add username search field for TokenAdmin (#8927)

.github/workflows/main.yml
Reverts encode/django-rest-framework#8946
=> Revert "test codecov gha"

rest_framework/pagination.py
remove unwanted blank line from import which was causing error in isort(pre commit)
=> remove unnecessary line which was causing isort error

rest_framework/pagination.py, tests/test_pagination.py
Make paginated responses schema more real. This small fix is required for some instruments which generate typed code.
=> Fix: Pagination response schemas.

docs/community/tutorials-and-resources.md
This PR adds a courses section (along with a course) to the community resources section of the documentation.
=> add courses section to community resources

requirements/requirements-optionals.txt
=> Update pygments>=2.12.0,<2.14.0 in requirements-optionals

requirements/requirements-testing.txt
to make it work with newer python versions
=> Update pytest version in requirements-testing.txt

README.md, docs/index.md
updated readme.md and docs/index.md
=> removed hyperlink for web browsable API on homepage

docs/community/3.11-announcement.md
=> Fixed typo in docs/community/3.11-announcement.md.

rest_framework/versioning.py, tests/test_versioning.py
Reverts encode/django-rest-framework#7278
=> Revert "Fix NamespaceVersioning ignoring DEFAULT_VERSION on non-None namespaces"

docs/community/tutorials-and-resources.md
This PR just updates a couple of links pointing to some tutorials which now have an invalid link.
=> Update tutorials links in Community contributions docs

docs/api-guide/viewsets.md
=> Add note in 'Introspecting ViewSet actions' docs section

docs/api-guide/relations.md
add rest-framework-gm2m-relations package that provides read/write serialization for generic many to many field
=> add rest-framework-gm2m-relations package that provides read/write serialization for generic many to many field
