encode/django-rest-framework

- rest_framework/relations.py
- tests/test_model_serializer.py
This allows you to have a related field that traverses nullable relations. A default is required to have the value in the output, but the current behaviour is to throw an AttributeError.
Closes #5848
> Allow traversing nullable related fields

- docs/topics/tutorials-and-resources.md
Here's my Django REST / React tutorial. Thanks to @wsvincent for suggesting the pull request!
> Added: Tutorial: Django REST with React (Django 2.0)

- rest_framework/pagination.py
This PR:
- removes `pagination._get_count`
- adds `LimitOffsetPagination.get_count` instance method
- modifies `LimitOffsetPagination.paginate_queryset`
I have a custom pagination class that subclasses `LimitOffsetPagination`. When paginating a large queryset with an `.order_by()` clause, the combination of sorting can add a lot of overhead to the pagination calculation, which in turn slows down the entire response. Adding `get_count()` as an instance method gives developers the ability to override it's behavior if necessary. In my case, I will override the method to remove any ordering constraints from the queryset.
> Add LimitOffsetPagination.get_count to allow method override

- rest_framework/metadata.py
- tests/test_metadata.py
`HiddenField` is meant to be entirely hidden, but we discovered it showing up in `OPTIONS` requests in `actions`.
This fixes the problem by skipping `HiddenField` instances in `SimpleMetadata.get_serializer_info`, and adds a test.
> Don't show hidden fields in OPTIONS responses

- docs/api-guide/exceptions.md
- rest_framework/exceptions.py
- tests/test_exceptions.py
Closes #4556
Adds generic handlers for generic server error and bad request errors. (To be used with Django's `handler500` and `handler400`.) 
Unit tests on functions themselves but no integration tests, [since the test client insists on re-raising any exceptions, rather than processing the error view.](https://code.djangoproject.com/ticket/18707)
> Added generic 500 and 400 JSON error handlers.

- docs/api-guide/settings.md
- docs/topics/3.8-announcement.md
- docs/topics/release-notes.md
- rest_framework/__init__.py
- rest_framework/decorators.py
- rest_framework/schemas/generators.py
- tests/test_schemas.py
This is the PR for the Version 3.8 Release.
> Version 3.8 Release

- docs/topics/release-notes.md
`super().data()` leads to a `TypeError` saying that 'ReturnDict' object
is not callable.
> release_notes: fix call to super().data

- docs/topics/release-notes.md
- rest_framework/decorators.py
- tests/test_decorators.py
- Change deprectaed `*_route` decorators to use old behavior for generating `url_name`.
- Update changelog to reflect that the `action` decorator has generates `url_name` differently, while the `*_route` decorators are unchanged.
> Use old url_name behavior in route decorators

- docs/api-guide/routers.md
The [namedtuple Route](https://github.com/encode/django-rest-framework/pull/5705/files#diff-88b0cad65f9e1caad64e0c9bb44615f9R34) requires `detail` to be specified, otherwise it fails with: `TypeError: __new__() missing 1 required positional argument: 'detail'`.
Since PR #5705 `Route()` requires argument `detail`.  It was [added to the SimpleRouter](https://github.com/encode/django-rest-framework/pull/5705/files#diff-88b0cad65f9e1caad64e0c9bb44615f9R116), but forgotten in an example in the documentation.
> docs: Add missing argument 'detail' to Route

- rest_framework/authtoken/views.py
- tests/test_renderers.py
Closes #5918 
Import coreapi from rest_framework.compat, not directly.
> Improve coreapi importing

- docs/topics/release-notes.md
- rest_framework/__init__.py
> Version 3.8.2 Release

- docs/api-guide/serializers.md
Fix a broken link to the django-rest-marshmallow docs.
> Update link to django-rest-marshmallow docs

- docs/topics/third-party-packages.md
Seamless integration between Django REST framework and Datatables (https://datatables.net).
When you call your API with ?format=datatables it will return a JSON structure that is fully compatible with what Datatables expects. It handles searching, filtering, ordering and most usecases you can imagine with Datatables.
The great benefit of django-rest-framework-datatables is that you don't have to create a different API, your API will be untouched unless you specify the datatables format on your request.
> docs: Added djangorestframework-datatables to third-party packages

- README.md
- docs/index.md
- docs/topics/project-management.md
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
> Update all pypi.python.org URLs to pypi.org

- rest_framework/static/rest_framework/docs/css/base.css
> Ensure docs sidebar can scroll to bottom.

- rest_framework/exceptions.py
- tests/test_exceptions.py
Allow hashing of ErrorDetail objects to address #5919.
I'm not entirely sure if `hash(ErrorDetail('msg')) == hash('msg')` should be true. I'd love some feedback on this.
> Allow hashing of ErrorDetail

- docs/topics/api-clients.md
Tried token authentication today and found those small errors. If it really should have ben JWT and you are using djangorestframework-simplejwt then the action should look more like this:
```action = ['auth', 'token', 'obtain', 'create']```
> Small example code fixes

- docs/api-guide/fields.md
Update custom field documentation. Change argument names in overridden field methods to match those of the base classes.
I got the following warning from `pylint`:
```
Parameters differ from overridden 'to_representation' method (arguments-differ)
```
Then I returned to [the docs](http://www.django-rest-framework.org/api-guide/fields/#custom-fields) just to realise that I did exactly what it said. A look at [the source](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L561) revealed that the warning was actually correct: The name of the second argument to `to_representation` is `value`, not `obj`.
To help others avoid warnings like these, I propose these changes to the docs. But if the argument names have deliberately been altered, feel free to reject …
> Match original argument names

- rest_framework/templates/rest_framework/docs/link.html
This fixes #5715. Descriptions in the docs view not render HTML like it is done anywhere else.
> docs: Render descriptions correctly

- rest_framework/fields.py
- tests/test_fields.py
Its never a good idea to return the provided input in an error message, as it can easily result in an reflected XSS. Imagine someone sends a form with a field like "<script>something evil</script>", you return the value in the error message  as it does not pass your serializer and the frontend may not sanitize it proper, as it trusts its own backend. :)
> Removed input value from deault_error_message

- rest_framework/relations.py
- tests/test_relations.py
Not sure if this is the right place to put the test or where the situation comes up in the real world when not using ORM hacks (like how we found it), but it *does* test the thing, and the thing *is* broken in a case that it appears to be intended to handle.
> Fix replaced instance being used when pk-only optimization raises AttributeError

- docs/api-guide/testing.md
import for RequestsClient is missing in the docs
> update testing.md - fixes related to RequestsClient

- tests/test_model_serializer.py
`pytest.mark.skipUnless` does not exist, it was confused with
`unittest.skipUnless` probably.
> tests: fix skipping with TestPosgresFieldsMapping

- requirements/requirements-optionals.txt
With 2.7.3 I am seeing an ImportError on Arch Linux:
> ImportError: …/.venv/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so:
> symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
> requirements-optionals.txt: bump psycopg2 to 2.7.4

- tox.ini
This causes errors with invalid markers:
> AttributeError: 'skipUnless' not a registered marker
Fixed in https://github.com/encode/django-rest-framework/pull/5965.
> pytest: use --strict

- docs/api-guide/filtering.md
> Added import statement on filtering docs

- docs/tutorial/1-serialization.md
- docs/tutorial/2-requests-and-responses.md
- docs/tutorial/3-class-based-views.md
- docs/tutorial/4-authentication-and-permissions.md
- docs/tutorial/5-relationships-and-hyperlinked-apis.md
- docs/tutorial/6-viewsets-and-routers.md
- docs/tutorial/7-schemas-and-client-libraries.md
Updated part 1 of the DRF tutorial to use django.urls.path instead of
django.conf.urls.url
refs #5963 , updated tutorial part 1 to use Django 2.0 routing syntax.
> Update tutorial to Django 2.0 routing syntax (#5963)

- docs/api-guide/authentication.md
- docs/topics/third-party-packages.md
project has been archived on github and hasn't had any activity since 2014, and I'm not aware of an active fork.
> remove references to DOAC in docs

- requirements/requirements-optionals.txt
Ref: https://github.com/encode/django-rest-framework/pull/5967#issuecomment-386431446
> requirements-optionals: use psycopg2-binary

- tests/test_write_only_fields.py
This adds the required `test_` prefix.
Found via https://github.com/encode/django-rest-framework/pull/5970.
> tests: fix test_write_only_fields not being executed

- runtests.py
- setup.cfg
It is useful to see if tests itself are covered after all - missing
coverage there typically indicates dead/missed code paths.
> runtests.py: include coverage for tests

- rest_framework/templatetags/rest_framework.py
- tests/test_templates.py
We use a `404.html` which extends `rest_framework/base.html`. With the default `handler404` implementation, this template is rendered when you encounter a `Resolver404`. With DRF <3.6 this worked fine. Since then it throws an `AttributeError`. I traced the problem to 0173e9bd21e70c7fa973b2daf1480d2fff0089ae.
Since `Resolver404` goes via django's `handler404` and not via DRF's exception handling,
it doesn't get any extra context.
Since the `|items` filter doesn't check for `response_headers` being null (missing) it attempts
to call `<None>.items()`, thus raising an AttributeError.
This fixes the problem by checking for the presence of `response_headers` before calling `|items` with it.
* This could alternatively be solved in the `items` filter, making it just check for null before …
> Fix AttributeError in base.html when called without `response_headers`

- rest_framework/static/rest_framework/js/default.js
The jQuery upgrade throws the following exception when browsing endpoints:
e.indexOf is not a function error
.load, .unload or .error are deprecated since jQuery 1.8
> fix e.indexOf is not a function error

- mkdocs.yml
This branch adds the link to `mkdocs.yml` to expose the Caching API Guide that was created with PR #5514.
Fixes #6011
> Add linkage to Caching API Guide.

- docs/topics/third-party-packages.md
To register an account on PyPI, the URL is https://pypi.org/account/register/, which changed after the move to pypi.org.
> Update incorrect PyPI URL to register an account

- docs/api-guide/pagination.md
fixed a link to disqus article on cursor pagination that was broken in the pagination docs.
> (fix) link to disqus article on cursor pagination

- docs/api-guide/relations.md
`queryset` is not an argument to `HyperlinkedRelatedField.get_object()`. The example below this signature in the docs shows the correct usage, with the correct signature, it's just this bit that doesn't match.
> Documentation: Correct the signature for HyperlinkedRelatedField.get_object()

- docs/api-guide/routers.md
Since no extra `url_path` is given, `url_path` should be same with the action name
See details from http://www.django-rest-framework.org/api-guide/routers/#example (in the mapping table)
> Fix url for group_names action example

- runtests.py
1. `tests` and `--tb=short` is not necessary, since it is in
`pytest.addopts` already.
2. removes `-s` (shortcut for --capture=no): it is typically a good idea
to not display output from successful tests.
If you really want to keep `-s` it should be moved to addopts then.
Regarding `-q` for `--fast`: `--fast` is used by default, i.e. it could also be moved to `addopts`, but then I also do not like using it by default at all (default verbosity should be good).
(I still think that the indirection via `runtests.py` is not necessary and adds confusion - it would be better to run pytest and the other tools via tox directly)
> runtests.py: clean up PYTEST_ARGS

- tests/test_atomic_requests.py
This currently fails with Django 2.1 (beta), and it looks like the
decorator should be used just as is in general?!
NonAtomicDBTransactionAPIExceptionTests.test_api_exception_rollback_transaction_non_atomic_view:
../django/django/db/transaction.py:277: in _non_atomic_requests
view._non_atomic_requests.add(using)
E   AttributeError: 'function' object has no attribute '_non_atomic_requests'
During handling of the above exception, another exception occurred:
tests/test_atomic_requests.py:149: in test_api_exception_rollback_transaction_non_atomic_view
response = self.client.get('/')
../django/django/test/client.py:527: in get
response = super().get(path, data=data, secure=secure, **extra)
../django/django/test/client.py:339: in get
**extra,
../django/django/test/client.py:414: in generic …
> tests: fix usage of transaction.non_atomic_requests

- docs/tutorial/6-viewsets-and-routers.md
Updated the code in tutorial part 6, "Using Routers", to Django 2.0
routing syntax using path(). Refs #5964, there was one missing bit that wasn't updated.
> Update to Django 2.0 Routing Syntax

- setup.cfg
Fixes:
> [pytest] section in setup.cfg files is deprecated, use [tool:pytest]
> instead.
> setup.cfg: use [tool:pytest]

- tests/test_permissions.py
I've pulled out the permissions fix separately from #6044 while we wait for the UTC timezone issue to be fixed. Currently, the permissions error massively slows down the test suite, causing the Django 2.1+ builds to take ~12 minutes.
> Fix Django 2.1 permissions tests

- setup.cfg
- tests/test_viewsets.py
In tests, uncalled stub methods should raise `NotImplementedError` instead of simply passing. This helps ensure that methods are not called unexpectedly by various code paths. As a trivial example, getting a view method's description should not unintentionally invoke that method.
> Add NotImplementedError to coverage exclusion

- tests/test_parsers.py
~~Needs https://github.com/encode/django-rest-framework/pull/6043 also.~~
> Fixes for Django 2.1

- docs/api-guide/settings.md
- docs/api-guide/viewsets.md
- rest_framework/decorators.py
- rest_framework/renderers.py
- rest_framework/routers.py
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- rest_framework/utils/breadcrumbs.py
- rest_framework/views.py
- rest_framework/viewsets.py
- tests/test_decorators.py
- tests/test_description.py
- tests/test_renderers.py
- tests/test_routers.py
- tests/test_schemas.py
- tests/test_utils.py
- tests/test_viewsets.py
Resolves #2062, #2934, #3271, #5755
Fixes #4920
This will obviously require more extensive testing and documentation updates, but I'd like to hammer out the implementation details first. But first, here's a preview of the changes to the browsable API:
The above changes include:
- Breadcrumb and page title support custom names/titles for actions instead of just "User instance".
- The method docstring is now used as the action's description.
- A dropdown of "Extra Actions" (appropriately filtered to detail/non-detail actions).
- Also, note that custom serializer classes were already supported.
----
To implement this, it was necessary to change how routers and viewsets interact. At a higher level: 
- `View`s more explicitly customize their display name and description.
- `ViewSet`s are …
> Improvements to ViewSet extra actions

- setup.cfg
- tox.ini
- tox: move {posargs} to the end, so that it can override previous
entries, e.g. `-ra` when `-rw` was used.
- pytest: add `-ra` to addopts: it is good to see a summary of skipped
and failed tests at the end.
> tox/pytest: move posargs, use -ra

- docs/api-guide/schemas.md
- rest_framework/schemas/generators.py
- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
Ensures that view instances are operating on their own `schema` instance. Previously, all instances of the class were using a *shared*, class-level schema instance, and the descriptor was mutating the schema to ensure the most recently accessed view instance was set on the schema.
- Fixes #5630
- Fixes #5995
> Fix schemas for extra actions

- rest_framework/fields.py
- tests/test_fields.py
This is necessary to get code(s) for validation errors.
Via e.g. `password_validation.validate_password` and `get_error_detail` used in https://github.com/encode/django-rest-framework/blob/75cf06e40f11da7b942c73e90234cde67c94dd28/rest_framework/serializers.py#L471 then.
TODO:
> get_error_detail: use error_list to get code(s)

- rest_framework/renderers.py
- rest_framework/templates/rest_framework/admin/list.html
- tests/test_renderers.py
Resolves #3338 - `AdminRenderer` will now attempt to reverse a result's detail view URL and set that as a default if no URL is present. Additionally, the detail link/chevron will be disabled if the result has no URL, and it's column size has been set to 1, so as to consume as little space as possible.
> Admin renderer urls

- docs/api-guide/routers.md
- docs/api-guide/viewsets.md
- docs/topics/release-notes.md
- rest_framework/routers.py
- tests/test_routers.py
- tests/test_schemas.py
- tests/test_viewsets.py
The viewsets and routers use both `base_name` and `basename`. It would be nice if this were consistent.
I've deprecated `base_name` in favor of `basename`, and `get_default_base_name` in favor of `get_default_basename`. Fortunately, the deprecation is fairly straightforward. 
- `Router.register` needs to handle both arguments appropriately (fallback to the old value if present, raise deprecation warnings, complain if both arguments are provided)
- Django has a deprecation utility metaclass that already handles method renames.
> Rename base_name => basename for consistency's sake

- rest_framework/compat.py
- rest_framework/filters.py
- tests/test_permissions.py
Supersedes #6038. The check now just ensures `guardian` is present in the `INSTALLED_APPS`, without attempting an import. Since this check is called during runtime by the framework, we won't trigger a "Django is not configured" error.
> Move guardian imports out of compat

- .travis.yml
- README.md
- docs/index.md
- requirements/requirements-optionals.txt
- rest_framework/authentication.py
- rest_framework/authtoken/serializers.py
- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/urls.py
- setup.cfg
- setup.py
- tests/test_fields.py
- tox.ini
Per the [official recommendation](https://docs.djangoproject.com/en/2.0/releases/2.0/#python-compatibility), we should drop 1.10 support now that 2.0 has been released.
> Drop Django 1.10 support

- rest_framework/relations.py
- tests/test_relations.py
Fixes #6025. Basically, `get_object()` should handle the type/value error from `.get()` by reraising as a more specific exception type.
cc @tomchristie, @tveastman
> Only catch TypeError/ValueError for object lookups

- setup.py
Tests are already running against Django 2.1 (see encode/django-rest-framework#6001) and the classifier is now available (see pypa/warehouse#4090).
> Add Django 2.1 to classifiers

- rest_framework/serializers.py
- tests/test_model_serializer.py
This pull request is a proposed fix for #6110 .
Regression test-case is added.
Alternative solution is to use `Model._default_manager`, but current solution seems more simple.
> Handle models without .objects manager in ModelSerializer.

- rest_framework/serializers.py
- tests/test_model_serializer.py
This is an improvement for ModelSerializer.create() error message, now it does not mention "._default_manager".
Error message was previously made less readable in scope of #6111.
> Improve ModelSerializer.create() error message.

- rest_framework/authentication.py
- tests/test_authentication.py
Fixes CSRF failures when using cookie-based csrf with session auth and django 1.11.6+.
Test included (fails with old DRF and passes with this fix). Fixes #6088
> Fix CSRF cookie check failure when using session auth

- .travis.yml
~There is some incompatibility with tox/pytest/virtualenv that causes the 'dist' build to fail. By using the builtin venvs, the issue is bypassed.~
~I'm also too lazy to figure out why exactly this is happening.~
> Fix dist build

- docs/api-guide/renderers.md
This adds the drf-renderer-xlsx package to third-party packages. It allows endpoints to be "rendered" as a spreadsheet using OpenPyXL.
Cheers!
> Add drf-renderer-xlsx package.

- docs/api-guide/serializers.md
- docs/tutorial/1-serialization.md
- rest_framework/request.py
- tests/test_parsers.py
On all supported Pythons, the io.BytesIO is always a stream implementation using an in-memory bytes buffer.
Makes code slightly more forward compatible by reducing use of the six module and promotes more forward compatible practices in the docs.
> Prefer io.BytesIO over six; available on all supported Pythons

- rest_framework/compat.py
- rest_framework/serializers.py
Fixes warning:
```
rest_framework/serializers.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Mapping, OrderedDict
```
> Fix Python 3.7 DeprecationWarning (Python 3.8 compatibility)

- .travis.yml
- README.md
- docs/index.md
- tests/test_model_serializer.py
- tox.ini
Attempt at adding Python 3.7, which requires switching to Xenial. I've also updated the Travix matrix to be an explicit include list, as opposed to a mix of both include and exclude.
> Add Python 3.7 support

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/utils/encoders.py
The type `bytes` is available on all supported Pythons. On Python 2.7, it is an alias for `str`, same as `six.binary_type`. Makes the code more forward compatible with Python 3.
> Remove unnecessary use compat shim of six.binary_type

- .travis.yml
The current travis matrix is kind of a pain to parse, given that it's a combination of python/env expansion and both an include and exclude list. This simplifies the matrix by using only an include list.
Broken out of #6141.
> Simplify job matrix on Travis

- docs/api-guide/viewsets.md
It fixes an error in documentation.
> Fix queryset ordering method in the viewsets docs

- tutorial/4-authentication-and-permissions/index.html
While it would be invoked with a dot, I believe the the method should be referenced by its name
> Removing (potential erroneous) confusing dot "`.`method()"

- docs/api-guide/authentication.md
[GetBlimp/django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt) seems to be [abandoned for quite a while](https://github.com/GetBlimp/django-rest-framework-jwt/issues/449). This PR removes the recommendation from the docs.
Closes https://github.com/encode/django-rest-framework/issues/5838
> Remove mentions to djangorestframework-jwt in docs

- docs/api-guide/filtering.md
- docs/api-guide/permissions.md
- docs/community/release-notes.md
- rest_framework/filters.py
- tests/test_permissions.py
From the discussion in #6038, the objective is to move django-guardian integrations out of the core framework and into a 3rd-party package. Motivating factors are in [this comment](https://github.com/encode/django-rest-framework/pull/6038#issuecomment-399092645).
This PR is fairly straightforward, as `DjangoObjectPermissionsFilter` is the only direct integration. `DjangoObjectPermissions` just hooks into the object-level permissions and isn't directly dependent.
3rd-party package: https://github.com/rpkilby/django-rest-framework-guardian
> Deprecate DjangoObjectPermissionsFilter

- docs/api-guide/fields.md
- rest_framework/compat.py
- rest_framework/fields.py
- tests/test_fields.py
Followup on #6068.
I've left the first commit as a diff to the second one. Please feel free to squash.
I'd love if someone else could edit in the documentation example mentioned by @rpkilby because I've no idea how to achieve that :)
> Prohibit null characters in CharField by default

- rest_framework/compat.py
- rest_framework/management/commands/generate_schema.py
- rest_framework/management/commands/generateschema.py
- rest_framework/renderers.py
This is a low footprint refinement of #6119.
Closes #5839.
Adds `OpenAPIRenderer` and `JSONOpenAPIRenderer`.
Add the `generate_schema` management command.
TODO:
> Add `OpenAPIRenderer` and `generate_schema` management command.

- docs/api-guide/permissions.md
- rest_framework/permissions.py
- tests/test_permissions.py
Implement a system to compose permissions with and / or.
This is performed by returning an `OperationHolder` instance that keeps the
permission classes and type of composition (and / or).
When called it will return a AND/OR instance that will then delegate the
permission check to the operands.
This will allow permissions to look such as:
permission_classes = [IsAuthenticated & (ReadOnly | IsAdmin)]
> permissions: Allow permissions to be composed

- README.md
- docs/community/project-management.md
- docs/tutorial/1-serialization.md
- docs/tutorial/quickstart.md
`refs #6231`
Fixes instances in docs where user is told to enter commands like:
`django-admin.py startproject tutorial`
to the correct:
`django-admin startproject tutorial`
> Documentation fix for django-admin commands

- docs/api-guide/schemas.md
- requirements/requirements-optionals.txt
- rest_framework/schemas/views.py
* Use `OpenAPIRenderer` and `CoreJSONRenderer` by default for `get_schema_view`.
* Add schema docs.
TODO:
> Add OpenAPIRenderer by default, and add schema docs.

- rest_framework/templatetags/rest_framework.py
- tests/test_templatetags.py
Solution: set needs_autoescape=True when registering the filter
Without this patch, the disabling autoescape in the template does not work.
refs #6201
> Problem: autoescape not getting passed to urlize_quoted_links filter

- docs/community/3.9-announcement.md
- docs/community/release-notes.md
- mkdocs.yml
- rest_framework/__init__.py
- rest_framework/decorators.py
- rest_framework/routers.py
- rest_framework/schemas/generators.py
- tests/test_decorators.py
- tests/test_routers.py
- tests/test_schemas.py
Let's get this show on the road, part 2. (Part 1 is #6119)
This is the Release PR for v3.9. Expected 1<sup>st</sup> Oct
Checklist:
> Version 3.9

- docs/api-guide/authentication.md
Make a print python3 compatible on the TokenAuthentication section of Authentication docs page.
> docs: make a print python3 compatible   

- rest_framework/permissions.py
- tests/test_permissions.py
`x and y` actually returns object y when both are true. This means`SomePermission & IsAuthenticated` will fail with `TypeError: unsupported operand type(s) for &: 'instance' and 'bool'` as `IsAuthenticated` now returns a `CallableBool` which does not overload `__ror__` (at least in Django==1.11.16)
An alternative approach is explicitly calling `bool()` in `AND` and `OR`, which would allow `has_permission` to return truthy non boolean objects, but i feel permissions should be more explicit than that. If this approach makes sense I can add tests.
Please describe your pull request. If it fixes a bug or resolves a …
> permissions must return a boolean to allow &/| operator comparison

- rest_framework/schemas/generators.py
- rest_framework/schemas/inspectors.py
Fix typo and too long line in the documentation about schemas.
> Fix typo in schemas

- rest_framework/permissions.py
- tests/test_permissions.py
In some cases we end with an operation between two `OperandHolder`.
This didn't work as it didn't knew how to deal with | or &
This fixes by adding those operations.
Closes https://github.com/encode/django-rest-framework/issues/6296
> Fix composable permissions

- rest_framework/renderers.py
Introduced OpenAPI Schema renderer in 8908934928f448c1ec5f00bae754aacd6dbc0cfc has a bug that converts `schema['title']` from string to tuple.
The resulting OpenAPI Schema YAML then contains `!!python/tuple`, which causes `apistar` to fail.
```
schema:
description: A unique integer value identifying this thing.
title: !!python/tuple
- ID
type: integer
```
> FIX: openapi schema title should be a string not a tuple

- rest_framework/templates/rest_framework/base.html
the tool tip of "POST" button is different from other buttons, since it loses the "js-tooltip" class.
> add "js-tooltip" class to "POST" button

- docs/api-guide/permissions.md
Comma was missing in documentation of permissions composition
> Add missing comma in documentation of permission composition

- docs/community/third-party-packages.md
Follow-up to https://github.com/encode/django-rest-framework/pull/6138, which removed mentions of djangorestframework-jwt from the authentication docs, this removes it from the third-party packages list.
> Remove further mention of djangorestframework-jwt

- CONTRIBUTING.md
Tiny suggestion to include an example of an acceptable alternative to 'Hey guys,'.
My thinking is this'll make it just a bit easier for people to use inclusive language. 'folks' is just my personal go-to.  Can't hurt anyways, right?
> Add example of gender-neutral language in contributing guide. 

- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
If a SlugField set allow_unicode, the ModelSelializer have not set it.
when user create/update a model, the validator will reject the unicode slug field.
So, this fix add this option in field mapping.
> [BugFix] add "allow_unicode" option to ModelSerializer SlugField

- docs/api-guide/relations.md
In response to this comment: https://github.com/encode/django-rest-framework/issues/6230#issuecomment-449595754
This is compatible with both Python 3.x and 2.7.
```py
print(repr(serializer))
```
> Fix example to be Python 3.x and 2.7 compatible

- docs/api-guide/parsers.md
`MultipartParser` is enough to denote that it is a parser.
> correct grammar, remove common noun after proper noun.

- docs/api-guide/renderers.md
Warning: this solves only half of Issue #3387 (Point 1)
I'm not sure what should be done with point 2.
> Fix #3387: Documentation - Remove leading '.' before format option

- docs/tutorial/4-authentication-and-permissions.md
Previous code snippet used in example were only compatible with Python 2. This makes them compatible with 2.7 and 3.x.
> Make code snippets Python 3 compatible

- docs/community/3.0-announcement.md
- docs/community/3.1-announcement.md
- docs/community/3.2-announcement.md
- docs/community/3.4-announcement.md
- docs/community/3.5-announcement.md
- docs/community/3.6-announcement.md
- docs/community/3.7-announcement.md
- docs/community/3.8-announcement.md
- docs/community/3.9-announcement.md
- docs/community/funding.md
- docs/community/jobs.md
- docs/community/kickstarter-announcement.md
Following Issue #6289 recommendations, I installed [textlint](https://github.com/textlint/textlint) with the rule `textlint-rule-no-dead-link`.
Here is the relevant output that I fixed with this PR. At the end, you can find the broken URLs found that I did not fix. I'm not sure what to do with those.
```
33:379  error    http://cramer.io/2011/03/08/building-cursors-for-the-disqus-api is dead. (404 Not Found)
117:83   error    https://www.transifex.com/projects/p/django-rest-framework/ is dead. (301 MOVED PERMANENTLY) no-dead-link
158:153  ✓ error  https://github.com/evonove/django-oauth-toolkit is redirected to https://github.com/jazzband/django-oauth-toolkit. (301 Moved Permanently) no-dead-link
163:35   ✓ error  https://jpadilla.github.io/django-rest-framework-xml is redirected to …
```
> Fix links 404/302/303 in docs/community

- rest_framework/versioning.py
Use default version (It's latest version as often) when 'version' is not specified by client instead of return 404 error "Invalid version in URL path.".
Closes #6379
> Use Default Version in URLPathVersioning if 'version' Didn't Specified by Client

- rest_framework/serializers.py
- tests/test_serializer.py
Fixes #6053.
`to_internal_value()` is expected to return a dict. #5922 relied on this, but users are implementing custom serialisers that return application objects[*]. This PR bypasses the _read-only defaults_ handling for non-dict objects. 
[*]: This is why static typing will never work for Python 😀
Original test case thanks to @vdel in #6242.
> Allow run_validators() to handle non-dict types.

- docs/tutorial/quickstart.md
As a new user to DRF, I was confused when I did the Django tutorial (which uses `path`) and then tried out the DRF quickstart and saw that it still used the older ([probably soon to be deprecated](https://docs.djangoproject.com/en/dev/ref/urls/#url)) `url` routing. I think this will help alleviate some confusion for new users.
I believe this was overlooked in #5964.
Related to #5963.
cc @chrisshyi
> Update quickstart to Django 2.0 routing syntax

- docs/api-guide/schemas.md
Several OpenAPI links were not correctly formatted. This PR fixes them.
> Fix OpenAPI links

- rest_framework/compat.py
- rest_framework/renderers.py
We were mistakenly importing the 'urlparse' function from the Python 2
'urlparse' module, as opposed to the module itself. Correct this.
Signed-off-by: Stephen Finucane <stephen@that.guru>
Closes: #6261
> compat: (py2) urlparse = urllib.parse (py3)

- docs/api-guide/testing.md
While having code blocks in a title is valid Markdown, MkDocs does not
render it as expected. This removes a code block placed in a title.
------
Before:
------
After:
> Fix a badly formatted title in docs

- rest_framework/templates/rest_framework/base.html
- rest_framework/templatetags/rest_framework.py
- tests/test_templatetags.py
> Fix XSS caused by disabled autoescaping in the default DRF Browsable API view templates

- rest_framework/routers.py
- tests/test_routers.py
Closes https://github.com/encode/django-rest-framework/issues/5660
Trying to register new routes on a router after having accessed the
router `urls` attribute leads to surprising results.
The route is added without error to the router's `registry` but the urls
are not updated, because they are cached in `_urls`.
This commit invalidates the cache after each new registration.
> routers: invalidate _urls cache on register

- .travis.yml
`sudo:` has been deprecated since Travis CI has migrated to the new VM-based infrastructure: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Remove sudo from .travis.yml

- rest_framework/fields.py
Closes #6363.
Don't think a docstring is that handy here. The method is only one line.
> Removed incorrect DictField docstring.

- rest_framework/management/commands/generateschema.py
Closes #6366.
Generate schema command is currently untested. Even so, not sure _how_ we catch this...
> Deferred schema renderer creation to avoid requiring pyyaml.

- rest_framework/templates/rest_framework/base.html
Supersedes: #6337
Resolves: #6339
On advice from @tomchristie, I've deliberately left indentation as it is.
I've also simplified things by only adding a single block instead of three. While not quite as helpful for users wanting to override other bits within the `content` block, it's a smaller change with less of a maintenance commitment.
> Add a 'request_forms' block to base.html

- rest_framework/templates/rest_framework/docs/langs/shell.html
- tests/test_renderers.py
Remove “> “ when rendering template.
Closes #6333.
> Corrected coreapi CLI code example generation.

- .travis.yml
- tox.ini
> Added testing against Django 2.2a1.

- .travis.yml
- tox.ini
> Drop testing Python 3.5 against Django master.

- docs/api-guide/relations.md
REST framework is still compatible with versions of Django that work with Python 2.7, so the docs still need to mention the use of `__unicode__`, but it shouldn't be the default.
> Use `__str__` in relations docs.

- docs/api-guide/throttling.md
This PR is a small update to the documentation for specifying an alternate cache for a throttle.  The `get_cache` method was deprecated in Django 1.7 and [removed](https://docs.djangoproject.com/en/2.1/releases/1.9/#features-removed-in-1-9) in Django 1.9.  The new method uses `django.core.cache.caches`.
I've confirmed that the documentation builds and looks reasonable with this change.
> Fix documentation for specifying an alternate throttle cache

- docs/api-guide/serializers.md
- docs/community/3.0-announcement.md
- docs/tutorial/1-serialization.md
- docs/tutorial/2-requests-and-responses.md
- Replace `print x` with `print(x)`
- Remove `u` prefix from strings
Inspired by the work done in encode/django-rest-framework#6376
> Fix Python 3 compat in documentation

- docs/topics/api-clients.md
- rest_framework/static/rest_framework/js/csrf.js
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- tests/test_templates.py
Closes #6206 
Pass the actual CSRF token value instead of the name of the cookie in which to find the value, and use this actual value in the `X-CSRFToken` header.
> Fix web UI when using session-based CSRF

- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_fields.py
- tests/test_serializer.py
> Ensure serializer and field validators support both lists and tuples

- docs/api-guide/filtering.md
- rest_framework/filters.py
- tests/test_filters.py
This pull request refactors `#filter_queryset` and extracts a `#get_search_fields` method, passing in the request in as a second argument (currently unused). This allows subclasses to override this method and dynamically set search fields (vs. overriding the entire `#filter_queryset` method). A few example use cases:
1. Suppose you have 5 search fields, with `email` being one of them. If you run the search terms through a regex and recognize an email, you can dynamically set the search fields only to `email`. (This avoids wasteful searches on the other 4 fields.)
2. Suppose the default search fields are `("^book_title",)`. In combination with overriding the `#get_search_terms` method, a subclass might implement a light lexer/parser to recognize when a search term is encased in quotes, …
> Let SearchFilter subclasses dynamically set search fields

- docs/api-guide/filtering.md
'filter_class' => 'filterset_class'
Also fixed some errant tabs
> Update filtering docs

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/utils/serializer_helpers.py
Since the `Mapping` and `MutableMapping` classes will no longer be available to import directly from the `collections` module in Python 3.8, we should create and use aliases for them in the compat module. I noticed this due to deprecation warnings appearing in tests in a project using rest framework that I ran on Python 3.7.
This builds on the work started in #6154 and removes the remaining references to the abstract base classes that are used in the project.
> Fix DeprecationWarning when accessing collections.abc classes via collections

- rest_framework/utils/field_mapping.py
- tests/models.py
- tests/test_relations_pk.py
> Allowed Q objects in limit_choices_to introspection.

- rest_framework/compat.py
- rest_framework/permissions.py
- tests/test_permissions.py
When composing permissions, all permissions are evaluated even when the outcome is already set. This can lead to errors when the order of the permission was logically set.
For example with `IsReadonly |  IsAssumingNotReadonly`, if `IsReadonly` responds `True` for `GET` requests, logically `IsAssumingNotReadonly` can assume that the method is not `GET`. Presently, this is not the case as `IsAssumingNotReadonly` is being evaluated.
The patch suggests switching to lazy `or` and `and` instead of the bitwise operators.
([Initial report](https://github.com/encode/django-rest-framework/issues/6402#issuecomment-465050530))
> Composed permissions should be lazily evaluated

- tests/test_renderers.py
- tests/test_serializer.py
This is a follow up PR on #6268 to fix similar cases in tests as noted in https://github.com/encode/django-rest-framework/pull/6268#issuecomment-453858077
Thanks for the library :)
> Fix DeprecationWarning in tests when accessing collections.abc classes via collections

- docs/api-guide/permissions.md
- rest_framework/permissions.py
- tests/test_permissions.py
This PR add support for `~` "NOT" operator.
Recent updates from @xordoquy add support for `&` "AND" and `|` "OR" operator with permissions. I felt `~` "NOT" was missing.
We could now do something like `permission_classes = (~cond1 & cond2)`.
I updated only a very tiny bit of the documentation.
If we keep going further with this approach, I don't know if the mentions of "Composed Permissions" and "Rest Condition" will stay relevant. More documentation on how to compose permissions could be a good thing, it is a bit discrete right now.
> Permissions: Add ~ operator to permissions composition

- rest_framework/filters.py
- tests/test_filters.py
Fixes bug with searching in annotated fields.
refs #6094
> Allows searching with SearchFilter in annotated fields

- docs/community/release-notes.md
- rest_framework/__init__.py
- rest_framework/decorators.py
- rest_framework/filters.py
- rest_framework/routers.py
- tests/test_decorators.py
- tests/test_permissions.py
- tests/test_routers.py
> Introduce RemovedInDRF…Warning classes to simplify deprecations.

- docs/api-guide/filtering.md
Just noticed something in the docs and created a quick PR. Not linked to any issue that I could find
> Fix get_search_fields example

- rest_framework/fields.py
- rest_framework/relations.py
- tests/test_pagination.py
- tests/test_validation.py
As all source files import `unicode_literals`, `type('')` is always equivalent to `six.text_type` (`str` on Python 3 and `unicode` on Python 2). Removes the need to call `type()`, is more explicit, and will be easier to catch places to change for when it is time to eventually drop Python 2.
> Replace type('') with six.text_type

- rest_framework/schemas/inspectors.py
- tests/test_schemas.py
This implements the changes mentioned in https://github.com/encode/django-rest-framework/pull/6438#issuecomment-469916730 so that a `ManyRelatedField` will now document the correct inner type. Before it was being forced to a `String`, which was incorrect for the default case and also incorrect for a few other edge cases as well.
> Fix schema generation of `ManyRelatedField` to detect the child type

- docs/api-guide/fields.md
Fixes #6468 
Adds some documentation about the `default_timezone` keyword argument that `DateTimeField` accepts.
> #6468 document DateTimeField default_timezone argument

- tests/test_renderers.py
- tests/test_routers.py
Use `basename` instead of `base_name` to get rid of deprecation warning in `test_renderers.py` and `test_routers.py`.
> Use `basename` instead of `base_name` to get rid of deprecation warning

- rest_framework/schemas/inspectors.py
- tests/schemas/test_openapi.py
This pull request adds an `operationId` property on generated OpenAPI operations from #6532. This property is recommended in the OpenAPI specification and is actually a requirement if we want the generated schema to have any use with OpenAPI clients ; most client libraries will use those operation IDs to build methods. See the [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object) in the OpenAPI spec for more info.
Example with `openapi3` and an hypothetical `ThingsListAPIView`:
``` python
>>> import yaml
>>> from openapi3 import OpenAPI
>>> api = OpenAPI(yaml.safe_load(open('schema.yml').read()))
>>> api.call_ListThings()
[{'id': 1, 'name': 'thing1'}, {'id': 2, 'name': 'thing2'}]
```
Same example with `apistar`:
``` python
>>> …
```
> Add operationId on OpenAPI operations

- rest_framework/schemas/inspectors.py
- tests/schemas/test_openapi.py
Fixes #6562, on the OpenAPI generation PR #6532 by @carltongibson: wraps schemas in the `requestBody` property on an operation in a `schema` key.
``` yaml
requestBody:
content:
application/json:
schema:
properties: ...
required: ...
```
> Fix requestBody not wrapped in a schema in OpenAPI

- docs/api-guide/serializers.md
Adds a sentence about `extra_kwargs` not being used when a field is explicitly defined in the serializer.
Fixes #6581
> Minor documentation fixes (#6581)

- docs/api-guide/serializers.md
- docs/community/3.0-announcement.md
Description
---
Fix an error in documentation example. 
Add `.startswith` method to check that `attribute_name` is a private attribute and ignore it.
Without `.startswith` method calling `attribute_name('_')` raises `TypeError: 'str' object is not callable` exception.
> Fix private attributes ignore in documentation

- docs/api-guide/serializers.md
Fixes typo of the attribute name.
> Fix typo in docs

- docs/community/release-notes.md
- rest_framework/__init__.py
Final release before dropping Python 2.
> Update version and release notes for v3.9.3.

- docs/api-guide/validators.md
Change class name from `UniqueTogetherValidation` to `UniqueTogetherValidator`
> Correct misspelled class name in validators docs

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/serializers.py
- rest_framework/utils/serializer_helpers.py
- tests/test_renderers.py
- tests/test_serializer.py
For Python 3, collections.abc.Mapping and collections.abc.MutableMapping
are always available from the stdlib.
> Remove unnecessary compatibility shims from rest_framework/compat.py

- tests/test_decorators.py
Was added only for Python 2 compatibility.
> Remove unnecessary coerce to str() in test_decorators.py

- tests/test_serializer.py
The test tested Python functionality, not django-rest-framework
functionality. That is best left to the Python test suite.
> Remove pointless test

- rest_framework/fields.py
- rest_framework/management/commands/generateschema.py
- rest_framework/parsers.py
- rest_framework/renderers.py
- rest_framework/utils/encoders.py
- tests/authentication/test_authentication.py
- tests/browsable_api/test_browsable_api.py
- tests/browsable_api/test_browsable_nested_api.py
- tests/test_generics.py
- tests/test_parsers.py
- tests/test_renderers.py
- tests/test_routers.py
- tests/test_templates.py
A Python 3 cleanup that allows for less noise in the code.
https://docs.python.org/3/library/stdtypes.html#bytes.decode
https://docs.python.org/3/library/stdtypes.html#str.encode
> Drop default 'utf-8' to .encode()/.decode()

- rest_framework/authentication.py
- rest_framework/authtoken/apps.py
- rest_framework/authtoken/models.py
- rest_framework/authtoken/serializers.py
- rest_framework/exceptions.py
- rest_framework/fields.py
- rest_framework/filters.py
- rest_framework/pagination.py
- rest_framework/relations.py
- rest_framework/schemas/inspectors.py
- rest_framework/serializers.py
- rest_framework/validators.py
- rest_framework/versioning.py
- tests/models.py
- tests/test_exceptions.py
- tests/test_renderers.py
On Python 3, the ugettext functions are a simple aliases of their non-u
counterparts (the 'u' represents Python 2 unicode type). Starting with
Django 3.0, the u versions will be deprecated.
https://docs.djangoproject.com/en/dev/releases/3.0/#id2
> django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(),
> ungettext(), and ungettext_lazy() are deprecated in favor of the
> functions that they’re aliases for:
> django.utils.translation.gettext(), gettext_lazy(), gettext_noop(),
> ngettext(), and ngettext_lazy().
> Replace all usage ugettext functions with the non-u versions

- CONTRIBUTING.md
- docs/community/contributing.md
- docs/tutorial/1-serialization.md
- docs/tutorial/quickstart.md
On Python 3, creating virtual environments is available through the
stdlib module venv.
https://docs.python.org/3/library/venv.html
> Replace virtualenv references with venv in the docs

- rest_framework/parsers.py
- rest_framework/renderers.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/inspectors.py
- rest_framework/utils/representation.py
- tests/test_renderers.py
Cleans up the pattern:
...
myvar = <expression>
return myvar
To:
...
return <expression>
> Remove unnecessary assignments immediately before a return statement

- docs/api-guide/authentication.md
Since django-oauth-toolkit 1.2.0 (2018-06-03), the package requires Python 3.4+.
https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md#120-2018-06-03
> Update docs on django-oauth-toolkit

- tests/test_schemas.py
When Python is run with the -b command line argument, the following
warning was previously emitted:
tests/test_schemas.py::test_schema_handles_exception
.../django-rest-framework/tests/test_schemas.py:1361: BytesWarning: str() on a bytes instance
assert "You do not have permission to perform this action." in str(response.content)
To fix this warning decode the bytes with an explicit encoding.
For details on the -b command line argument, see:
https://docs.python.org/3/using/cmdline.html#cmdoption-b
> Fix BytesWarning in test_schemas.py

- rest_framework/templates/rest_framework/docs/auth/session.html
Use the get_username() method instead of the username attribute as recommended in Django
Cf. https://docs.djangoproject.com/en/dev/ref/contrib/auth/#django.contrib.auth.models.User.get_username
> Use the get_username() method instead of the username attribute

- docs/topics/documenting-your-api.md
The `Pygments` and `Markdown` python packages have first letter capital.
Fixed link to markdown syntax to go directly to the syntax page.
> Fix dependency naming and Markdown syntax link

- docs/api-guide/relations.md
As pointed here: https://github.com/encode/django-rest-framework/pull/6585#issuecomment-490145334 I suggest to add the small clarification to work with **ManyToManyFields with a Through Model**.
> adding small clarification on ManyToManyFields with a Through Model

- tests/test_utils.py
Test is not overriding the intended setting, should be nested inside settings.REST_FRAMEWORK
> Fix test with STRICT_JSON setting

- docs/index.md
- rest_framework/__init__.py
- rest_framework/compat.py
```
The latest version of Markdown now displays a deprecation warning if
accessing markdown.version, by careful use of checking the type and
existence of markdown.__version__ it is possible to handle the changes
to markdown over various releases where markdown.__version__ at first
did not exist before being a module and finally being just a string.
```
> Make Markdown 2.6 the minimum compatible version

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/test_fields.py
This patch adds support for `allow_empty` option to `DictField` and `HStoreField`.
Enforcing that the field value is not empty is a common use case in my opinion.
The same parameter was already supported by the other composite field `ListField`.
Param defaults to `False` so current behaviour is not changed.
> Dict field allow empty

- rest_framework/fields.py
This is needed to avoid problems with recursive loops. See
https://docs.python.org/3.7/library/copy.html
toward the end.
> Pass through memo in __deepcopy__ as required by the docs

- rest_framework/pagination.py
- tests/test_pagination.py
Pair-coded with ❤️  and with the excellent @tomquinonero, at the DjangoCon Europe 2019 Copenhagen. Thank you 👍 ✨ 
Fixes #6504. This is a bug in the CursorPagination algorithm, occuring when the current page is based on a "position" for which there is no corresponding element (a.k.a page is empty), it will generate offset-based cursors for previous (and in some cases next) pages, and following those links crash.
The fix is in 3 parts:
- Make sure to generate correct links: offset-based pagination should only be used when several consecutive items have the same `position`. One could argue that if the page is empty, all its elements are indeed equal, but it's obviously not the intended behaviour.
- Make sure an incorrect offset doesn't crash
- Make sure that the pages that used to crash now …
>  Fix CursorPagination when objects get deleted between calls (#6504) 

- docs_theme/main.html
To prevent #6682 from occuring in the future. Make the funding sidebar async so it won't block the rest of the page.
> Made the loading of the fund sidebar async 

- rest_framework/fields.py
- tests/test_serializer.py
Fixes #3451, #5635, and #6609.
When a field like `CustomField(source='*', allow_null=True)` is attempting to validate a null value, the `Field.validate_empty_values()` method returns `(True, None)`. This indicates that further validation should be skipped. However, `set_value` breaks, because the empty `source_attrs` indicates that a dictionary should be provided, but the value returned from `validate_empty_values` is `None`. 
This an unusual edge case, but I'd argue it's valid. Although the given value may be null, `source='*'` indicates that the field is validating the whole object, not just the given value. If we decide *not* validating is the correct behavior, then `validate_empty_values` should at least return an empty dict.
I'm not entirely sure what the behavior should be when …
> Fix nullable `source='*'` fields

- rest_framework/serializers.py
- tests/test_fields.py
It might be useful for a serializer with many many fields which uses
read_only and write_only on a large percentage of the fields. But the
memory usage and statefulness it adds are not worth it for the common
case.
> Don't cache _readable_fields and _writable_fields

- rest_framework/__init__.py
- rest_framework/compat.py
- rest_framework/decorators.py
- rest_framework/filters.py
- rest_framework/routers.py
- tests/test_decorators.py
- tests/test_permissions.py
Removed the following deprecations:
- `@detail_route`/`@list_route` (replaced by `@action`)
- `DjangoObjectPermissionsFilter` (moved to [rpkilby/django-rest-framework-guardian](https://github.com/rpkilby/django-rest-framework-guardian))
Also inlines the `is_guardian_installed` check, since guardian is only used in the test suite. Basically, a test suite implementation detail. DRF itself no longer directly provides a django-guardian integration.
> Remove 3.10 deprecations

- rest_framework/fields.py
- tests/importable/__init__.py
- tests/importable/test_installed.py
Spun this off of #6644. 
- Fixes lazy translations for ListField.
- Adds a regression test to ensure that fields with lazily translated validation errors can be imported and instantiated during class creation. This test fails without the corresponding fix to ListField.
- Clarifies purposes of `tests.importable`
<details>
<summary>Test failure snippet:</summary>
```python
INTERNALERROR>   File "/Users/bagel/Documents/projects/django-rest-framework/tests/importable/__init__.py", line 10, in <module>
INTERNALERROR>     class ExampleSerializer(serializers.Serializer):
INTERNALERROR>   File "/Users/bagel/Documents/projects/django-rest-framework/tests/importable/__init__.py", line 16, in ExampleSerializer
INTERNALERROR>     listfield = serializers.ListField(min_length=1, max_length=2) …
```
> Fix lazy translation of ListField errors

- docs/api-guide/fields.md
- rest_framework/fields.py
- rest_framework/serializers.py
- tests/test_model_serializer.py
JSONField doesn't allow to use a custom encoder, but django JSONField allow it.
With this patch a drf JSONField try to get the related model field encoder and use it for all its operations.
> Allow JSONField encoder customization.

- docs/community/jobs.md
Adds findwork.dev as a site for DRF jobs.
> Add more DRF job sites

- README.md
- SECURITY.md
GitHub now has a security tab for projects. For consistency, information on how to disclose security issues should be located in the security policy.
I have created the SECURITY.md file using the information that is currently in README.md and have also added a link pointing to the security policy, which will function once the security policy file is merged into the master branch.
> Move security information to the GitHub security tab

- tests/schemas/test_managementcommand.py
Use of PyYAML's yaml.load function without specifying the Loader
parameter has been deprecated, see https://msg.pyyaml.org/load.
Earlier versions of PyYAML already had the alternative safe_load
function, which limits the loader to a subset of YAML constructs, that
is enough for what we need here.
Fixes #6677
> Use yaml.safe_load instead of load

- rest_framework/compat.py
- rest_framework/fields.py
- rest_framework/utils/formatting.py
- tests/test_utils.py
Replaces #6644.
As a fix for issue #3354, commit 607e4edca77441f057ce40cd90175 made the
evaluation of some validation error messages lazy. To achieve that,
Django's django.utils.functional.lazy() function was used. However, that
function is extremely heavy and slow, and slows down string validation
significantly (lazy() is evaluated each time for each validator for each
field which has one). We noticed this in our production system.
Use a custom lazy_format() object instead which does the formatting
lazily with less overhead.
Using the benchmark attached to the PR (snipped to tottime>100ms):
Before, model serializer:
```
9225123 function calls (9200068 primitive calls) in 8.337 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
25000 …
```
> Improve performance of lazy validation message formatting

- docs/api-guide/renderers.md
Fix a typo in a github.com URL.
> Fix typo in github.com URL.

- rest_framework/renderers.py
- rest_framework/response.py
- rest_framework/test.py
- Use a simpler literal for an empty bytes object.
- `.encode()` always returns a new immutable bytes object, no need to coerce it a 2nd time.
> Remove unnecessary bytes() calls

- docs/index.md
- rest_framework/compat.py
django-crispy-forms isn't used anymore
> Removed references to django-crispy-forms

- docs/community/release-notes.md
- docs/index.md
- requirements/requirements-optionals.txt
- rest_framework/compat.py
This is an update to #6412 and fixes #6317. I created a new PR since there were a number of merge conflicts. Also, added `pygments` to the optional test requirements so that the markdown preprocessor is ran during testing.
Thanks @mcab for getting this started.
> Update markdown preprocessor registration

- tests/test_utils.py
Remove duplicate test. this test already is in https://github.com/encode/django-rest-framework/blob/9ac9c1b2eafa05cf5b6a605ce54e2d5f2f866f1b/tests/test_utils.py#L206
Also, this test is for `replace_query_param` but by mistake placed on `UrlsRemoveQueryParamTests`.
> Remove duplicate test in `tests/test_utils.py`

- rest_framework/schemas/generators.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Fixes `//` prefix for a path that has a common prefix. Prior to this fix, urls with a common prefix
would result in a doubled `/`. For example:
```python
router = routers.DefaultRouter()
router.register(r'courses', views.CourseViewSet)
urlpatterns = [
path('v1/', include(router.urls)),
```
generates this schema:
```yaml
paths:
//courses/:
get:
```
Here's reproducing it showing that the assumption of trailing `/` being returned (as documented) is incorrect:
https://github.com/encode/django-rest-framework/blob/3e210ae48d250b36c66c2b438b8ac1428fa24f3b/rest_framework/schemas/generators.py#L239-L253
```
Python 3.6.6 (default, Jul 27 2018, 14:31:43) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information. …
```
> fix openapi // path prefix

- docs/community/release-notes.md
- rest_framework/management/commands/generateschema.py
- tests/schemas/test_managementcommand.py
See #6670. Adds the ability to override the SchemaGenerator class from the `generateschema` CLI command.
> add --generator_class CLI option to generateschema

- docs/community/release-notes.md
- requirements/requirements-optionals.txt
- rest_framework/renderers.py
- rest_framework/schemas/generators.py
This adds a new PyYAML >= 5.1 feature to suppress sorting the dict when dumping to yaml.
This makes the openapi.yaml file more human-readable with keys appearing in the order they were added.
@carltongibson another candidate for 3.10?
> don't sort YAML keys

- rest_framework/management/commands/generateschema.py
This adds an `urlconf` parameter to the `generateschema` in order to restrict the schema generation to a subpart.
> Add urlconf to the generateschema command

- rest_framework/serializers.py
- tests/test_model_serializer.py
Many to many fields are updated separately after other serializer fields in `ModelSerializer`. Please see issue #6751 for more information.
refs #6751
> Fixes #6751 - ModelSerializer fields does not get updated correctly when signals are connected to some fields 

- docs/api-guide/permissions.md
- docs/community/third-party-packages.md
Hi! This is just an addition to the 3rd party packages section of the permissions docs.
> Adds DRF Access Policy to permissions 3rd party section

- docs/community/third-party-packages.md
Updates third party packages documentation to include the djangorestframework-mvt package.  The djangorestframework-mvt package helps with serving [Map Box Vector Tiles](https://docs.mapbox.com/vector-tiles/reference/).
> Add djangorestframework-mvt to third party packages

- rest_framework/authtoken/admin.py
TokenAdmin is unusable with a big number of user records (in this case ~150k). Django 2.0 added the [ModelAdmin.autocomplete_fields](https://docs.djangoproject.com/en/stable/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) option to use select2 to provide a better user experience.
If support for django 1.11 is dropped, this change would make the `TokenAdmin` usable again.
> TokenAdmin: add 'user' to autocomplete_fields

- docs/api-guide/permissions.md
Hi, the Django REST Framework API Key package listed in the Permissions third-party packages has a new documentation site. I also went ahead and updated the project description.
Fixes https://github.com/florimondmanca/djangorestframework-api-key/issues/56
> Update description and link to djangorestframework-api-key

- docs/api-guide/authentication.md
The example for Custom Authentication is wrong. Currently, the headers are converted (hyphens to underscores) and have the `HTTP_` prefix added
> Fix custom authentication example docs

- docs/api-guide/authentication.md
- docs/api-guide/content-negotiation.md
- docs/api-guide/exceptions.md
- docs/api-guide/fields.md
- docs/api-guide/filtering.md
- docs/api-guide/format-suffixes.md
- docs/api-guide/generic-views.md
- docs/api-guide/metadata.md
- docs/api-guide/parsers.md
- docs/api-guide/permissions.md
- docs/api-guide/relations.md
- docs/api-guide/renderers.md
- docs/api-guide/requests.md
- docs/api-guide/responses.md
- docs/api-guide/reverse.md
- docs/api-guide/routers.md
- docs/api-guide/schemas.md
- docs/api-guide/serializers.md
- docs/api-guide/settings.md
- docs/api-guide/status-codes.md
- docs/api-guide/testing.md
- docs/api-guide/throttling.md
- docs/api-guide/validators.md
- docs/api-guide/versioning.md
- docs/api-guide/views.md
- docs/api-guide/viewsets.md
- mkdocs.yml
- requirements/requirements-documentation.txt
- tox.ini
Updates mkdocs to the 1.0.4, which allows us to move the build to Python 3. Aside from some minor configuration changes, page metadata is now YAML-based so we can use lists. Fixes #6623.
> Update mkdocs to 1.x

- setup.py
Fixes #4012. In short, `twine check dist/*` should help ensure we don't publish distributions with malformed long descriptions. In our case, we were using an outdated version of wheel that didn't support metadata 2.1 and the `long_description_content_type` option.
> Add `twine check` to publish process

- rest_framework/fields.py
- tests/test_fields.py
Resolves #2420 by removing the redundant `SerializerMethodField.method_name` restriction.
cc @tomchristie?
> Allow redundant SerializerMethodField method names

- rest_framework/fields.py
- tests/test_fields.py
This resolves #6351 by raising an exception when a field's source is a built-in function type. 
```python
class MySerializer(serializers.Serializer):
date = serializer.ReadOnlyField(source='timestamp.date')
```
Because built-in signatures cannot be inspected, serialization causes the method to be coerced into a string instead of being invoked. It would be nice if this could be fixed, however, the suggestion is fairly complicated and brittle and raising a helpful error should be Good Enough™.
cc @antwan
> Raise exception when field source is a built-in

- rest_framework/fields.py
- tests/test_fields.py
This prevents exceptions when the error message contains `%`, but is not intended for formatting (more details are available in the linked issue).  Django itself does the same: https://github.com/django/django/blob/6866c91b638de5368c18713fa851bfe56253ea55/django/core/exceptions.py#L168-L169
refs #6622
> [fields] Format error message only if params exist

- rest_framework/serializers.py
- tests/test_serializer_lists.py
Refs #6509
This enforces allow_empty=True when a ListSerializer is a child of another serializer and partial validation is being performed on the parent serializer.
This is because partial validation should allow fields to be omitted, but should not cause values that are invalid without partial validation to become valid.
This effectively reverts #4222. None of the tests added in that PR fail if the associated change is removed, so I‘m not sure what that PR was trying to fix.
> Enforce allow_empty=False during partial validation of parent serializer

- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
Fixes #6597 Correctly map Postgres ArrayField `blank=False` attribute to `allow_empty=False` of ListField
The default mappings between Django and DRF are not clean here. Django, by default set `blank=False` on ArrayField(most fields), which should translate to DRF non-default `allow_empty=False`, and vice-versa.
Need feedback if this is good enough or we should add some comments here.
refs #6597
> Fix ArrayField kwargs mapping with ListField

- docs/api-guide/settings.md
Documents `DEFAULT_PAGINATION_CLASS` and removes other, outdated pagination settings.
Resolves #6185
> Update docs for pagination settings

- rest_framework/filters.py
- tests/test_filters.py
Fixes 6453 by stripping null characters from the search parameter. 
In the future, we may want to use validators for more complex validation.
> Strip null characters from search param

- docs_theme/nav.html
`rel="prev"` should be set for the link which goes back to the previous page, `rel="next"` for the one which goes forward to the next page.
See e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types
cc @d0ugal who added those in b8aa7e0c34dc839a47b679aa2402d0f1b98704a0 (almost 5 years ago :wink:)
> docs: Fix rel=prev/next

- docs/topics/browser-enhancements.md
Hello,
In the browser enhancement docs, the example middleware class for HTTP method overriding doesn't work with recent Django versions because  of the middleware API [changed in 1.10](https://docs.djangoproject.com/en/1.11/topics/http/middleware/#middleware).
This PR replaces the example with one that works with recent Django versions (tested in 2.2.3).
> docs: update http method override middleware example

- docs/api-guide/filtering.md
Give reader a link to `django-filter` docs the first time they are introduced to the package.
> Add link to django-filter on first reference

- docs/tutorial/1-serialization.md
In Tutorial 1: Serialization, when creating the Snippets model in snippets/models.py, the variable STYLE_CHOICES is assigned:
`STYLE_CHOICES = sorted( (item, item) for item in get_all_styles() )`
The global function sorted() expects a list, or an iterable. However this is not being given. STYLE_CHOICES should be generated by using a list comprehension just like the LANGUAGE_CHOICES variable defined immediately before it.
`STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])`
> Missing List Comprehension in Tutorial 1: Serialization | snippets/models.py

- rest_framework/renderers.py
- tests/test_renderers.py
Fixed #6761. The list of extra actions aren't rendered when the user is not authenticated or does not have the appropriate permissions. Note that this mimics the handling for the view description.
> Don't render extra actions when unauthenticated

- rest_framework/serializers.py
- tests/test_serializer_nested.py
This supersedes and closes #5212. There were a few merge conflicts, and a few changes to the test suite that caused the test case to no longer run. Also adds a test for nested serializer writes.
Short version of the issue is for serializers like the following:
```python
class PersonSerializer(serializers.ModelSerializer):
address = serializers.CharField(source='profile.address')
```
`raise_errors_on_nested_writes` was previously asserting that the field's attribute name (address) wasn't present in the validated data, however, the source traversal means that the validated data looks like `{'profile': {'address': '...'}}`, and the assertion should check the first source attr (profile).
Thanks to @practual for raising this.
> Fix dotted-source field checking on serializer write

- rest_framework/static/rest_framework/docs/css/base.css
This PR tackles #5638, with a different approach: make the sidebar look good with the default size even if the endpoints names are long.
We could make it resizable if still needed.
Also contains a fallback font when Verdana is missing (`sans-serif`).
Done in pair with @ewjoachim
We also thought about other ideas to improve the sidebar but @tomchristie said there is going to be change with API star.
> Docs sidebar improvements (#5638)

- rest_framework/utils/encoders.py
- tests/test_encoders.py
I found out that when using JSONEncoder's `default()` method with JSON serializer libraries that do not internally handle list subclasses (such as [`orjson`](https://github.com/ijl/orjson)), empty indexable collections (such as `ReturnList`s, as used by paginators etc.) get turned into dicts, leading into interesting situations á la 
```json
{"count":0,"next":null,"previous":null,"results":{}}
```
(where `"results"` should naturally be a list).
The patch is happily short enough.
> JSONEncoder: ensure empty listlikes remain lists, not dicts

- README.md
- docs/api-guide/authentication.md
- docs/api-guide/fields.md
- docs/api-guide/filtering.md
- docs/api-guide/format-suffixes.md
- docs/api-guide/generic-views.md
- docs/api-guide/parsers.md
- docs/api-guide/permissions.md
- docs/api-guide/relations.md
- docs/api-guide/renderers.md
- docs/api-guide/serializers.md
- docs/api-guide/settings.md
- docs/api-guide/testing.md
- docs/api-guide/throttling.md
- docs/api-guide/validators.md
- docs/api-guide/views.md
- docs/community/3.0-announcement.md
- docs/community/3.1-announcement.md
- docs/coreapi/schemas.md
- docs/index.md
- docs/topics/writable-nested-serializers.md
- docs/tutorial/1-serialization.md
- docs/tutorial/4-authentication-and-permissions.md
- docs/tutorial/5-relationships-and-hyperlinked-apis.md
- docs/tutorial/6-viewsets-and-routers.md
- docs/tutorial/quickstart.md
And all similar attributes that are semantically homogeneous sequences.
See #6604 
I have tried to find all the similar attributes and settings, including things that are Django defined attributes and settings (e.g. `INSTALLED_APPS`, `django.db.models.Model.Meta.ordering`), as Django docs also use lists for these too these days.
I have only touched documentation, not any code, to avoid any possible compatibility issues. This means that there is one area of the docs I have not touched - for the sake of complete accuracy, the documentation of default values of things like `DEFAULT_AUTHENTICATION_CLASSES` still shows a tuple (because that is what the default value is). However, in other example code that sets `DEFAULT_AUTHENTICATION_CLASSES` I have used lists.
> Update docs to use lists instead of tuples

- docs/api-guide/schemas.md
- docs/community/3.10-announcement.md
Fixes the `get_schema_view` import in the documentation for `schemas` and `3.10 announcement ` pages
> Fixes import in the schemas documentation

- requirements/requirements-optionals.txt
Bumps to 2.2, which adds the relevant bits.
> Update Django Filter dependency for OpenAPI schema support.

- rest_framework/__init__.py
- rest_framework/authtoken/admin.py
- rest_framework/compat.py
Refs #6814
Closes #6808
Refs https://github.com/encode/django-rest-framework/pull/6762
I think we should instead document how to customize the TokenAuth admin, using an `autocomplete` field as an example case. (Looking into it I can see that expanding on #3831 slightly is what we'd want)
Also closes #6811
> Version 3.10.1

- docs/api-guide/filtering.md
A small fix to the documentation, `'search'` instead of `'search`'
> fix quote was outside of inline code

- rest_framework/documentation.py
There is a problem in the current implementation that if one exports docs via `include_docs_urls` he will be using `ROOT_URLCONF` (https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/generators.py#L73), which is a big problem, if one is working with subdomains and he has sets of disjoint URLs.
This simple fix allows to pass through forgotten `urlconf` parameter.
refs #6801
> Ability to specify urlconf in include_docs_urls added

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Fixes #6815  
The `array` type in OpenAPI should come with corresponding `items`. Currently, if a `serializers.ListField` is used, the documentation will display the message 'Could not render this component'. In this commit I just add the `items` with the proper type of the child so it renders correctly.
> Handles ListField mapping for OpenAPI

- rest_framework/schemas/coreapi.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
Specifically: Closes #6675. Closes #6823.
* Corrected one test, which was ultimately a logic error on my part, for common prefixes. 
* Adds another to check the `url` parameter functions as a mount point. 
* Fixes the above. 
* A couple of tidy-ups.
> OpenAPI Schema Generation Fixes.

- docs/api-guide/validators.md
Supersedes/closes #6798. Thanks @samims for raising this!
> Remove incorrect note about read_only+default

- docs/community/third-party-packages.md
I would like to add [drf-action-serializer](https://github.com/gregschmit/drf-action-serializer) to the docs per rejected PR 6842. Also, please let me know if I've added it to the wrong place in the docs.
> Add drf-action-serializer to third party packages in docs

- rest_framework/fields.py
Hello :)
This PR is used for enhance performance when use with [`django-storages`](https://github.com/jschneier/django-storages).
When serializer encode data with `FileField`, the original way will cause `S3Boto3Storage.url` called twice. This method calls [`generate_presigned_url`](https://github.com/jschneier/django-storages/blob/44fe7698ece8bdf125d5529194e5277952bc6193/storages/backends/s3boto3.py#L622), which uses many computing times.
> change FileField.to_representation to EAFP style to better work with `django-storages`

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Refs #6846 
This is the first part of #6846.
Previously, the response schema for list views was an object representing a single item. However, list views return a list of items, and hence it should be an array.
Further work will need to be done to support how pagination classes modify list responses. 
There should be no change for views not determined to be list views.
I also slightly refactored the logic to get a serialiser instance in `AutoSchema` so that it's shared between `_get_request_body()` and `_get_responses()`.
I'd recommend looking at the two commits separately.
> Use an array type for list view response schemas

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
> OpenAPI: only include non-empty required property.

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
As discussed in #6833, just add an empty description to satisfy editor.swagger.io
Closes #6833.
> OpenAPI: Added description to responses.

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
> Fixed incorrect OpenAPI response schema generation for a DELETE method in generic views

- rest_framework/views.py
- tests/test_throttling.py
> Handle 'None' return value of wait() properly during throttling.

- requirements.txt
> Fixed typos

- rest_framework/pagination.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/test_pagination.py
Refs #6846
This provides a way for pagination classes to add pagination properties (`count`, `next`, `results` etc.) to OpenAPI response schemas.
A new method `get_paginated_response_schema()` has been added to `BasePagination`. This method is intended to mirror `get_paginated_response()` (which takes a `list` and typically wraps it in a `dict`). 
Hence, `get_paginated_response_schema()` takes an unpaginated response schema (of type `array`) and wraps that with a schema object of type `object` containing the relevant properties that the pagination class adds to responses.
The default implementation of `BasePagination.get_paginated_response_schema()` simply passes the schema through unmodified, for backwards compatibility.
> Add support for pagination in OpenAPI response schemas

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
Fixes #6862 
Had to replace `validators` with a `field` argument in `_map_field_validators` because otherwise there is no way to test whether the field is a `ListField` or a `CharField` and we need to know this since they have different length attributes in OpenAPI spec.
> Fixed incorrect min/max attributes for serializers.ListField

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Fixes incorrect casing of `operationId` in OpenAPI generation - refs #6875. Specifically fixing `ListThings` to `listThings` which standardizes on `lowerInitialCamelCase` like the other method types.
Updated tests as well.
> Fixes #6875 - OpenAPI Schema inconsistent operationId casing

- rest_framework/schemas/generators.py
The OpenAPI `['info']['version']` property now defaults to the empty string, unless explicitly set.
Discussed at https://github.com/encode/django-rest-framework/commit/e57c1505fc4ed957332ae547a35c8713acfdf30c#r34944838
> Default OpenAPI version to the empty string

- docs/community/release-notes.md
- rest_framework/__init__.py
Version 3.10.3
Also includes 3.10.1 and 3.10.2 release notes that were not commited.
Need to be stricter on releases only occuring through PRs, rather than local commits, pushed to master.
TODO:
> Version 3.10.3

- docs/community/third-party-packages.md
I'd like to add my [djangorestframework-dataclasses](https://github.com/oxan/djangorestframework-dataclasses) package to the list of 3rd party packages in the docs.
> Add djangorestframework-dataclasses to 3rd party packages in docs

- docs/community/third-party-packages.md
I'd like to add my [django-restql](https://github.com/yezyilomo/django-restql) package to the list of 3rd party packages in the docs.
> Add django-restql to 3rd party packages in docs

- rest_framework/serializers.py
`FieldDoesNotExist` was moved to `django.core.exceptions` in https://github.com/django/django/commit/8958170755b37ce346ae5257c1000bd936faa3b0 and removed from `django.db.models.fields` in https://github.com/django/django/commit/129583a0d3cf69b08d058cd751d777588801b7ad.
> Fixed import of FieldDoesNotExist exception.

- rest_framework/fields.py
- rest_framework/relations.py
fixed no-cls-argument on staticmethod `__new__` .
Class method `__new__` should have `cls` as first argument.
> fixed no-cls-argument

- rest_framework/routers.py
`escape_curly_bracket` incorrectly checks for `{` and `}`, there's actually no need to check if they exist before calling `replace`.
> Fix bug in escape_curly_brackets

- docs/api-guide/fields.md
- docs/api-guide/serializers.md
Fixes minor grammatical errors in the Docs.
> Fix minor grammatical errors in Docs

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Improve delete of required property from OpenAPI schema avoiding `KeyError` exception.
```
ERROR    django.request:log.py:228 Internal Server Error: /
File "/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File …
```
> Fix KeyError when delete required property from schema with patch method

- docs/api-guide/serializers.md
This updates the documentation so that the examples for overriding `Serializer.to_representation` use [the same signature as the base implementation](https://github.com/encode/django-rest-framework/blob/30e56f62ba1115ce23851995c6ed6bff45defbb7/rest_framework/serializers.py#L503). The doc also says "The signatures for these methods are as follows:" but then gave the wrong parameter name.
The main reason for this change is that several times now I have looked at these docs to learn the signature and copied it into a project, only to later get a pylint warning: `.to_representation: Parameters differ from overridden 'to_representation' method`.
> Update serializer docs to use correct param name

- rest_framework/fields.py
- tests/test_fields.py
Added test case to reproduce the bug described here #7001 ('sNaN' string raises InvalidOperation exception instead of validation error ) and fixed the bug.
refs #7001
> Fixed decimal snan deserialization

- docs/api-guide/schemas.md
Hello guys,
Just fixing an incredibly minor rendering issue that makes the paragraph more complicated to understand
Cheers
> Fix markdown code indent in schemas doc

- requirements/requirements-codestyle.txt
- rest_framework/schemas/__init__.py
- setup.cfg
- tests/schemas/test_coreapi.py
- tests/test_permissions.py
Update the linter requirements and fix new errors.
The addition of W504 is a little confusing. In short, pycodestyle somewhat recently added [W504](https://lintlyci.github.io/Flake8Rules/rules/W504.html), which contradicts the older W503. By default, both W503 and W504 are ignored, however we override the flake8 ignore list to just E501, so these contradictory rules are running in conflict with each other. 
For now, the fix is to add W504 to the ignore list, although conforming to W504 is the recommendation and we may want to follow it in the future.
> Update linter requirements

- docs/api-guide/schemas.md
`get_link()` was a method in the deprecated CoreAPI-based AutoSchema [class](https://github.com/encode/django-rest-framework/blob/3.10.0/rest_framework/schemas/coreapi.py#L302).  In 3.10, DRF moved to OpenAPI schema generation, and its `AutoSchema` class defines `get_operation()` instead.  I updated the code example to follow suit.
refs #6887
> Update method override example in Schemas docs 

- rest_framework/schemas/openapi.py
Replace "pagninator" by "paginator".
This is a private method, so it does not affect API users.
> Fix a spelling error in openapi AutoSchema method

- docs/api-guide/fields.md
- docs/api-guide/requests.md
- docs/api-guide/schemas.md
- docs/community/release-notes.md
- docs/community/third-party-packages.md
- docs/coreapi/schemas.md
- tests/test_serializer.py
I'm not sure it is allowed to use `serialis*`(like `serialiser`) ，or it should be replaced as `serializ*`.
> Fix docs typos

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
HStoreFields were described as `{"type": "string"}` inside OpenAPI schemas, while they should actually be `{"type": "object"}`, because the generator did not recognize them. This PR fixes this issue and adds a test case for this particular field.
Fixes #6913
> Set the proper JSON schema type for HStoreFields in OpenAPI schemas

- docs/api-guide/generic-views.md
- docs/community/third-party-packages.md
The project seems to be obsolete per https://github.com/miki725/django-rest-framework-bulk/issues/77 .
> Remove unmaintained django-rest-framework-bulk from docs

- docs/api-guide/responses.md
It's all in the title; the link to the Django documentation quoted in [this page](https://www.django-rest-framework.org/api-guide/responses/) was dead. The link was probably written by hand and nobody ever clicked on it!
> Fix link to Django docs in responses documentation

- docs/api-guide/settings.md
I changed the docs to reflect that the default value for `DEFAULT_SCHEMA_CLASSES` now points to the OpenAPI `AutoSchema` class.  The docs were leading users to believe that `rest_framework.schemas.AutoSchema` was the default: as of this PR, the root AutoSchema is [still imported](https://github.com/encode/django-rest-framework/blob/3.10.0/rest_framework/schemas/__init__.py#L27) from the coreapi module.
> Update DEFAULT_SCHEMA_CLASSES default value in Settings docs

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Issue #6863
**TL;DR** I ended up implementing an automatic parser/renderer mapping to corresponding request/response media type. The tests are passing.
So while testing this I discovered that every endpoint that supports request body, accepts multipart requests even if there are no file fields in serializers. This is correct since this is how DRF default parsers setting actually works. So there is no longer a need to handle endpoints that accept files in a special way. Anyway, this is just an idea let me know what you think @carltongibson @tomchristie
> Schemas: Map renderers/parsers for request/response media-types.

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
This fixes #7017 where we can produce a better openapi spec.
> OpenAPI: Use int64 format for large integers.

- rest_framework/schemas/coreapi.py
- rest_framework/schemas/inspectors.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
I would like to document my operation with a description as a docstring comment like it was with coreapi.
> OpenAPI: Ported docstring operation description from CoreAPI inspector.

- docs/api-guide/schemas.md
- rest_framework/schemas/generators.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Generated openapi definition is not valid if title or version are not provided.
- title and version are required by openapi specification 3.x
- fixed my mistake with default parameter introduced here: #6899 
- reverted my documentation change after #6907
> OpenAPI: Fixed generation when title or version not provided.

- docs/api-guide/versioning.md
Fixes #6885:
- replaces instances of url() with re_path() in `URLPathVersioning` and `NamespaceVersioning` in the Versioning Docs
> replaced url() with re_path() in Versioning docs

- docs/tutorial/2-requests-and-responses.md
This PR removes the reference to `JSONResponse` in the part 2 of the tutorial. It seems like this class was [used before in the part 1](https://github.com/encode/django-rest-framework/blame/149b00a070fcbfd44feee5b37096081e18356f93/docs/tutorial/1-serialization.md#L166) but it has been removed.
> [Doc] Remove the old reference to `JSONResponse`

- rest_framework/relations.py
- tests/test_relations.py
> Escape hyperlink URLs on lookup

- docs/api-guide/fields.md
- docs/api-guide/validators.md
- rest_framework/fields.py
- rest_framework/validators.py
- tests/test_validators.py
Follow on from #6172
Drops `set_context()` on defaults and validators, in favour of a `requires_context = True` marker, which causes the serializer field to be passed as an additional argument.
What do we think about this?
> Drop `set_context()`

- docs/community/release-notes.md
Forgive the political nature of this pull request because it's the last thing people want to deal with when maintaining an open-source package. To qualify this, I am a long-time and heavy Django REST Framework user and not a drive-by activist looking to cause controversy. I think the vast majority of people are sensible and will not turn this into a divisive issue.
There is a quote from Eric S. Raymond at the top of the release notes document. This quote is largely inconsequential to achieving the intent of the document, as is the style in DRF documentation generally. ESR has had an [extremely long, public, and ongoing fall from grace](https://rationalwiki.org/wiki/Eric_S._Raymond), including ongoing comments of a racist, sexist, islamophobic.etc nature. I put forward the position …
> Removed Eric S. Raymond quote from the release notes

- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
- tests/test_utils.py
> Changed default widget for TextField with choices to select box.

- rest_framework/fields.py
- rest_framework/relations.py
- rest_framework/schemas/inspectors.py
- rest_framework/schemas/utils.py
- rest_framework/views.py
Fixes a few deprecation warnings. No issues since we're Python 3-only.
> Fix Django 3.0 deprecations

- rest_framework/__init__.py
- rest_framework/routers.py
- tests/test_routers.py
- Bump version numbers for deprecation warnings
- Drop deprecated features
> Update framework deprecation warnings

- rest_framework/fields.py
- rest_framework/validators.py
- tests/test_fields.py
- tests/test_validators.py
Hi @tomchristie. Just a review/followup for #7062.
- Bump deprecation from 3.12 to 3.13 to be inline with our stated deprecation policy.
- Raise  `RemovedInDRF313Warning` instead of `DeprecationWarning`.
- In some methods, pass the serializer instead of the model instance. This is necessary in order to correctly handle field source mappings (will followup in a separate PR). Also, this signature was introduced in #7062, so breaking it now isn't an API breakage.
- Change `instance = getattr(serializer, 'instance', None)` to just `serializer.instance`. The `BaseSerializer` declares `instance`, so I'm not aware of a case where it wouldn't exist.
- Remove the validator `.serializer_field`, which is a holdover from `set_context`.
> Followup to set_context removal

- rest_framework/decorators.py
Improves the docstring for `@action`, as discussed in the comments on #6748.
> Improve the docstring on @action

- rest_framework/serializers.py
- rest_framework/validators.py
- tests/test_validators.py
This is an updated version of #7005 that I was helping @anveshagarwal put together. In short, there are two related bugs:
- As pointed out by @anveshagarwal in https://github.com/encode/django-rest-framework/pull/5922#discussion_r336450337, `_read_only_defaults` does not correctly account for the field `source`. The initial check does account for compatible sources, but when assigning the read only default, the `field_name` is used instead of `source`. 
- Generally, `UniqueTogetherValidator` doesn't handle field sources. Handling this is a little annoying, because the objective is to validate the serializer fields/data. However, the given `attrs` use the source/model field names, which are used in the actual validation check.
As to potential breaking changes, we may want to call out that …
> Fix UniqueTogetherValidator with field sources

- setup.py
Pip's dependency resolver (used in pipenv, pip-compile, poetry, etc.) can use this to infer whether there's a verison collision in what it's being asked to install or not.
> Declare Django versions in install_requires

- rest_framework/serializers.py
- tests/test_serializer.py
Fixes #5798. As pointed out by @svilendobrev, the current code reverses the field order twice, defeating the point of reversing the first place. Thanks to @mwhansen for providing a minimal test case.
Note that I ran the test locally to verify the failure. Also, even though this is a relatively minor bugfix, I'm adding to the 3.11 milestone since it's technically a change in behavior to the public API.
> Fix serializer multiple inheritance bug

- rest_framework/fields.py
If you don't implement`to_representation` in your `Field` subclass, you get a friendly error message suggesting that you might want to subclass `ReadOnlyField` instead. However, by not implementing `to_representation` you would have effectively made the field `write_only`, so the error message would be misleading (unless I'm horribly mixed up for some reason. Feel free to tell me that my head is on backwards :D)
Also making sure both errors have the field name for consistency's sake.
> Fix NotImplementedError message: Field to_internal_value and to_representation

- README.md
- docs/community/3.10-announcement.md
- docs/community/3.11-announcement.md
- docs/index.md
- mkdocs.yml
- rest_framework/__init__.py
- rest_framework/renderers.py
Initial pass at release notes.
> Version 3.11

- docs/api-guide/fields.md
- docs/api-guide/generic-views.md
- rest_framework/serializers.py
These are a few trivial things I noticed while browsing serializers.py. Please see the commits.
> Remove a few no longer needed compat checks and references

- docs/topics/api-clients.md
- trailing commas (as both Python and JavaScript allow them)
- trailing semicolons in JavaScript
- URL name `api-docs`
I was going over the documentation and saw some errors when I copied and pasted the code. Commas were missing, semicolons were missing, and there a URL was not named. Also, I added some trailing commas as both Python and JavaScript allow trailing commas.
> Add missing punctuation marks and URL name

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
This simply avoids emitting callable field defaults to the openapi schema.
Fixes #6858
> Avoid outputting callable defaults to schema

- docs/topics/documenting-your-api.md
This pull request fixes swagger-ui example placed in the docs, allowing usage of "Try it out" functionality with POST method.
Closes #6859.
> Add X-CSRFToken HTTP header in swagger-ui example

- docs_theme/css/default.css
The code blocks in the documentation are quite hard to read because of low contrast and small font.
This changes that.
> Documentation: make codeblocks easier to read.

- docs/api-guide/filtering.md
As far as I can tell, Django supports full text search with PostgreSQL, not MySQL.  I updated the wording in the `filtering.md`.
https://docs.djangoproject.com/en/3.0/topics/db/search/#document-based-search
https://docs.djangoproject.com/en/dev/ref/contrib/postgres/search/
> Fix full-text search typo (mysql => postgres)

- docs/tutorial/quickstart.md
The quickstart tutorial implies that the endpoints are restricted to authorized users and the examples include basic authentication for an "admin" user.
`curl -H 'Accept: application/json; indent=4' -u admin:password123 http://127.0.0.1:8000/users/`
However, the requests are successful with or without authentication which is confusing to beginners like me.  This patch adds `permission_classes = [permissions.IsAuthenticated]` to each endpoint.
Alternatively, we could keep the quickstart tutorial simple and remove the basic authentication from the example `curl` and `httpie` requests.
> add permissions to quickstart tutorial

- MANIFEST.in
Adds tests to the sdist tarball, so they will also be available in the source tarball on pypi.org.
Fixes #7141.
> MANIFEST.in: Adding tests to sdist tarball.

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
This just _inline method_s `get_path()` which wasn't really needed. It's preparatory to add reference component generation parallel to the current path operation generation. 
It includes the commits from #7125 and #7126. So can be Rebase & Merged to close all three. 
(They're intended as three commits for the history.)
> OpenAPI endpoint enumeration refactoring.

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Instead of copying over a select few fields from the schema generation for `ListField`, we are now copying over the entire generated schema and trusting our schema generation to produce the right sub-schema for the child field.
This fixes #7023.
This closes #7080.
> Improve ListField introspection of the child field

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Includes in the OpenAPI schema of boolean fields the default value when it's false
e.g. `serializers.BooleanField(default=False)` generates `{type: boolean, default: false}`
> handle default=false for boolean fields

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
@carltongibson @kevin-brown As we have discussed in #7080, In majority cases, the `type` of enum values for the choicefield will be one of the following.
1. string
2. int
3. float
In this merge request, I have added code to generate the `type` for majority cases.
> Add type for choicefield

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Update openapi.py to include a type of object to anything that requires 'properties' during schema generation (_map_serializer method). Also, fix unit tests.
This fixes`refs #7168` in the description of the pull request.
> Fix for #6984

- rest_framework/renderers.py
- tests/schemas/test_openapi.py
@carltongibson as requested in #7096
when objects are reused in a structure, yaml creates aliases for those objects. 
- makes the schema harder to read with only alias tags like `&id001` instead of proper names
- usage of advanced yaml feature possibly not supported everywhere
- the openapi client generators also chokes on that feature
(will push fix once test fails)
> Disable yaml aliases for generateschema

- docs/api-guide/schemas.md
- rest_framework/management/commands/generateschema.py
- tests/schemas/test_managementcommand.py
@carltongibson as requested in #7096
If a codebase outputs anything on stdout (e.g. debug messages) while generating schema, the schema will be broken.
Add explicit "write to file" as a robust way to obtain a schema.
> Add --file option to generateschema

- rest_framework/authentication.py
- tests/authentication/test_authentication.py
This PR concerns issue https://github.com/encode/django-rest-framework/issues/7183 and makes `BasicAuthentication` auth backend decode the base64-encoded credentials with utf-8.
> decode base64 credentials as utf8; adjust tests

- docs/tutorial/quickstart.md
- docs_theme/404.html
- docs_theme/main.html
This fixes #7180 by linking to a valid API guide doc, but it also generally fixes our 404 styling. See individual commits for details.
The issue with the template is that the `base_url` for the 404 pages was `/`, so the templated URLs were like `//foo.css` instead of `/foo.css`. We could just remove the extra slash, but it's more correct to use the `url` template filter.
Update 404 page now looks like:
> Fix docs 404

- docs/api-guide/serializers.md
The [serializers docs](https://www.django-rest-framework.org/api-guide/serializers/#handling-saving-related-instances-in-model-manager-classes) have an example of calling a custom model manager, but the call to `create()` is invalid Python. This PR adds commas between the args/kwargs so it becomes a valid function call.
> Fix invalid function call syntax in example

- docs/api-guide/schemas.md
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
This merge request adds logic to generate open API tags automatically. It also allows the user to override auto-generated tags as an argument to the constructor of `AutoSchema`. This solution will not break the encapsulation of schema generation. Inspiration: https://github.com/encode/django-rest-framework/issues/7103#issuecomment-582583173
There is another merge request(#7182) with a possible solution. You can merge whichever solution is the best. 
This Fixes: #7103 
This closes: #7104 & #7177
> Possible solution for tags generation 

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Related to: https://github.com/encode/django-rest-framework/issues/7205
Fixes only 201 status code for POST request.
I've added additional asset to check if status code 201 available in responses for POST action.
I will try to fix all issues with openapi because I really need this in my project.
> Fix: use 201 status code for POST requests.

- docs/api-guide/schemas.md
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
This PR allow the user to customize the operationId's name.
It fixes the subtask " Allow setting a custom operation ID on views with an attribute?" defined here https://github.com/encode/django-rest-framework/pull/6549
Thanks !
> Openapi custom operation name

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
This PR add a check to AutoSchema which warns the developer if the schema contains duplicated operationId.
As described in the [OpenAPI specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-8), the operationId should be unique across the schema.
> Schema/OpenAPI - Warns users about duplicated operationId

- docs/api-guide/schemas.md
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
Closes #6984
As described in [this issue](https://github.com/encode/django-rest-framework/issues/6984), the OpenAPI specs generated by DRF may use a reference to existing models.
This PR add a components/schema property in the OpenAPI specs for serializers having a `model` property. The schema's name is the model's class name.
For serializers without model, the properties are inlined as before.
I added a sample test but I may add other ones if this PR is okay for you.
Edit: The schema references are also [discussed here.](https://github.com/encode/django-rest-framework/pull/6532#issuecomment-489443998)
Thanks :)
> Generate components for OpenAPI schemas.

- rest_framework/authtoken/serializers.py
- rest_framework/authtoken/views.py
- tests/schemas/test_openapi.py
This PR fixes the AutoSchema generation for the `obtain_auth_token` view.
Here is the invalid (partial) OpenAPI schema currently generated.
```yaml
/api-token-auth/:
post:
operationId: CreateObtainAuthToken
description: ''
parameters: []
requestBody:
content:
application/x-www-form-urlencoded:
schema: &id029 {}
multipart/form-data:
schema: *id029
application/json:
schema: *id029
responses:
'200':
content:
application/json:
schema: {}
description: ''
```
As you can see the requestBody's schema and response's schema are empty.
This is because:
- The `ObtainAuthToken` class inherit from `rest_framework.views.APIView` which do not have a `get_serializer` method (this is what is used by the `rest_framework.schemas.openapi.AutoSchema` class to get the serializer).
- The `AuthTokenSerializer` …
> fix(obtain_auth_token): Fix openapi schema generation

- docs/api-guide/schemas.md
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
This PR intend to make the OpenAPI - AutoSchema's operationIds camel case and consistent across the schema.
The operationId in OpenAPI examples are all camel case.
[e.g. : Do a CTRL-F for "operationId" on the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md)
The current behavior is the following :
- if you have `ViewSet` (with the inherited methods : `get`, `list`, `retrieve`, `partial_update` etc..), you will get an `operationId` like `partial_updateItem` which is half `snake_case` and half `camelCase`.
- if you have APIView (with the inherited methods: `get`, `post`, `put` etc...), you will get an `operationId` like `RetrieveItem` which is "PascalCase" or "upper camel case".
With this PR, the auto-generated `operationId` will be camelCase.
> Schema/OpenAPI:  Make operationId camel-case

- rest_framework/viewsets.py
- tests/test_viewsets.py
Fixes #7216
This adds a failing test to demonstrate the inspection of a viewset to find its actions is too permissive.
The same can be achieved with mocked objects because unfortunately `hasattr(MagicMock(), 'mapping') is always true.
> Extra action detection is too permissive. Add failing test + fix

- rest_framework/viewsets.py
- tests/test_viewsets.py
Fixes #6196 by setting the `head` handler in the `actions` map instead of on the view instance.
> Set action for HEAD requests

- docs/api-guide/serializers.md
The [serializer docs](https://www.django-rest-framework.org/api-guide/serializers/), contain an example of a `UniqueTogetherValidator` that's not correct and if someone tries to use this as is he will get an error.
As stated in its [documentation](https://www.django-rest-framework.org/api-guide/validators/#uniquetogethervalidator), the `validators` Meta field needs to be a list. This PR wraps that `UniqueTogetherValidator` in a list.
> Fix serializer example in docs

- docs/api-guide/authentication.md
Regarding the last update of django-rest-auth which said The repo is on pause and is currently unsupported.
I figured it out when I was searching for something that provides essential authentication endpoints on the go, a lot of open issues and Pull requests are still there for more than 6 months.
Source: https://github.com/Tivix/django-rest-auth/issues/568
> Add django-rest-auth fork to docs

- rest_framework/request.py
- tests/test_request.py
Adds a repr to Request, returning:
```
<rest_framework.request.Request: GET '/example'>
```
This is similar to the underlying `WSGIRequest`, which returns:
```
<WSGIRequest: GET '/example'>
```
One question is if we want to provide the full `Request` class path, or just the name.
Fixes #7231.
> Add Request repr

- docs/api-guide/renderers.md
Hi there.
I guess [this example](https://www.django-rest-framework.org/api-guide/renderers/#example) is not working now.
And if I write this example, then it throws the below error and I think smart_unicode is not used. 
```
ImportError: cannot import name 'smart_unicode' from 'django.utils.encoding' (/usr/local/lib/python3.7/site-packages/django/utils/encoding.py)
```
If I delete `from django.utils.encoding import smart_unicode`, then it throws the below error.
```
AttributeError: 'ReturnList' object has no attribute 'encode'
```
So I replace `smart_unicode` to `smart_text`, and use it for encoding data.
> Fix modify custom render example document

- rest_framework/filters.py
Django master removed the `ORDER_PATTERN` regex with commit https://github.com/django/django/commit/513948735b799239f3ef8c89397592445e1a0cd5
> Updated ordering field name checks for Django master

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Mostly, We do not need a serializer for the delete method. Component generation logic expects a serializer defined for each method. which will create an error in the following scenarios:
1. A View with only delete action & serializer class is not defined.
2. A View with overridden `get_serializer_class` method that does not provide serializer for the delete action. 
This merge request fixes the above scenarios.
Also, I have added a test case that will fail without this fix.
> Component should not be generated for delete method

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
The API renders DecimalFields as strings. The generated schema now renders decimal fields correctly as strings.
Fixes #7253
> Corrected OpenAPI schema type for DecimalField

- rest_framework/__init__.py
- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
- Bumps deprecation warning classes for 3.12. 
- Removes RemovedInDRF312Warning.
- Adds RemovedInDRF314Warning. 
- Renames AutoSchema methods to be public. 
- Deprecates old hooks. (Didn't add additional tests for these...) 
Docs changes for now public methods in schemas.md to follow separately.
> Convert openapi.AutoSchema methods to public API.

- rest_framework/checks.py
Add a missing space in warning message when `DEFAULT_PAGINATION_CLASS` is unset.
> Fix punctuation in system check

- docs_theme/css/default.css
Remove the scroll bars for the "Topics" and "Tutorial" submenus on the website. Previously, unnecessary scroll bars appeared in Firefox and Chrome. Applying this change allows "Community" and "API Guide" submenues to still have scroll bars as necessary.
> Remove a few submenu scroll bars on docs site

- docs/api-guide/filtering.md
- rest_framework/filters.py
- tests/test_filters.py
Since JSONFields and HStoreFields use `__` we needed to update the m2m checking code to handle search_fields that contain __ that are not relationships.
For `SearchFilter` to support [JSONFields](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#querying-jsonfield) and [HStoreFields](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#querying-hstorefield).
This enables:
`search_fields = ['jsonfieldname__nestedkey__path',]`.
When traversing the `__` separated search_field path the code expects the `opts` value to be updated on each iteration of the traversal. However the JsonField/HStoreField does not provide a `get_path_info` (since it is not a relation). This results in the next iteration of the traversal reusing the old `opts` value and raising an error …
> SearchFilter to support JSONField and HStoreField

- docs/api-guide/schemas.md
There should be extra line between list header and list items, otherwise it is not rendered as a list.
> Fix markdown lists formatting.

- docs/api-guide/schemas.md
Reference-style link should be enclosed in square brackets. Otherwise it is treated as an inline-style link.
See also: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links
> Fix typo in links

- docs/community/third-party-packages.md
Small update to third-party packages to include [drf-typed-views](https://github.com/rsinger86/drf-typed-views).
> Adds drf-typed-views to 3rd party packages

- rest_framework/generics.py
- tests/test_generics.py
Allows the `context` kwarg to be provided to the call to `get_serializer`. Currently a given context is overridden by the `get_serializer_context` result. 
refs #6956
> Allow context to be provided to get_serializer

- tests/test_model_serializer.py
The tests expect `/tmp/` to be always available which is not the case sinsce it's system dependent. 
Luckily Python has a function to fill this properly :)
> Changed hardcoded /tmp/ directory to autodetect from system

- tests/test_decorators.py
- tests/test_renderers.py
- tests/test_request.py
- tests/test_viewsets.py
- Removes an unused testcase helper method
- Attach the `view`/`request` directly to the response object instead of leveraging the `renderer_context`. This pattern is already used elsewhere, and it seems preferable than relying on an implementation detail of the view.
> Minor test improvements

- docs/api-guide/testing.md
The old link led to a 404. Since the contributing guidelines state that links should always use the reference style I fixed that as well.
> Fix broken documentation link

- docs/api-guide/permissions.md
- rest_framework/views.py
- tests/test_permissions.py
Fixes #7038
Supersedes https://github.com/encode/django-rest-framework/pull/7039, keeping the implementation like the one already in place for custom `message`.
> Pass custom code to PermissionDenied if permission class had one set

- docs/api-guide/metadata.md
Endpoint `schema` collides with `schema` class variable which is used for specification generation. Fixed docs
> Fix schema endpoint example

- rest_framework/filters.py
- tests/test_filters.py
Fixes https://github.com/encode/django-rest-framework/pull/6240#discussion_r361321402. `SearchFilter.must_call_distinct` incorrectly exits early if it encounters an annotation. Any subsequent m2m fields are ignored instead of causing the method to return true. By continuing, the annotations still bypass the distinct check, and will return false at the end if no m2m fields are encountered.
> Fix SearchFilter.must_call_distinict for annotation+m2m

- README.md
- docs/index.md
Hi! I noticed that path() in documentation is used in some places and url() in other places. Url is slowly deprecated so I allowed myself to replace in the project homepage and readme url() to path().
> Updating documentation / switching from url to path

- rest_framework/serializers.py
- tests/test_validators.py
This fixes #7100 which was caused by related changes in #7086. Model serializers will now correctly use serializer field names that map to the field sources in `unique_together`. If there are multiple fields that use the same source (seems unlikely but doesn't hurt to check?), then an error is raised instead. Note that the error is raised somewhat late during validation, but that's when the validators are generated. We could create/cache them on `__init__` (maybe cache fields and validators?), but that seems like a separate discussion.
> Fix ModelSerializer unique_together handling for field sources

- rest_framework/__init__.py
- rest_framework/fields.py
- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
This merges the logic for `NullBooleanField`, which originally started off as a unique field, with the `BooleanField`. This reduces the repeated logic and removes the need for additional special cases. This also aligns with the recent changes within Django to discourage the use of `NullBooleanField`.
Fixes #6115
Closes #6116
> Merge NullBooleanField with BooleanField(allow_null=True)

- docs/api-guide/fields.md
- docs/api-guide/generic-views.md
- docs/api-guide/serializers.md
- docs/api-guide/validators.md
- rest_framework/schemas/generators.py
Since Python 2.7 has been dropped, the docs can be simplified and the unnecessary `object` base class removed as this is default behavior in Python 3.
> Remove unnecessary object class derive in docs

- rest_framework/compat.py
- rest_framework/fields.py
- tests/test_fields.py
> Remove compat for ProhibitNullCharactersValidator

- docs/api-guide/permissions.md
- docs/community/third-party-packages.md
`dry-rest-permissions` was no maintain since 2018 and communications with the maintener are broked since more than a year, so FJNR-inc just got a new PyPi version on their fork. I changed the URL available in DRF doc in order to correctly help DRF's users find this package.
> Update link to dry-rest-permissions

- rest_framework/authtoken/admin.py
- rest_framework/authtoken/models.py
Closes #6131.
* Adds a proxy model for Token that uses the user.pk, rather than it's own.
* Adjusts Admin to map back from User ID to token instance.
Proof of concept. Works but...
* Needs some unit tests. 
* Could do with testing against a custom user model. 
Thoughts?
> Adjusted token admin to map to user ID.

- docs/api-guide/schemas.md
~~**DRAFT**~~ I'll finish it over the next ~~few days~~ couple of months. (My word: not had a moment since this pandemic struck here in earnest.) 🗿
OK, done now. Explains the approach and covers the most important methods. Maybe we can add some of the lesser ones over time, but TBH folks'll see that when they're using the main ones, so it's not urgent for this pass, especially given lack of bandwidth now.
> Updates to Schema docs for 3.12

- docs/api-guide/fields.md
Changed `to_internal_value()` to `.to_internal_value()`
> Add missing dot when refer to_internal_value() in fields.md

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
Fixes #7204
`\Z` is `\z` for non-python regex implementation. See: https://stackoverflow.com/questions/53283160/the-z-anchor-not-working-in-python-regex
> Corrected regex serialization for OpenAPI. 

- rest_framework/viewsets.py
Use the current request's namespace to resolve action urls.
Use the current request's namespace to resolve action urls.
Fixes #7287
> Fix viewsets action urls with namespaces (#7287)

- rest_framework/test.py
This occurred when APIClient was used in the test code.
When the charset of the renderer is None, such as JSONRender, we will receive `application/json; charset=None` as the content-type of the request.
So I modified not to include the charset in the content-type if the charset of the renderer is None. As a result of the modified code, the content-type can receive `application/json`.
> Not include charset when charset is None

- rest_framework/serializers.py
- tests/test_serializer.py
- tests/test_serializer_lists.py
> Allow type checkers to make serializers generic

- rest_framework/urlpatterns.py
Functions `path` and `register_converter` are constants.
> urlpatterns: Remove unnecessary branching

- docs/api-guide/permissions.md
> Blacklist-whitelist is not a metaphor for lightness or darkness, it is a good-evil metaphor and therefore entirely based in racism.  This trope has significant impact on how people are seen and treated.
https://tools.ietf.org/id/draft-knodel-terminology-00.html
> Update an example to not use oppressive language

- rest_framework/request.py
The kwargs were renamed nearly 8 years ago in commit https://github.com/encode/django-rest-framework/commit/9d8bce8f5b0915223f57d9fe3d4b63029cfc64c2 but in the docstring.  Nobody ever noticed the mismatch.
There are also the newer (kw)args `negotiator` and `parser_context`.  Is it worth documenting them as well?
> Fix names of kwargs in docstring

- rest_framework/viewsets.py
- tests/test_viewsets.py
The extra `@action` rework is incompatible with some decorator patterns. For example:
```python
def decorate(fn):
def wrapper(self, request, *args, **kwargs):
return fn(self, request, *args, **kwargs)
return wrapper
```
The issue is that the `@action` rework looks up functions by their `__name__` instead of their actual attribute name on the viewset. Normally, this isn't an issue since the two coincide. In the mean time, the workaround is to use `functools.wraps`, which will correctly set the `__name__`.
```python
def decorate(fn):
@functools.wraps(fn)
def wrapper(self, request, *args, **kwargs):
return fn(self, request, *args, **kwargs)
return wrapper
```
Fixes #7097
> Check extra action func.__name__

- docs/topics/rest-hypermedia-hateoas.md
Fixed `cite` link (for *`REST fest 2012 keynote`*), linking to correct URL for Mike Amundsen's talk
> [docs] Fix link in rest-hypermedia-hateoas for Mike Amundsen's talk

- rest_framework/schemas/openapi.py
Perhaps the most useless PR ever, but I ran into this error as I was migrating to the new OpenAPI stuff as part of a Django 3 migration and figured I'd upstream the changes :)
> Fix typo (accros -> across)

- rest_framework/documentation.py
- rest_framework/routers.py
- rest_framework/urlpatterns.py
- rest_framework/urls.py
Hello, world! Please do not judge strictly, if i made a mistake. It is my first contribution to Open-source.
url() deprecated since version 3.1:
Alias of django.urls.re_path() for backwards compatibility.
> url()'s were replaced by path() and re_path()

- docs/api-guide/renderers.md
- docs/community/third-party-packages.md
[drf-ujson-renderer is no longer maintained (no commits  for 5 years)](https://github.com/gizmag/drf-ujson-renderer/issues/14). A fork of this library, [`drf_ujson2`](https://github.com/Amertz08/drf_ujson2) is actively maintained. This PR updates the documentation references to point to the new, maintained version of this library.
> Add drf_ujson2 reference

- rest_framework/fields.py
- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- tests/test_model_serializer.py
Django 3.1 adds a new generic JSONField to replace the PostgreSQL-specific one. This adds support for the new field type, which should behave the same as the existing PostgreSQL field.
Fixes #7466
> Add support for Django 3.1 JSONField

- rest_framework/authtoken/models.py
- tests/authentication/test_authentication.py
Simply adds a classmethod wrapper to Token.generate_key so that it can be called when the `save` method isn't (bulk_create, etc.)
Additionally adds a test to prove that access as a class method works without breaking access from self.
References https://github.com/encode/django-rest-framework/issues/7501
> Change Token.generate_key to a Classmethod

- requirements/requirements-codestyle.txt
- rest_framework/renderers.py
- rest_framework/utils/field_mapping.py
- tests/test_fields.py
This pull request increases `flake8` to version 3.8.3, and `pycodestyle` to 2.6.0. 
The new version of `flake8` raises a few new errors which I've also fixed.
> Bump flake8 to 3.8.3

- tests/conftest.py
- tests/schemas/test_coreapi.py
- tests/test_model_serializer.py
- tests/test_permissions.py
- tests/test_urlpatterns.py
This PR removes elements in the test suite which enabled compatibility with Django versions lower than 2.2.
> Updated tests -- Django 2.2 is minimum supported version

- .travis.yml
- README.md
- docs/index.md
- setup.py
- tox.ini
Run test against Python 3.9, mention compatibility and also add the trove classifier. Also mention Django 3.1 compatibility where missing.
3.9.0 final is [expected](https://www.python.org/dev/peps/pep-0596/#schedule) on Monday, 2020-10-05.  I'm pretty sure that Django 3.1 will gain Python 3.9 compatibility because the same thing happened for [Django 2.2 and Python 3.8](https://docs.djangoproject.com/en/3.1/releases/2.2/#python-compatibility).
I've no idea if Django 2.2 (the current LTS release) will gain Python 3.9 compatibility.  But I think it's unlikely that someone running an LTS release will switch to Python 3.9 soon. :shrug: 
Issue for Python 3.9 compatibility in Django: https://code.djangoproject.com/ticket/31040
> Run tests against Python 3.9

- rest_framework/pagination.py
- rest_framework/renderers.py
- rest_framework/serializers.py
- rest_framework/utils/urls.py
Since 3.5, it's possible to merge dictionaries with the `**` syntax.
When Python 3.9 is the minimum supported version (2024), we'll be able to do `validated_data = self.validated_data | kwargs `.
> Remove unnecessary type conversions

- docs/community/third-party-packages.md
Adding the Django API Client library as the third-party packages to the Misc list. Follows the library link below:
https://github.com/rhenter/django-api-client 
Or the documentation:
https://rhenter.github.io/django-api-client/
> Add Django API Client to the third party packages

- docs/api-guide/permissions.md
- docs/community/third-party-packages.md
Please checkout our extension for the Django REST framework.
https://github.com/drf-psq/drf-psq/
> Add drf-psq package to docs

- docs/api-guide/filtering.md
Make it more clear that `'django_filters'` needs to be installed into `INSTALLED_APPS` to help users avoid this common mistake: https://github.com/carltongibson/django-filter/issues/562#issuecomment-291035404
It's currently easy to breeze past that part in the docs because it is directly before a `pip install` step.
> Make it more clear to add django_filters to INSTALLED_APPS

- docs/coreapi/schemas.md
- docs/topics/documenting-your-api.md
Hi, i kindly ask that `drf-spectacular` is included besides `drf-yasg` in the third-party section for schema generation. 
Quite a few people use it in production already and I would call it reasonably mature by now. Thanks for considering.
> Add third-party schema library drf-spectacular to docs

- rest_framework/renderers.py
- rest_framework/templates/rest_framework/base.html
- rest_framework/templatetags/rest_framework.py
- tests/test_templatetags.py
We no longer need our `urlize_quoted_links` filter, since Django's `urlize` handles our use-case just fine, now.
> Drop urlize_quoted_links

- rest_framework/serializers.py
correct typo in  line 118 of serializer.py
from  **automagically** to **automatically**
> corrects typographical error in serializers.py 

- rest_framework/fields.py
The argument to Field is 'allow_null'.
> Fix NullBooleanField warning

- docs/tutorial/6-viewsets-and-routers.md
Currently in the documentation, it says :
`Viewsets [...] provide operations such as read, or update`
but the word `retrieve` is used for read operations in DRF.
Actually, from what I understand actions can take any custom name in Viewsets, but I think it would be cool to have consistent naming for this introductory sentence.
> Documentation: use retrieve instead of read for Viewset

- rest_framework/__init__.py
- rest_framework/authtoken/__init__.py
`default_app_config` is deprecated in Django 3.2. 
https://code.djangoproject.com/ticket/31180
> default_app_config application variable is deprecated in Django 3.2

- docs/topics/documenting-your-api.md
The changed links were not working on the documentation site. I'm not 100% sure that these changes are correct but they generate working links in the GitHub previews.
> Fix broken links in documenting API section

- docs/api-guide/schemas.md
Fixed error:
ERROR Internal Server Error: /v1/openapi.json
TypeError at /v1/openapi.json
Exception Value: get_schema() takes 1 positional argument but 3 were given
> Fix example override of SchemaGenerator.get_schema()

- rest_framework/authentication.py
- tests/test_request.py
Fixes #7417.
Fixes all these issues seen with `tox -e py38-django31`:
```
/Users/chainz/Documents/Projects/django-rest-framework/tests/test_request.py:208: RemovedInDjango40Warning: Passing None for the middleware get_response argument is deprecated.
SessionMiddleware().process_request(self.wrapped_request)
tests/test_requests_client.py: 1 test with warning
tests/test_testing.py: 4 tests with warnings
tests/test_throttling.py: 1 test with warning
tests/authentication/test_authentication.py: 4 tests with warnings
tests/browsable_api/test_browsable_api.py: 4 tests with warnings
/Users/chainz/Documents/Projects/django-rest-framework/rest_framework/authentication.py:139: RemovedInDjango40Warning: Passing None for the middleware get_response argument is deprecated.
check = CSRFCheck()
```
> Fix RemovedInDjango40Warning for middleware get_response()

- .travis.yml
This was added in #6139. However it seems [tox-venv is no longer maintained](https://github.com/tox-dev/tox-venv), the related [virtualenv issue has been closed](https://github.com/pypa/virtualenv/issues/355), and I suspect with the virtualenv rewrite fixed the problem with site.py and the warnings referred to for the DRF tests.
> Remove tox-venv from Travis setup

- rest_framework/authtoken/models.py
- tests/test_authtoken.py
Used the first of solutions @kalekseev proposed in https://github.com/encode/django-rest-framework/issues/7442#issuecomment-666264890
> Fix: authtoken.TokenProxy cannot be proxy when not installed #7442 

- rest_framework/exceptions.py
The test suite raises warnings when tested against Python 3.9.
`DeprecationWarning: NotImplemented should not be used in a boolean context`
In `__eq__` for `ErrorDetail` is where the warning is being raised. This is due to `r` potentially returning `NotImplemented`. This PR captures when this takes place and returns `NotImplemented` sooner.
> Return NotImplemented sooner for ErrorDetail equality test

- tox.ini
Erroring on deprecation or pending deprecation warnings means they are caught early. This will avoid the cycle of releasing with 'support for Django X', then chasing all the deprecation warnings one-by-one. Instead, when a new Django version is added to the test matrix, it will fail until all the relevant warnings are fixed. This avoids passing these warnings on to users, some of whom don't upgrade until they are all fixed.
> Error on deprecation and pending deprecation warnings

- docs/api-guide/serializers.md
Add missing quoting for `data` keyword argument in serializer doc
> Add missing quoting for `data` keyword argument in serializer doc

- docs/api-guide/relations.md
> Add docs link to to_internal_value()

- docs/api-guide/fields.md
- docs/api-guide/serializers.md
This is a simple fix on a headline line 4 that was not rendering properly.
> Fixed some documentation headings to use a space

- rest_framework/relations.py
In the `to_internal_value` method of the primary key and slug related fields, `TypeError`s and `ValueError`s are caught from `self.get_queryset().get(...)` and presented to the user. This works fine for most cases, but can cause problems if the exception is coming from `self.get_queryset()` rather than from the `.get(...)`.
It means errors in the `get_queryset` method can be hidden and presented back to the user as though, for example, the input provided to the `to_internal_value` was the wrong type, whereas in reality there's a bug in the `get_queryset` method and therefore it should bubble up and be exposed as a server error.
I've decided to fix this because twice now I've had to debug why I'm seeing `invalid_type` errors from my serializer (errors like `wrong pk type - int` when the …
> Don't catch exceptions in get_queryset

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
If the BrowsableAPIRenderer has been subclassed, it wouldn't be correctly ignored by the OpenAPI Schema generator.
Fixes #7477
> Ignore derivations of BrowsableAPIRenderer in OpenAPI schema

- requirements/requirements-optionals.txt
- tests/test_description.py
Markdown version 3.3 changes the whitespace of the output. 
Looking at the failing test it is suited to pass on multiple versions of Markdown. However, the tests are only run against the pinned dependency. Therefore I've simplified the test to only test against this one version. 
Secondly, I've also added a `pytest` skip mark so it skips the test 'loudly'. 
Final note, and more of a question really, most of the tests here are under a class which is subclass from `TestCase` however, all of the tests are written `pytest` style. Is there a reason for this, I guess it allows categorisation of the tests?
> Bumped Markdown version to 3.3

- docs/api-guide/viewsets.md
> Fix #7612 (`data` used instead of `validated_data` in API guide)

- docs/api-guide/throttling.md
There were recent updates to the `@action` decorator calling a little more attention to the kwargs it accepts. 
I thought it would be useful to also provide an example in the throttling section of how those kwargs can be used to define/override throttle_classes through the action decorator as well.
> Update throttling.md to provide context for granular throttling control through the action decorator

- docs/api-guide/parsers.md
- docs/api-guide/requests.md
This documents the return type of `JSONParser`, modifies the `request.data` wording in the Parsers page and links to JSON and form parsers.
refs #7633
> docs: outline the difference between JSON and form parsers. Fix #7633

- docs/api-guide/renderers.md
This partially addresses #5236 to clarify that the response from a view may need to be modified to provide TemplateHTMLRenderer with a dict for it to use.
I do not completely understand the issue in #5236 so the wording could possibly be improved.
>  Clarify documentation for TemplateHTMLRenderer

- rest_framework/exceptions.py
- tests/test_validation_error.py
This PR changes the behavior of ValidationError slightly. Previously when handling details passed into the constructor, e.g. `ValidationError(detail=('message1', 'message2')) tuples got converted to strings.  This means that the resulting JSON in the response looked similar to
1)
```
"error": "('message1', 'message2')"
```
instead of
2)
```
"error": ["message1", "message2"]
```
which one might expect.
The described behavior might be unintuitive users. This is why after this PR would be merged, tuples would get the same treatment as lists in this regard, ergo result in outcome 2 instead of 1.
> Handle tuples same as lists in ValidationError detail context

- docs/api-guide/authentication.md
> Jazzband became the maintainers of DOT

- rest_framework/views.py
- tests/conftest.py
- tests/test_atomic_requests.py
When using https://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-DATABASE-ATOMIC_REQUESTS, django wraps each invoked view with transactions to _all databases_ (https://github.com/django/django/blob/master/django/core/handlers/base.py#L323-L330). https://github.com/encode/django-rest-framework/pull/2887 resolved https://github.com/encode/django-rest-framework/issues/2034 _for the default database, only_.
In particular, https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L67-103 does not handle the fact that multiple transactions can be created by django. This PR adds a unit test and associated fix to ensure DRF rollsback all transactions setup by django for ATOMIC_REQUESTS rather than just the default db's transaction.
Added unit tests. Fail with …
> support multi db atomic_requests

- docs/api-guide/exceptions.md
A very minor edit that provides an example for the use of a dictionary as the detail argument of a ValidationError.
> Provide example for dict in ValidationError detail

- docs/topics/documenting-your-api.md
Have options example in documenting-your-api.md to return a Response
It was returning data which is not correct. Closes #7638.
> Have options example in documenting-your-api.md to return a Response

- docs/api-guide/permissions.md
Updating docs for DjangoModelPermissions. Sentinel querysets not needed after v3.1.2
Closes https://github.com/encode/django-rest-framework/issues/7659
> Docs: DjangoModelPermissions works on views with get_queryset() method.

- rest_framework/templates/rest_framework/filters/search.html
Missing `trans` in the template for `SearchFilter`
> Overlooked translation in search.html

- docs/community/release-notes.md
Closes https://github.com/encode/django-rest-framework/issues/7703
Adding the `detail_route` and `list_route` deprecations to the 3.10.x release notes. Let me know if I need to update the format at all.
> #7703 adding deprecations to release notes

- rest_framework/fields.py
- tests/test_fields.py
Closes #7721 
* Handle None in to_representation()
* Return None as '' in to_representation() when coerce_to_string=True
* Handle '' as None in to_internal_value(), for symmetry with
to_representation(), and because the empty concept doesn't make sense
for Decimal.
The main fix is the handling of None in to_representation(), but I'm not sure the handling of coerce_to_string makes sense, so I'm definitely open to discussion here.
> Respect allow_null=True on DecimalFields

- docs/api-guide/caching.md
add an example base on `vary_on_headers`， and  allowed it  to use auth(token) to cache.
> Add example for caching

- docs/api-guide/authentication.md
- docs/community/third-party-packages.md
This pull request adds [django-rest-authemail](https://github.com/celiao/django-rest-authemail) to Third Party Packages, under Authentication.
[django-rest-authemail](https://github.com/celiao/django-rest-authemail) supports and is tested with Python 3.6/3.7/3.8, Django 2.2.8/2.2.13/3.0/3.1, and Django REST Framework 3.11.0.
[django-rest-authemail](https://github.com/celiao/django-rest-authemail) can be found on PyPi [here](https://pypi.org/project/django-rest-authemail/).
[django-rest-authemail](https://github.com/celiao/django-rest-authemail) can be found on the [Django REST Framework grid](https://djangopackages.org/grids/g/django-rest-framework/) on Django Packages [here](https://djangopackages.org/packages/p/django-rest-authemail/).
> Add django-rest-authemail to Third Party Packages

- docs/topics/api-clients.md
> Actually use the loginUser arguments in the example

- rest_framework/pagination.py
Even if  I do not request pagination in HTTP-query `LimitOffsetPagination` still calls self.get_count(queryset) which results in an extra `SELECT count(*) FROM ...`. This becomes important if the query itself is comparatively heavy. Let's fix it by checking if pagination is requested first.
The pull request was not tested. Please, consider it as an issue report with proposed solution.
P.S.:
Here is my log before
```
2018-07-27 10:53:09,741 DEBUG django.db.backends (0.350) SELECT COUNT(*) FROM (SELECT "core_agent"."id" AS Col1, (COALESCE(EXTRACT(EPOCH FROM now() - last_online_dt) < 30, False)) AS "is_online_db" FROM "core_agent" WHERE ("core_agent"."user_id" = 14 AND "core_agent"."is_hidden" = false AND "core_agent"."id" IN (SELECT DISTINCT U0."source_id" AS Col1 FROM "core_ping" U0 INNER …
```
> Do not do `SELECT count(*) FROM ...` if pagination is not requested

- rest_framework/renderers.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
> Fix OpenAPISchema rendering for timedelta

- rest_framework/pagination.py
refs [Allow 'get_page' method for overriding ](https://github.com/encode/django-rest-framework/pull/7626)
> Allow 'get_page' method for overriding #7626

- docs/api-guide/permissions.md
Clarifying a sentence on how the default permission classes are overridden.
> Make the doc on overriding the default permission classes more clear.

- docs/community/third-party-packages.md
`django-extra-fields` is renamed to `drf-extra-fields` a while ago. To be consistent, I have renamed it in this PR.
> Rename django-extra-fields to drf-extra-fields

- docs/api-guide/permissions.md
This documentation update clarifies a common and unexpected issue with object level permissions through permission classes in that they don't apply at all to create actions. A previous issue would be #6409
My use case was that I had Users within Organizations and they should only be allowed to view, create or update certain objects within their organizations. The current documentation was not clear that custom permissions `.check_object_permissions()` would only apply to modification, and not to creation. (The limitation with listing was documented.)
---
**Note:** This pull request contains two commits: The first is a simple warning at the appropriate place and should IMHO be included in any case. The second is a more complete treatment of the different ways REST framework can restrict …
> Document object level permissions gotchas

- rest_framework/fields.py
- rest_framework/utils/serializer_helpers.py
- tests/test_bound_fields.py
Fixes bugs related to nested JSONField `as_form_field` rendering.
Closes #6211
> Render JSON fields with proper indentation in browsable API forms.

- rest_framework/filters.py
- tests/test_filters.py
- A model property called `description` added to the `OrderingFilterModel`
- Created `OrderingFilterSerializerWithModelProperty` which includes all fields of `OrderingFilterModel` and the model property `description`.
- Failing test has been added under `test_ordering_without_ordering_fields` with two passing `assert` statements to see using model properties on a serializer with `OrderingFilter` doesn't have any side effect.
- A solution has been added to `OrderingFilter.get_default_valid_fields()` method which basically checks if the ~`field_name` or `field.source` is in `model_field_names`~ `field.source` is in `model_property_names` (c7f8b14).
> Ordering filter bug with model property serializer field

- docs/tutorial/5-relationships-and-hyperlinked-apis.md
A tiny fix to tutorial part 5. "Too" was incorrectly being used where "to" was intended.
> Correct the use of "to" in tutorial documentation

- rest_framework/templates/rest_framework/base.html
- tests/test_templates.py
HTML responses generated by the Browsable API otherwise generate
inconsistent ETAGs -- due to the presence of CSRF tokens in the response
-- even when the API is read-only, (and as such when the response
contains no resource-modifying forms, i.e. neither POST nor PUT forms,
which might require the CSRF token).
While the template was appropriately including CSRF tokens only within
POST and PUT forms, its AJAX overlay included the CSRF token in *every*
response, regardless of whether it would be needed.
This change brings the logic of the `script` block into line with that
of the rest of the template -- and such that read-only APIs (and really
the Browsable API pages of *any* read-only resources) will not
needlessly include the CSRF token, and will now be safely cachable -- by
both back-end …
> made Browsable API base template cachable: omit CSRF token when unnecessary

- docs/api-guide/filtering.md
Since `query_params` is as same as `QueryDict` which uses `None` as default return value, we don't need to explicitly set `None`, especially in the official document which would mislead the users.
> Docs tweak

- rest_framework/relations.py
- tests/test_relations.py
In case maintainers intend to explicitly forbid `bool` values for `PrimaryKeyRelatedField` lookup.
Closes https://github.com/encode/django-rest-framework/issues/7542
> Reject PrimaryKeyRelatedField bool lookup values

- rest_framework/authtoken/models.py
When using nplusone middleware from https://github.com/jmcarp/nplusone, the error occurs if one tries to access Token app in django admin. 
This happens due to recursive DB calls, as the user `id` is accessed through the `user` object rather than through `user_id` field. 
Not sure if it's a problem of DRF itself, but the following change fixes the problem as well as reduces DB hits.
https://github.com/jmcarp/nplusone/issues/38
> Don't hit db to access user_id in TokenProxy

- docs/api-guide/fields.md
This PR will update the code in the example below ([as seen in the docs](https://www.django-rest-framework.org/api-guide/fields/#serializermethodfield)), which will throw the following error if run:
> AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the AlbumSerializer serializer.",)
```
from django.contrib.auth.models import User
from django.utils.timezone import now
from rest_framework import serializers
class UserSerializer(serializers.ModelSerializer): …
```
> update SerializerMethodField example in docs

- rest_framework/throttling.py
Currently, a list object, `self.history`, is used for storing request history.
`self.history.insert(0, self.now)` in function `throttle_success` and `self.history.pop()` in function `allow_request`, are used to insert and remove request history, respectively.
If deque is picked, we would have fast insertion and removal at both ends.
Please see the information below for more details about [deque](https://docs.python.org/3/library/collections.html#collections.deque).
> Though [list](https://docs.python.org/3/library/stdtypes.html#list) objects support similar operations, they are optimized for fast fixed-length operations and incur O(n) memory movement costs for `pop(0)` and `insert(0, v)` operations which change both the size and position of the underlying data representation.
Would it be …
> pick deque instead of list

- docs/community/release-notes.md
- rest_framework/__init__.py
Date: 25th March 2021
* Properly handle ATOMIC_REQUESTS when multiple database configurations are used. [#7739]
* Bypass `COUNT` query when `LimitOffsetPagination` is configured but pagination params are not included on the request. [#6098]
* Respect `allow_null=True` on `DecimalField`. [#7718]
* Allow title cased `"Yes"`/`"No"` values with `BooleanField`. [#7739]
* Add `PageNumberPagination.get_page_number()` method for overriding behavior. [#7652]
* Fixed rendering of timedelta values in OpenAPI schemas, when present as default, min, or max fields. [#7641]
* Render JSONFields with indentation in browsable API forms. [#6243]
* Remove unnecessary database query in admin Token views. [#7852]
* Raise validation errors when bools are passed to `PrimaryKeyRelatedField` fields, instead of …
> Version 3.12.3

- docs/community/release-notes.md
- rest_framework/__init__.py
Date: 26th March 2021
* Revert use of `deque` instead of `list` for tracking throttling `.history`. (Due to incompatibility with DjangoRedis cache backend.) [#7849]
> Version 3.12.4

- tests/test_description.py
The pygments rendering of invalid json changed in  pygments>=2.7.3
Fixes issue seen in https://github.com/encode/django-rest-framework/pull/7589#issuecomment-803471199
> Fixed markdown test

- requirements/requirements-codestyle.txt
- requirements/requirements-documentation.txt
- requirements/requirements-optionals.txt
- requirements/requirements-packaging.txt
- requirements/requirements-testing.txt
- tests/test_status.py
- tests/test_validators.py
I've bumped all the dependency versions with the exception of Markdown. Bumping that version causes a test fail (separate PR incoming shortly). 
The main change here is bumping Pytest to version 6.
> Updated dependencies

- .github/workflows/pre-commit.yml
- .gitignore
- .pre-commit-config.yaml
- .travis.yml
- docs/community/contributing.md
- requirements.txt
- requirements/requirements-codestyle.txt
- runtests.py
- tox.ini
Following [my comment here](https://github.com/encode/django-rest-framework/pull/7589#issuecomment-813301322) and [Django's own move to pre-commit](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#pre-commit-checks).
* Add pre-commit config file to run flake8 and isort.
* Add extra "common sense" hooks.
* Run pre-commit on GitHub actions using the [official action](https://github.com/pre-commit/action/). This is a good way to get up-and-running but it would be better if we activated [pre-commit.ci](https://pre-commit.ci/), which is faster and will auto-update the hooks for us going forwards.
* Remove `runtests.py` code for running linting tools.
* Remove `runtests.py --fast` flag, since that would now just run `pytest -q`, which can be done with …
> Lint with pre-commit

- .pre-commit-config.yaml
See: https://twitter.com/codewithanthony/status/1378746934928699396
> Update pre-commit for flake8 move

- .github/workflows/main.yml
The config I copied in #7903 was from a repo with the new name 'main', so tests have not been running on master since.
> Fix GitHub Actions to run on 'master' branch

- tests/test_fields.py
Django no longer checks for `hasattr(timezone, 'localize')` and instead does an inheritance check:
https://github.com/django/django/blob/da542ccab6d61e1467199b52f77f64a2d72f5faf/django/utils/timezone.py#L259-L261
> Fix tests with mock timezone

- setup.cfg
* Use `--strict-markers` instead of `--strict`, as per this warning:
```
/.../_pytest/config/__init__.py:1183: PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
```
* Remove config option 'testspath' - pytest is logging a warning about this being unknown:
```
/.../_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: testspath
```
I can't find any reference to it in the pytest docs or changelog.
> Fix pytest warnings

- requirements/requirements-packaging.txt
Hi :wave: 
first of all big thanks for developing such an awesome package! 
I was going through [Contributing guide](https://www.django-rest-framework.org/community/contributing/#testing) and for the following command:
```bash
pip install -r requirements.txt
```
I have got this error:
```
ERROR: Could not find a version that satisfies the requirement transifex-clien<0.14,>=0.13.12
ERROR: No matching distribution found for transifex-clien<0.14,>=0.13.12
```
This PR simply fixes typo in the`transifex-client` package name ;)
> fix typo in packaging requirements

- runtests.py
Regression in aa12a5f967705f70b1dbe457bb2396d106e3570b.
```bash
$ ./runtests.py 
File "./runtests.py", line 49, in <module>
sys.exit(pytest.main(pytest_args))
NameError: name 'pytest_args' is not defined
```
> Fix running runtests.py without arguments.

- rest_framework/static/rest_framework/docs/css/base.css
these intended comments were causing errors in sonarqube scans due to using wrong css comment syntax
> fix comments by using correct css comment syntax

- README.md
- docs/index.md
The project works and has been tested under Django version 3.2, but the documentation did not reflect this, yet. I added version 3.2 to the supported versions both in the `README.md` and the `docs/index.md` files.
This pull request closes `refs #7993` (#7993) and `refs #7944` (#7944).
> Update documentation to include Django 3.2 as supported version

- requirements/requirements-optionals.txt
- setup.py
- tox.ini
> Stop ignoring test outcome for Django 3.2

- docs/api-guide/serializers.md
Some headers were using `.`, some - were not.
Now, all of them are the same with `.`, because it was easier to fix.
> Fixes inconsistent headers in `serializer` docs

- rest_framework/fields.py
- tests/test_fields.py
Closes #8064 
When `DecimalField (allow_null=True)` has Max or Min validators , validation crashes on empty strings like '' and ' '.
Added a fix covered with a test.
> Fix empty string as a value for a validated DecimalField (#8064)

- rest_framework/serializers.py
- tests/schemas/test_openapi.py
Propagate the nullability of underlying model fields in ModelSerializer
when those fields are marked as read only. This ensures the correct
generation of OpenAPI schemas.
Closes #8041.
cc @canassa @kevin-brown
> Propagate nullability in ModelSerializer

- rest_framework/fields.py
- tests/test_fields.py
This PR makes the Field constructor keyword-only by adding a `*` (and turning `*args, **kwargs` into just `**kwargs` in subclasses). I don't believe anyone is (or should be) constructing fields as `serializers.CharField(False, True, False, serializers.empty, ...)`
The root issue this fixes is the nonobvious problem in e.g.
```python
aliases = serializers.ListField(serializers.CharField(), default=list)
```
– you wouldn't expect that yields a non-validated read-only list field, would you? 😄 What happens is the positional `serializers.CharField()` argument gets passed up into the `serializers.Field()` call as the first argument, which just so happens to be `read_only`, and the field instance is a truthy value...
/cc @magdapoppins for having initially bumped into this issue.
> Make Field constructors keyword-only

- docs/index.md
Do we have another IRC logger somewhere?  Is Botbot logging Libera.chat?
Signed-off-by: Paul Wayper <paulway@redhat.com>
> Botbot has been acquired, all paths now point to startupresources

- README.md
- docs/index.md
Signed-off-by: Paul Wayper <paulway@redhat.com>
> We now use Libera.chat rather than Freenode for IRC

- docs/tutorial/1-serialization.md
Before it was linking to a fork of a fork of httpie. I've changed it to the right URL.
> Use correct link for httpie

- docs/community/third-party-packages.md
The django-rest-auth package is outdated and unmaintained.
dj-rest-auth is the continuation of the project. So it is better to have an up to date link.
See https://github.com/encode/django-rest-framework/discussions/8141
> Replacing django-rest-auth with dj-rest-auth

- docs/api-guide/authentication.md
Grammatical Error
Corrected to `always runs`
> Fix: Grammatical Error in `api-guide/authentication`

- rest_framework/throttling.py
This pull request is to fix the wording issue on SimpleRateThrottle Docstring
This was discussed there -> #8143
> fix: change View class to Throttle class on SimpleRateThrottle Docstring

- docs/tutorial/quickstart.md
`path()` has no argument `namespace`, it has `name` argument
Raises `TypeError: _path() got an unexpected keyword argument 'namespace'`, \
argument should be changed to `name`
> Fix arguments of `path()`

- docs/api-guide/serializers.md
- rest_framework/serializers.py
- tests/test_serializer_lists.py
I needed to restrict the amount of elements within a `ListSerializer` (to prevent big and long requests).
I initially implemented this in a "per field" validation but I thought it could be implemented like the already existing `allow_empty` option.
> Add max_length and min_length options to ListSerializer

- docs/api-guide/fields.md
- rest_framework/test.py
- setup.py
- tests/authentication/test_authentication.py
- tests/conftest.py
- tests/test_fields.py
- tests/test_testing.py
- tox.ini
Adds compatibility for Django 4.0. 
[From Django 4.0 `zoneinfo` is the default time zone implementation](https://docs.djangoproject.com/en/dev/releases/4.0/#zoneinfo-default-timezone-implementation). This PR makes the minimum changes to work with that, plus other necessary adjustments.  
DRF now requires `pytz` in `install_requires`. There's a small amount of work to be done in `fields.py` and `test_fields.py` to remove the `pytz` dependency. (Django will remove support for `pytz` in Django 5.0.)
> Django 4.0 compatibility

- docs/api-guide/fields.md
- docs/api-guide/generic-views.md
- docs/api-guide/relations.md
Hi, I have tried to update documentation to cover details about possible n+1 problems and how to avoid them. I think this should close the documentation ticket #1977
> Highlight `select_related` and `prefetch_related` usage in documentation

- docs/api-guide/testing.md
This PR fixes some minor typos in the docs.
> docs (api-guide/testing.md): Fix typo 'CRSF' -> 'CSRF', use plural in the expression 'a few core pieces'

- docs/api-guide/pagination.md
Fix broken link to GitHub REST API documentation: https://docs.github.com/en/rest/guides/traversing-with-pagination
> Docs: Pagination API Guide: fix broken link to GitHub docs

- docs/tutorial/quickstart.md
Right now httpie moved to "httpie" organization (https://github.com/httpie/httpie) and they don't have "installation" at their GitHub. Instead of that, they have "Getting started" section with link to "Installation instructions".
> Fix link to installation of httpie

- docs/topics/ajax-csrf-cors.md
Ownership of this project was transfered a while ago: https://github.com/adamchainz/django-cors-headers/issues/110
> Update django-cors-headers links

- docs/api-guide/viewsets.md
- docs/community/3.9-announcement.md
Documentation change to keep up with the code permission changes.
> Docs: IsAdmin permissions changed to IsAdminUser

- docs/api-guide/permissions.md
I might just be misunderstanding something (always a strong possibility!), but it seems to me that the table on the Permissions page is slightly inaccurate.
For `permission_classes`, wouldn't it have global-level permissions for list actions (rather than no permission control, as is currently listed)?
> Docs: Fix minor issue with permissions table

- rest_framework/renderers.py
We've noticed that `UNICODE_JSON` setting doesn't affect schema `json`. 
But this suppose to be useful.
This PR makes `CoreAPIJSONOpenAPIRenderer` and `OpenAPIRenderer` behave as `JSONRenderer`.
> Made api_setting.UNICODE_JSON/ensure_ascii affecting json schema

- docs/coreapi/7-schemas-and-client-libraries.md
- docs/coreapi/from-documenting-your-api.md
- docs/coreapi/index.md
- docs/coreapi/schemas.md
Include deprecation notice in pages related to coreapis. refs #7932
Please do tell me if I need to make any changes. Thanks!
> Update docs related to coreapi to include deprecation notice

- README.md
- docs/index.md
- setup.py
- tox.ini
> Test Django 4.0

- setup.py
Just a left-over from #8288 to sync the "Unsupported Python version" message with `python_requires`.
> Fix `REQUIRED_PYTHON` in setup.py

- rest_framework/decorators.py
- tests/test_decorators.py
When using Django 4, we get slightly unexpected behaviour using the `api_view` decorator:
```
@api_view(["POST"])
def some_view(request):
pass
```
```
>>> some_view.__name__
'some_view'
>>> some_view.__qualname__
'WrappedAPIView'
```
```
>>> some_view.__name__
'view'
>>> some_view.__qualname__
'View.as_view.<locals>.view'
```
This change is caused by a change in the way that Django 4 implements `View.as_view()`. [The change and a full discussion can be viewed here](https://github.com/django/django/pull/14124), but in short: `as_view` used to use `update_wrapper` and now it doesn't.
I was definitely for the change above, and argued against using `update_wrapper` in that case, but for a decorator such as `api_view` it is definitely appropriate, and I would expect things like `__name__` and …
> Fix api_view decorator with Django 4

- rest_framework/pagination.py
The CursorPagination's cursor query parameter expects a string and not
an integer.
This fixes issues where a valid cursor is rejected due to an incompatible type in the schema.
refs #7691
> Fix CursorPagination parameter schema type

- rest_framework/decorators.py
- tests/test_decorators.py
Reverts encode/django-rest-framework#8291
> Revert "Fix api_view decorator with Django 4"

- docs/api-guide/serializers.md
In "Specifying fields explicitly" https://github.com/encode/django-rest-framework/blob/master/docs/api-guide/serializers.md#specifying-fields-explicitly paragraph from the docs, the code example provided was missing the `fields` meta argument, which is mandatory from `3.3.0`. 
The assertion error was: `Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the CalendarTaskSerializer serializer.`
> Fixed missing "fields" meta argument in docs

- rest_framework/utils/serializer_helpers.py
- tests/test_serializer.py
Fixes issue #8301
For tests, as there were no other direct tests of `ReturnDict`, I thought it best to consider this as an implementation detail of `Serializer`, and just added it to the serializer tests.
As the union operator was added in PEP 584 for Python 3.9, I think it makes most sense to only add this support for Python 3.9 upwards.
One decision made here is that the union operator, both for left hand and right hand versions, produces a `ReturnDict`, instead of just an `OrderedDict` or a `dict`. My rationale is as follows:
If you do:
```python
d = serializer_instance.data
d |= other_data
```
then `d` ends up as an instance of `ReturnDict`. If you refactored this to:
```python
d = serializer_instance.data | other_data
```
you would probably expect it to stay the same type. Also, …
> Make ReturnDict support dict union operators on Python 3.9 and later

- docs/api-guide/format-suffixes.md
urlpatterns name variable name in space remove.
> Correct variable name in docs/api-guide/format-suffixes.md

- docs/api-guide/filtering.md
In the documentation, postgres search link points to the development environment, and gives warning:
> This document is for Django's development version, which can be significantly different from previous releases. For older releases, use the version selector floating in the bottom right corner of this page.
Changes in the PR will point the link to stable documentation. Also changes made according to the [reference style](https://www.django-rest-framework.org/community/contributing/#2-links) guidelines.
> Documentation : Reference link points to stable version.

- docs/topics/internationalization.md
The `MIDDLEWARE_CLASSES` setting got changed to `MIDDLEWARE` in [Django 1.10](https://docs.djangoproject.com/en/1.10/topics/http/middleware/).
> Change `MIDDLEWARE_CLASSES` to `MIDDLEWARE`

- rest_framework/decorators.py
> Minor code cleanup

- docs/api-guide/renderers.md
Fixes a disconnect between the documentation of custom Renderers and the implementation in the DRF source code.
In the documentation, the `render` function is described as taking a `media_type` argument. However, in the majority of Renderers provided by DRF the argument is named `accepted_media_type`.
This PR brings the documentation more in line with how DRF internally implements Renderers.
Note: There are actually inconsistencies in DRF's own code with the argument. Most of them use `accepted_media_type`, however there are a couple that use `media_type`. I have not made any changes to those Renderers to fix this …
> Update `accepted_media_type` argument in Renderer docs

- docs/api-guide/renderers.md
We've renamed the drf-renderer-xlsx package to drf-excel. This updates the documentation.
> We've renamed the drf-renderer-xlsx package to drf-excel.

- README.md
Hi there,
The code block below show imply `Python` as it lives in `settings.py`
```
INSTALLED_APPS = [
...
'rest_framework',
]
```
This pull request essentially fixes that.
Sorry if i didn't discuss it on a discussion thread. As its a very minor issue. I think it can be resolved without any discussion.
> Fix code block in `README.md`

- SECURITY.md
Following on from discussion with the Django team. I believe our shared outlook is that security issues are better handled by the Django security team, than via the existing route. This change will ensure more comprehensive oversight and transparency around resolving security issues.
See also #8411
> Update SECURITY policy

- docs/api-guide/testing.md
Changes contains following :
- Link added for Test Case Classes to point to [Provided test case classes](https://docs.djangoproject.com/en/stable/topics/testing/tools/#provided-test-case-classes) of Django Docs
- Correction of link for `Refresh from DB docs` from version `1.11` to `stable` version.
> Link added for Test Case Classes and corrected stable link for Refresh from DB

- docs/api-guide/authentication.md
I am updating the authentication list of libraries as django-rest-framework-social-oauth2 is not a maintained library anymore.
> docs: include drf-social-oauth2 to docs.

- .github/stale.yml
Add a StaleBot, configured with the lowest possible run limit.
The intent here is to help us sweep through the issue and pull request backlog, and review what does and does not need to remain open at this point in time.
> Add StaleBot

- rest_framework/test.py
- tests/test_testing.py
Integrate with changes from https://github.com/django/django/commit/272f685794de0b8dead220ee57b30e65c9aa097c.
Closes #8406.
> Added test client support for HTTP 307 and 308 redirects

- docs/api-guide/relations.md
While reading the docs, I noticed a confusing phrase, and realized it could confuse non-native English readers. It seemed like the phrase should be _fetch a related object_ or _fetch related objects_. After consulting my co-worker @williln, our resident language expert, I went with the 2nd option.
> corrected grammar to improve clarity

- docs/api-guide/throttling.md
As discussed in #5181, the least we can do about race conditions in throttling is note that they are in fact possible.
> docs: Add a note on concurrency and races

- docs/api-guide/fields.md
fix: Documentation did not point out that the default value of `required`
`Field` parameter is `False` depending on Django's `Model.field`.
This is a continuation of https://github.com/encode/django-rest-framework/pull/7222.
The rationale of my PR is this part of the code: https://github.com/encode/django-rest-framework/blob/b1004a47334a0dd1929e6d50b8f7ff6badc959f4/rest_framework/utils/field_mapping.py#L104
> Update description of docs/api-guide/fields.md -> required

- docs/api-guide/authentication.md
- requirements/requirements-documentation.txt
* Recommend Django REST Knox directly in the `TokenAuthentiction` docs, since it provides a better implementation for the use-case.
* Push Django REST Knox to the top of the third party packages.
* Few docs formatting tweaks to make the new note stand out more clearly.
> Recommend Django REST Knox

- docs/community/third-party-packages.md
Added [django-requestlogs](https://github.com/Raekkeri/django-requestlogs) in third party packages. django-requestlogs hooks into the Django REST framework in the simplest way possible while logging every request without the need of remembering to enable it for each view separately.
> Added django-requestlogs in third party packages

- rest_framework/fields.py
- tests/test_fields.py
The issue that this MR trying to fix, was described in the other MR that was not finished https://github.com/encode/django-rest-framework/pull/8318 
I faced the same problem, python spend most of the time in larges serializers with a lot of nested objects in `is_simple_callable`. 
Based on your comments in mentioned MR, this MR contains only a 2 lines of code to fix this issue. 
Here an example of code ( this issue effect almost all fields types):
```python
from timeit import timeit
from rest_framework import serializers
class Comment:
def __init__(self, email, number=0):
self.email = email
self.number = number
class CommentSerializer(serializers.Serializer):
email = serializers.CharField()
number = serializers.IntegerField()
comments = [Comment(email='leila@example.com') for _ in …
```
> Improve performance for noncallable attributes

- docs/api-guide/schemas.md
This solves an issue I ran into when following the docs to customize schema creation. You also have to add `public` when you subclass `SchemaGenerator`.
> Update get_schema in docs

- rest_framework/utils/field_mapping.py
- tests/test_validators.py
The same as #3435, but for relation.
Use error_messages from model instead of the default UniqueValidator message.
> Respect model error_messages for relation

- docs/tutorial/6-viewsets-and-routers.md
Correction on an example that errors. HyperlinkIdentityFields in serializers reference 'snippet-highlight' and 'snippet-detail', router basenames updated to match.
> Docs: Removed pluralisation from basenames

- tests/test_fields.py
`QueryDict` takes a `str` argument. But this makes no difference in practice. Discovered while working on djangorestframework-stubs.
> Fix QueryDict type error in test

- rest_framework/templatetags/rest_framework.py
As of now, relative URLs are not clickable. This creates problems for some users who can't rely on the request's host to generate absolute URLs.
Very relevant:
https://github.com/encode/django-rest-framework/discussions/8460
https://stackoverflow.com/questions/64022460/drf-how-to-render-relative-urls-as-hyperlinks-in-the-browsable-api
https://stackoverflow.com/questions/71839932/django-rest-framework-how-to-make-relative-urls-clickable
Somehow relevant:
https://stackoverflow.com/questions/70092287/changing-url-path-of-api-in-django-rest-framework
https://stackoverflow.com/questions/62421753/how-to-change-the-host-in-next-key-in-a-paginated-url-in-django-rest-framework
https://stackoverflow.com/questions/34231393/how-to-change-the-django-rest-frameworks-default-url-to-a-custom
This change …
> Made relative URLs clickable as well.

- requirements/requirements-optionals.txt
- tests/test_description.py
> Update docstring test for more recent pygments version

- rest_framework/fields.py
If you set a custom timezone for a DateTimeField, the function
self.default_timezone() is still called, since fallback params to
getattr are still evaluated.
This rewrites to use hasattr, so the fallback case is only executed if
it will actually be used. If you render a lot of DateTimeFields in a
serializer, the time spent evaluating default_timezone() once for each
of them can accumulate to quite a bit, which is just unused work in the
case where timezone is already specified on the field.
> Don't evaluate default_timezone unless needed

- rest_framework/throttling.py
Fix "`" typo in Throttle comments
> Fix "`" typo in Throttle comments

- rest_framework/throttling.py
While trying to remove the Django authentication module, I've ran into an error when using the configuration below.
Specifically, an `AttributeError` is raised because DRF does not expect the user to be `None`.
```python
REST_FRAMEWORK = {
...
"DEFAULT_THROTTLE_CLASSES": (
"rest_framework.throttling.AnonRateThrottle",
),
"DEFAULT_THROTTLE_RATES": {"anon": "10000/day"},
'DEFAULT_AUTHENTICATION_CLASSES': [],
'DEFAULT_PERMISSION_CLASSES': [],
'UNAUTHENTICATED_USER': None,
}
```
This PR fixes the issue by checking if `request.user` is set before proceeding with further authentication checks.
The test suite and pre-commit hooks are passing. If needed, I'll be happy to write a test-case for this.
As this is my first contribution to DRF please let me know in case I am missing any contribution …
> Fix error in throttling when request.user is None

- rest_framework/utils/field_mapping.py
Move null attr check before return for read-only fields. While as of now it doesn't break anything, it leads to incorrect API schema generation when using drf-spectacular(https://github.com/tfranzel/drf-spectacular/issues/383) or drf-yasg(https://github.com/axnsan12/drf-yasg/issues/310).
> Make autogenerated read only fields to be able to be nullable

- rest_framework/compat.py
- rest_framework/negotiation.py
- rest_framework/parsers.py
- rest_framework/renderers.py
- rest_framework/request.py
- rest_framework/utils/mediatypes.py
Follow-up to #8554 (with edits).
Closes #8540.
> Replaced parse_header with parse_header_parameters.

- tests/schemas/test_managementcommand.py
This PR replaced the links to the `sample.com` domain (which seems to be associated with phishing/spam) with an `example.com`.
> Use example.com domain in tests.

- rest_framework/exceptions.py
As per the sole commit:
> PR #7531 resolved issue #7433 by updating `ErrorDetails.__eq__` to correctly handle the `NotImplemented` case. However, Python 3.9 continues to issue the following warning:
>
>     DeprecationWarning: NotImplemented should not be used in a boolean context
>
> This is because `__ne__` still doesn't handle the `NotImplemented` case correctly. In order to avoid this warning, this commit makes the same change for `__ne__` as previously made for `__eq__`.
refs #7433 #7531
> Handle `NotImplemented` correctly in `ErrorDetail.__ne__`

- rest_framework/fields.py
- tests/test_fields.py
Per the deprecation warnings (which have been raised since DRF 3.11),
`set_context()` was planned not to be supported in DRF 3.13. I think we
can safely delete it, in favor of `requires_context`.
Since this represents an API change, maybe it's best slated for 3.14?
(We could alternatively start raising `RemovedInDRF314Warning`)
From the 3.11 announcement:
> Previous our approach to this was that implementations could include a
> `set_context` method, which would be called prior to validation. However
> this approach had issues with potential race conditions. We have now
> move this approach into a pending deprecation state. It will continue to
> function, but will be escalated to a deprecated state in 3.12, and
> removed entirely in 3.13.
Why keep `RemovedInDRF313Warning` around? …
> Stop calling `set_context`, planned for 3.13 drop

- setup.cfg
Fix this warning from setuptools:
```
/.../setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
warnings.warn(msg, warning_class)
```
It could be seen at the top of the wheel building command run on CI:
```
python3 setup.py bdist_wheel 2>&1 | head
```
(It would be best to use [`build`](https://pypi.org/project/build/) these days)
> Fix setuptools warning about license_files

- rest_framework/serializers.py
At the moment `is_valid` calls are possible without keyword-only arguments, so code
`serializer.is_valid(True)` is possible and will be quite misleading, especially for new developers. This pull requests makes "raise_exception" name mandatory if serializer is called with argument.
> Enforce `is_valid(raise_exception=False)` as a keyword-only argument.

- rest_framework/schemas/coreapi.py
- tests/schemas/test_coreapi.py
This PR resolves an untested backwards incompatible schema change that sneaked in along with the `3.12` release.
In the nested view of `ViewSetMixin`, the `head` method is auto mapped [here](https://github.com/encode/django-rest-framework/blob/1ec0f86b585cd87e4b413aeaad1ecc947bacfef2/rest_framework/viewsets.py#L107) to the `get` action, leading to the view's action mapping to contain more than 1 mapping under normal `read` conditions.
The length of the action map is later used to determine the action names and depth for the links in the schema document, generated by `SchemaGenerator`.
The `head` method should not be accounted for when generating the depth and details of the links, since it's not part of the schema anyways.
Furthermore this also propagates and changes the operation ids for …
> Prevent head method mapping to coerce action name

- README.md
Update Twitter of the project's author. It seems that the project author's Twitter handle has changed over the time, and [_tomchristie](https://twitter.com/_tomchristie) is now used by someone else.
A tweet of project's author in the Web Archive.
https://web.archive.org/web/20180828104335/https://twitter.com/_tomchristie
That same tweet in Twitter now.
https://twitter.com/starletdreaming/status/1030486286560321536
> Update Twitter handle of project's author in README.md

- docs/api-guide/permissions.md
I found it unclear how the model was determined for `DjangoModelPermissions`. The docs say you need a `queryset` or `get_queryset`, but not that the value returned from those is what determines the model that is used.
> Docs: Clarify model used in DjangoModelPermissions

- docs/api-guide/generic-views.md
In the "Creating custom mixins" documentation, the code example recommends using
```python
if self.kwargs[field]
```
However, if the correct field is not present in kwargs, a KeyError arises.
A more secure option is tu use .get() to validate that the field is contained in the kwargs dictionary:
```python
if self.kwargs.get(field)
```
> Use .get() to find correct kwargs field and avoid KeyError

- rest_framework/viewsets.py
Before this fix, namespaced views would not appear in the extra actions. With this fix they do.
See issue https://github.com/encode/django-rest-framework/issues/8463 and discussion https://github.com/encode/django-rest-framework/discussions/7816
Closes #8463
> Fixes that namespaced views now also appear in the extra actions

- docs/api-guide/serializers.md
The namespace was omitted and it was causing confusion.
> docs: add the missing module name

- docs/api-guide/serializers.md
there was an extra # for two of the headings that made them indistinguishable.
> docs: fix level of some headings

- rest_framework/test.py
- tests/test_testing.py
See the issue: #8211  for why this is needed.
Previously `force_authenticate()` called `logout()` if no user is provided. However as described in the issue, there is
a case where we want to authenticate with a token but not a user, so we don't want to logout in this case.
> Make `APIClient.force_authenticate()` work with `user=None`

- rest_framework/permissions.py
- setup.cfg
- tests/test_permissions.py
Follow on from #6605 
- Rebase
- Fixed test
- Added additional regression test (fail on `master` branch, pass with this change).
Closes #6605
Closes #7601
Closes #7117
> Change semantic of OR of two permission classes

- rest_framework/management/commands/generateschema.py
Adds support for `--version` CLI argument to `generateschema` management command. 
refs #8551
> Add --version CLI option to generateschema

- rest_framework/management/commands/generateschema.py
Reverts PR #8552, since it introduced a CI regression under Python 3.6
> Revert #8552

- docs/api-guide/fields.md
- docs/community/3.14-announcement.md
- docs/community/release-notes.md
- rest_framework/__init__.py
- rest_framework/fields.py
- rest_framework/metadata.py
- rest_framework/schemas/openapi.py
- rest_framework/serializers.py
- tests/test_fields.py
Currently projects using Django 4.1 are blocked from using Django Rest Framework due to #8591. Since that was merged, I think a release is warranted.
I started putting together the changes from 3.13.1, and discovered there were a couple of API changes. I suspect this should require a minor version change, but a maintainer should make that final call.
If the version change isn't desired, let me know and I can remove that.
> Version 3.14.0 proposal

- README.md
- docs/community/3.14-announcement.md
- tests/authentication/test_authentication.py
- tox.ini
Update supported versions in line with this proposal...
https://github.com/encode/django-rest-framework/pull/8518#issuecomment-1247915701
---
* We release new versions of REST framework twice a year. Same [as for Django](https://www.djangoproject.com/download/#supported-versions).
* We aim each new release to arrive shortly after each Django release.
* We always support the latest 5 Django releases.
* We support whichever Python versions are required by Django.
Why "support the latest 5 Django releases"? Well, because I'd like it to always be a simple fixed number, and (unless I'm messing this up?) that's the lowest number we could pick that ensures we never drop a Django version that's still covered by their "extended support" policy.
The implication for our upcoming [3.14 …
> Update supported versions for 3.14 release

- docs/api-guide/fields.md
The same thing was explained above, in the definition of arguments.
> docs: delete duplicate explanation

- docs/community/3.14-announcement.md
- docs/community/release-notes.md
- setup.py
As prompted by https://github.com/encode/django-rest-framework/pull/8599#issuecomment-1254371840
> Update setup.py to drop Django 2.2 and update release notes

- rest_framework/__init__.py
`PendingDeprecationWarning` means "we plan to deprecate, but haven't yet." A feature that's to be deleted in the next release is not planned to be deprecated; it **is** deprecated.
> Base class for warnings about features which are obsolete and expected
> to be deprecated in the future, but are not deprecated at the moment.
>
> This class is _**rarely used**_ as emitting a warning about a possible
> upcoming deprecation is unusual, and _**DeprecationWarning is preferred**_ for
> already active deprecations.
(emphasis mine)
https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning
> Use correct class to indicate present deprecation

- rest_framework/schemas/inspectors.py
Unnecessary list comprehension. Refactored using list().
Both perform the same task but in
[line for line in description.splitlines()]
You manually iterate over description causing heigh time complexity.
> Minor refactor: Unnecessary list comprehension

- rest_framework/schemas/inspectors.py
as **joncle** mentioned in [this message](https://github.com/encode/django-rest-framework/pull/8670#issuecomment-1258174101) that **.splitlines()** already returns a list type so no need to call **list()**  function here.
> Minor refactor: Unnecessary use of list() function

- rest_framework/fields.py
Very minor fix to `SerializerMethodField` docstring. It now follows the same pattern as the example in the docstring of `ReadOnlyField `
> Minor fix to SerializerMethodField docstring

- docs/topics/browsable-api.md
Today I followed the documentation about overriding the default theme of the browsable API and stumbled upon a broken example. Also I noticed a wrong Bootstrap version.
To improve the docs I
- replaced the broken Bootswatch link with an Jsdelivr link as suggested at https://bootswatch.com/help/,
- updated the stated Bootstrap version,
- added a note that the Bootstrap version must match the default one.
Thank you for this great framework!
> Docs: Updated browsable-api.md

- rest_framework/fields.py
- rest_framework/pagination.py
- rest_framework/parsers.py
- rest_framework/relations.py
- rest_framework/renderers.py
- rest_framework/serializers.py
- rest_framework/utils/encoders.py
- rest_framework/utils/serializer_helpers.py
If the desire is to simply suppress an error, rather than perform some sort of branching logic, the Python standard library has a paradigm for that: **contextlib.suppress()**.
- It reduces the code size and increases the readability of the code.
- It is more elegant in terms of the coding style.
> Refactor: Replace try/except with contextlib.suppress()

- rest_framework/views.py
- tests/test_generics.py
I did not review your contributing guidelines, nor did I test anything using the automated tests. I also did only the most minimal of non-automated testing. Still, I thought I'd leave this here, as it may be useful to others. See it as an "issue description with PoC of a solution" if you will.
The problem: when raising standard Django exceptions `Http404` or `PermissionDenied`, the error messages of these exceptions do not show up in the DRF's response. This is because these exceptions are recreated in the piece of code that this PR adapts.
In this PR this is solved by making sure the recreated exceptions are recreated with the same arguments as the original versions. Whether the signatures actually match up, I did not check properly.
> Preserve exception messages for wrapped Django exceptions

- docs/api-guide/authentication.md
- docs/api-guide/content-negotiation.md
- docs/api-guide/reverse.md
- docs/api-guide/serializers.md
- docs/api-guide/throttling.md
- docs/community/3.12-announcement.md
> Docs: Convert all tabs into spaces

- docs/api-guide/schemas.md
I was doing docs for my API and unfortunately run into issue with some endpoints. It turned out that because of required permissions few of the classes wasn't included in *api schema*. I was looking for some help in documentation, but for nothing. After some time I found in source code `public` that i needed. This attribute wasn't described anywhere in the docs so I thought it will be nice to describe it.
> Docs: describe "public" attribute in get_schema_view() docuentation.

- rest_framework/permissions.py
The reason behind this proposal is to fully enable `permission_classes` comparison, e.g. in tests:
```python
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser
from myapp.permissions import MyPermission
class MyView(APIView):
permission_classes = [MyPermission | IsAdminUser]
```
```python
from myapp.views import MyView
from rest_framework.permissions import IsAdminUser
from myapp.permissions import MyPermission
def test__permission_classes():
cls = MyView
assert cls.permission_classes == [MyPermission | IsAdminUser]
```
I'd love to submit an actual test, but being a first-time contributor here I'm not sure where and how exactly would it fit in just by looking at `tests/test_permissions.py`.
Have a nice day!
> Add `__eq__` method for `permissions.OperandHolder` class

- docs/api-guide/parsers.md
- Removes the word "Both" which appears to be out of place.
> Remove extraneous word "Both"

- tests/test_fields.py
- tests/test_pagination.py
- tests/test_relations.py
- tests/test_serializer.py
- tests/test_serializer_lists.py
- tests/test_serializer_nested.py
Pytest 7.2.0 deprecated plain `setup` and `teardown` functions and methods as nose idioms:
https://docs.pytest.org/en/latest/changelog.html#pytest-7-2-0-2022-10-23
`setup` can be safely replaced with `setup_method`:
https://docs.pytest.org/en/stable/deprecations.html#setup-teardown
Closes #8757
> Fix Pytest's deprecation warnings about nose usage

- rest_framework/pagination.py
As discussed in https://github.com/encode/django-rest-framework/discussions/8761, this pull request modifies the CursorPagination such that it stores the current request in an instance field. This ensures that all three pagination classes consistently have access to a request reference.
As a related change, this pull request also updates the PageNumberPagination and LimitOffsetPagination to be consistent and both store the request at the start of the `paginate_queryset` method: previously LimitOffsetPagination stored the request early in the flow whereas PageNumberPagination stored it late.
> Make request consistently available in pagination classes

- docs/api-guide/permissions.md
Updating documentation to include my [permissions library](https://github.com/Pithikos/rest-framework-roles).
> Update documentation with new 3rd party entry

- .github/workflows/main.yml
- docs/index.md
- setup.py
- tox.ini
refs #8751 - Add support to Python 3.11
Add support to Python 3.11 in tests, docs and classifier.
> Fix #8751 - Add support to Python 3.11

- rest_framework/pagination.py
- tests/test_pagination.py
It will return 404 if page query parameter is empty string, like `/?page=`.
Some of api testing tools will assign query parameter with empty string (like `Apifox`, as I know), this PR handles this case.
> fix 404 when page query parameter is empty string

- tests/test_settings.py
Added `test_pagination_settings` test case.
Test case was added for `rest_framework.checks.pagination_system_check`, which make warnings about rest_framework pagination settings.
> Added pagination settings test case

- docs/api-guide/schemas.md
- docs/topics/documenting-your-api.md
As discussed in #8453, this PR re-arranges some aspects of the schema documentation.
- `schema.md`: add deprecation notice
- `documenting-your-api.md`: add deprecation notice 
- `documenting-your-api.md`: push deprecated approach below the recommended one
- `documenting-your-api.md`: adapt intro text
- `documenting-your-api.md`: recommend drf-spectacular 
- `documenting-your-api.md`: make clear that drf-yasg is OpenAPI 2
> Update schema generation doc & add deprecation notice #8453

- rest_framework/permissions.py
- tests/test_permissions.py
Refs #8771 , refs #8425 
We should check for authentication even when the `_ignore_model_permissions` flag is set to `True`.
Otherwise it will bypass the check for authentication, not only the one for permissions
> Fix #8771 - Checking for authentication even if `_ignore_model_permissions = True`

- rest_framework/fields.py
- tests/test_fields.py
Related: https://github.com/django/django/pull/8870/files
Properly handle OverflowError in DurationField deserialization. Solution is the same as for the corresponding Django form field.
> Properly handle OverflowError in DurationField deserialization

- docs/tutorial/quickstart.md
Without adding the URLs manually, the users and groups APIs were not usable.
My env:
(venv) ➜  tutorial pip freeze
asgiref==3.5.2
astroid==2.12.13
autopep8==2.0.0
dill==0.3.6
Django==4.1.3
djangorestframework==3.14.0
isort==5.10.1
lazy-object-proxy==1.8.0
mccabe==0.7.0
platformdirs==2.5.4
pycodestyle==2.10.0
pylint==2.15.6
pylint-django==2.5.3
pylint-plugin-utils==0.7
pytz==2022.6
sqlparse==0.4.3
tomli==2.0.1
tomlkit==0.11.6
wrapt==1.14.1
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the …
> Register Django urls

- rest_framework/schemas/openapi.py
#8017 indirectly introduced a new hard dependency. `rest_framework.openapi.AutoSchema` is imported in the default settings, which makes this a new dependency for nearly everyone. That is the reason why the builds are failing at the moment, as the `tox -e base` target does not install the optionals.
So either we move that newly introduced import out of the main code path or DRF needs to gain that dependency in `setup.py`, which would probably be excessive.
> mitigate global dependency on inflection #8017

- rest_framework/static/rest_framework/js/csrf.js
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- tests/test_templates.py
Scripts with type="application/json" or "text/plain" are not executed, so we can use them to inject dynamic CSRF data, without allowing inline-script execution in Content-Security-Policy.
This helps towards fixing #6069 a bit.
> Avoid inline script execution for injecting CSRF token

- rest_framework/static/rest_framework/js/load-ajax-form.js
- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
(Copied from https://github.com/encode/django-rest-framework/pull/5740, conflicting CSRF changes removed. These were already handled as part of https://github.com/encode/django-rest-framework/pull/7016)
Currently the browsable API contains inline JS for configuring forms and allowing for custom CSRF cookie/header names. Use of CSP with this page requires 'unsafe-inline'.
This patch is a concept for getting rid of all inline scripts from the browsable API. It's not tested, as I just wanted to see if there was interest in merging this before I spend too much time on it.
> Changes to make browsable API compatbile with strong CSP

- docs/api-guide/validators.md
Function validators seem to have to return their value (which will become part of `validated_data`) as part of their signature.
> Fix bug in validators documentation

- rest_framework/authtoken/admin.py
Use `autocomplete_fields` to keep the select user field manageable.
Refs #8533
> Use autocomplete widget for user selection in TokenAdmin

- rest_framework/static/rest_framework/css/bootstrap-tweaks.css
- rest_framework/templates/rest_framework/base.html
- rest_framework/templates/rest_framework/pagination/numbers.html
(Copied from https://github.com/encode/django-rest-framework/pull/7960, but nonce removed to avoid conflicts with user-defined policies)
Remove a few instances of inline CSS which could trigger Content Security Policies (CSPs) and replace with classes where required.
Part of https://github.com/encode/django-rest-framework/issues/6069.
I've left JavaScript alone as it's covered by https://github.com/encode/django-rest-framework/pull/5740 and https://github.com/encode/django-rest-framework/pull/7016 (which I think are duplicates of each other?).
> Remove a bit of inline CSS. Add CSP nonce where it might be required and is available.

- rest_framework/fields.py
- tests/test_fields.py
Without this, Django's ValidationErrors will bypass the error collection
from ListField's children.
Here is an example that illustrates this change.
Consider a Serializer that uses ListField like this:
```python
class SomeSerializer(serializers.Serializer):
uuids = serializers.ListField(
child=serializers.PrimaryKeyRelatedField(
queryset=Model.objects.something(),
validators=[SomeCustomValidator()]
)
)
```
Validating data that looks like this works fine:
```python
{uuids: ['some-valid-uuid', 'some-valid-uuid']}
```
Raising a DRF ValidationError for one of the children works fine, giving
an error object like:
```python
{'uuids': {0: ErrorDetail(string='Some validation error')}}
```
Raising a Django ValidationError for one of the children works
differently (which …
> Handle Django's ValidationErrors in ListField

- .github/workflows/main.yml
- tox.ini
Copy of [#458](https://github.com/django/daphne/pull/458) for this repo.
tox 4 has just been released: https://fosstodon.org/@gaborbernat/109473528072009278
tox-py no longer works with it, but that’s okay since the new `-f` factor option fills the need to run Python 3.X tests in the Python 3.X CI run. I documented this pattern in the package install instructions: https://github.com/adamchainz/tox-py/#installation . Plus, I’ve already changed all the projects I maintain to use it, for example: https://github.com/adamchainz/django-htmx/pull/296
tox 4 only supports Python 3.7+. I’ve added a temporary fork on Python version to retain running with old tox and tox-py on Python 3.6. I think we should drop Python 3.6 in a follow-up PR since it’s been EOL for a while now.
> Upgrade to tox 4

- rest_framework/schemas/openapi.py
- tests/schemas/test_openapi.py
As per the unit test, changed to use `pk_field` argument when creating schema of `PrimaryKeyRelatedField`.
This fix isn't the perfect solution, but I couldn't come up with another best idea.
I'm sorry that my English isn't very good.
Ex,
```
class SampleSerializer(Serializer):
user_id = serializers.PrimaryKeyRelatedField(queryset=User.objects.all())
user_id_with_pk_field = serializers.PrimaryKeyRelatedField(queryset=User.objects.all(), pk_field=serializers.UUIDField())
Sample:
type: object
properties:
user_id:
type: integer (or string)
user_id_with_pk_field:
type: string
format: uuid
```
> Use PrimaryKeyRelatedField pkfield in openapi

- requirements/requirements-packaging.txt
Hello, first of all thanks for developing this great package!
During the setup of django-rest-framework on local environment, I observed that version of package 'transifex-client` throwing following error.
```
ERROR: Ignored the following versions that require a different python version: 0.13.0 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.6; 0.13.1 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.7; 0.13.10 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9; 0.13.11 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9; 0.13.12 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9; 0.13.2 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.7; 0.13.3 Requires-Python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.7; 0.13.4 …
```
> fix transifex-client version in packaging requirements.

- docs/api-guide/permissions.md
- docs/community/third-party-packages.md
`djangorestframework-guardian` has not had a new release for over 3 years
- https://pypi.org/project/djangorestframework-guardian/#history
There are no commits for 2.5 years:
- https://github.com/rpkilby/django-rest-framework-guardian/commits/master
The maintainer has not responded to an issue about this for over a year
- https://github.com/rpkilby/django-rest-framework-guardian/issues/19
`djangorestframework-guardian2` is a friendly fork I created that supports the currently supported Django and Python versions
- https://pypi.org/project/djangorestframework-guardian2/
Out of courtesy (not trying to bug the maintainer more), I will CC @rpkilby here in case he would like to contend this (in which case I'll happily allow him to maintain the original package again if he desires).
> Update docs to maintained `djangorestframework-guardian2`

- rest_framework/fields.py
- tests/test_fields.py
Following on the discussion in #8804 this PR fixes `required` argument lost in `FilePathField` constructor by making sure it is passed to the `super().__init__` call with other keyword arguments.
> Fix FilePathField required argument

- docs/api-guide/exceptions.md
The documentation used to state that the `detail` argument was mandatory, but in fact it currently is not.
Here is the line that defines the default argument:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/exceptions.py#L148
> Update documentation regarding arguments of ValidationError

- docs/api-guide/routers.md
- rest_framework/routers.py
- tests/test_routers.py
Add `SimplePathRouter` to handle Django 2.x _path converters_ (refs #6148).
> Add SimplePathRouter

- docs/api-guide/permissions.md
- rest_framework/permissions.py
- tests/test_permissions.py
This PR implements the `view` permission in `DjangoModelPemissions` class. The old PR #6325 tried to fix it, but it contains a flaw i.e., even if an object has `change`, `add`, `delete` permission the detail page of any objects returns `"detail": "Not found."`. which is not expected. As any objects which has `change` permission should also allow `GET` requests as well.
FIXES: #6324
- https://github.com/encode/django-rest-framework/pull/6325#issuecomment-569997047
- https://github.com/encode/django-rest-framework/pull/6325#pullrequestreview-664894357
> Fix Respect `can_read_model` permission in DjangoModelPermissions

- tests/test_reverse.py
- tests/test_versioning.py
After adding typing of `APIClient.get` method to drf stubs project https://github.com/typeddjango/djangorestframework-stubs/pull/330 mypy started complaining about these classes in tests:
```
drf_source/tests/test_reverse.py:43: error: Incompatible types in assignment (expression has type "MockVersioningScheme", variable has type "Optional[BaseVersioning]")
drf_source/tests/test_reverse.py:50: error: Incompatible types in assignment (expression has type "MockVersioningScheme", variable has type "Optional[BaseVersioning]")
drf_source/tests/test_versioning.py:136: error: Incompatible types in assignment (expression has type "Type[FakeResolverMatch]", variable has type "Optional[ResolverMatch]")
drf_source/tests/test_versioning.py:209: error: Incompatible types in assignment (expression has …
```
> Inherit from faked classes in tests to satisfy mypy

- .pre-commit-config.yaml
This fixes recent issues with installing isort via pre-commit that was introduced in recent versions of poetry-core.
See https://github.com/PyCQA/isort/pull/2078
> Upgrade isort version in pre-commit

- rest_framework/fields.py
- rest_framework/generics.py
- rest_framework/request.py
- rest_framework/response.py
- tests/test_fields.py
- tests/test_generics.py
- tests/test_request.py
- tests/test_response.py
Allow Request, Response, Field, and GenericAPIView to be subscriptable. This is a follow up to encode/django-rest-framework#7385 and allows the classes to be made generic for type checking.
By making these classes generic, type checkers can more easily do their job when working with DRF classes. Today,
django-stubs and djangorestframework-stubs must monkey patch types to support generic typing, but the approach is problematic with DRF since DRF eagerly loads settings resulting in [issues like this][1].
[1]: https://github.com/typeddjango/djangorestframework-stubs/issues/299
> Allow generic requests, responses, fields, views

- docs/tutorial/6-viewsets-and-routers.md
added a missing import statement for `renderer` in tutorial 6 (ViewSets & Routers) in the first snippet where renderer is used
> docs: add a missing renderer import in tutorial 6

- rest_framework/serializers.py
- rest_framework/utils/field_mapping.py
- tests/test_validators.py
A starting point for discussion, that pr supports both cases when UniqueConstraint consist of one field -> `UniqueValidator`, and several fields -> `UniqueTogetherValidator`. The implementation of single field unique validator is quite naive where we loop over all constraints searching for single field constraints and we do it for each field, would be good to cache that somehow.
refs #7173
> Primary Support of UniqueConstraint

- docs/api-guide/permissions.md
- rest_framework/templates/rest_framework/docs/error.html
Apart from a few exceptions, django-rest-framework uses the American English spelling "authorization"/"authorized".
$ git grep -oi authorised | wc -l
2
$ git grep -oi authorized | wc -l
30
Replace the few occurences of the British English spelling with the American English one.
> Use consistent spelling for "authorization"

- docs/api-guide/permissions.md
`IsAuthenticatedOrReadOnly` authorizes users that are not authenticated for read-only access to resources.
Therefore, they are unauthenticated users, not unauthorized users.
> docs: Fix authentication / authorization mixup

- rest_framework/relations.py
- tests/test_relations.py
- tests/utils.py
Currently if you define the slug field as a nested relationship in a `SlugRelatedField` while many=False, it will cause an attribute error. For example:
For this code:
```
class SomeSerializer(serializers.ModelSerializer):
some_field= serializers.SlugRelatedField(queryset=SomeClass.objects.all(), slug_field="foo__bar")
```
The POST request (or save operation) should work just fine, but if you use GET, then it will fail with Attribute error:
> AttributeError: 'SomeClass' object has no attribute 'foo__bar'
Thus I am handling nested relation here. Apart from that, I have added test cases regarding nested relations.
Reference: https://stackoverflow.com/questions/75878103/drf-attributeerror-when-trying-to-creating-a-instance-with-slugrelatedfield-and/75882424
> Handle Nested Relation in SlugRelatedField when many=False

- rest_framework/fields.py
- rest_framework/utils/timezone.py
- setup.py
- tests/test_fields.py
This PRs switches over to `ZoneInfo` as the primary source of timezone data in DRF. This PR accomplishes several things:
- Adds deprecation warning for a test that relies off `pytz`.
- Switches over tests that do not rely on `pytz` functionality over to `ZoneInfo`.
- Add additional error handling for `ZoneInfo` timezones. This is because unlike `pytz`, error checking has to be done more or less manually in able to determine ambiguous and imaginary timezones (see [this doc](https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html#detecting-ambiguous-and-imaginary-times) on migrating to `ZoneInfo`). We previously …
> Use ZoneInfo as primary source of timezone data

- docs/api-guide/validators.md
- rest_framework/validators.py
- tests/test_validators.py
Implement equality operator for validators and add test coverage.
Fixes https://github.com/encode/django-rest-framework/issues/8905.
> Implement `__eq__` for validators

- .github/workflows/main.yml
might need to try part of the following in another PR if needed
- name: Generate coverage report
run: |
pip install pytest
pip install pytest-cov
pytest --cov=./ --cov-report=xml
- name: Upload coverage to Codecov
uses: codecov/codecov-action@v3
with:
token: ${{ secrets.CODECOV_TOKEN }}
directory: ./coverage/reports/
env_vars: OS,PYTHON
fail_ci_if_error: true
files: ./coverage1.xml,./coverage2.xml,!./cache
flags: unittests
name: codecov-umbrella
verbose: true
> test codecov gha

- rest_framework/metadata.py
- tests/test_metadata.py
Refactor get_field_info method to include max_digits and decimal_places attributes in SimpleMetadata class
This commit adds the max_digits and decimal_places attributes to the list of attributes included in the get_field_info method of the SimpleMetadata class in the Django Rest Framework. These attributes provide additional information about decimal fields, which was not previously included in the metadata. By adding these attributes to the output of the method, clients consuming the API will have more complete information about the fields in the serialized data, allowing them to make more informed decisions about how to interact with the API. This change was made in response to user feedback and is not expected to have any negative impact on existing functionality.
before change
```
{ …
```
> Refactor get_field_info method to include max_digits and decimal_places attributes in SimpleMetadata class

- rest_framework/fields.py
- rest_framework/metadata.py
- rest_framework/pagination.py
- rest_framework/relations.py
- rest_framework/renderers.py
- rest_framework/routers.py
- rest_framework/schemas/coreapi.py
- rest_framework/schemas/openapi.py
- rest_framework/serializers.py
- rest_framework/templatetags/rest_framework.py
- rest_framework/utils/model_meta.py
- rest_framework/utils/serializer_helpers.py
- rest_framework/viewsets.py
- tests/test_model_serializer.py
- tests/test_renderers.py
- tests/test_viewsets.py
See discussion: https://github.com/encode/django-rest-framework/discussions/8736
Also see: https://github.com/encode/django-rest-framework/pull/7524
> Replaced `OrderedDict` with `dict`

- rest_framework/pagination.py
- tests/test_pagination.py
https://github.com/encode/django-rest-framework/discussions/8953
* this commit fixes the usage of a CursorPagination combined with a view implementing an ordering filter, without a default ordering value.
* former behavior was to fetch the ordering value from the filter, and raises an error if the value was None, preventing the fallback on the ordering set on the CursorPagination class itself.
* we reversed the logic by getting first the value set on the class, and override it by the ordering filter if the parameter is present
> fix: fallback on CursorPagination ordering if unset on the view

- setup.py
This commit updates the read function to use a context manager when opening the file, ensuring that the file is properly closed after it has been read. This improves the code's readability and helps to prevent potential resource leaks.
> Refactor read function to use context manager for file handling

- rest_framework/fields.py
- tests/test_fields.py
This pull request fixes the mapping between the human-labels and the database-values for the `ChoiceField` class. This PR has been mutated from [8955](https://github.com/encode/django-rest-framework/pull/8955)
Discussion [8965](https://github.com/encode/django-rest-framework/discussions/8965)
> Fix mapping for choice values

- rest_framework/fields.py
- tests/test_fields.py
> feat: enforce Decimal type in min_value and max_value arguments of DecimalField

- docs/index.md
> remove django 2.2 from docs index

- README.md
> Declared Django 4.2 support in README.md

- docs/api-guide/reverse.md
The documentation links to the Django documentation for the `reverse` and `reverse_lazy` functions were broken. Fixes it.
> Fix Links in Documentation to Django `reverse` and `reverse_lazy`

- docs/api-guide/validators.md
Improving code example of `requires_context` attribute in validator classes. No code changes, only one doc change.
> Fix example of `requires_context` attribute

- docs/community/3.12-announcement.md
- docs/community/3.14-announcement.md
- docs/community/release-notes.md
I noticed that the NullBooleanField deprecation (#7122) wasn't mentioned in the docs, so I've added it to the release announcements and the release notes.
> Add NullBooleanField deprecation to docs

- rest_framework/renderers.py
- tests/test_renderers.py
When using ListSerializer as viewset serializer_class rendering of view in BrowsableAPI fails with:
```
Internal Server Error: /api/snippets/
File "/home/nz/.local/lib/virtualenvs/django-rest-framework-demo/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
^^^^^^^^^^^^^^^^^^^^^
File "/home/nz/.local/lib/virtualenvs/django-rest-framework-demo/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
response = response.render()
^^^^^^^^^^^^^^^^^
File "/home/nz/.local/lib/virtualenvs/django-rest-framework-demo/lib/python3.11/site-packages/django/template/response.py", line 114, in render
self.content = self.rendered_content
^^^^^^^^^^^^^^^^^^^^^
File …
```
> Fixes `BrowsableAPIRenderer` for usage with `ListSerializer`.

- rest_framework/fields.py
- tests/test_fields.py
In this PR, all values of type `str` being serialized to `bool` for fields typed `BooleanField` are first cast to lowercase and _then_ validated against the lists of `TRUE_VALUES`, `FALSE_VALUES`, and `NULL_VALUES`. Discovered this restriction when a user tried to send "Yes" as a valid value for a Boolean field to my team's Public-facing API.
> Permit mixed casing of string values for BooleanField validation

- rest_framework/templates/rest_framework/horizontal/select_multiple.html
Removed the `{{ field.choices|yesno:",disabled" }}` block because this triggers the loading of full database table worth of objects just to determine whether the multi-select widget should be set as disabled or not.
Since this "disabled" marking feature is not present in the normal select field, then I propose to remove it also from the multi-select.
The reason why I found this was that HTML forms in the browsable API became extremely slow, but only when relation fields with many=True were being used.
> Removed usage of field.choices that triggered full table load

- rest_framework/versioning.py
- tests/test_versioning.py
* Fix the case where if the namespace is not None and there's no match,
NamespaceVersioning always raises NotFound even if DEFAULT_VERSION
is set or None is in ALLOWED_VERSIONS
* Add test cases
If my namespace is just `'api'` (i.e. doesn't include version info), `ALLOWED_VERSIONS` is set to `['v1', 'v2']` and `DEFAULT_VERSION` is set to `'v2'`, I would expect `request.version` to resolve to `'v2'`. The current behavior in this scenario is `404 Not Found` which is inconsistent with the [documentation](https://www.django-rest-framework.org/api-guide/versioning/#other-versioning-settings).
Similarly, if `DEFAULT_VERSION` is not set and `ALLOWED_VERSIONS` includes `None`, I would expect `request.version` to be `None`. The current behavior is, once again, 404.
> Fix NamespaceVersioning ignoring DEFAULT_VERSION on non-None namespaces

- rest_framework/__init__.py
- rest_framework/filters.py
- rest_framework/pagination.py
- rest_framework/renderers.py
- rest_framework/schemas/coreapi.py
- rest_framework/templates/rest_framework/horizontal/select_multiple.html
- rest_framework/utils/encoders.py
- rest_framework/versioning.py
- setup.cfg
- tests/schemas/test_coreapi.py
- tests/schemas/test_openapi.py
- tests/schemas/views.py
- tests/test_versioning.py
1. fixed openapi schema yaml rendering for timedelta
2. yaml default scalar convert timedelta into python tag !!python/object/apply:datetime.timedelta which is cant be rendered into swagger and redoc.
3. added custom scalar which convert python tag into str
> Fix OpenAPI Schema yaml rendering for timedelta

- rest_framework/filters.py
- tests/test_filters.py
This Pull request fixes an issue described in discussion #9018
> Fix: SearchFilter renders search field with invalid value

- rest_framework/fields.py
- tests/test_fields.py
Python support Enum in version 3.4, but changed `__str__` to `int.__str__` until version 3.11 to better support the replacement of existing constants use-case. [https://docs.python.org/3/library/enum.html#enum.IntEnum](https://docs.python.org/3/library/enum.html#enum.IntEnum)
rest_framework support Python 3.6+, this commit will support the Enum as datatype of choices in Field.
Discussions: [https://github.com/encode/django-rest-framework/discussions/8945](https://github.com/encode/django-rest-framework/discussions/8945)
> Fix choices in ChoiceField to support IntEnum

- rest_framework/serializers.py
- tests/test_model_serializer.py
My real scenario is when I include some fields that does not exists in the model. For example assume that I have a model called `Store`, which does not have `token` field.
In this example, if I have a `ModelSerializer` like this:
```python
class StoreSerializer(ModelSerializer):
...
class Meta:
fields = (
...
"token"
)
```
Then I will face an exception like: ```'Field name `token` is not valid for model `Store`.'``` .
This can really be a headache, when I have multiple serializers for `Store` model. So I suggest to simply have the model path, to be more clear about which serializer is corrupt.
> Fix unknown field error in ModelSerializer

- rest_framework/serializers.py
- tests/test_serializer_lists.py
Move `child.run_validation()` call to a separated method: `ListSerializer.run_child_validation`.
This allows to easily customize this behavior without overriding `ListSerializer.to_internal_value` (which duplicates rest_framework code).
It is useful to support multiple updates where `child.instance` should be set during run_validation (else a queryset or a list of instances is passed to child serializer).
See 
- https://github.com/encode/django-rest-framework/discussions/7805 / https://github.com/encode/django-rest-framework/issues/6130
- https://github.com/encode/django-rest-framework/issues/5345
> Allow to override child.run_validation call in ListSerializer

- .github/workflows/main.yml
- docs/community/project-management.md
- requirements/requirements-documentation.txt
This is a way to automatically check if the documentation contains any broken links in order to avoid issues like #6928 
The task is currently on `allow_failures`, but it could be added to the regular tasks in order to avoid linking to non existent pages in future.
The current documentation contains 17 broken links:
```
not found (404): http://localhost:8000/tutorial/#api-guide
from http://localhost:8000/tutorial/quickstart/
not found (404): http://localhost:8000/api-guide/pagination/github-link-pagination
from http://localhost:8000/api-guide/pagination/
from http://localhost:8000/api-guide/pagination/#setting-the-pagination-style
from http://localhost:8000/api-guide/pagination/#modifying-the-pagination-style
not found (404): http://localhost:8000/topics/api-guide/schemas/#examples
from …
```
> Add docs validation to release process

- docs/api-guide/fields.md
- docs/api-guide/validators.md
Add note for `HiddenField` partial behavior. Details: https://github.com/encode/django-rest-framework/discussions/8259#discussioncomment-6537296
> Add note for HiddenField behavior

- docs/api-guide/viewsets.md
- tests/test_decorators.py
This pull request ensures that the `http.HTTPMethod` added in Python 3.11 is fully supported in the `@action` decorator, as mentioned in issue #8995.
Only one test and documentation update is needed, since `http.HTTPMethod` already functions as is.
The reason for this is that `@action` already invokes `lower()` on each `method`, which converts `http.HTTPMethod` to a `str` a format that is already supported.
> Document support for http.HTTPMethod in the @action decorator added in Python 3.11.

- rest_framework/routers.py
- tests/test_routers.py
Improves #6789 by using `str` as default path converter instead of `path`.
This because re-reading the [docs](https://docs.djangoproject.com/en/3.2/topics/http/urls/#path-converters) the more appropriate to use is `str`.
This because its regex is [`[^/]+`](https://github.com/django/django/blob/9946f0b0d9356b55e819f861b31615fa5b548f99/django/urls/converters.py#L16) which, among converters, is the most similar to the default used by router (`[^/.]+`).
> Use str as default path converter

- .github/workflows/main.yml
The `test-docs` workflow added with https://github.com/encode/django-rest-framework/pull/6967 needs to be reverted to Python 3.9, otherwiese the docs cannot be served. This might be related to the version of [mkdocs](https://github.com/encode/django-rest-framework/blob/master/requirements/requirements-documentation.txt) that is currently in use. 
```
Run mkdocs serve &
File "/opt/hostedtoolcache/Python/3.10.[12](https://github.com/nezhar/django-rest-framework/actions/runs/5888078513/job/15968572627#step:5:13)/x64/bin/mkdocs", line 5, in <module>
from mkdocs.__main__ import cli
File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 16, in <module>
from mkdocs import config                                 # …
```
> Fixes documentation link test

- .github/workflows/main.yml
An attempt to fix a issue on a PR
> Updated Checkout action version & Ubuntu OS version

- docs/api-guide/authentication.md
- docs/topics/ajax-csrf-cors.md
Hi!
`https://docs.djangoproject.com/en/stable/ref/csrf/#ajax` link is no longer valid and is referenced in:
- https://www.django-rest-framework.org/api-guide/authentication/#:~:text=Django%20CSRF%20documentation
- https://www.django-rest-framework.org/topics/ajax-csrf-cors/#:~:text=described%20in%20the%20Django%20documentation 
I think was moved to ["How-to" guides](https://docs.djangoproject.com/en/4.2/howto/#:~:text=How%20to%20use%20Django%E2%80%99s%20CSRF%20protection) so I updated to -> `https://docs.djangoproject.com/en/stable/howto/csrf/#using-csrf-protection-with-ajax`
Thank you!
> Updated links to CSRF/AJAX Django documentation

- rest_framework/utils/model_meta.py
- tests/test_utils.py
Having different names doesn't seem to be an issue, but I think it's still better this way
> Fix type name of `FieldInfo` namedtuple

- runtests.py
- tests/conftest.py
This change fixes the dist test by moving the --no-pkgroot option from pytest to the runtests script.
The current "filterwarnings" setting for pytest includes rest_framework, which causes an early import of the module. As a result the current --no-pkgroot behavior fails with an assertion error. Trying to remove the module from sys.modules will cause the warning filter to not apply, so this change moves this code before pytest parses the config and loads the "filterwarnings".
> fix dist test by moving --no-pkgroot to runtests.py

- docs/index.md
Updates the documentation page to add Django 4.2 requirement. This is consistent with the [README](https://github.com/encode/django-rest-framework/blob/master/README.md).
Here is the current state that is live:
> docs: update django requirement to 4.2

- docs/api-guide/settings.md
Let me know what description you'd like to put
> Add missing `DEFAULT_VERSIONING_CLASS` entry to API docs

- .pre-commit-config.yaml
- docs/api-guide/caching.md
- docs/api-guide/schemas.md
- docs/api-guide/viewsets.md
- docs/community/3.10-announcement.md
- docs/community/3.11-announcement.md
- docs/community/3.12-announcement.md
- docs/community/3.9-announcement.md
- docs/community/release-notes.md
- docs/topics/documenting-your-api.md
This PR  shows the changes made by applying blacken-docs to the project's `docs`.
It's objective is to show:
1. The changes required for the command to run without errors -- first commit
2. The changes that would be made by the command -- third commit
The second commit adds `blacken-docs` step to the precommit hook config file. ~This breaks on CI _right now_. And I couldn't replicate the issue locally. Help very much appreciated.~
Update: Fixed in ~fourth and~ fifth commit.
> blacken-docs

- docs/tutorial/6-viewsets-and-routers.md
The previous parts (1-5) of the tutorial always told the reader which file they need to edit to follow along. It was missing here in tutorial part 6 and I fixed it.
> Docs: tutorial part 6 - adding hint which file to edit

- docs/tutorial/quickstart.md
add .order_by() to eliminate Pagination UnorderedObjectListWarning
> Docs: Minor improvement to code in `quickstart.md`

- docs/topics/browsable-api.md
I spent several hours tonight looking for how to easily add the Login button to the browseable api. This PR adds a code snippet directly to the browseable api topic to show how to do this quickly. I found this solution from an older version of the tutorial linked from [this question on Stack Overflow](https://stackoverflow.com/questions/28044219/urest-framework-is-not-a-registered-namespace). I pulled up the version of the docs at that time from [the Internet Archive](http://web.archive.org/web/20150114020613/https://www.django-rest-framework.org/tutorial/6-viewsets-and-routers/). I am happy for suggestions about the exact placement of the section I added or wording describing the snippet.
> Docs: Show how to add URLs for authentication for the browseable API.

- rest_framework/compat.py
- rest_framework/fields.py
`ip_address_validators` return value changed in Django 5.1. Before Django 5.1, `ip_address_validators` returns a tuple containing 1) the list of validators and 2) the error message. Starting from Django 5.1 `ip_address_validators` only returns the list of validators. See django/django#17305. This make tests fail with `ValueError: not enough values to unpack (expected 2, got 1)`.
This PR creates a compatibility shim for `ip_address_validators` for Django < 5.1 to behave the same way as in Django >= 5.1.
> Fix use of ip_address_validators for Django 5.1+

- tests/schemas/test_managementcommand.py
Add `@pytest.mark.skipif(coreapi is None, reason='coreapi is required.')` for 3 tests in `GenerateSchemaTests` that require `coreapi`.
> Skip coreapi tests in GenerateSchemaTests if coreapi is not installed

- .pre-commit-config.yaml
- docs/community/3.5-announcement.md
- docs/topics/browsable-api.md
- rest_framework/decorators.py
- tests/test_throttling.py
% `pre-commit autoupdate`
> [https://github.com/pre-commit/pre-commit-hooks] updating v3.4.0 -> v4.5.0
[https://github.com/pycqa/isort] updating 5.12.0 -> 5.13.2
[https://github.com/PyCQA/flake8] updating 3.9.0 -> 7.0.0
[https://github.com/adamchainz/blacken-docs] updating 1.13.0 -> 1.16.0
% `pre-commit run --all-files`
> pre-commit autoupdate && pre-commit run --all-files

- docs/api-guide/fields.md
- docs/community/release-notes.md
- rest_framework/filters.py
- rest_framework/schemas/generators.py
- rest_framework/schemas/openapi.py
- rest_framework/settings.py
- tests/schemas/test_openapi.py
- tests/test_response.py
- tests/test_serializer_nested.py
% `codespell --ignore-words-list=childs,fo,malcom,ser --skip="*.js,*/kickstarter-announcement.md,*.map,*.po" --write-changes`
* https://pypi.org/project/codespell
> Fix typos discovered by codespell

- docs/api-guide/viewsets.md
Add missing import in https://www.django-rest-framework.org/api-guide/viewsets/#example_3
To be a correct example in case of a quick copy/paste it requires import `viewsets` to work as expected
> Add missing import in /api-guide/viewsets/ example

- rest_framework/validators.py
- tests/test_validators.py
Skip unnecessary unique-together validations when all unique field values remain unchanged.
> Skip unnecessary unique together checking

- docs/api-guide/validators.md
#5886 altered behaviour of `read_only` plus `default` in serializer fields. But documentation still describes old usage. Updated documentation to the current example.
> Remove read_only deprecated behaviour from documentation

- docs/community/3.14-announcement.md
> Fix typo in 3.14 announcement

- rest_framework/templates/rest_framework/admin.html
- rest_framework/templates/rest_framework/base.html
- rest_framework/templatetags/rest_framework.py
- tests/browsable_api/test_browsable_api.py
> Use POST method instead of GET to perform logout in browsable API

- .github/workflows/main.yml
- setup.py
- tox.ini
This is a test for the CI of python 3.12 since I can't commit to auvipy:py312 nor make a pull request to that branch (#9157). The tests pass locally, if confirmed on the CI, @auvipy can apply the commit to his branch and then merge. Otherwise, please ignore and close.
> Add Python 3.12 support

- README.md
- docs/index.md
- setup.py
- tests/test_fields.py
- tests/test_model_serializer.py
- tests/test_validators.py
- tox.ini
This PR (based on https://github.com/encode/django-rest-framework/pull/9230) fixes the test suite for supporting Django 5.0, enables it on the CI, and updates the documentation.
It also fixes the tests for djangomain (up to https://github.com/django/django/commit/e412d85b4626bc56eb25206a40c3529162ce5dfc)
> Add Django 5.0 support

- .github/workflows/main.yml
This PR resolves the deprecation warnings for `setup-python` in Github actions. An example of them appearing is here: https://github.com/encode/django-rest-framework/actions/runs/8065738414
Showing that the deprecation warnings are now removed: https://github.com/encode/django-rest-framework/actions/runs/8069177070?pr=9266
> Resolve setup-python deprecation warnings on Github actions

- .github/workflows/pre-commit.yml
Removes some warnings at the bottom right of https://github.com/encode/django-rest-framework/actions/runs/8079303418
* https://github.com/pre-commit/action/releases
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
https://github.com/pre-commit/action#using-this-action-in-private-repositories explains why `token` was removed but is a bit difficult to understand.
Moving to running pre-commit on https://pre-commit.ci has proved to be the best solution on other projects.
Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that …
> GitHub Actions: Upgrade pre-commit and drop the removed token

- rest_framework/static/rest_framework/js/ajax-form.js
Currently, DRF does not work well with `debug_toolbar`, due to the way it handles non-GET and non-POST requests.
To perform `PUT`, `PATCH`, `DELETE` and `OPTIONS` requests in browsable API, we send an ajax request to fetch the resulting HTML. The contents are then dynamically rendered using JavaScript.
During this time, the entire toolbar gets re-rendered (with proper data) but since the related JavaScript code is not executed (normally done on document load), the toolbar is instead hidden.
I added a simple check during JavaScript re-render to load the toolbar. It's unlikely this issue could be solved on `debug_toolbar` side given the way DRF handles content rendering.
IMHO this should be a great QOL improvement given how annoying it becomes to track requests with mentioned methods. …
> Improve integration with Django Debug Toolbar

- rest_framework/utils/representation.py
… django 5.0
This pull request resolves #9274 
1. the implementation of `force_str` in django 3 and django 5 versions doesn't seem to differ much except for a few code styles (https://www.diffchecker.com/kGpPbE3K/)
Therefore, I don't think we need to add logic in our code to look at the django version.
2. the removed `_delegate_text` being `False` means "don't expect that object to be a string", so I think adding `strings_only` like the code in the original issue is sufficient.
P.S.: If @jayden-arrai can send us a better PR, I'll close this one. I hope this doesn't offend the original issue raiser..
> Remove the `_delegate_text` attribute, which is being removed in django 5.0 (#9274)

- docs/tutorial/quickstart.md
Hello, this PR reverts the PR #8778.
When I was doing the Quickstart tutorial, I was a bit confused with the `urlpatterns` configurations in the URLs section (https://www.django-rest-framework.org/tutorial/quickstart/#urls) because it includes URL routes for REST framework twice.
I think we don't have to append the same routes to make the REST framework routes working properly.
Here are the routes before and after this PR's change:
**Before**
**After**
As you can see, `urlpatterns += router.urls` makes the extra duplicated routes unnecessarily.
> Revert "Register Django urls (#8778)"

- rest_framework/serializers.py
- tests/test_serializer.py
Reverts encode/django-rest-framework#8979
> Revert "Fix validation for ListSerializer"

- docs/api-guide/schemas.md
- rest_framework/compat.py
- rest_framework/schemas/openapi.py
Fix #9291
The 3.15 release started to use the `inflection` package (https://github.com/encode/django-rest-framework/pull/8017), but this was neither added as a dependency from DRF nor properly documented.
Since this is only needed for generating the OpenAPI schema ([which is deprecated](https://www.django-rest-framework.org/api-guide/schemas/)), I don't think it's worth introducing this package as a hard dependency, we can document it like `pyyaml` and `uritemplate`.
Since the former solution was ~1~ 3 lines, perhaps we can use it as fallback when `inflection` isn't installed?
> Make `inflection` package truly optional

- docs/community/release-notes.md
A few links aren't rendered properly [in the docs](https://www.django-rest-framework.org/community/release-notes/#315x-series), seems to be due to extra spaces.
> Fix broken links in release notes for 3.15

- rest_framework/mixins.py
- tests/test_prefetch_related.py
Closes #9319
Closes #9306
Reverts encode/django-rest-framework#8043
> Revert "Re-prefetch related objects after updating"

- docs/api-guide/permissions.md
- rest_framework/permissions.py
- tests/test_permissions.py
> Revert #8009

- rest_framework/filters.py
https://github.com/encode/django-rest-framework/pull/9017 unintentionally treated `SearchFilter.get_search_terms` as a private method, changing its signature from a list of strings, to a string.
This pull request reverts that change, by pulling the `"search_smart_split"` inside the method, ensuring that search terms are correctly tokenised by `"quoted strings like this"` and `comma`, `sperated`, `strings`, `like`, `this`.
Closes #9308
> `SearchFilter.get_search_terms` returns list.

- docs/community/3.15-announcement.md
- docs/community/release-notes.md
- rest_framework/__init__.py
Date: 22nd March 2024
* Fix `SearchFilter` handling of quoted and comma seperated strings, when `.get_search_terms` is being called into by a custom class. See [[#9338](https://github.com/encode/django-rest-framework/issues/9338)]
* Revert number of 3.15.0 issues which included unintended side-effects. See [[#9331](https://github.com/encode/django-rest-framework/issues/9331)]
---
Closes #9331
> Version 3.15.1

- docs/api-guide/caching.md
I am using @api_view heavily in my project and wanted to cache one of the views. I couldn't find any official documentation for how to do it on the caching page. I found out on a [Stackoverflow answer](https://stackoverflow.com/a/43577416/13815107) that it is extremely simple, so I wanted to add some example snippets to the documentation.
> Add @api_view example to caching documentation

- docs/api-guide/caching.md
It _looks_ like blacken-docs is failing on this file. Running black locally fails with a failed to reformat. This is because it expects python code, and  when it hits the ">", there's invalid python.
> Apply black formatting to caching markdown

- docs/api-guide/renderers.md
Hi,
Renderers documentation example still uses `smart_text` https://www.django-rest-framework.org/api-guide/renderers/#example and it was deprecated in Django 3.0 https://docs.djangoproject.com/en/4.0/releases/3.0/#features-deprecated-in-3-0. So I replaced by `smart_str`
Thank you!
> Update renderers documentation example

- README.md
- docs/community/project-management.md
- docs/index.md
- docs/tutorial/1-serialization.md
**1. The tutorial code in the official documentation is no longer hosted in the sandbox, so I've removed that reference from the official documentation.**
#8887 
#9357 
(before the change)
(after the change)
**2. minor change, DRF now supports Django 5.0. I've updated the parts of the documentation where Django 4.0 is used to 5.0.**
(before the change)
(after the change)
**3. minor concern... The source code for the tutorial is currently using DRF 3.11. I think it would be nice to use a tool like dependabot to ensure that the code in the tutorial follows the latest version of DRF (even if there is very little difference in behavior between DRF 3.11 and 3.15).**
> Removing live examples of tutorial code that are no longer hosted

- docs/tutorial/quickstart.md
Since django is a dependency of djangorestframework, we don’t need to install it manually.
> Docs: Remove an unnecessary step from quickstart.md

- docs/index.md
Add a missing required Python 3.12 version to the main documentation page.
> Documentation: Add Python 3.12 to the requirements

- README.md
Drop unnecessary self-serving promo text. (🤮 / 😅)
Really not relevant to the project.
I haven't checked to see if there are other `encode` projects which still include the same - contributors are welcome to issue similar pull requests referencing this if there's other similar bits of clean-up to be done.
> Tweak README.md links.

- rest_framework/pagination.py
- tests/test_pagination.py
As @kylebebak has mentioned in https://github.com/encode/django-rest-framework/issues/9359 attempting to accounting for nulls in the ordering field can lead to a serious performance regression in Postgres due to an index not being hit on the second query. This is blocking upgrades for some to 3.15, so putting out this PR to revert the changes. As he mentioned, it's a pretty uncommon use-case for the ordering field to be null, in the mean-time a reasonable work around would be using some sentinel value to ensure the items come last, or simply not using a nullable column.
> Revert "Ensure CursorPagination respects nulls in the ordering field"

- rest_framework/fields.py
- tests/test_fields.py
addressing https://github.com/encode/django-rest-framework/pull/8972#issuecomment-2039940577
> use warnings rather than logging a warning for DecimalField warnings

- .github/ISSUE_TEMPLATE/1-issue.md
- PULL_REQUEST_TEMPLATE.md
- docs/api-guide/serializers.md
- docs/community/contributing.md
- docs/community/project-management.md
- docs/community/release-notes.md
- docs/index.md
- docs_theme/css/default.css
- mkdocs.yml
Docs and GitHub template updates to reflect project management reality.
> 20240426 docs

- tests/test_testing.py
According to docs:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.addClassCleanup
> Add a function to be called after tearDownClass() to cleanup resources
used during the test class. Functions will be called in reverse order to
the order they are added (LIFO).
This was revealed with recent change in pytest (`8.2.0`):
> pytest-dev/pytest#11728: For unittest-based tests, exceptions during
class cleanup (as raised by functions registered with
TestCase.addClassCleanup) are now reported instead of silently failing.
`check_urlpatterns` is called before `cleanup_url_patterns` and fails (problem was hidden by `pytest < 8.2.0`).
`doClassCleanups` can be used instead to check after-cleanup state:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.doClassCleanups
> …
> tests: Check urlpatterns after cleanups

- docs/tutorial/1-serialization.md
Fixed some evaluation results in django shell.
- value from `JSONRenderer().render(serializer.data)` does not contain whitespace
- retrurned type of `serializer.validated_data` is not `OrderedDict` but standard `dict`
- in this tutorial, three snippets are obtained with `http http://127.0.0.1:8000/snippets/`
Added httpie option
- `--unsorted` option is required to prevent response json sorted
> docs: Correct some evaluation results and a httpie option in Tutorial1

- rest_framework/permissions.py
`OperandHolder` is not hashable, so need to add `__hash__` method
`OperandHolder` is not hashable after #8710, need to add `__hash__` method to it to provide convenient syntax to filter unique permissions using `set` or `dict.fromkeys`
```python
1. from rest_framework import permissions
2. set([permissions.IsAuthenticated & permissions.IsAdminUser])
```
* Remove `__eq__` method from `OperandHolder`
or
* Provide `__hash__` method to `OperandHolder`
Second way is provided in this PR
> Add `__hash__` method for `permissions.OperandHolder` class

- rest_framework/templatetags/rest_framework.py
The header input is now properly escaped before splitting and joining with `<br>` tags. This prevents potential XSS attacks if the header contains unsanitized user input.
This pull request addresses a potential XSS vulnerability in the `break_long_headers` template filter. By escaping the header input before processing, the risk of XSS attacks is mitigated.
> Fix potential XSS vulnerability in break_long_headers template filter

- docs/community/release-notes.md
- rest_framework/__init__.py
**Date**: 14th June 2024
* Fix potential XSS vulnerability in browsable API. [#9435](https://github.com/encode/django-rest-framework/pull/9157)
* Revert "Ensure CursorPagination respects nulls in the ordering field". [#9381](https://github.com/encode/django-rest-framework/pull/9381)
* Use warnings rather than logging a warning for DecimalField. [#9367](https://github.com/encode/django-rest-framework/pull/9367)
* Remove unused code. [#9393](https://github.com/encode/django-rest-framework/pull/9393)
---
I think these are the relevant code changes since 3.15.1. See [the history](https://github.com/encode/django-rest-framework/commits/master/) for changes, which mostly consists of docs fixs.
> Version 3.15.2.

- tests/test_permissions.py
Provide tests for #9417 according to [comment](https://github.com/encode/django-rest-framework/pull/9417#issuecomment-2162437647)
> Provide tests for hashing of `OperandHolder`

- rest_framework/request.py
This code has been deprecated and "removed" from version 3.2 (which was released in 2015).
It is not worth keeping it since all the docs states to use the lowercase variant.
> Remove long deprecated code from request wrapper

- docs/community/third-party-packages.md
Updated documentation: Added [adrf](https://github.com/em1208/adrf) as a third party package and updated the API documentation to refer to the async counterparts of:
- `@api_view`
- `APIView`
- `Serializer` 
- `ModelSerializer` 
- `BaseSerializer`
- `ListSerializer`
- `ViewSet`
See also #8496
> Update documentation: Add adrf third party package

- docs/community/release-notes.md
Fix wrong PR link for #9435 on release-notes v3.15.2
> Fix wrong link PR(#9435) on release-notes 3.15.2

- rest_framework/renderers.py
- tests/test_htmlrenderer.py
Fixes #9209 (replace #9212).
Since the problem is in `TemplateHTMLRenderer.get_template_context` the test to cover it was placed into that renderer testcases.
> Fix get_template_context to handle also lists

- rest_framework/request.py
- tests/test_request.py
Updates the `Request` class's `data`, `FILES`, and `POST` properties to utilize the `wrap_attributeerrors` context manager to ensure any properties that run `_load_data_and_files` in the `Request` class properly handle any `AttributeError`s raised internally.
Updates the `__getattr__` function to explicitly raise an `AttributeError` rather than calling `__getattribute__` again, as calling `__getattribute__` can have unexpected side effects (see #9433).
Adds a unit test to cover the case where a Parser raises an attribute error when the `Request.data` property is accessed.
`AttributeError`s raised in properties such as from parsing will now produce sane error messages and will no longer result in errors being suppressed.
None that I am currently aware of.
- fixes #9433
There appears to …
> Added protections to AttributeErrors raised within properties

- rest_framework/validators.py
- tests/test_validators.py
This fixed https://github.com/encode/django-rest-framework/issues/9442 
Fields with specified sources should now be handled correctly.
The unique together queryset with condition is another separated issue, which should be addressed in https://github.com/encode/django-rest-framework/pull/9360
> Fix unique_together validation with source

- rest_framework/urlpatterns.py
Raised by another at #9495. This avoids creating the converter entirely if it is already registered.
> Fix "Converter is already registered" deprecation warning.

- docs/api-guide/fields.md
- rest_framework/fields.py
- tests/importable/__init__.py
- tests/test_fields.py
The type of min/max values for `DecimalField` should be `Decimal` objects since https://github.com/encode/django-rest-framework/pull/8972 and we turn this into a Python warning in https://github.com/encode/django-rest-framework/pull/9367. However, [@terencehonles pointed out](https://github.com/encode/django-rest-framework/pull/8972#issuecomment-2039940577) that integers should be accepted.
Update the warning to ignore integers and clarify in the docs what types are accepted.
> Accept integers as min/max values of DecimalField

- docs/api-guide/routers.md
And remove note regarding only working with Django 2.x or above, as it's been a while the feature is present, and DRF only supports Django 4.2+.
I was looking for this but couldn't see it in the docs, having it in a separate section would make it easier to find and link to.
Moreover, as it stands, one might think that the feature is limited to `SimpleRouter`, while it's also available for `DefaultRouter`.
Refs:
- #6148
- #6789
- #8126
> Move path converter docs into a separate section

- tests/test_prefetch_related.py
Add test covering an expected behaviour from pre 3.15, where update views don't have to define a `queryset` attribute or `get_queryset` method. The behaviour regressed in 3.15 and the change was reverted in 3.15.1. However, it's a behaviour users care about which isn't covered by the test suite.
- Original PR: #8043
- Regression report: #9306
- Reverted in #9327
- Test extracted from: #9314
> Add test covering update view without `queryset` attribute

- .github/workflows/main.yml
- docs/index.md
- rest_framework/schemas/inspectors.py
- setup.py
- tox.ini
Python 3.13 introduced docstrings for the `None` singletong: https://github.com/python/cpython/pull/117813
In Python 3.12, this is an empty string:
```
➜ python3.12
Python 3.12.6 (main, Sep 10 2024, 19:06:17) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = None
>>> d.__doc__
>>>
```
In Python 3.13, it's no longer empty:
```
➜ python3.13
Python 3.13.0rc2+ (heads/3.13:660baa1, Sep 10 2024, 18:57:50) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> d = None
>>> d.__doc__
'The type of the None singleton.'
>>>
```
The fix: added a check in the inspector that get the view description out the view function docstring to catch this edge case.
> Add support for Python 3.13

- rest_framework/locale/pt_BR/LC_MESSAGES/django.po
*Note*: Before submitting a code change, please review our [contributing guidelines](https://www.django-rest-framework.org/community/contributing/#pull-requests).
Fixing wrong translations and adding missing ones in PT-BR. Closes #9526.
> Fixing and adding missing pt-br translations

- .github/workflows/main.yml
Final version of Python 3.13 has been released and is now also available on GitHub actions. Follow up of pull request #9527.
> Use final version of Python 3.13

- docs/api-guide/serializers.md
**Fix: Correct example for UniqueTogetherValidator in serializer documentation**
The example provided for using `UniqueTogetherValidator` in the serializer documentation currently uses an `IntegerField` for the `room_number` field. This is incorrect, as `UniqueTogetherValidator` is designed to work with relational fields, not integer fields.
This pull request replaces the `IntegerField` with a `ChoiceField` for the `room_number` field, which is a more appropriate field type for this scenario. This change ensures that the example accurately demonstrates how to use `UniqueTogetherValidator` with related fields.
**Changes Made:**
- In the example code snippet, the `room_number` field has been changed from:
```python
room_number = serializers.IntegerField(choices=[101, 102, 103, 201])
```
to: …
> Fix docs typo in Serializers Validators

- docs/api-guide/validators.md
Fixes #9585 
Removed the extra <> around UniqueValidator.
> Removed extra <> in validators example

- rest_framework/serializers.py
- tests/test_model_serializer.py
- tests/test_validators.py
> Fix raising on nullable fields part of `UniqueConstraint`

- docs/api-guide/testing.md
- rest_framework/test.py
- tests/test_testing.py
- Support Django 2.1+ test client auto serializing data if the content type is a json type
- Ensure the result of `_encode_data` is always `Tuple[bytes, str]` rather than `Tuple[Union[bytes,str], str]`
> support django 2.1+ test client json data automatically serialized

- docs/api-guide/renderers.md
Simple fix of typo.
It's called lUAlatex and not lAUlatex.
> edit typo in renderers.md

- rest_framework/test.py
- tests/test_testing.py
This is a fix for a regression introduced in PR #6511 which we discovered in our tests run on Django REST framework JSON:API against DRF master.
The error only occurred on tests which return no content (e.g. delete), use a renderer without charset (e.g. JSONRenderer) and using format to determine the renderer.
> Fixed regression that tests using format still work

- docs/api-guide/settings.md
The original added link is incorrect. The correct link which provides datetime format codes is: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
> Update `strftime` formats link in the documentation

- .github/workflows/main.yml
While coverage seems to be reported with the current method, the package [we rely on is deprecated](https://github.com/codecov/codecov-python). Trying this method to see if it works out of the box or if need more work.
Fix #7908
> Switch to codecov GHA

- rest_framework/__init__.py
- rest_framework/schemas/openapi.py
In preparation for the upcoming 3.16 release, drop `AutoSchema._get_reference` method which is marked as `RemovedInDRF316Warning`. 
The warning class is now unused, so dropping that as well (shouldn't be needed with DRF 3.16).
- #9516
> Drop deprecated `AutoSchema._get_reference` method

- docs/api-guide/throttling.md
Clarified the identifiers for the rate period in the documentation as per discussion https://github.com/encode/django-rest-framework/discussions/9639
Specified the allowed rate period strings after the `/` separator.
Fix #9639
> Improved description of allowed throttling rates

- tox.ini
We have that for all runs against Django main but was missed when we added Python 3.13.
> Add missing ignore_outcome=true for the Python 3.13 - Django main combination

- rest_framework/compat.py
- rest_framework/serializers.py
- rest_framework/validators.py
- tests/test_validators.py
> Fix unique together validator doesn't respect condition's fields

- setup.py
This PR removes a Python 2 compatible import and redundant read mode for the `open()` function from `setup.py`.
> Update usage of open() in setup.py

- docs/api-guide/authentication.md
- docs/community/third-party-packages.md
Hello there ! 👋
After a few years of work we just released a library that implements OpenID Connect (OIDC) authentication for Django and django-rest-framework. There are others libraries that implements OIDC for django/drf, but we were not satisfied with their implementation (read more [here](https://django-pyoidc.readthedocs.io/latest/explanation.html)).
Would you mind adding a link to this library in drf documentation ?
> Add django-pyoidc as a third party authentication library

- rest_framework/utils/serializer_helpers.py
- setup.py
- tests/test_fields.py
- tests/test_generics.py
- tests/test_model_serializer.py
- tests/test_request.py
- tests/test_response.py
- tests/test_serializer.py
- tests/test_serializer_lists.py
*Note*: Before submitting a code change, please review our [contributing guidelines](https://www.django-rest-framework.org/community/contributing/#pull-requests).
Remove optional dependency `backports.zoneinfo` and conditions for unsupported Python versions that were recently dropped. We support Python 3.9 and above so anything for Python <3.9 can go.
> Cleanup dependencies and conditions for unsupported Python versions

- .pre-commit-config.yaml
- rest_framework/authtoken/management/commands/drf_create_token.py
- rest_framework/fields.py
- rest_framework/negotiation.py
- rest_framework/permissions.py
- rest_framework/response.py
- rest_framework/schemas/coreapi.py
- rest_framework/schemas/openapi.py
- rest_framework/utils/field_mapping.py
- tests/schemas/test_coreapi.py
- tests/schemas/test_managementcommand.py
- tests/test_exceptions.py
- tests/test_fields.py
- tests/test_generics.py
- tests/test_pagination.py
- tests/test_permissions.py
- tests/test_relations_pk.py
- tests/test_renderers.py
- tests/test_response.py
- tests/test_routers.py
- tests/test_validation.py
Inspired from @browniebroke 's [PR](https://github.com/encode/django-rest-framework/pull/9681) We can and we should automate this type of checks. `pyupgrade` is a great tool to do that and we already had `pre-commit` setup in place.
I tried to minimize the changes by excluding `%s` to  f-string conversions but it looks like the code was a bit neglected so the resulting changes are still not so small.
This looks like nitpicking and "churn", but in my experience, `pyupgrade` and `django-upgrade` helps a lot to minimize the maintenance efforts.
> Add pyupgrade to pre-commit hooks

- docs/api-guide/schemas.md
Replaced the outdated Heroku JSON Schema reference URL, which was returning a 404 error, with the updated working link from the official Heroku blog.
*Note*: Before submitting a code change, please review our [contributing guidelines](https://www.django-rest-framework.org/community/contributing/#pull-requests).
> Fix broken Heroku JSON Schema link in schemas.md

- requirements/requirements-testing.txt
- tests/test_fields.py
- tox.ini
When running tests against Django 5.2, I am getting the following test failure when pytz is available on the machine. When I remove it, the issue is gone.
```pytb
_______________________ TestPytzNaiveDayLightSavingTimeTimeZoneDateTimeField.test_invalid_inputs _______________________
test_fields.py:682: in test_invalid_inputs
self.field.run_validation(input_value)
../../build/prototype/sparc/usr/lib/python3.13/vendor-packages/rest_framework/fields.py:538: in run_validation
value = self.to_internal_value(data)
../../build/prototype/sparc/usr/lib/python3.13/vendor-packages/rest_framework/fields.py:1190: in to_internal_value
return self.enforce_timezone(parsed)
../../build/prototype/sparc/usr/lib/python3.13/vendor-packages/rest_framework/fields.py:1168: in enforce_timezone
raise e …
```
> Fix test with Django 5 when pytz is available

- docs/community/release-notes.md
- rest_framework/__init__.py
As discussed in https://github.com/encode/django-rest-framework/discussions/9748
Checklist:
- Build and serve docs `mkdocs serve`
- Validate links `pylinkvalidate.py -P http://127.0.0.1:8000`
> Prepare 3.16.1 release

- rest_framework/authtoken/models.py
- tests/test_authtoken.py
Fix #9250
This pull request addresses issue #9250, which highlighted a theoretical possibility of an existing authentication token being overwritten due to a key collision during token creation. While the probability was infinitesimally small, this change ensures robust handling of token uniqueness and improves the underlying key generation mechanism.
1. **Token Model `save` method refinement**:
- The `save` method of the `Token` model (`rest_framework/authtoken/models.py`) has been adjusted to explicitly use `force_insert=True` only when a new token instance is being created (`self._state.adding` is `True`).
- This ensures that if a newly generated key happens to collide with an existing key in the database, an `IntegrityError` is correctly raised, preventing the accidental overwrite of …
> Prevent small risk of `Token` overwrite

- .github/workflows/mkdocs-deploy.yml
Automatcially deployes the docs to GH pages each time a push to master changes the content of the docs, theme, config or dependencies.
Repo with a minimal setup https://github.com/browniebroke/poc-mkdocks-gh-deploy-gh-actions 
Deployed https://browniebroke.github.io/poc-mkdocks-gh-deploy-gh-actions/ 
Right now, maintainers have to remember to run `mkdocs gh-deploy` manually.
> Automate docs deployment

- docs/api-guide/fields.md
- docs/api-guide/settings.md
- rest_framework/__init__.py
- rest_framework/fields.py
- rest_framework/settings.py
- tests/test_fields.py
As explained in #8527 this PR will provide the ability to choose the output format for `DurationFields`.
Since Python builtim `timedelta` object does not have any format function we are going to allow only formats which are already defined in Django codebase in the package `django.utils.duration`:
- `duration_string`
- `duration_iso_string`
> DurationField output format

- rest_framework/validators.py
- tests/test_validators.py
We can't always expect to find the value of the unique condition in the serializer if the field is read-only.
The proposed solution is to fallback on instance's value.
> Condition of UniqueTogetherValidator can be read-only

- .github/workflows/main.yml
- .github/workflows/mkdocs-deploy.yml
- .github/workflows/pre-commit.yml
- README.md
- docs/api-guide/schemas.md
- docs/api-guide/testing.md
- docs/community/3.0-announcement.md
- docs/community/contributing.md
- docs/community/project-management.md
- docs/community/third-party-packages.md
- docs/topics/internationalization.md
- docs_theme/main.html
- docs_theme/nav.html
- rest_framework/schemas/openapi.py
To follow the current conventions, as both git and GitHub now default to `main`. I think this repo is perhaps the last one where I'm a maintainer and where this is not the case. GitHub has refined the rename workflow a few years back and it's prety painless now, even giving nudges to forks to do the switch.
Before merging this, a maintainer will have to go the General settings page and use the "Reanme branch" button (the one with a pencil)
> Rename 'master' branch to 'main'

- docs/api-guide/testing.md
- tests/test_testing.py
Hi there!
As there were many issues opened around this topic: _"`APIRequestFactory` **does not** return a `Request` object"_ I think it would be worth to have a place in the documentation where explains it. 
Following the Tom's comment in the last issue https://github.com/encode/django-rest-framework/issues/6488#issuecomment-2049940926:
> If someone's invested and there's clearly a good existing place in the docs to highlight this, then we could accept a docs PR here.
*Past issues related: https://github.com/encode/django-rest-framework/issues/4440 and https://github.com/encode/django-rest-framework/issues/3608
This is what my proposal looks like:
I've also added a test to follow the Carlton's comment https://github.com/encode/django-rest-framework/issues/6488#issuecomment-2048962774 …
> Add documentation about how to transform factory request to DRF request

- tox.ini
Looking at the [supported Python versions from the Django docs](https://docs.djangoproject.com/en/dev/faq/install/), the `main` branch (which will be the upcoming v6.0) only supports Python 3.12 and 3.13.
Our CI runs the tests against it but all the way to Python 3.10, ignoring the failures. We shouldn't even bother running tests on Python 3.10/3.11 + Django main, as we can't even install.
> Adjust CI matrix to reflect upstream Django support
